! ------------------- Superclass check
run
AbstractNode ifNil: [self error: 'AbstractNode is not defined. Check file ordering.'].
%

! ------------------- Class definition for ModuleAst
expectvalue /Class
doit
AbstractNode subclass: 'ModuleAst'
  instVarNames: #(body name path
                    source type_ignore useTempsForBlock)
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonAst
  options: #()

%

expectvalue /Class
doit
ModuleAst comment:
'https://docs.python.org/3/library/ast.html#ast.Module

A Python module, as with file input.
Node type generated by ast.parse() in the default "exec" mode.

body is a list of the module''s Statements.
type_ignores is a list of the module''s type ignore comments.

Example:
>>> print(ast.dump(ast.parse(''x = 1''), indent=4))
Module(
    body=[
        Assign(
            targets=[
                Name(id=''x'', ctx=Store())],
            value=Constant(value=1))])
'
%

expectvalue /Class
doit
ModuleAst category: 'Grail-Parser'
%

! ------------------- Remove existing behavior from ModuleAst
removeallmethods ModuleAst
removeallclassmethods ModuleAst

set compile_env: 0

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluate: sourceString withScope: aSymbolList
	"Evaluate sourceString in a persistent scope for REPL usage."

	| module |
	module := self parseSource: sourceString.
	module useTempsForBlock: false.
	^module evaluateWithScope: aSymbolList
%

category: 'Grail-evaluation'
classmethod: ModuleAst
___resignalSyntaxError___: ex
	"Re-signal a parser SyntaxError as a Python one, KEEPING its location.

	Two callers re-raise a parse error so that the Python ``str(e)'' carries the
	parser's message: this class's evaluateSource: (the exec path) and builtins'
	compile:.  The env-0 parser can set only GemStone's messageText, and the
	Python ``args'' tuple that BaseException>>__str__ reads is populated by the
	env-1 constructor -- so a re-signal is genuinely needed.

	What it must not do is DROP the location.  Both callers used to re-signal the
	message alone, so however precisely the parser had located the error,
	compile() and exec() answered a SyntaxError with filename / lineno / offset /
	text all absent and traceback.py had no source line to draw a caret under.

	NO TUPLE WHEN THERE IS NO LOCATION.  ___pyAttrLoad___ treats a dynamic
	instVar holding Smalltalk nil as ABSENT, so a tuple of nils does not say
	``these are None'' -- it SHADOWS the accessors that answer None, and
	``e.lineno'' then raises AttributeError instead.  A tokenizer error has no
	position to report (it fails before the token list exists), so this branch is
	taken in practice, not defensively."

	| msg lineno loc |
	msg := ex @env0:messageText ifNil: ['invalid syntax'].
	lineno := [ex @env0:dynamicInstVarAt: #'lineno']
		@env0:on: AbstractException do: [:e2 | e2 @env0:return: nil].
	lineno isNil ifTrue: [^ (ex @env0:class) @env1:___signal___: msg].
	loc := Array @env0:new: 6.
	#( #'filename' #'lineno' #'offset' #'text' #'end_lineno' #'end_offset' )
		@env0:doWithIndex: [:nm :i |
			| v |
			v := [ex @env0:dynamicInstVarAt: nm]
				@env0:on: AbstractException do: [:e2 | e2 @env0:return: nil].
			loc @env0:at: i put: (v isNil ifTrue: [None] ifFalse: [v])].
	"``ex class'', not SyntaxError: an indentation problem is an
	 IndentationError and the class is observable -- test_bad_indentation asks for
	 it by name, and ``except IndentationError'' is a thing people write.  A
	 hardcoded SyntaxError here silently downgraded every one of them."
	^ (ex @env0:class) @env1:___signalNew___:
		(Array @env0:with: msg with: (tuple @env0:withAll: loc)) kw: nil
%

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluateSource: sourceString
	"Evaluate sourceString in a fresh module scope. Use this for one-shot
	evaluations where no globals need to persist after the call."

	^self evaluateSource: sourceString usingModuleScope: SymbolDictionary new
%

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluateSource: sourceString usingModuleScope: aSymbolDictionary
	"Evaluate sourceString with aSymbolDictionary as the module scope.
	The caller owns the dictionary and may pass the same instance to
	successive calls so that user-defined globals persist across them —
	this is the REPL contract (e.g. `x = 1` then `x + 2` resolving x).
	One-shot callers should use #evaluateSource: instead."

	^ self
		evaluateSource: sourceString
		usingModuleScope: aSymbolDictionary
		as: #doit
%

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluateSource: sourceString usingModuleScope: aSymbolDictionary as: aKind
	"Three-arg variant used by entry points that want their doit
	tagged in the $TMP/codegen/ debug capture — aKind is a Symbol
	(#exec / #eval / #doit) that determines the filename prefix.
	Python's ``exec()'' passes #exec; Python's ``eval()'' passes
	#eval; everything else (the REPL, test helpers) defaults to
	#doit via the 2-arg form."

	^ self
		evaluateSource: sourceString
		usingModuleScope: aSymbolDictionary
		as: aKind
		globalNamesInto: nil
%

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluateSource: sourceString usingModuleScope: aSymbolDictionary as: aKind globalNamesInto: aSetOrNil
	"As the 3-arg variant, and additionally collects into aSetOrNil every
	name the source declares ``global'' ANYWHERE in it, nested defs included.

	exec(source, globals, locals) needs this to reflect its bindings back to
	the right mapping.  Grail runs an exec'd body in ONE flat scope -- it has
	no separate globals/locals at runtime -- so after the body has run,
	deciding where a binding belongs is a question about the SOURCE, and a
	``global'' declaration is the whole answer: a name declared global is the
	one kind that must land in the globals mapping even though every other
	binding the body made belongs to locals.

	    a = 10            # -> locals
	    def spam():
	        global a
	        (a := 20)     # -> globals
	    spam()

	is test_named_expressions' test_named_expression_scope_25, which asserts
	exactly that split.  aSetOrNil is nil for the callers that do not care,
	which skips the walk entirely."

	| module symbolList |
	"Re-raise a PARSER SyntaxError so the Python ``str(e)'' carries its
	message.  The env-0 parser can set only GemStone's messageText;
	___signal___: populates the ``args'' tuple BaseException>>__str__ reads.
	compile() has done this since test_dictcomps needed it, but exec() and
	eval() reach the parser through here and did NOT, so every SyntaxError
	they raised arrived with an EMPTY message -- assertRaisesRegex could
	match nothing, and the test that checks WHICH syntax error you get could
	not be written.  test_named_expressions checks all 15 of its invalid
	cases through exec().

	Wraps the PARSE only, not the evaluation below: a SyntaxError raised at
	RUN time is already a Python one carrying its own args, and re-signalling
	it from messageText would throw those away."
	module := [self parseSource: sourceString]
		on: SyntaxError
		do: [:ex | self ___resignalSyntaxError___: ex].
	module useTempsForBlock: false.
	module ensureModuleScope: aSymbolDictionary.
	aSetOrNil ifNotNil: [self collectGlobalNamesFrom: module into: aSetOrNil].
	symbolList := self symbolListForModuleScope: aSymbolDictionary.
	^module evaluateWithScope: symbolList as: aKind
%

category: 'Grail-evaluation'
classmethod: ModuleAst
collectGlobalNamesFrom: node into: aSet
	"Recursive walk collecting the names of every ``global x, y'' statement
	beneath node, as Symbols.  Same shape as FunctionDefAst >>
	collectDeletedNamesFrom:into:, including its two guards: strings are
	SequenceableCollections and recursing into one walks its Characters for
	nothing, and the ``parent'' back-pointer is skipped so the walk cannot
	cycle up the tree.

	DESCENDS INTO NESTED DEFS -- which is the point, since the declaration
	that matters is almost always inside one."

	node isNil ifTrue: [^ self].
	node isString ifTrue: [^ self].
	(node isKindOf: SequenceableCollection) ifTrue: [
		node do: [:each | self collectGlobalNamesFrom: each into: aSet].
		^ self].
	(node isKindOf: AbstractNode) ifFalse: [^ self].
	(node isKindOf: GlobalAst) ifTrue: [
		node names ifNotNil: [:ns |
			ns do: [:n | aSet add: n asString asSymbol]]].
	node class allInstVarNames doWithIndex: [:nameSym :i |
		nameSym == #parent ifFalse: [
			self collectGlobalNamesFrom: (node instVarAt: i) into: aSet]]
%

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluateExpressionSource: sourceString
	"One-shot evaluation of a single Python expression — Python's
	eval() with no globals.  Uses a fresh module scope."

	^ self
		evaluateExpressionSource: sourceString
		usingModuleScope: SymbolDictionary new
%

category: 'Grail-evaluation'
classmethod: ModuleAst
evaluateExpressionSource: sourceString usingModuleScope: aSymbolDictionary
	"Parse sourceString as a single Python expression and evaluate
	it in aSymbolDictionary's scope, returning the expression's
	value.  Raises SyntaxError if the source is anything other than
	a bare expression (assignments, multiple statements, etc.).
	Used to implement Python's eval() builtin."

	| module |
	module := self parseSource: sourceString.
	module isSingleExpressionBody ifFalse: [
		SyntaxError @env1:___signal___:
			'eval() arg 1 must be a single expression: ' , sourceString].
	module useTempsForBlock: false.
	module ensureModuleScope: aSymbolDictionary.
	^ module
		evaluateWithScope: (self symbolListForModuleScope: aSymbolDictionary)
		as: #eval
%

category: 'Grail-evaluation'
classmethod: ModuleAst
nextSeqFor: aKind
	"Bump and return the per-session counter for aKind (#exec /
	#eval / #doit).  Counters live in SessionTemps so each gem
	process gets its own independent sequence and no two sessions
	can conflict on the same committed slot."

	| key temps |
	key := aKind == #exec ifTrue: [#'___grailExecCounter___']
		ifFalse: [aKind == #eval ifTrue: [#'___grailEvalCounter___']
		ifFalse: [#'___grailDoitCounter___']].
	temps := SessionTemps current.
	temps at: key put: (temps at: key ifAbsent: [0]) + 1.
	^ temps at: key
%

category: 'Grail-parsing'
classmethod: ModuleAst
parseSource: sourceString
	"Parse Python source code and return a ModuleAst."

	^PythonParser parse: sourceString
%

category: 'Grail-evaluation'
classmethod: ModuleAst
symbolListForModuleScope: aSymbolDictionary
	"Return a SymbolList with the module scope at the front, followed by the
	Grail compile symbol list (importlib>>___grailCompileSymbolList___: the
	Python dict + PythonModules, NOT Globals).  Every symbol generated code
	resolves by name -- exception classes, None, PythonReturn, PyCode,
	PythonClass, imported modules -- lives in those two dictionaries; kernel
	Globals is deliberately excluded so Python code sees only Python builtins
	and what it imported (builtin CALLS still go via ((builtins instance) …))."

	| symbolList |
	symbolList := importlib ___grailCompileSymbolList___.
	symbolList insertObject: aSymbolDictionary at: 1.
	^symbolList
%

category: 'Grail-accessors'
method: ModuleAst
body

	^body
%

category: 'Grail-evaluation'
method: ModuleAst
ensureModuleScope: aSymbolDictionary
	"Ensure module scope has entries for declared variables."

	self setParent: nil.
	"Under the doit-scope spelling: a body variable named like a Smalltalk
	pseudo-variable is emitted mangled by NameAst codegen, so the slot the
	compiler has to find must carry the same name."
	body variables do: [:each |
		aSymbolDictionary at: (NameAst doitScopeNameFor: each) ifAbsentPut: [nil] ].
	"A handle on the scope itself, for the one case a bare identifier cannot
	reach it: a name declared ``global'' and read or written from inside a
	nested def whose ENCLOSING def has a same-named local.  The local is a
	Smalltalk block temp, and Smalltalk resolves the bare identifier
	LEXICALLY, so the temp wins over this dictionary and the global
	declaration is silently ignored (test_scope testScopeOfGlobalStmt).
	Going through the handle names the slot explicitly, which no temp can
	shadow.  ___reflectDoitScope___: drops the key again so it never reaches
	the caller's namespace."
	aSymbolDictionary at: #'___pyGlobals___' put: aSymbolDictionary.
%

category: 'Grail-evaluation'
method: ModuleAst
evaluateWithScope: aSymbolList
	"Evaluate this module using the provided symbol list.  Backward-
	compat 1-arg form — tags the debug capture as #doit."

	^ self evaluateWithScope: aSymbolList as: #doit
%

category: 'Grail-evaluation'
method: ModuleAst
evaluateWithScope: aSymbolList as: aKind
	"Evaluate this module using the provided symbol list, tagging the
	debug capture with aKind (#exec / #eval / #doit).  Returns the
	expression value if the body's last statement is a bare
	expression (REPL convention — ``x'' returns the value of x);
	returns None for statement-only bodies (``x = 1'' returns None
	per Python ``exec()'' semantics)."

	| result |
	result := self executeWithScope: aSymbolList as: aKind.
	self shouldReturnExpressionResult ifTrue: [^ result].
	^ None
%

category: 'Grail-evaluation'
method: ModuleAst
smalltalkSource
	"Return this module transpiled to Smalltalk source. Pure code
	generation — no compilation, execution, or filesystem side effects.
	Use this when you want to inspect the generated code without running it."

	| writeStream |
	writeStream := PrettyWriteStream on: Unicode7 new.
	self printSmalltalkOn: writeStream.
	^writeStream contents
%

category: 'Grail-evaluation'
classmethod: ModuleAst
compilingDoitScope
	"The symbol list a DOIT's Smalltalk source is currently being generated
	against -- exec(), eval(), the ad-hoc REPL path, and the runtime
	compilation of a class body nested inside a function -- or nil during
	ordinary module compilation.

	NameAst's free-name fallback needs this, and needs it to be the SYMBOL LIST
	rather than any static property of the AST.  Two cheaper tests were tried
	and both are wrong:

	  ``CallAst moduleClassBeingCompiled isNil'' -- also nil while compiling
	    the methods of a class defined inside a function.
	  a plain ``am I in a doit'' flag -- true there as well, because such a
	    class body IS compiled as a doit.

	In that case ``class Base:'' in a function is reachable from a sibling
	method purely because the enclosing scope's bindings are in the doit's
	symbol list, which no amount of AST inspection can see.  Asking the symbol
	list is asking exactly the question the Smalltalk compiler is about to ask,
	so the answers cannot disagree.

	Session-local, and saved/restored rather than set/cleared, so an exec()
	nested inside another exec() returns to the outer scope."

	^ SessionTemps current at: #'___grailDoitScope___' ifAbsent: [nil]
%

category: 'Grail-evaluation'
classmethod: ModuleAst
whileCompilingDoitWithScope: aSymbolList do: aBlock
	"Evaluate aBlock with ``compilingDoitScope'' set to aSymbolList, restoring
	the prior value afterwards even if codegen raises."

	| temps key prior |
	temps := SessionTemps current.
	key := #'___grailDoitScope___'.
	prior := temps at: key ifAbsent: [nil].
	temps at: key put: aSymbolList.
	^ aBlock ensure: [temps at: key put: prior]
%

category: 'Grail-evaluation'
method: ModuleAst
executeWithScope: aSymbolList
	"Compile and execute this module, returning the raw execution
	result.  Backward-compat 1-arg form — tags the debug capture as
	#doit (REPL, test helpers, ad-hoc callers).  Use the :as:
	variant from Python's exec()/eval() entry points so the file
	name reflects which Python builtin produced the doit."

	^ self executeWithScope: aSymbolList as: #doit
%

category: 'Grail-evaluation'
method: ModuleAst
executeWithScope: aSymbolList as: aKind
	"Compile and execute this module, returning the raw execution
	result.  aKind is a Symbol (#exec / #eval / #doit) that
	identifies the entry point.

	Codegen debug capture is OPT-IN, gated by the same
	``GRAIL_CODEGEN_TRACE_DIR'' env var as importlib's module-load
	capture — ``importlib ___codegenTraceDir___'' is the single
	source of truth (it returns nil when the var is unset and creates
	the directory when it is set).  When tracing is on, the generated
	Smalltalk source and the post-compile IR snapshot are written to
	that directory as ___<kind>_<N>___.tpz and matching .ir; each call
	gets its own sequence number so successive exec/eval/doit calls
	accumulate instead of overwriting.  When tracing is off (default),
	no sequence number is consumed and no file I/O happens — this is
	what keeps ``run_tests.sh'' from flooding $TMP/codegen with a
	___doit_<N>___ pair per executed statement."

	| code traceDir seq tpzPath irPath compiledMethod result tpzSource |
	code := ModuleAst whileCompilingDoitWithScope: aSymbolList do: [self smalltalkSource].
	traceDir := importlib ___codegenTraceDir___.
	traceDir ifNotNil: [
		seq := ModuleAst nextSeqFor: aKind.
		tpzPath := traceDir , '/___' , aKind asString , '_' , seq printString , '___.tpz'.
		irPath := traceDir , '/___' , aKind asString , '_' , seq printString , '___.ir'.
		"Topaz-style wrapping: the doit framing matches what topaz
		would see if you fed the file through it.  Caveat: the symbol
		list passed to _compileInContext: isn't reproduced here, so
		free-name resolution may differ in a true topaz run; the file
		is for inspection rather than literal replay."
		tpzSource := (AppendStream on: Unicode7 new)
			nextPutAll: '! '; nextPutAll: tpzPath;
			nextPutAll: '   (Module: '; nextPutAll: name;
			nextPut: $); lf; lf;
			nextPutAll: 'doit'; lf;
			nextPutAll: code; lf;
			nextPutAll: '%'; lf;
			yourself.
		(GsFile open: tpzPath mode: 'wb' onClient: false)
			nextPutAll: tpzSource contents encodeAsUTF8;
			close.
	].
	compiledMethod := code
		_compileInContext: nil
		symbolList: aSymbolList
		oldLitVars: nil
		environmentId: 1
		flags: 0 .
  " Add   on: AbstractException do:[:ex| self pause ]  here if you want to debug compile errors here "
	"Snapshot IR for the freshly-compiled doit before any later
	compile overwrites __sessionStateAt: 19."
	traceDir ifNotNil: [
		(GsFile open: irPath mode: 'w' onClient: false)
			nextPutAll: (System __sessionStateAt: 19) printString;
			close.
	].
	result := compiledMethod _executeInContext: nil .
  " Add   on: AbstractException do:[:ex| self pause ]  here if you want to debug execute errors here "
	^ result
%

category: 'Grail-variables'
method: ModuleAst
globals

	^body
%

category: 'Grail-querying'
method: ModuleAst
isInClass

	^false
%

category: 'Grail-querying'
method: ModuleAst
isPackage
	"True if this module was loaded from a package __init__.py.
	A package's __init__.py is its own package context — relative
	imports from inside it don't strip a component the way they
	would from a sibling submodule."

	^ path notNil and: [path asString endsWith: '/__init__.py']
%

category: 'Grail-variables'
method: ModuleAst
locals

	^body
%

category: 'Grail-accessors'
method: ModuleAst
module

	^self
%

category: 'Grail-accessors'
method: ModuleAst
name

	^name
%

category: 'Grail-accessors'
method: ModuleAst
name: aString

	name := aString
%

category: 'Grail-accessors'
method: ModuleAst
path

	^path
%

category: 'Grail-accessors'
method: ModuleAst
path: aString

	path := aString
%

category: 'Grail-code generation'
method: ModuleAst
printSmalltalkOn: aStream

	body printSmalltalkOn: aStream useTemps: useTempsForBlock.
%

category: 'Grail-variables'
method: ModuleAst
set: aSymbol to: anObject

	self halt.
%

category: 'Grail-accessors'
method: ModuleAst
setBlock: aBlockAst

	body := aBlockAst.
%

category: 'Grail-evaluation'
method: ModuleAst
shouldReturnExpressionResult

	| statements |
	statements := body body.
	^statements notEmpty and: [(statements last isKindOf: ExprAst)]
%

category: 'Grail-evaluation'
method: ModuleAst
isSingleExpressionBody
	"True iff the body is exactly one statement and that statement
	is a bare expression (ExprAst).  Anything else — assignment,
	for-loop, def, multiple statements — fails Python's eval()
	contract."

	| statements |
	statements := body body.
	^ statements size = 1 and: [statements first isKindOf: ExprAst]
%

category: 'Grail-accessors'
method: ModuleAst
source

	^source
%

category: 'Grail-accessors'
method: ModuleAst
source: aString

	source := aString
%

category: 'Grail-variables'
method: ModuleAst
useTempsForBlock: aBoolean

	useTempsForBlock := aBoolean.
%
method: ModuleAst
body: newValue
	body := newValue
%
method: ModuleAst
type_ignore
	^type_ignore
%
method: ModuleAst
type_ignore: newValue
	type_ignore := newValue
%
method: ModuleAst
useTempsForBlock
	^useTempsForBlock
%
