! ------------------- Superclass check
run
AbstractNode ifNil: [self error: 'AbstractNode is not defined. Check file ordering.'].
%

! ------------------- Class definition for ModuleAst
expectvalue /Class
doit
AbstractNode subclass: 'ModuleAst'
  instVarNames: #(body name path
                    source type_ignore useTempsForBlock)
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonAst
  options: #()

%

expectvalue /Class
doit
ModuleAst comment:
'https://docs.python.org/3/library/ast.html#ast.Module

A Python module, as with file input.
Node type generated by ast.parse() in the default "exec" mode.

body is a list of the module''s Statements.
type_ignores is a list of the module''s type ignore comments.

Example:
>>> print(ast.dump(ast.parse(''x = 1''), indent=4))
Module(
    body=[
        Assign(
            targets=[
                Name(id=''x'', ctx=Store())],
            value=Constant(value=1))])
'
%

expectvalue /Class
doit
ModuleAst category: 'Parser'
%

! ------------------- Remove existing behavior from ModuleAst
removeallmethods ModuleAst
removeallclassmethods ModuleAst

set compile_env: 0

category: 'evaluation'
classmethod: ModuleAst
evaluate: sourceString withScope: aSymbolList
	"Evaluate sourceString in a persistent scope for REPL usage."

	| module |
	module := self parseSource: sourceString.
	module useTempsForBlock: false.
	^module evaluateWithScope: aSymbolList
%

category: 'evaluation'
classmethod: ModuleAst
evaluateSource: sourceString usingModuleScope: aSymbolDictionary
	"Evaluate sourceString in a persistent scope for REPL usage."

	| module symbolList |
	module := self parseSource: sourceString.
	module useTempsForBlock: false.
	module ensureModuleScope: aSymbolDictionary.
	symbolList := self symbolListForModuleScope: aSymbolDictionary.
	^module evaluateWithScope: symbolList
%

category: 'parsing'
classmethod: ModuleAst
parseSource: sourceString
	"Parse Python source code and return a ModuleAst."

	^PythonParser parse: sourceString
%

category: 'evaluation'
classmethod: ModuleAst
symbolListForModuleScope: aSymbolDictionary
	"Return a SymbolList with module scope before builtins."

	^SymbolList new
		add: aSymbolDictionary;
		add: builtins ___instance___;
		yourself
%

category: 'accessors'
method: ModuleAst
body

	^body
%

category: 'evaluation'
method: ModuleAst
ensureModuleScope: aSymbolDictionary
	"Ensure module scope has entries for declared variables."

	self setParent: nil.
	body variables do: [:each | aSymbolDictionary at: each ifAbsentPut: [nil] ].
%

category: 'evaluation'
method: ModuleAst
evaluateWithScope: aSymbolList
	"Evaluate this module using the provided symbol list."

	| result |
	result := self executeWithScope: aSymbolList.
	self shouldReturnExpressionResult ifTrue: [
		^result
	].
	^None.
%

category: 'evaluation'
method: ModuleAst
executeWithScope: aSymbolList
	"Compile and execute this module, returning the raw execution result."

	| tmpPath file writeStream compiledMethod result |
	writeStream := PrettyWriteStream on: Unicode7 new.
	self printSmalltalkOn: writeStream.
	tmpPath := '/tmp/grail'.
	(GsFile isServerDirectory: tmpPath) ifNil: [
		GsFile createServerDirectory: tmpPath.
	] ifNotNil: [
		(GsFile isServerDirectory: tmpPath) ifFalse: [
			self error: '/tmp/grail should be a directory!'.
		].
	].
	"Write source to disk to allow debugging/inspecting"
	file := GsFile open: tmpPath , '/' , name , '.gs' mode: 'w' onClient: false.
	file nextPutAll: writeStream contents.
	file close.
	[
		compiledMethod := writeStream contents
			_compileInContext: nil
			symbolList: aSymbolList
			oldLitVars: nil
			environmentId: 1
			flags: 0.
	] on: AbstractException do: [:ex |
		ex pass.
	].
	[
		result := compiledMethod _executeInContext: nil.
	] on: AbstractException do: [:ex |
		ex pass.
	].
	^result
%

category: 'variables'
method: ModuleAst
globals

	^body
%

category: 'querying'
method: ModuleAst
isInClass

	^false
%

category: 'querying'
method: ModuleAst
isPackage

	^false
%

category: 'variables'
method: ModuleAst
locals

	^body
%

category: 'accessors'
method: ModuleAst
module

	^self
%

category: 'accessors'
method: ModuleAst
name

	^name
%

category: 'accessors'
method: ModuleAst
name: aString

	name := aString
%

category: 'accessors'
method: ModuleAst
path

	^path
%

category: 'accessors'
method: ModuleAst
path: aString

	path := aString
%

category: 'code generation'
method: ModuleAst
printSmalltalkOn: aStream

	body printSmalltalkOn: aStream useTemps: useTempsForBlock.
%

category: 'variables'
method: ModuleAst
set: aSymbol to: anObject

	self halt.
%

category: 'accessors'
method: ModuleAst
setBlock: aBlockAst

	body := aBlockAst.
%

category: 'evaluation'
method: ModuleAst
shouldReturnExpressionResult

	| statements |
	statements := body body.
	^statements notEmpty and: [(statements last isKindOf: ExprAst)]
%

category: 'accessors'
method: ModuleAst
source

	^source
%

category: 'accessors'
method: ModuleAst
source: aString

	source := aString
%

category: 'variables'
method: ModuleAst
useTempsForBlock: aBoolean

	useTempsForBlock := aBoolean.
%
