# shutil.copystat / os.chmod / archive extraction -- METADATA, read back.
#
# WHAT THIS EXISTS TO STOP.  os.utime shipped before this as a real call that
# nothing used: shutil.copystat was a "return None" and tarfile.extract wrote
# bytes and no attributes.  Half the reason was honest -- there was no os.chmod
# -- but the shape of the gap is the dangerous kind, because "copy2() copied
# the metadata" is a thing callers BELIEVE rather than check.  os.chmod now
# exists, and copystat/copy2/copytree and tarfile.extract use it and os.utime.
#
# EVERY POSITIVE CHECK BELOW READS THE METADATA BACK with os.stat.  None of
# them is satisfied by a call that merely fails to raise -- that is the lesson
# the os.utime lane paid for: a no-op os.utime passed 4 of its 13 tests,
# because a file that has just been created already HAS "now" for an mtime, so
# "set it to now and see" cannot tell setting from not setting.  So:
#
#   * every mtime asserted here is a FIXED INSTANT YEARS IN THE PAST (2001,
#     2004, 2008, 2011), never "now" and never "the time the file was made";
#   * every mode asserted here DIFFERS from what the file would have got from
#     open() under a normal umask.  0o644 is useless as evidence for exactly
#     that reason and appears nowhere as an expected value; the modes used are
#     0o600 (more restrictive than the default) and 0o755 (more permissive),
#     plus 0o777 and 0o4755 in the archive, which must NOT survive.
#
# THE RESTRICTIVE DIRECTION IS THE ONE THAT MATTERS.  A chmod bug that leaves
# a file MORE permissive than asked is a security answer, not a wrong one, so
# the checks are written to catch that specifically: copying a 0o600 file's
# mode onto a 0o666 destination must end at 0o600, and an archive member
# claiming 0o777 or setuid must come out at 0o755 with the setuid bit gone.
#
# SHELL QUOTING.  Grail has no chmod(2) or utimes(2) -- os.chmod and os.utime
# run chmod(1) and touch(1) -- so an archive member's NAME reaches a command
# line.  One member of the tar fixture is named
#
#     m/od'd ; touch grail_extract_pwned_marker ; x.txt
#
# and the checks are not only that its mode and mtime landed but that the
# marker file the semicolons would have created does not exist.  Note that the
# usual ``--'' guard is NOT what protects it: BSD chmod does not implement
# ``--'' at all (measured on macOS 26.6, where ``chmod 0600 -- f'' reports
# ``chmod: --: No such file or directory'' and chmods f anyway), so os.chmod
# prefixes a leading-dash path with ``./'' instead, which needs no cooperation
# from the utility.  chmod_leading_dash_name below is the check for that.
#
# ZIPFILE RESTORES NOTHING, ON PURPOSE.  CPython's ZipFile._extract_member
# writes the file and stops: no chmod, no utime, anywhere in CPython's
# zipfile.  So the zip checks here assert that the recorded mode and date_time
# are IGNORED.  That is conformance; wiring them up would be the deviation.
#
# WHOLE SECONDS.  Grail's os.stat answers an int st_mtime where CPython
# answers a float, so everything here compares int(st.st_mtime).
#
# The two archives are produced by CPython's own tarfile/zipfile;
# tests/scripts/make_archive_fixtures.py regenerates them and its --check mode
# (run by ci.yml) fails if the hex below is hand-edited.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import os
import shutil
import stat
import tarfile
import tempfile
import zipfile

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = type(e).__name__


_TARMODEHEX = (
    "1f8b08000000000002ffedd7cb4e84301406e0ae7d8a1a17eee0f4bef06108422344b94c290e8f2fd3892be3684c6021"
    "ffb729699ab038f94f4fbb9c6d8e568e28adf4754ddf4218e5c85a9df6ad54c4b8613b98a75886f597ec98ba7c0ced7b"
    "197d1697b861fdedcdfa3b464e696bb449fb82b4568c13eabfb9c957c1c73b0647cd7f98fb6c6a36efffc67c9f7f2199"
    "20a1b590e6daff9db2c8ff2e1eeef3e7b6cfa7062de0a0f93fb7f59697ff67fe9dfb21ff4e0b73191352fe9d94c8ff1e"
    "2ed5e7c3e87be4ffa0f99f7c9cdb3a5b6f810df3af6fdeff64d6f79fd4249d95d7f95f4adcfffbccff6bed11fd23e77f"
    "a81f6bfec4e330570d7f0965fb56f82586b28ac578ee7d5d746578f5613db2fc714cf8cdfb5f4852c61a9bce09eb9c45"
    "fef7709a87e8d101000000000000000000fea50f226d7dee00280000")

_ZIPMODEHEX = (
    "504b0304140000000800000021588cb2ebe209000000070000000d0000006d2f707269766174652e7478742b4e4d2e4a"
    "2de10200504b0304140000000800000021581d9dfb040c0000000a000000080000006d2f72756e2e73685356d44fcacc"
    "d32fcee00200504b030414000000080000002158a1efb6a80c0000000a0000000a0000006d2f776964652e7478742bcf"
    "4c4955c82f48cde30200504b030414000000080000002158be8af38207000000050000000c0000006d2f736574756964"
    "2e62696e2b2ecd4ce10200504b030414000000080000002158b201fbdc0900000007000000310000006d2f6f64276420"
    "3b20746f75636820677261696c5f657874726163745f70776e65645f6d61726b6572203b20782e7478742b2ccd2f494d"
    "e10200504b01021403140000000800000021588cb2ebe209000000070000000d00000000000000000000008001000000"
    "006d2f707269766174652e747874504b01021403140000000800000021581d9dfb040c0000000a000000080000000000"
    "000000000000ed01340000006d2f72756e2e7368504b0102140314000000080000002158a1efb6a80c0000000a000000"
    "0a0000000000000000000000ff01660000006d2f776964652e747874504b0102140314000000080000002158be8af382"
    "07000000050000000c0000000000000000000000ed099a0000006d2f7365747569642e62696e504b0102140314000000"
    "080000002158b201fbdc09000000070000003100000000000000000000008001cb0000006d2f6f642764203b20746f75"
    "636820677261696c5f657874726163745f70776e65645f6d61726b6572203b20782e747874504b050600000000050005"
    "0042010000230100000000")

ROOT = tempfile.mkdtemp(prefix='grail_meta_')
J = os.path.join

MARKER = 'grail_extract_pwned_marker'
HOSTILE = "m/od'd ; touch %s ; x.txt" % MARKER
# A filename cannot hold a '/', so an injected `touch MARKER' would land in
# whatever directory the command ran in.  All three plausible ones are checked.
PWNED_DIRS = [ROOT, tempfile.gettempdir(), os.getcwd()]

# Fixed instants, none of them "now": 2001-09-09, 2004-11-09, 2008-01-19,
# 2009-02-13, 2012-10-13.  A no-op utime leaves the file's creation time,
# which is none of these.
T_A = 1000000000
T_B = 1100000000
T_C = 1200000000
T_D = 1250000000
T_DIR = 1300000000
T_HOSTILE = 1350000000


def imode(path):
    return stat.S_IMODE(os.stat(path).st_mode)


def mtime(path):
    return int(os.stat(path).st_mtime)


def write(path, text, mode=None):
    f = open(path, 'w')
    f.write(text)
    f.close()
    if mode is not None:
        os.chmod(path, mode)
    return path


def unhex(h):
    return bytes.fromhex(h)


# ---------------------------------------------------------------- os.chmod

CH = J(ROOT, 'chmod')
os.mkdir(CH)

_p = write(J(CH, 'f.txt'), 'x')
rec('chmod_returns_none', lambda: os.chmod(_p, 0o600))
rec('chmod_restrictive', lambda: oct(imode(_p)))
os.chmod(_p, 0o755)
rec('chmod_permissive', lambda: oct(imode(_p)))
# A file left group/other-writable, then locked down: the direction a bug
# would silently skip.
os.chmod(_p, 0o666)
os.chmod(_p, 0o600)
rec('chmod_666_down_to_600', lambda: oct(imode(_p)))
# High (file-type) bits are ignored, as chmod(2) ignores them under CPython.
os.chmod(_p, 0o100640)
rec('chmod_ignores_high_bits', lambda: oct(imode(_p)))

_d = J(CH, 'sub')
os.mkdir(_d)
os.chmod(_d, 0o700)
rec('chmod_on_a_directory', lambda: oct(imode(_d)))

# A name that begins with '-' is an OPTION to chmod(1) unless the path is made
# unambiguous.  Quoting does not help: the shell strips the quotes before
# chmod sees argv.
_dash = write(J(CH, '-rw'), 'y')
os.chmod(_dash, 0o600)
rec('chmod_leading_dash_name', lambda: oct(imode(_dash)))

rec('chmod_missing_path', lambda: os.chmod(J(CH, 'nope'), 0o600))
rec('chmod_mode_not_an_int', lambda: os.chmod(_p, '0600'))

# ------------------------------------------------------- shutil.copystat

CS = J(ROOT, 'copystat')
os.mkdir(CS)

_src = write(J(CS, 'src.txt'), 'source', 0o600)
os.utime(_src, (T_A, T_B))
# The destination starts WIDE OPEN and with a different time, so nothing here
# can pass by accident.
_dst = write(J(CS, 'dst.txt'), 'dest', 0o666)
os.utime(_dst, (T_C, T_C))

rec('copystat_returns_none', lambda: shutil.copystat(_src, _dst))
rec('copystat_mode', lambda: oct(imode(_dst)))
rec('copystat_mtime', lambda: mtime(_dst))
rec('copystat_atime', lambda: int(os.stat(_dst).st_atime))
# The one check whose only job is to fail a no-op: the destination's mode and
# mtime must have MOVED OFF what they were set to a moment ago.
rec('copystat_moved_dst_off_its_own_values',
    lambda: (imode(_dst) != 0o666, mtime(_dst) != T_C))

_src2 = write(J(CS, 'src2.txt'), 's2', 0o755)
os.utime(_src2, (T_A, T_A))
_dst2 = write(J(CS, 'dst2.txt'), 'd2', 0o600)
os.utime(_dst2, (T_D, T_D))
rec('copymode_returns_none', lambda: shutil.copymode(_src2, _dst2))
rec('copymode_mode', lambda: oct(imode(_dst2)))
# copymode is MODE ONLY: the destination keeps its own time.  Both times here
# are fixed instants, so "they happen to be equal" cannot make this pass.
rec('copymode_leaves_mtime_alone', lambda: mtime(_dst2) == T_D)

# copyfile copies CONTENT ONLY -- CPython's does too, and a copystat that
# leaked into it would be a deviation.
_dst3 = J(CS, 'dst3.txt')
shutil.copyfile(_src, _dst3)
rec('copyfile_does_not_copy_mtime', lambda: mtime(_dst3) != T_B)

# --------------------------------------------------------- shutil.copy2

C2 = J(ROOT, 'copy2')
os.mkdir(C2)
_c2src = write(J(C2, 'a.txt'), 'alpha', 0o600)
os.utime(_c2src, (T_A, T_B))
_c2dst = J(C2, 'b.txt')
rec('copy2_returns_the_destination', lambda: shutil.copy2(_c2src, _c2dst) == _c2dst)
rec('copy2_content', lambda: open(_c2dst).read())
rec('copy2_mode', lambda: oct(imode(_c2dst)))
rec('copy2_mtime', lambda: mtime(_c2dst))
# copy() is copyfile + copymode in CPython: the MODE comes across, the times
# do not.  Grail's copy() dropped the mode until this lane, and the difference
# was invisible for exactly the reason the header gives -- the destination
# landed on 0o644 either way whenever the source was 0o644.  The source here
# is 0o600, so it is not invisible.
_cpdst = J(C2, 'c.txt')
shutil.copy(_c2src, _cpdst)
rec('copy_copies_the_mode', lambda: oct(imode(_cpdst)))
rec('copy_does_not_copy_mtime', lambda: mtime(_cpdst) != T_B)

# ------------------------------------------------------- shutil.copytree

CT = J(ROOT, 'copytree')
os.makedirs(J(CT, 'src', 'sub'))
write(J(CT, 'src', 'top.txt'), 'top', 0o600)
write(J(CT, 'src', 'sub', 'deep.txt'), 'deep', 0o755)
os.utime(J(CT, 'src', 'top.txt'), (T_A, T_A))
os.utime(J(CT, 'src', 'sub', 'deep.txt'), (T_B, T_B))
os.utime(J(CT, 'src', 'sub'), (T_C, T_C))
shutil.copytree(J(CT, 'src'), J(CT, 'dst'))
rec('copytree_file_mode', lambda: oct(imode(J(CT, 'dst', 'top.txt'))))
rec('copytree_file_mtime', lambda: mtime(J(CT, 'dst', 'top.txt')))
rec('copytree_nested_mode', lambda: oct(imode(J(CT, 'dst', 'sub', 'deep.txt'))))
rec('copytree_nested_mtime', lambda: mtime(J(CT, 'dst', 'sub', 'deep.txt')))
# A directory's mtime is stamped AFTER its contents are written; doing it
# before would be undone by the writes.
rec('copytree_directory_mtime', lambda: mtime(J(CT, 'dst', 'sub')))

# ---------------------------------------------------- tarfile extraction

TX = J(ROOT, 'tar')
os.mkdir(TX)
_tgz = J(TX, 'modes.tar.gz')
_f = open(_tgz, 'wb')
_f.write(unhex(_TARMODEHEX))
_f.close()
_out = J(TX, 'out')
os.mkdir(_out)
_t = tarfile.open(_tgz, 'r:gz')
_t.extractall(_out)
_t.close()

rec('tar_private_mode', lambda: oct(imode(J(_out, 'm', 'private.txt'))))
rec('tar_private_mtime', lambda: mtime(J(_out, 'm', 'private.txt')))
rec('tar_exec_mode', lambda: oct(imode(J(_out, 'm', 'run.sh'))))
rec('tar_exec_mtime', lambda: mtime(J(_out, 'm', 'run.sh')))
# 0o777 in the archive must be CLAMPED, not honoured: group/other write is
# dropped by CPython 3.14's default data filter, and by Grail unconditionally.
rec('tar_world_writable_is_clamped',
    lambda: oct(imode(J(_out, 'm', 'wide.txt'))))
# ... and setuid must not survive extraction at all.
rec('tar_setuid_is_stripped', lambda: oct(imode(J(_out, 'm', 'setuid.bin'))))
rec('tar_setuid_bit_gone',
    lambda: bool(imode(J(_out, 'm', 'setuid.bin')) & 0o4000))
# The directory's mtime, which the writes into it would have reset.
rec('tar_directory_mtime', lambda: mtime(J(_out, 'm')))
# The shell-syntax member: metadata landed...
rec('tar_hostile_name_mode',
    lambda: oct(imode(J(_out, HOSTILE))))
rec('tar_hostile_name_mtime', lambda: mtime(J(_out, HOSTILE)))
# ... and nothing the semicolons introduce ran.
rec('tar_no_injected_command_ran',
    lambda: [d for d in PWNED_DIRS if os.path.exists(J(d, MARKER))])
rec('tar_nothing_extra_in_the_output',
    lambda: sorted(os.listdir(J(_out, 'm'))) == sorted(
        ['private.txt', 'run.sh', 'wide.txt', 'setuid.bin',
         HOSTILE.split('/')[1]]))
# set_attrs=False must still be honoured.
_out2 = J(TX, 'out2')
os.mkdir(_out2)
_t = tarfile.open(_tgz, 'r:gz')
_t.extract(_t.getmember('m/private.txt'), _out2, False)
_t.close()
rec('tar_set_attrs_false_leaves_mtime',
    lambda: mtime(J(_out2, 'm', 'private.txt')) != T_A)

# ---------------------------------------------------- zipfile extraction

ZX = J(ROOT, 'zip')
os.mkdir(ZX)
_zp = J(ZX, 'modes.zip')
_f = open(_zp, 'wb')
_f.write(unhex(_ZIPMODEHEX))
_f.close()
_zout = J(ZX, 'out')
os.mkdir(_zout)
_z = zipfile.ZipFile(_zp)
_z.extractall(_zout)
_z.close()

# 2024-01-01T00:00:00 is what the archive records; CPython does not apply it,
# so an extracted file's mtime is "now" -- far past this fixed instant.
_ZIP_RECORDED = 1704067200
rec('zip_content_is_extracted',
    lambda: open(J(_zout, 'm', 'private.txt')).read())
rec('zip_does_not_restore_mtime',
    lambda: mtime(J(_zout, 'm', 'private.txt')) > _ZIP_RECORDED + 86400)
rec('zip_does_not_restore_mode',
    lambda: imode(J(_zout, 'm', 'run.sh')) != 0o755)
rec('zip_records_the_mode_it_ignores',
    lambda: oct(zipfile.ZipFile(_zp).getinfo('m/run.sh').external_attr >> 16))


def _rmtree(path):
    for name in os.listdir(path):
        p = J(path, name)
        if os.path.isdir(p):
            _rmtree(p)
        else:
            os.remove(p)
    os.rmdir(path)


def _chmod_all(path):
    os.chmod(path, 0o700)
    for name in os.listdir(path):
        p = J(path, name)
        if os.path.isdir(p):
            _chmod_all(p)
        else:
            os.chmod(p, 0o600)


def _teardown():
    # Everything was chmod'ed on the way through, including a 0o400 file and a
    # 0o700 directory, so make the tree writable again before removing it.
    _chmod_all(ROOT)
    _rmtree(ROOT)
    for d in PWNED_DIRS:
        if os.path.exists(J(d, MARKER)):
            os.remove(J(d, MARKER))


# Torn down AT IMPORT, not from the __main__ block, because the SUnit case that
# drives this file IMPORTS it -- once per test -- and never reaches __main__.
# Written the other way round first, this leaked 101 temp trees into /tmp in a
# single afternoon.  Everything above is already recorded in `r', so the checks
# read recorded answers and share no filesystem state.
_teardown()


# Generated by RUNNING CPython 3.14.6 -- `python3 tests/python/archive_metadata.py
# --emit'.  Never hand-edited: a table written from a Grail session pins Grail's
# CURRENT behaviour, bug and all, and then reads as conformance evidence forever.
EXPECTED = {
    'chmod_666_down_to_600': '0o600',
    'chmod_ignores_high_bits': '0o640',
    'chmod_leading_dash_name': '0o600',
    'chmod_missing_path': 'FileNotFoundError',
    'chmod_mode_not_an_int': 'TypeError',
    'chmod_on_a_directory': '0o700',
    'chmod_permissive': '0o755',
    'chmod_restrictive': '0o600',
    'chmod_returns_none': None,
    'copy2_content': 'alpha',
    'copy2_mode': '0o600',
    'copy2_mtime': 1100000000,
    'copy2_returns_the_destination': True,
    'copy_copies_the_mode': '0o600',
    'copy_does_not_copy_mtime': True,
    'copyfile_does_not_copy_mtime': True,
    'copymode_leaves_mtime_alone': True,
    'copymode_mode': '0o755',
    'copymode_returns_none': None,
    'copystat_atime': 1000000000,
    'copystat_mode': '0o600',
    'copystat_moved_dst_off_its_own_values': (True, True),
    'copystat_mtime': 1100000000,
    'copystat_returns_none': None,
    'copytree_directory_mtime': 1200000000,
    'copytree_file_mode': '0o600',
    'copytree_file_mtime': 1000000000,
    'copytree_nested_mode': '0o755',
    'copytree_nested_mtime': 1100000000,
    'tar_directory_mtime': 1300000000,
    'tar_exec_mode': '0o755',
    'tar_exec_mtime': 1100000000,
    'tar_hostile_name_mode': '0o600',
    'tar_hostile_name_mtime': 1350000000,
    'tar_no_injected_command_ran': [],
    'tar_nothing_extra_in_the_output': True,
    'tar_private_mode': '0o600',
    'tar_private_mtime': 1000000000,
    'tar_set_attrs_false_leaves_mtime': True,
    'tar_setuid_bit_gone': False,
    'tar_setuid_is_stripped': '0o755',
    'tar_world_writable_is_clamped': '0o755',
    'zip_content_is_extracted': 'secret\n',
    'zip_does_not_restore_mode': True,
    'zip_does_not_restore_mtime': True,
    'zip_records_the_mode_it_ignores': '0o755',
}


def zip_extract_restores_nothing():
    """A GRAIL/CPython AGREEMENT, stated as a check so it cannot rot quietly.

    If CPython ever starts restoring a zip member's metadata, this fixture's
    zip_does_not_restore_* checks turn into DIFFs here and the deviation
    becomes visible, rather than Grail silently falling behind.
    """
    return r['zip_does_not_restore_mtime'] is True


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r.get(k) == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-42s %s %r' % (k, 'OK ' if ok else 'DIFF', r.get(k)))
        print('%d difference(s)' % bad)
