# AN ASGI APP, SERVED.
#
# This is the first fixture in which Grail runs a PROTOCOL rather than exercising
# a primitive.  Every probe below is one or more real HTTP requests over a real
# loopback socket into `grail.asgi.Server`, and what makes that worth having is
# that a wrong answer is almost never localised: a request that comes back with
# the right status, headers and body has already required accept to hand over a
# usable socket, readiness to fire, a partial read to be resumed, a partial
# write to be finished, a task to be scheduled and a keep-alive connection to
# park without stalling anything else.  The socket fixtures test those one at a
# time; this tests them composed, which is the only way the failure modes that
# come from composition show up at all.
#
# WHERE THE SERVER LIVES: src/python/stdlib/grail_asgi.py, in the bundled
# importable tree beside flask / django / asgiref rather than in the ``grail``
# package.  Not a style choice -- importing any submodule of ``grail`` corrupts
# this session's import state, so the next unrelated import fails.  That is a
# pre-existing bug (``import grail.gemstone`` does it on a clean checkout, and
# the identical file under a package named ``grailx`` is fine), found by putting
# the server there first: it broke 80 tests further down the same SUnit shard.
#
# WHY THERE IS A SERVER TO TEST, given that uvicorn cannot run yet.  uvicorn
# asks the loop for create_server(protocol_factory, ...) and Grail has no
# transports, so "run an ASGI app" looks blocked.  But ASGI is just
# `async def app(scope, receive, send)`, and accept/read/write already exist as
# sock_accept/sock_recv/sock_sendall.  Transports are how CPython's asyncio
# prefers to REACH those calls, not a precondition for them -- so the server
# under test here is written straight onto the socket coroutines.
#
# THE PROBE THAT MATTERS MOST is `two_clients_interleave`, for the same reason
# `two_clients_served_concurrently` mattered in asyncio_io.py: every other probe
# here would also pass on a server that ran each connection to completion before
# looking at the next, which is precisely the bug a cooperative loop invites.
# It is arranged so that the only way to produce the recorded answer is for a
# handler that is waiting on a slow client to yield and for another handler to
# run to completion in the gap.
#
# THE SECOND MOST INTERESTING is `keep_alive_then_a_second_request`.  A
# keep-alive connection is the one case where bytes for request N+1 arrive in
# the same read that finished request N, so a server with a per-request buffer
# discards them and then waits forever for a request it has already been sent.
# That bug cannot be reached by any single-request test.
#
# NOT COVERED, because the server does not claim it: TLS, HTTP/2, WebSocket,
# chunked request bodies (refused, and there is a probe for the refusal),
# streaming request bodies (delivered as one message), and timeouts.
#
# Everything here is ordinary CPython: asyncio, socket, and an ASGI app written
# to the published interface.  The server module itself is pure Python with no
# Grail-specific spelling, which is what lets this file be ground truth rather
# than a description of what Grail happens to do.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import asyncio
import os
import socket
import sys

# Grail finds grail_asgi on its own -- src/python/stdlib is one of its standard
# search roots -- so this dance is purely for running the fixture under CPython.
#
# APPENDED, not inserted.  src/python/stdlib holds Grail's PORTS of the stdlib
# (types.py, enum.py, ...), so putting it at the front under CPython shadows
# CPython's own and the first ``import types'' dies in a circular import.  Last
# place is safe: nothing else on the path provides ``grail_asgi'', and every
# real stdlib name still resolves to CPython's.  Removed again afterwards,
# because sys.path is session state under Grail and a fixture that leaves an
# entry behind changes how everything imported after it resolves.
_STDLIB = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    'src', 'python', 'stdlib')
_added = _STDLIB not in sys.path
if _added:
    sys.path.append(_STDLIB)
try:
    from grail_asgi import Server
finally:
    if _added and _STDLIB in sys.path:
        sys.path.remove(_STDLIB)

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- a client, written on the same loop as the server ----------------------
#
# Deliberately NOT the blocking socket module and not http.client: those would
# need a thread to run alongside the server, and on Grail's cooperative loop a
# blocking read is a stalled gem rather than a stalled thread.  Driving both
# ends from the one loop is also a stronger test -- it means the server has to
# yield for the client to make progress at all.

class _Conn:
    """A client connection with a buffer that OUTLIVES one response.

    The buffer has to live on the connection rather than in the read call, and
    the reason is the same one that applies to the server: on a keep-alive
    connection the read that completes response N routinely also contains the
    start of response N+1.  A per-call buffer discards those bytes and then
    waits forever for a response it has already received.

    This was not a hypothesis.  The first version of this helper did buffer
    per call, and `both_requests_pipelined_into_one_write` hung under CPython --
    which is a fair result for a probe written to catch exactly that mistake,
    just on the wrong side of the socket."""

    def __init__(self, loop, sock):
        self.loop = loop
        self.sock = sock
        self.buf = bytearray()

    async def send(self, raw):
        await self.loop.sock_sendall(self.sock, raw)

    async def _fill(self):
        """Read more; answer False at EOF."""
        chunk = await self.loop.sock_recv(self.sock, 65536)
        if not chunk:
            return False
        self.buf.extend(chunk)
        return True

    async def read_response(self):
        """Read one complete response; answer (status, headers, body).

        Completeness is decided by content-length when there is one and by EOF
        when there is not -- exactly the rule the server writes to, see
        Server._should_keep_alive.  A client that guessed differently would
        hang on a perfectly correct response."""
        while True:
            end = bytes(self.buf).find(b'\r\n\r\n')
            if end >= 0:
                break
            if not await self._fill():
                raise AssertionError('closed inside the response head')
        head = bytes(self.buf[:end])
        del self.buf[:end + 4]
        lines = head.split(b'\r\n')
        status = int(lines[0].split(b' ')[1])
        headers = []
        for line in lines[1:]:
            if line:
                name, _, value = line.partition(b':')
                headers.append((name.lower(), value.strip()))
        length = None
        for name, value in headers:
            if name == b'content-length':
                length = int(value)
        if length is None:
            # Framed by the close, so read to EOF.
            while await self._fill():
                pass
            body = bytes(self.buf)
            del self.buf[:]
            return status, headers, body
        while len(self.buf) < length:
            if not await self._fill():
                raise AssertionError('closed inside the response body')
        body = bytes(self.buf[:length])
        del self.buf[:length]
        return status, headers, body

    async def recv_raw(self, n):
        """Whatever is buffered, else one read.  Used only where a probe is
        asking whether the server closed."""
        if self.buf:
            out = bytes(self.buf[:n])
            del self.buf[:n]
            return out
        return await self.loop.sock_recv(self.sock, n)

    def close(self):
        self.sock.close()


async def _connect(loop, address):
    sock = socket.socket()
    sock.setblocking(False)
    await loop.sock_connect(sock, address)
    return _Conn(loop, sock)


async def _request(loop, address, raw):
    """One request on a fresh connection; answer (status, headers, body)."""
    conn = await _connect(loop, address)
    try:
        await conn.send(raw)
        return await conn.read_response()
    finally:
        conn.close()


def _get(path='/', host='x'):
    return ('GET %s HTTP/1.1\r\nhost: %s\r\n\r\n' % (path, host)).encode('ascii')


# --- apps ------------------------------------------------------------------

def _text_app(body=b'hello', status=200, extra=()):
    """The ordinary shape: one start, one body, a content-length."""
    async def app(scope, receive, send):
        await receive()
        headers = [(b'content-type', b'text/plain'),
                   (b'content-length', str(len(body)).encode('ascii'))]
        headers.extend(extra)
        await send({'type': 'http.response.start', 'status': status,
                    'headers': headers})
        await send({'type': 'http.response.body', 'body': body})
    return app


def _echo_scope_app(keys):
    """Answers the requested scope keys, one per line, so a probe can assert on
    what the app actually saw rather than on what the server logged."""
    async def app(scope, receive, send):
        parts = []
        for key in keys:
            parts.append('%s=%r' % (key, scope.get(key)))
        body = ('\n'.join(parts)).encode('utf-8')
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})
    return app


async def _with_server(app, fn, **kw):
    """Start a server, run fn(loop, address), stop it.  Always stops -- a
    leaked listener would make the NEXT probe fail, which is the worst kind of
    test failure to read."""
    loop = asyncio.get_event_loop()
    server = Server(app, host='127.0.0.1', port=0, **kw)
    address = await server.start()
    try:
        return await fn(loop, address)
    finally:
        await server.stop()


# --- the basics ------------------------------------------------------------

async def a_get_returns_the_apps_bytes():
    async def probe(loop, address):
        status, headers, body = await _request(loop, address, _get('/'))
        return status, body, dict(headers).get(b'content-type')
    return await _with_server(_text_app(), probe)


async def the_scope_the_app_sees():
    app = _echo_scope_app(['type', 'method', 'scheme', 'http_version',
                           'path', 'query_string', 'root_path'])
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address,
                                     _get('/items/7?limit=2&q=x'))
        return body.decode('utf-8')
    return await _with_server(app, probe)


async def headers_reach_the_app_lowercased():
    """ASGI requires lower-cased header names, and values as raw bytes with the
    surrounding whitespace stripped."""
    async def app(scope, receive, send):
        found = [(n, v) for (n, v) in scope['headers']
                 if n in (b'x-mixed-case', b'x-padded')]
        body = repr(sorted(found)).encode('utf-8')
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})
    raw = (b'GET / HTTP/1.1\r\nhost: x\r\n'
           b'X-Mixed-Case: Value\r\n'
           b'x-padded:    spaced   \r\n\r\n')
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address, raw)
        return body.decode('utf-8')
    return await _with_server(app, probe)


async def a_post_body_reaches_the_app():
    async def app(scope, receive, send):
        message = await receive()
        body = b'%s|%s|%s' % (message['type'].encode('ascii'),
                              message['body'],
                              repr(message['more_body']).encode('ascii'))
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})
    raw = (b'POST /submit HTTP/1.1\r\nhost: x\r\ncontent-length: 11\r\n\r\n'
           b'hello=world')
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address, raw)
        return body.decode('utf-8')
    return await _with_server(app, probe)


async def path_is_decoded_and_raw_path_is_not():
    """The distinction matters for security, not tidiness: a traversal check
    written against `path` sees the decoded `/a/../b`, so anything that must
    reject an ENCODED slash has to read `raw_path`."""
    app = _echo_scope_app(['path', 'raw_path'])
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address, _get('/a%2Fb/c%20d'))
        return body.decode('utf-8')
    return await _with_server(app, probe)


async def a_status_other_than_200_round_trips():
    async def probe(loop, address):
        status, headers, body = await _request(loop, address, _get('/missing'))
        return status, body
    return await _with_server(_text_app(b'nope', status=404), probe)


# --- keep-alive ------------------------------------------------------------

async def keep_alive_then_a_second_request():
    """TWO requests on ONE connection, and the second is sent immediately after
    the first response is read -- so its head very often arrives in the same
    read that completed the first response's body.  A server that buffers per
    request drops those bytes and then waits forever."""
    async def probe(loop, address):
        sock = await _connect(loop, address)
        try:
            out = []
            for path in ('/one', '/two'):
                await sock.send(_get(path))
                status, headers, body = await sock.read_response()
                out.append((status, body, dict(headers).get(b'connection')))
            return out
        finally:
            sock.close()
    return await _with_server(_text_app(), probe)


async def both_requests_pipelined_into_one_write():
    """Both requests in a SINGLE send, so the server certainly has request 2 in
    its buffer before it has answered request 1.  This is the read-ahead case
    stated as sharply as it can be."""
    async def probe(loop, address):
        sock = await _connect(loop, address)
        try:
            await sock.send(_get('/a') + _get('/b'))
            first = await sock.read_response()
            second = await sock.read_response()
            return first[0], second[0], first[2], second[2]
        finally:
            sock.close()
    return await _with_server(_text_app(), probe)


async def no_content_length_closes_the_connection():
    """A response with no content-length is framed by the CLOSE, so the server
    must not keep the connection open -- the client would wait for bytes that
    are never coming."""
    async def app(scope, receive, send):
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-type', b'text/plain')]})
        await send({'type': 'http.response.body', 'body': b'unsized'})
    async def probe(loop, address):
        sock = await _connect(loop, address)
        try:
            await sock.send(_get('/'))
            status, headers, body = await sock.read_response()
            # Reading to EOF is how _read_response framed it, so getting the
            # body at all proves the server closed.
            return status, body, dict(headers).get(b'connection')
        finally:
            sock.close()
    return await _with_server(app, probe)


async def connection_close_from_the_client_is_honoured():
    async def probe(loop, address):
        sock = await _connect(loop, address)
        try:
            await sock.send(
                b'GET / HTTP/1.1\r\nhost: x\r\nconnection: close\r\n\r\n')
            status, headers, _body = await sock.read_response()
            after = await sock.recv_raw(100)
            return status, dict(headers).get(b'connection'), after
        finally:
            sock.close()
    return await _with_server(_text_app(), probe)


async def http_1_0_gets_no_keep_alive():
    async def probe(loop, address):
        sock = await _connect(loop, address)
        try:
            await sock.send(b'GET / HTTP/1.0\r\nhost: x\r\n\r\n')
            status, headers, _b = await sock.read_response()
            return status, dict(headers).get(b'connection')
        finally:
            sock.close()
    return await _with_server(_text_app(), probe)


# --- the headline: concurrency ---------------------------------------------

async def two_clients_interleave():
    """The probe a sequential server cannot pass.

    The app waits for a per-path event.  Client SLOW connects first and its
    handler parks; client FAST connects second and is released immediately.  The
    recorded answer is the completion ORDER, so serving in arrival order --
    which is what a server that runs each connection to completion does --
    produces ['slow', 'fast'] instead."""
    released = {}

    async def app(scope, receive, send):
        name = scope['path'].strip('/')
        await released[name]
        body = name.encode('ascii')
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})

    async def probe(loop, address):
        # A Future rather than the asyncio.Event this obviously wants: Grail's
        # asyncio has no Event yet (nor Lock / Semaphore / Queue -- the next
        # small increment).  A Future awaited once and resolved once is the same
        # guarantee here, and it is ordinary CPython either way, so the probe
        # stays valid ground truth.
        released['slow'] = loop.create_future()
        released['fast'] = loop.create_future()
        order = []

        async def client(name):
            _s, _h, body = await _request(loop, address, _get('/' + name))
            order.append(body.decode('ascii'))

        slow = asyncio.get_event_loop().create_task(client('slow'))
        # Let the slow client connect and its handler reach the wait before the
        # fast one exists at all, so arrival order and completion order differ.
        await asyncio.sleep(0.05)
        fast = asyncio.get_event_loop().create_task(client('fast'))
        await asyncio.sleep(0.05)
        released['fast'].set_result(True)
        await fast
        released['slow'].set_result(True)
        await slow
        return order
    return await _with_server(app, probe)


async def many_clients_are_all_served():
    """Eight concurrent connections, each asking for its own path.  Asserts the
    SET of answers, not the order: the order is a scheduling detail and pinning
    it would be pinning local timing, which has already cost this repo three CI
    failures."""
    async def app(scope, receive, send):
        body = scope['path'].strip('/').encode('ascii')
        await asyncio.sleep(0)      # force at least one yield per handler
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})

    async def probe(loop, address):
        async def one(n):
            _s, _h, body = await _request(loop, address, _get('/%d' % n))
            return body.decode('ascii')
        results = await asyncio.gather(*[one(n) for n in range(8)])
        return sorted(results)
    return await _with_server(app, probe)


async def a_big_response_survives_partial_writes():
    """256 KiB is well past any loopback socket buffer, so sock_sendall has to
    park on writability and resume -- several times."""
    payload = (b'0123456789abcdef' * 16384)          # 256 KiB
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address, _get('/'))
        return len(body), body == payload
    return await _with_server(_text_app(payload), probe)


async def a_big_request_body_survives_partial_reads():
    payload = b'x' * 200000
    async def app(scope, receive, send):
        message = await receive()
        got = message['body']
        body = ('%d %s' % (len(got), got == payload)).encode('ascii')
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})
    raw = (b'POST / HTTP/1.1\r\nhost: x\r\ncontent-length: 200000\r\n\r\n'
           + payload)
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address, raw)
        return body.decode('ascii')
    return await _with_server(app, probe)


async def a_streamed_response_arrives_whole():
    """Several http.response.body messages with more_body, which is how a real
    app streams.  The content-length makes it keep-alive-able even so."""
    async def app(scope, receive, send):
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length', b'9')]})
        for part in (b'abc', b'def', b'ghi'):
            await send({'type': 'http.response.body', 'body': part,
                        'more_body': part != b'ghi'})
    async def probe(loop, address):
        status, _h, body = await _request(loop, address, _get('/'))
        return status, body
    return await _with_server(app, probe)


# --- failure paths ---------------------------------------------------------

async def an_app_that_raises_gets_a_500():
    """Nothing has been written yet, so a 500 is still possible -- and far more
    useful to the client than a dropped connection."""
    async def app(scope, receive, send):
        raise RuntimeError('boom')
    async def probe(loop, address):
        status, _h, body = await _request(loop, address, _get('/'))
        return status, body
    return await _with_server(app, probe)


async def an_app_that_sends_nothing_gets_a_500():
    async def app(scope, receive, send):
        return None
    async def probe(loop, address):
        status, _h, _b = await _request(loop, address, _get('/'))
        return status
    return await _with_server(app, probe)


async def an_app_that_raises_mid_response_drops_the_connection():
    """Once the head is out a 500 is impossible -- the status has been sent.  So
    the connection ends, which is the only signal left that says "incomplete"."""
    async def app(scope, receive, send):
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length', b'100')]})
        await send({'type': 'http.response.body', 'body': b'partial',
                    'more_body': True})
        raise RuntimeError('boom')
    async def probe(loop, address):
        sock = await _connect(loop, address)
        try:
            await sock.send(_get('/'))
            got = bytearray()
            while True:
                chunk = await sock.recv_raw(65536)
                if not chunk:
                    break
                got.extend(chunk)
            head, _, body = bytes(got).partition(b'\r\n\r\n')
            return head.split(b'\r\n')[0], body, len(body) < 100
        finally:
            sock.close()
    return await _with_server(app, probe)


async def a_malformed_request_line_gets_400():
    async def probe(loop, address):
        status, _h, body = await _request(
            loop, address, b'NOTAREQUEST\r\nhost: x\r\n\r\n')
        return status, body
    return await _with_server(_text_app(), probe)


async def an_unsupported_http_version_gets_505():
    async def probe(loop, address):
        status, _h, _b = await _request(
            loop, address, b'GET / HTTP/2.0\r\nhost: x\r\n\r\n')
        return status
    return await _with_server(_text_app(), probe)


async def a_chunked_request_body_is_refused():
    """411 rather than treating the body as empty.  An app that receives an
    empty body where one was sent does not fail -- it succeeds WRONGLY."""
    async def probe(loop, address):
        status, _h, _b = await _request(
            loop, address,
            b'POST / HTTP/1.1\r\nhost: x\r\ntransfer-encoding: chunked\r\n\r\n')
        return status
    return await _with_server(_text_app(), probe)


async def an_oversized_head_gets_431():
    async def probe(loop, address):
        raw = (b'GET / HTTP/1.1\r\nhost: x\r\nx-pad: ' + b'A' * 5000
               + b'\r\n\r\n')
        status, _h, _b = await _request(loop, address, raw)
        return status
    return await _with_server(_text_app(), probe, max_head_bytes=2048)


async def a_folded_header_is_refused():
    """Obsolete line folding, removed by RFC 7230 and a known request-smuggling
    vector.  Refused rather than unfolded."""
    async def probe(loop, address):
        raw = b'GET / HTTP/1.1\r\nhost: x\r\nx-a: one\r\n  two\r\n\r\n'
        status, _h, _b = await _request(loop, address, raw)
        return status
    return await _with_server(_text_app(), probe)


async def a_client_that_hangs_up_costs_nothing():
    """Connect and close without sending: the ordinary end of a keep-alive
    connection, and it must not be an error.  The following request proves the
    server is still serving."""
    async def probe(loop, address):
        sock = await _connect(loop, address)
        sock.close()
        await asyncio.sleep(0.05)
        status, _h, body = await _request(loop, address, _get('/'))
        return status, body
    return await _with_server(_text_app(), probe)


async def receive_after_the_body_reports_disconnect():
    async def app(scope, receive, send):
        first = await receive()
        second = await receive()
        body = ('%s,%s' % (first['type'], second['type'])).encode('ascii')
        await send({'type': 'http.response.start', 'status': 200,
                    'headers': [(b'content-length',
                                 str(len(body)).encode('ascii'))]})
        await send({'type': 'http.response.body', 'body': body})
    async def probe(loop, address):
        _s, _h, body = await _request(loop, address, _get('/'))
        return body.decode('ascii')
    return await _with_server(app, probe)


async def stop_closes_the_listener():
    """After stop the port must refuse, not accept-and-hang.  ConnectionRefused
    is the answer; the errno itself is platform-specific, so only the exception
    NAME is recorded."""
    loop = asyncio.get_event_loop()
    server = Server(_text_app(), host='127.0.0.1', port=0)
    address = await server.start()
    status, _h, _b = await _request(loop, address, _get('/'))
    await server.stop()
    try:
        await _request(loop, address, _get('/'))
        return status, 'connected'
    except OSError as exc:
        return status, type(exc).__name__


async def stop_cancels_a_parked_keep_alive_connection():
    """A keep-alive connection is parked in sock_recv with no natural end, so
    `stop` has to cancel it.  Answers the number of live connection tasks after
    stop -- a server that only closed its listener would leave one behind, and
    the loop would then never finish."""
    server = None

    async def probe(loop, address):
        sock = await _connect(loop, address)
        await sock.send(_get('/'))
        await sock.read_response()
        live_before = len(server._connections)
        await server.stop()
        live_after = len(server._connections)
        sock.close()
        return live_before, live_after

    loop = asyncio.get_event_loop()
    server = Server(_text_app(), host='127.0.0.1', port=0)
    address = await server.start()
    try:
        return await probe(loop, address)
    finally:
        await server.stop()


# --- the whole suite as one coroutine --------------------------------------
#
# One asyncio.run for all the probes rather than one each: `run` closes the loop
# it made, and a fixture that opened and closed twenty loops would be testing
# loop teardown as much as anything else.

_PROBES = [
    ('a_get_returns_the_apps_bytes', a_get_returns_the_apps_bytes),
    ('the_scope_the_app_sees', the_scope_the_app_sees),
    ('headers_reach_the_app_lowercased', headers_reach_the_app_lowercased),
    ('a_post_body_reaches_the_app', a_post_body_reaches_the_app),
    ('path_is_decoded_and_raw_path_is_not', path_is_decoded_and_raw_path_is_not),
    ('a_status_other_than_200_round_trips', a_status_other_than_200_round_trips),
    ('keep_alive_then_a_second_request', keep_alive_then_a_second_request),
    ('both_requests_pipelined_into_one_write',
     both_requests_pipelined_into_one_write),
    ('no_content_length_closes_the_connection',
     no_content_length_closes_the_connection),
    ('connection_close_from_the_client_is_honoured',
     connection_close_from_the_client_is_honoured),
    ('http_1_0_gets_no_keep_alive', http_1_0_gets_no_keep_alive),
    ('two_clients_interleave', two_clients_interleave),
    ('many_clients_are_all_served', many_clients_are_all_served),
    ('a_big_response_survives_partial_writes',
     a_big_response_survives_partial_writes),
    ('a_big_request_body_survives_partial_reads',
     a_big_request_body_survives_partial_reads),
    ('a_streamed_response_arrives_whole', a_streamed_response_arrives_whole),
    ('an_app_that_raises_gets_a_500', an_app_that_raises_gets_a_500),
    ('an_app_that_sends_nothing_gets_a_500', an_app_that_sends_nothing_gets_a_500),
    ('an_app_that_raises_mid_response_drops_the_connection',
     an_app_that_raises_mid_response_drops_the_connection),
    ('a_malformed_request_line_gets_400', a_malformed_request_line_gets_400),
    ('an_unsupported_http_version_gets_505',
     an_unsupported_http_version_gets_505),
    ('a_chunked_request_body_is_refused', a_chunked_request_body_is_refused),
    ('an_oversized_head_gets_431', an_oversized_head_gets_431),
    ('a_folded_header_is_refused', a_folded_header_is_refused),
    ('a_client_that_hangs_up_costs_nothing', a_client_that_hangs_up_costs_nothing),
    ('receive_after_the_body_reports_disconnect',
     receive_after_the_body_reports_disconnect),
    ('stop_closes_the_listener', stop_closes_the_listener),
    ('stop_cancels_a_parked_keep_alive_connection',
     stop_cancels_a_parked_keep_alive_connection),
]


async def _run_all():
    for name, probe in _PROBES:
        try:
            r[name] = await probe()
        except BaseException as e:
            r[name] = '%s: %s' % (type(e).__name__, e)


asyncio.run(_run_all())


EXPECTED = {
    'a_get_returns_the_apps_bytes': (200, b'hello', b'text/plain'),
    'the_scope_the_app_sees': "type='http'\nmethod='GET'\nscheme='http'\nhttp_version='1.1'\npath='/items/7'\nquery_string=b'limit=2&q=x'\nroot_path=''",
    'headers_reach_the_app_lowercased': "[(b'x-mixed-case', b'Value'), (b'x-padded', b'spaced')]",
    'a_post_body_reaches_the_app': 'http.request|hello=world|False',
    'path_is_decoded_and_raw_path_is_not': "path='/a/b/c d'\nraw_path=b'/a%2Fb/c%20d'",
    'a_status_other_than_200_round_trips': (404, b'nope'),
    'keep_alive_then_a_second_request': [(200, b'hello', b'keep-alive'), (200, b'hello', b'keep-alive')],
    'both_requests_pipelined_into_one_write': (200, 200, b'hello', b'hello'),
    'no_content_length_closes_the_connection': (200, b'unsized', b'close'),
    'connection_close_from_the_client_is_honoured': (200, b'close', b''),
    'http_1_0_gets_no_keep_alive': (200, b'close'),
    'two_clients_interleave': ['fast', 'slow'],
    'many_clients_are_all_served': ['0', '1', '2', '3', '4', '5', '6', '7'],
    'a_big_response_survives_partial_writes': (262144, True),
    'a_big_request_body_survives_partial_reads': '200000 True',
    'a_streamed_response_arrives_whole': (200, b'abcdefghi'),
    'an_app_that_raises_gets_a_500': (500, b'500 Internal Server Error\n'),
    'an_app_that_sends_nothing_gets_a_500': 500,
    'an_app_that_raises_mid_response_drops_the_connection': (b'HTTP/1.1 200 OK', b'partial', True),
    'a_malformed_request_line_gets_400': (400, b'400 Bad Request\n'),
    'an_unsupported_http_version_gets_505': 505,
    'a_chunked_request_body_is_refused': 411,
    'an_oversized_head_gets_431': 431,
    'a_folded_header_is_refused': 400,
    'a_client_that_hangs_up_costs_nothing': (200, b'hello'),
    'receive_after_the_body_reports_disconnect': 'http.request,http.disconnect',
    'stop_closes_the_listener': (200, 'ConnectionRefusedError'),
    'stop_cancels_a_parked_keep_alive_connection': (1, 0),
}


def _emit():
    print('EXPECTED = {')
    for name, _probe in _PROBES:
        print('    %r: %r,' % (name, r[name]))
    print('}')


def _check():
    ok = fail = 0
    for name, _probe in _PROBES:
        got = r[name]
        want = EXPECTED.get(name, '<missing>')
        if got == want:
            ok += 1
            print('  OK    %s' % name)
        else:
            fail += 1
            print('  FAIL  %s\n          got  %r\n          want %r'
                  % (name, got, want))
    print('%d OK, %d FAIL' % (ok, fail))
    return fail


if __name__ == '__main__':
    if '--emit' in sys.argv:
        _emit()
    else:
        sys.exit(1 if _check() else 0)
