# ``async for'' -- ASYNC ITERATION, and the types that name async objects.
#
# `async for x in obj` is not `for` with a keyword in front. It is a different
# protocol at all three points:
#
#     obj.__aiter__()          gives the iterator   (an ordinary method)
#     await it.__anext__()     gives each item      (an AWAITABLE)
#     StopAsyncIteration       ends the loop        (NOT a StopIteration)
#
# Grail emitted `async for` as a plain synchronous `for` -- AsyncForAst
# inherited ForAst's codegen and said so in its header -- so __aiter__ and
# __anext__ were never consulted and iterating a real async iterator raised
# `TypeError: object is not iterable`. Everything starlette and anyio iterate
# (request bodies, task groups, streams) is an async iterator.
#
# The awaited __anext__ is what makes this more than a rename: a suspension
# INSIDE __anext__ has to suspend the whole loop and reach the driver, which is
# how a server yields between chunks of a streaming body. That is probed below
# and is the check a synchronous loop cannot fake.
#
# ALSO HERE: the type names. `types.CoroutineType` and `types.GeneratorType`
# were bare placeholder classes, so `type(coro) is types.CoroutineType` was
# False about a real coroutine -- and `inspect.iscoroutine()` was hardcoded
# `return False`. Those are dispatch decisions, not trivia: asgiref, anyio and
# starlette all ask `iscoroutine(result)` to decide whether to await what a
# call returned, and False means the body never runs.
#
# NOT PROBED, because Grail does not model it: an `async def` containing
# `yield` is an ASYNC GENERATOR upstream and a distinct type; Grail answers a
# coroutine, which has no __aiter__, so `async for` over one raises. Pinned as
# a known gap in AsyncIterationTestCase rather than recorded here as if CPython
# agreed.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import inspect
import types

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def drive(c):
    """Run a coroutine that never suspends; answer what it returned."""
    try:
        c.send(None)
        return 'did not finish'
    except StopIteration as e:
        return e.value


class Counter:
    """The ordinary async iterator: __aiter__ returns self, __anext__ is async."""

    def __init__(self, n):
        self.i = 0
        self.n = n

    def __aiter__(self):
        return self

    async def __anext__(self):
        self.i += 1
        if self.i > self.n:
            raise StopAsyncIteration
        return self.i


# --- the loop itself --------------------------------------------------------

def _basic():
    async def f():
        total = 0
        async for v in Counter(3):
            total += v
        return total
    return drive(f())


def _empty_iterator_runs_body_zero_times():
    async def f():
        seen = []
        async for v in Counter(0):
            seen.append(v)
        return seen
    return drive(f())


# --- the shared loop machinery must still apply -----------------------------
#
# break / continue / for-else / tuple unpacking are identical to `for`, which is
# the reason the implementation shares ForAst's codegen rather than copying it.
# These are the checks that the sharing is real.

def _break():
    async def f():
        seen = []
        async for v in Counter(5):
            if v == 3:
                break
            seen.append(v)
        return seen
    return drive(f())


def _continue():
    async def f():
        seen = []
        async for v in Counter(4):
            if v % 2:
                continue
            seen.append(v)
        return seen
    return drive(f())


def _else_on_natural_drain():
    async def f():
        seen = []
        async for v in Counter(2):
            seen.append(v)
        else:
            seen.append('else')
        return seen
    return drive(f())


def _break_skips_else():
    async def f():
        seen = []
        async for v in Counter(5):
            seen.append(v)
            break
        else:
            seen.append('else')
        return seen
    return drive(f())


def _tuple_unpacking():
    class Pairs:
        def __init__(self):
            self.i = 0

        def __aiter__(self):
            return self

        async def __anext__(self):
            self.i += 1
            if self.i > 2:
                raise StopAsyncIteration
            return (self.i, self.i * 10)

    async def f():
        seen = []
        async for a, b in Pairs():
            seen.append((a, b))
        return seen
    return drive(f())


def _nested_async_for():
    # Two loops in one coroutine: the temp-name disambiguation ForAst does by
    # nesting depth has to hold for the async emit too.
    async def f():
        seen = []
        async for a in Counter(2):
            async for b in Counter(2):
                seen.append((a, b))
        return seen
    return drive(f())


def _exception_from_anext_propagates():
    class Boom:
        def __aiter__(self):
            return self

        async def __anext__(self):
            raise ValueError('from anext')

    async def f():
        async for v in Boom():
            pass
    try:
        drive(f())
        return 'no exception'
    except ValueError as e:
        return ('ValueError', str(e))


# --- THE PAYOFF: a suspension inside __anext__ suspends the whole loop ------

class Parker:
    """__anext__ awaits something that parks, as a streaming read would."""

    def __init__(self, n):
        self.i = 0
        self.n = n

    def __aiter__(self):
        return self

    async def __anext__(self):
        self.i += 1
        if self.i > self.n:
            raise StopAsyncIteration
        return await _Suspend(self.i)


class _Suspend:
    def __init__(self, i):
        self.i = i

    def __await__(self):
        sent = yield ('park', self.i)
        return sent


def _suspension_inside_anext_reaches_the_driver():
    async def f():
        seen = []
        async for v in Parker(2):
            seen.append(v)
        return seen
    c = f()
    parked = []
    send_value = None
    while True:
        try:
            parked.append(c.send(send_value))
            send_value = 'v%d' % len(parked)
        except StopIteration as e:
            return (parked, e.value)


# --- the protocol errors ----------------------------------------------------

def _sync_iterable_is_rejected():
    async def f():
        async for v in [1, 2]:
            pass
    try:
        drive(f())
        return 'no exception'
    except TypeError as e:
        return ('TypeError', str(e))


def _aiter_without_anext_is_rejected():
    class NoNext:
        def __aiter__(self):
            return self

    async def f():
        async for v in NoNext():
            pass
    try:
        drive(f())
        return 'no exception'
    except TypeError as e:
        return ('TypeError', str(e))


def _aiter_returning_a_non_iterator_is_rejected():
    # CPython names the type of what __aiter__ RETURNED, not the original -- so
    # the check is on the result, at the loop head.
    class BadAiter:
        def __aiter__(self):
            return 42

    async def f():
        async for v in BadAiter():
            pass
    try:
        drive(f())
        return 'no exception'
    except TypeError as e:
        return ('TypeError', str(e))


# --- the type names, and the predicates that read them ----------------------

def _coroutine_type_names_the_real_class():
    async def c():
        pass
    co = c()
    try:
        return (type(co) is types.CoroutineType,
                isinstance(co, types.CoroutineType))
    finally:
        co.close()


def _generator_type_names_the_real_class():
    def g():
        yield 1
    return (type(g()) is types.GeneratorType,
            isinstance(g(), types.GeneratorType))


def _the_run_async_assertion_holds():
    # The exact expression CPython's own test_coroutines opens run_async with.
    # A placeholder types.CoroutineType made this False, so all ~99 tests of
    # that module failed at the assert with a bare, message-less AssertionError.
    async def c():
        pass
    co = c()
    try:
        return co.__class__ in {types.GeneratorType, types.CoroutineType}
    finally:
        co.close()


def _inspect_predicates():
    async def c():
        pass

    def g():
        yield 1
    co = c()
    try:
        return (inspect.iscoroutine(co),
                inspect.isgenerator(g()),
                inspect.iscoroutine(g()),
                inspect.isgenerator(co))
    finally:
        co.close()


def _types_coroutine_returns_a_callable_and_rejects_non_callables():
    @types.coroutine
    def gen_based():
        yield 'from-gen'
        return 'done'
    out = [callable(gen_based)]
    try:
        types.coroutine(42)
        out.append('no exception')
    except TypeError as e:
        out.append(('TypeError', str(e)))
    return out


rec('basic', _basic)
rec('empty_iterator_runs_body_zero_times', _empty_iterator_runs_body_zero_times)
rec('break', _break)
rec('continue', _continue)
rec('else_on_natural_drain', _else_on_natural_drain)
rec('break_skips_else', _break_skips_else)
rec('tuple_unpacking', _tuple_unpacking)
rec('nested_async_for', _nested_async_for)
rec('exception_from_anext_propagates', _exception_from_anext_propagates)
rec('suspension_inside_anext_reaches_the_driver',
    _suspension_inside_anext_reaches_the_driver)
rec('sync_iterable_is_rejected', _sync_iterable_is_rejected)
rec('aiter_without_anext_is_rejected', _aiter_without_anext_is_rejected)
rec('aiter_returning_a_non_iterator_is_rejected',
    _aiter_returning_a_non_iterator_is_rejected)
rec('coroutine_type_names_the_real_class', _coroutine_type_names_the_real_class)
rec('generator_type_names_the_real_class', _generator_type_names_the_real_class)
rec('the_run_async_assertion_holds', _the_run_async_assertion_holds)
rec('inspect_predicates', _inspect_predicates)
rec('types_coroutine_returns_a_callable_and_rejects_non_callables',
    _types_coroutine_returns_a_callable_and_rejects_non_callables)


EXPECTED = {
    'aiter_returning_a_non_iterator_is_rejected': ('TypeError', "'async for' received an object from __aiter__ that does not implement __anext__: int"),
    'aiter_without_anext_is_rejected': ('TypeError', "'async for' received an object from __aiter__ that does not implement __anext__: NoNext"),
    'basic': 6,
    'break': [1, 2],
    'break_skips_else': [1],
    'continue': [2, 4],
    'coroutine_type_names_the_real_class': (True, True),
    'else_on_natural_drain': [1, 2, 'else'],
    'empty_iterator_runs_body_zero_times': [],
    'exception_from_anext_propagates': ('ValueError', 'from anext'),
    'generator_type_names_the_real_class': (True, True),
    'inspect_predicates': (True, True, False, False),
    'nested_async_for': [(1, 1), (1, 2), (2, 1), (2, 2)],
    'suspension_inside_anext_reaches_the_driver': ([('park', 1), ('park', 2)], ['v1', 'v2']),
    'sync_iterable_is_rejected': ('TypeError', "'async for' requires an object with __aiter__ method, got list"),
    'the_run_async_assertion_holds': True,
    'tuple_unpacking': [(1, 10), (2, 20)],
    'types_coroutine_returns_a_callable_and_rejects_non_callables': [True, ('TypeError', 'types.coroutine() expects a callable')],
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-56s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
