# THE LOOP DOES I/O.
#
# The event loop Grail already had was the callback/timer half of asyncio: a
# ready queue, a timer heap, Future and Task, sleep and run.  Enough to
# schedule, not enough to serve -- there was no add_reader, no sock_recv, and
# so no way for a socket to wake it.  Networking went through the blocking
# socket module, which on a cooperative loop means the first read stops every
# other task.
#
# What closes the gap is that GemStone already had the hard half.  `Processor
# whenReadable: sock signal: aSemaphore` (and whenWritable:) is a per-socket
# readiness registry, and Grail's `select` was already built on it -- register
# every socket against one semaphore and wait, and the gem sleeps until the
# first one is ready while other green threads keep running.  So this is a
# wiring job: the loop waits inside `select` whenever a socket is registered,
# and the sock_* coroutines are the ordinary retry-on-BlockingIOError shape.
#
# THE PROBE THAT MATTERS MOST is `two_clients_served_concurrently`. Everything
# else here would also pass on a loop that ran each connection to completion
# before looking at the next one -- right bytes, wrong order.  Interleaving can
# only happen if a socket that is not ready really returns control to the
# scheduler and the scheduler really resumes someone else.
#
# The second most interesting is `a_timer_fires_while_waiting_on_io`: a loop
# that blocks in select with no timeout is easy to write by accident, and it
# passes every test except one where a timer has to beat an idle socket.
#
# NOT COVERED, because it does not exist yet: transports and protocols. There
# is no create_server / create_connection / StreamReader, so an ASGI server
# cannot be pointed at this loop unmodified -- see docs/Support_FastAPI.md.
#
# Everything below is ordinary CPython asyncio -- no Grail-specific spelling --
# which is what makes this usable as ground truth rather than a description of
# what Grail happens to do.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import asyncio
import errno
import socket
import time

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def _listener():
    srv = socket.socket()
    srv.bind(('127.0.0.1', 0))
    srv.listen(8)
    srv.setblocking(False)
    return srv, srv.getsockname()


def _client(address):
    cli = socket.socket()
    cli.connect(address)
    cli.setblocking(False)
    return cli


# --- the headline: a real exchange over a real socket ----------------------

def echo_over_a_real_socket():
    async def main():
        srv, address = _listener()

        async def server():
            loop = asyncio.get_running_loop()
            conn, _addr = await loop.sock_accept(srv)
            data = await loop.sock_recv(conn, 1024)
            await loop.sock_sendall(conn, data.upper())
            conn.close()

        async def client():
            loop = asyncio.get_running_loop()
            cli = _client(address)
            await loop.sock_sendall(cli, b'hello')
            answer = await loop.sock_recv(cli, 1024)
            cli.close()
            return answer

        task = asyncio.ensure_future(server())
        answer = await client()
        await task
        srv.close()
        return answer

    return asyncio.run(main())


rec('echo_over_a_real_socket', echo_over_a_real_socket)


# --- THE PROBE A STRAIGHT-THROUGH LOOP CANNOT FAKE -------------------------

def two_clients_served_concurrently():
    """Two connections, and the second client speaks FIRST.  A loop that
    handled connections one at a time would answer in accept order; the trace
    below can only come out in speaking order if the handler for the first
    connection really suspended on its unready socket."""
    async def main():
        srv, address = _listener()
        trace = []

        async def handler(conn, name):
            loop = asyncio.get_running_loop()
            data = await loop.sock_recv(conn, 1024)
            trace.append('read %s' % name)
            await loop.sock_sendall(conn, data)
            conn.close()

        async def accept_two():
            loop = asyncio.get_running_loop()
            conns = []
            for name in ('first', 'second'):
                conn, _addr = await loop.sock_accept(srv)
                trace.append('accepted %s' % name)
                conns.append(asyncio.ensure_future(handler(conn, name)))
            return conns

        accepting = asyncio.ensure_future(accept_two())
        a = _client(address)
        b = _client(address)
        conns = await accepting

        loop = asyncio.get_running_loop()
        # b speaks first, so b must be served first.
        await loop.sock_sendall(b, b'from-b')
        trace.append('b sent')
        got_b = await loop.sock_recv(b, 1024)
        await loop.sock_sendall(a, b'from-a')
        trace.append('a sent')
        got_a = await loop.sock_recv(a, 1024)

        for handle in conns:
            await handle
        a.close()
        b.close()
        srv.close()
        return (trace, got_b, got_a)

    return asyncio.run(main())


rec('two_clients_served_concurrently', two_clients_served_concurrently)


# --- a timer must beat an idle socket --------------------------------------

def a_timer_fires_while_waiting_on_io():
    """A registered-but-silent socket must not let the loop wait forever: the
    wait ends at the first DEADLINE too.  A loop that passes None to select
    whenever nothing is ready looks correct until this case."""
    async def main():
        srv, _address = _listener()
        loop = asyncio.get_running_loop()
        fired = []
        loop.add_reader(srv, lambda: fired.append('socket'))
        started = time.monotonic()
        await asyncio.sleep(0.2)
        elapsed = time.monotonic() - started
        loop.remove_reader(srv)
        srv.close()
        return (fired, elapsed >= 0.15, elapsed < 5.0)

    return asyncio.run(main())


rec('a_timer_fires_while_waiting_on_io', a_timer_fires_while_waiting_on_io)


def the_loop_sleeps_rather_than_spins():
    """Wall time passes; CPU time does not.  A loop that polls in a tight
    circle would burn a comparable amount of both, so the ratio is the
    evidence that the wait is a real suspension."""
    async def main():
        srv, _address = _listener()
        loop = asyncio.get_running_loop()
        loop.add_reader(srv, lambda: None)
        wall0, cpu0 = time.monotonic(), time.process_time()
        await asyncio.sleep(0.3)
        wall = time.monotonic() - wall0
        cpu = time.process_time() - cpu0
        loop.remove_reader(srv)
        srv.close()
        return (wall >= 0.25, cpu < wall * 0.5)

    return asyncio.run(main())


rec('the_loop_sleeps_rather_than_spins', the_loop_sleeps_rather_than_spins)


# --- the callback API itself -----------------------------------------------

def add_reader_fires_when_data_arrives():
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        conn, _addr = await loop.sock_accept(srv)

        seen = asyncio.get_running_loop().create_future()
        loop.add_reader(conn, lambda: seen.done() or seen.set_result(conn.recv(64)))
        cli.sendall(b'knock')
        data = await seen
        loop.remove_reader(conn)

        conn.close()
        cli.close()
        srv.close()
        return data

    return asyncio.run(main())


rec('add_reader_fires_when_data_arrives', add_reader_fires_when_data_arrives)


def a_reader_on_an_idle_socket_does_not_fire():
    async def main():
        srv, _address = _listener()
        loop = asyncio.get_running_loop()
        fired = []
        loop.add_reader(srv, lambda: fired.append('spurious'))
        await asyncio.sleep(0.15)
        loop.remove_reader(srv)
        srv.close()
        return fired

    return asyncio.run(main())


rec('a_reader_on_an_idle_socket_does_not_fire', a_reader_on_an_idle_socket_does_not_fire)


def remove_reader_reports_whether_it_removed():
    async def main():
        srv, _address = _listener()
        loop = asyncio.get_running_loop()
        loop.add_reader(srv, lambda: None)
        first = loop.remove_reader(srv)
        second = loop.remove_reader(srv)
        srv.close()
        return (first, second)

    return asyncio.run(main())


rec('remove_reader_reports_whether_it_removed', remove_reader_reports_whether_it_removed)


def a_watcher_can_be_registered_by_file_descriptor():
    """CPython's tables are keyed by descriptor, and `loop.add_reader(
    sock.fileno(), cb)` is the spelling library code uses.  Grail's readiness
    events are keyed by socket rather than by descriptor, so the int has to be
    resolved back through _socket's fd registry -- and the registration must be
    the SAME one, or adding by fd and removing by socket would leak a watcher."""
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        conn, _addr = await loop.sock_accept(srv)

        fired = loop.create_future()
        loop.add_reader(conn.fileno(),
                        lambda: fired.done() or fired.set_result('by fd'))
        cli.sendall(b'x')
        answer = await fired
        removed_by_socket = loop.remove_reader(conn)

        conn.close()
        cli.close()
        srv.close()
        return (answer, removed_by_socket)

    return asyncio.run(main())


rec('a_watcher_can_be_registered_by_file_descriptor',
    a_watcher_can_be_registered_by_file_descriptor)


# --- the sock_* surface ----------------------------------------------------

def sock_recv_at_eof_is_empty_bytes():
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        conn, _addr = await loop.sock_accept(srv)
        cli.close()
        data = await loop.sock_recv(conn, 64)
        conn.close()
        srv.close()
        return data

    return asyncio.run(main())


rec('sock_recv_at_eof_is_empty_bytes', sock_recv_at_eof_is_empty_bytes)


def sock_recv_requires_a_nonblocking_socket():
    """A blocking recv inside a cooperative loop stops every other task, not
    just its caller, so it is refused at the call site.

    Note the set_debug(True): CPython makes this check ONLY in debug mode and
    otherwise performs the blocking recv.  GRAIL REFUSES EITHER WAY -- a hang
    of the entire loop is not a thing to discover at runtime -- but the probe
    turns debug on so that both sides raise and the message can be compared.
    The always-on half cannot be probed here: under CPython it would hang."""
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        loop.set_debug(True)
        conn, _addr = await loop.sock_accept(srv)
        conn.setblocking(True)
        try:
            await loop.sock_recv(conn, 1)
            return 'no error'
        except ValueError as e:
            return ('ValueError', str(e), loop.get_debug())
        finally:
            loop.set_debug(False)
            conn.close()
            cli.close()
            srv.close()

    return asyncio.run(main())


rec('sock_recv_requires_a_nonblocking_socket', sock_recv_requires_a_nonblocking_socket)


def sock_accept_answers_a_nonblocking_socket():
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        conn, addr = await loop.sock_accept(srv)
        answer = (conn.gettimeout(), addr[0])
        conn.close()
        cli.close()
        srv.close()
        return answer

    return asyncio.run(main())


rec('sock_accept_answers_a_nonblocking_socket', sock_accept_answers_a_nonblocking_socket)


def sock_sendall_sends_more_than_one_write_worth():
    """64KiB is past a loopback send buffer, so this exercises the partial-write
    path: send answers a short count, sendall waits for writability and
    continues from where it stopped."""
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        conn, _addr = await loop.sock_accept(srv)
        payload = bytes(bytearray(range(256))) * 256      # 65536 bytes

        async def drain():
            got = bytearray()
            while len(got) < len(payload):
                chunk = await loop.sock_recv(cli, 16384)
                if not chunk:
                    break
                got += chunk
            return bytes(got)

        reader = asyncio.ensure_future(drain())
        await loop.sock_sendall(conn, payload)
        got = await reader
        conn.close()
        cli.close()
        srv.close()
        return (len(got), got == payload)

    return asyncio.run(main())


rec('sock_sendall_sends_more_than_one_write_worth',
    sock_sendall_sends_more_than_one_write_worth)


def sock_recv_into_fills_a_buffer():
    async def main():
        srv, address = _listener()
        cli = _client(address)
        loop = asyncio.get_running_loop()
        conn, _addr = await loop.sock_accept(srv)
        await loop.sock_sendall(conn, b'buffered')
        buf = bytearray(16)
        n = await loop.sock_recv_into(cli, buf)
        conn.close()
        cli.close()
        srv.close()
        return (n, bytes(buf[:n]))

    return asyncio.run(main())


rec('sock_recv_into_fills_a_buffer', sock_recv_into_fills_a_buffer)


def sock_connect_connects():
    """And leaves the socket non-blocking, so the reads that follow it are
    cooperative rather than a stall for every other task."""
    async def main():
        srv, address = _listener()
        loop = asyncio.get_running_loop()
        cli = socket.socket()
        cli.setblocking(False)
        await loop.sock_connect(cli, address)
        conn, _addr = await loop.sock_accept(srv)
        await loop.sock_sendall(conn, b'after connect')
        answer = (await loop.sock_recv(cli, 64), cli.gettimeout())
        conn.close()
        cli.close()
        srv.close()
        return answer

    return asyncio.run(main())


rec('sock_connect_connects', sock_connect_connects)


def a_nonblocking_connect_reports_in_progress():
    """The socket-level primitive underneath sock_connect: a non-blocking
    connect STARTS and says so, with EINPROGRESS rather than a failure.

    Grail reported a bare OSError here -- `connect failed: getpeername failed
    with Socket is not connected` -- which is the internal completion probe's
    complaint, not the connect's.  GemStone was doing the right thing all along:
    every socket it creates is non-blocking at the OS level and every connect is
    issued non-blocking, so `connectTo:on:timeoutMs: 0` starts one and polls
    once, which is exactly this."""
    srv, address = _listener()
    s = socket.socket()
    s.setblocking(False)
    try:
        s.connect(address)
        return 'connected immediately'
    except BlockingIOError as e:
        return ('BlockingIOError', e.errno == errno.EINPROGRESS)
    finally:
        s.close()
        srv.close()


rec('a_nonblocking_connect_reports_in_progress',
    a_nonblocking_connect_reports_in_progress)


def sock_connect_reports_a_refused_connection():
    """The failure path has to arrive as an exception rather than as a wait that
    never ends.  It is the case a writability-only wait gets wrong: a refused
    connect makes the socket READABLE and never writable, so a loop waiting only
    for writability hangs.  sock_connect waits for either."""
    async def main():
        loop = asyncio.get_running_loop()
        s = socket.socket()
        s.setblocking(False)
        try:
            await loop.sock_connect(s, ('127.0.0.1', 1))
            return 'connected?!'
        except OSError as e:
            return type(e).__name__
        finally:
            s.close()

    return asyncio.run(main())


rec('sock_connect_reports_a_refused_connection',
    sock_connect_reports_a_refused_connection)


def connect_ex_answers_a_code_rather_than_raising():
    """connect_ex has exactly one contract -- never raise -- and it was not
    being kept: a blocking connect_ex to a closed port RAISED `OSError: connect
    failed` instead of answering ECONNREFUSED.  It shares the classifier with
    connect now, so the two cannot disagree about what happened either."""
    srv, address = _listener()
    a = socket.socket()
    b = socket.socket()
    c = socket.socket()
    c.setblocking(False)
    try:
        blocking_open = a.connect_ex(address)
        blocking_refused = b.connect_ex(('127.0.0.1', 1))
        nonblocking_refused = c.connect_ex(('127.0.0.1', 1))
        # The BLOCKING refusal's code is only asserted to BE a code: connectTo:
        # has already waited and resolved by then, so it is read from readiness
        # rather than from the primitive, and readiness for an errored socket is
        # platform-dependent.  The NON-BLOCKING one comes from the primitive's
        # own errno and so is portable.
        return (blocking_open,
                isinstance(blocking_refused, int) and blocking_refused != 0,
                nonblocking_refused in (errno.ECONNREFUSED, errno.EINPROGRESS))
    finally:
        a.close()
        b.close()
        c.close()
        srv.close()


rec('connect_ex_answers_a_code_rather_than_raising',
    connect_ex_answers_a_code_rather_than_raising)


def _errno_name(exc):
    """The errno as a NAME, because the numbers are not portable: EISCONN is 56
    on BSD/macOS and 106 on Linux, ECONNREFUSED 61 against 111."""
    for name in ('EINPROGRESS', 'EALREADY', 'EISCONN', 'ECONNREFUSED', 'EINVAL'):
        if exc.errno == getattr(errno, name, None):
            return name
    return '%s/%s' % (type(exc).__name__, exc.errno)


def connect_state_machine():
    """What a non-blocking connect() answers once the connect has RESOLVED,
    which is the part Grail used to get wrong: it returned None when connect()
    was called again on a connect that had completed, where CPython raises
    EISCONN.

    EISCONN matters more than it looks.  It is not a BlockingIOError, so a loop
    written as `try: connect() except BlockingIOError: wait` TERMINATES on it
    rather than quietly succeeding -- which is why nobody writes the
    retry-connect pattern against CPython, and why Grail answering None there
    was a silent invitation to write it.

    THIS ASSERTS PROPERTIES, NOT A TRANSCRIPT, and it took three tries to find
    ones that are actually CPython's rather than macOS's:

      * recording the sequence with errno NUMBERS failed on Linux (EISCONN is
        56 on BSD and 106 there);
      * recording it with errno NAMES failed too, because the SHAPE varies --
        a loopback connect can resolve synchronously on Linux, skipping the
        EINPROGRESS step macOS always shows;
      * asserting "a completed connect never reports success again" ALSO failed,
        and that one was interesting: on Linux the call that COMPLETES a
        non-blocking connect returns 0, and only calls after it raise EISCONN.
        macOS raises EISCONN straight away.  So Grail's old behaviour -- None on
        the retry -- was Linux-like for exactly one call; the bug was repeating
        it forever.

    What holds everywhere: a connect that has resolved ends up at EISCONN, and
    success is reported AT MOST ONCE.  That is the bug, stated portably.

    Only the SUCCESS path is driven here.  Whether 127.0.0.1:1 refuses promptly
    or is firewalled into a pending connect is the runner's network behaviour
    rather than Grail's, and the refusal is already covered by
    sock_connect_reports_a_refused_connection.

    EALREADY is not probed from here at all: a loopback connect completes before
    a second Python statement can run, so from up here whether it is ever
    observed is timing.  AsyncioIoTestCase asserts it one level down, where an
    immediate re-poll is deterministic."""
    def drive(target, tries=6):
        s = socket.socket()
        s.setblocking(False)
        seen = []
        for _ in range(tries):
            try:
                s.connect(target)
                seen.append('connected')
            except OSError as exc:
                seen.append(_errno_name(exc))
            if seen[-1] in ('EISCONN', 'EINVAL', 'ECONNREFUSED'):
                break
            time.sleep(0.05)
        s.close()
        return seen

    srv, address = _listener()
    try:
        seen = drive(address)
        return (
            # Where a resolved connect ENDS UP, on every platform.
            seen[-1],
            # Success is reported at most once -- Linux reports it on the call
            # that completes the connect, macOS never.  Reporting it forever is
            # the bug: it makes a retry loop look as though it worked.
            seen.count('connected') <= 1,
        )
    finally:
        srv.close()


rec('connect_state_machine', connect_state_machine)




EXPECTED = {
    'a_reader_on_an_idle_socket_does_not_fire': [],
    'a_timer_fires_while_waiting_on_io': ([], True, True),
    'a_nonblocking_connect_reports_in_progress': ('BlockingIOError', True),
    'a_watcher_can_be_registered_by_file_descriptor': ('by fd', True),
    'connect_ex_answers_a_code_rather_than_raising': (0, True, True),
    'connect_state_machine': ('EISCONN', True),
    'add_reader_fires_when_data_arrives': b'knock',
    'echo_over_a_real_socket': b'HELLO',
    'remove_reader_reports_whether_it_removed': (True, False),
    'sock_accept_answers_a_nonblocking_socket': (0.0, '127.0.0.1'),
    'sock_connect_connects': (b'after connect', 0.0),
    'sock_connect_reports_a_refused_connection': 'ConnectionRefusedError',
    'sock_recv_at_eof_is_empty_bytes': b'',
    'sock_recv_into_fills_a_buffer': (8, b'buffered'),
    'sock_recv_requires_a_nonblocking_socket': ('ValueError', 'the socket must be non-blocking', True),
    'sock_sendall_sends_more_than_one_write_worth': (65536, True),
    'the_loop_sleeps_rather_than_spins': (True, True),
    'two_clients_served_concurrently': (['accepted first', 'accepted second', 'b sent', 'read second', 'a sent', 'read first'], b'from-b', b'from-a'),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-52s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        # Every probe is compared: there is nothing left here whose CPython
        # answer is unportable.  (connect_progression used to be, and its
        # replacements report errno NAMES instead of numbers.)
        for k in sorted(set(r) - set(EXPECTED)):
            print('%-52s %s %r' % (k, 'XFAIL', r[k]))
        print('%d difference(s)' % bad)
