# ASYNC GENERATORS -- ``async def'' with ``yield'' in it.
#
# An async generator body suspends for two completely unrelated reasons, and
# telling them apart is the whole problem:
#
#     yield v      hand v to whoever is doing `async for` -- this ENDS the
#                  current __anext__, and v is what awaiting it produces
#     await x      park until x resolves -- this must travel PAST __anext__ and
#                  out to the event loop, because __anext__ has produced nothing
#
# Grail answered a plain coroutine for these functions, so `async for v in
# agen()` raised `TypeError: 'async for' requires an object with __aiter__
# method, got PythonCoroutine`, and asend / athrow / aclose did not exist.
#
# Both suspensions reach the consumer by the same route (a forked body parked on
# a semaphore), so the real yield is now TAGGED and the suspension is not --
# see PyAsyncYield. Tagging the yield rather than the suspension is deliberate:
# yields are the ones the runtime emits, so the tag cannot be forged, whereas a
# suspension value comes from arbitrary user `__await__` code.
#
# The probe that matters most is `await_inside_the_body_suspends_the_loop`: a
# body that awaits between yields, driven by hand, must hand its suspensions to
# the driver and its yields to the loop. That is how a streaming response works,
# and it is the one check a wrong yield/await split cannot pass.
#
# ALSO HERE: the predicates. `isgenerator()` has to EXCLUDE async generators,
# which is a Grail-specific hazard -- PythonAsyncGenerator is a PythonGenerator
# subclass, so a bare isinstance() answers True where CPython answers False.
# That one is worse than the coroutine case it mirrors, because an async
# generator does answer to send(), so wrong dispatch would drive it and hand
# back the internal tag as if it were an item.
#
# NOT PROBED: `inspect.isasyncgenfunction()`, which asks whether a FUNCTION is
# an async generator function without calling it. CPython reads a code flag;
# Grail's functions carry none, so it still answers False. Pinned as a known
# gap in AsyncGeneratorsTestCase.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import inspect
import types

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def drive(c):
    """Run an awaitable that never suspends; answer what it produced."""
    try:
        c.send(None)
        return 'did not finish'
    except StopIteration as e:
        return e.value


# --- the object ------------------------------------------------------------

async def counter():
    yield 1
    yield 2
    yield 3


def _is_its_own_async_iterator():
    a = counter()
    return (hasattr(a, '__aiter__'), a.__aiter__() is a)


def _async_for_iterates_it():
    async def f():
        out = []
        async for v in counter():
            out.append(v)
        return out
    return drive(f())


def _a_plain_async_def_is_not_one():
    # The discrimination that matters: adding async generators must not turn
    # every coroutine into one.
    async def plain():
        return 5
    c = plain()
    try:
        return (type(c) is types.CoroutineType,
                type(c) is types.AsyncGeneratorType)
    finally:
        c.close()


def _a_sync_generator_is_not_one():
    def g():
        yield 9
    return (type(g()) is types.GeneratorType,
            type(g()) is types.AsyncGeneratorType,
            list(g()))


def _the_types_are_three_distinct_classes():
    # Grail implements all three by subclassing one generator machinery, so
    # this is the check that they stayed distinguishable.
    return len({types.GeneratorType,
                types.CoroutineType,
                types.AsyncGeneratorType}) == 3


# --- THE PAYOFF: yields and awaits go to different places ------------------

class _Park:
    def __init__(self, i):
        self.i = i

    def __await__(self):
        sent = yield ('park', self.i)
        return sent


async def awaits_between_yields():
    for i in (1, 2):
        got = await _Park(i)
        yield got


def _await_inside_the_body_suspends_the_loop():
    async def f():
        out = []
        async for v in awaits_between_yields():
            out.append(v)
        return out
    c = f()
    parked = []
    send_value = None
    while True:
        try:
            parked.append(c.send(send_value))
            send_value = 'v%d' % len(parked)
        except StopIteration as e:
            return (parked, e.value)


# --- exhaustion -----------------------------------------------------------

def _exhaustion_raises_stopasynciteration():
    async def one():
        yield 'only'
    a = one()
    out = [drive(a.__anext__())]
    try:
        drive(a.__anext__())
        out.append('no StopAsyncIteration')
    except StopAsyncIteration:
        out.append('StopAsyncIteration')
    return out


def _a_body_that_returns_early_ends_the_iteration():
    async def stops():
        yield 1
        return
        yield 2            # unreachable
    async def f():
        out = []
        async for v in stops():
            out.append(v)
        return out
    return drive(f())


# --- asend / athrow / aclose ----------------------------------------------

def _asend_threads_a_value_into_the_yield():
    async def echo():
        got = yield 'first'
        yield ('got', got)
    a = echo()
    return [drive(a.__anext__()), drive(a.asend('sent-in'))]


def _athrow_arrives_at_the_yield():
    async def catches():
        try:
            yield 'parked'
        except ValueError as e:
            yield ('caught', str(e))
    a = catches()
    first = drive(a.__anext__())
    second = drive(a.athrow(ValueError('boom')))
    return (first, second)


def _aclose_runs_the_finally():
    log = []

    async def cleans():
        try:
            yield 1
            yield 2
        finally:
            log.append('cleaned')
    a = cleans()
    first = drive(a.__anext__())
    drive(a.aclose())
    return (first, log)


def _aclose_on_an_unstarted_generator_is_harmless():
    log = []

    async def cleans():
        try:
            yield 1
        finally:
            log.append('cleaned')
    a = cleans()
    drive(a.aclose())
    # The body never ran, so its finally never ran either.
    return log


# --- the predicates -------------------------------------------------------

def _inspect_isasyncgen():
    async def ag():
        yield 1

    async def co():
        pass

    def g():
        yield 1
    c = co()
    try:
        return (inspect.isasyncgen(ag()),
                inspect.isasyncgen(c),
                inspect.isasyncgen(g()))
    finally:
        c.close()


def _isgenerator_excludes_async_generators():
    # THE GRAIL HAZARD, mirrored from the coroutine case: all three are one
    # machinery underneath, and CPython's predicates are mutually exclusive.
    async def ag():
        yield 1

    def g():
        yield 1
    return (inspect.isgenerator(g()),
            inspect.isgenerator(ag()),
            inspect.iscoroutine(ag()))


rec('is_its_own_async_iterator', _is_its_own_async_iterator)
rec('async_for_iterates_it', _async_for_iterates_it)
rec('a_plain_async_def_is_not_one', _a_plain_async_def_is_not_one)
rec('a_sync_generator_is_not_one', _a_sync_generator_is_not_one)
rec('the_types_are_three_distinct_classes', _the_types_are_three_distinct_classes)
rec('await_inside_the_body_suspends_the_loop',
    _await_inside_the_body_suspends_the_loop)
rec('exhaustion_raises_stopasynciteration',
    _exhaustion_raises_stopasynciteration)
rec('a_body_that_returns_early_ends_the_iteration',
    _a_body_that_returns_early_ends_the_iteration)
rec('asend_threads_a_value_into_the_yield',
    _asend_threads_a_value_into_the_yield)
rec('athrow_arrives_at_the_yield', _athrow_arrives_at_the_yield)
rec('aclose_runs_the_finally', _aclose_runs_the_finally)
rec('aclose_on_an_unstarted_generator_is_harmless',
    _aclose_on_an_unstarted_generator_is_harmless)
rec('inspect_isasyncgen', _inspect_isasyncgen)
rec('isgenerator_excludes_async_generators',
    _isgenerator_excludes_async_generators)


EXPECTED = {
    'a_body_that_returns_early_ends_the_iteration': [1],
    'a_plain_async_def_is_not_one': (True, False),
    'a_sync_generator_is_not_one': (True, False, [9]),
    'aclose_on_an_unstarted_generator_is_harmless': [],
    'aclose_runs_the_finally': (1, ['cleaned']),
    'asend_threads_a_value_into_the_yield': ['first', ('got', 'sent-in')],
    'async_for_iterates_it': [1, 2, 3],
    'athrow_arrives_at_the_yield': ('parked', ('caught', 'boom')),
    'await_inside_the_body_suspends_the_loop': ([('park', 1), ('park', 2)], ['v1', 'v2']),
    'exhaustion_raises_stopasynciteration': ['only', 'StopAsyncIteration'],
    'inspect_isasyncgen': (True, False, False),
    'is_its_own_async_iterator': (True, True),
    'isgenerator_excludes_async_generators': (True, False, False),
    'the_types_are_three_distinct_classes': True,
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-50s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
