"""Private-name mangling of BARE NAMES in a class body -- CPython's lexical rule.

An identifier spelled ``__x`` (two or more leading underscores, not ending in
``__``) anywhere inside a class body is rewritten to ``_C__x``: method bodies,
nested defs, lambdas, comprehensions, defaults and decorators included.

Grail used to mangle only the attribute-shaped names -- class attributes,
private methods, ``self.__x`` -- and left bare names alone, so ``global __x``
in a method wrote ``__x`` where CPython writes ``_C__x``.  That was
test_named_expressions' test_named_expression_scope_mangled_names; the test is
about mangling, not the walrus, which was already correct.

The fix mangles at PARSE time, where every name is recorded.  Mangling only at
the emit was tried and cannot be made consistent: the parser's scope sets are
keyed on the name as recorded, so a name mangled only at emit is looked up
under one spelling and bound under another -- that attempt fixed ``global
__x`` and broke a walrus targeting the pre-mangled spelling, which had passed.

WHAT STAYS RAW is checked here too, because each exception is as much the rule
as the mangling is: a def's or class's own ``__name__``/``__qualname__``;
call-site keywords (``self.f(__a=1)`` passes ``__a`` even inside the class);
and everything outside a class body.

EXPECTED was generated by RUNNING CPython 3.14.6.
"""

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except Exception as e:                      # noqa: BLE001 - the type IS the result
        r[k] = '%s: %s' % (type(e).__name__, e)


__helper = 'module-level __helper'           # a bare read of it from a class must NOT find it


class C:
    __cls_attr = 1

    def set_global(self):
        global __g
        __g = 5

    def read_module_private(self):
        return __helper

    def local_keys(self):
        __loc = 7
        return sorted(k for k in locals() if k != 'self')

    def same_local_two_spellings(self):
        __x = 1
        return _C__x

    def params(self, __a):
        return __a

    def call_kw_raw(self):
        return self.params(__a=7)                 # the keyword is NOT mangled

    def nested_def(self):
        def __inner():
            return 1
        return [__inner.__name__, __inner.__qualname__,
                sorted(k for k in locals() if k != 'self')]

    def closure_nonlocal(self):
        __n = 1
        def bump():
            nonlocal __n
            __n += 1
        bump()
        return __n

    def lam(self):
        __z = 3
        return (lambda: __z)()

    def comp(self):
        return [__i * 10 for __i in range(3)]

    def excepts(self):
        try:
            raise ValueError
        except ValueError as __e:
            return sorted(k for k in locals() if k != 'self')

    def imports(self):
        import os as __os
        return sorted(k for k in locals() if k != 'self')

    def fstr(self):
        __v = 4
        return f"{__v}"

    def dflt(self, x=lambda: __w):
        return x()

    def deletes(self):
        __d = 1
        del __d
        return sorted(k for k in locals() if k != 'self')

    def __m(self):
        return 'm'

    def _C__lit(self):                          # WRITTEN pre-mangled: keeps this spelling
        return 'lit'

    class __Inner:
        def m(self):
            return __q


# --- the global is declared and written under the MANGLED name -------------
C().set_global()
rec('global_key', lambda: sorted(k for k in globals() if k.endswith('__g')))
rec('global_value', lambda: _C__g)

# --- a bare read is mangled, so it does not reach the module's __helper -----
rec('bare_read_is_mangled', lambda: C().read_module_private())

# --- locals: one spelling, and __x / _C__x are the SAME local ---------------
rec('local_keys', lambda: C().local_keys())
rec('two_spellings_one_local', lambda: C().same_local_two_spellings())

# --- parameters are mangled; call-site keywords are not ---------------------
rec('param_mangled_kw_ok', lambda: C().params(_C__a=1))
rec('param_raw_kw_rejected', lambda: C().params(__a=1))
rec('call_site_kw_stays_raw', lambda: C().call_kw_raw())

# --- bindings mangle, __name__ / __qualname__ do not -----------------------
rec('nested_def', lambda: C().nested_def())
rec('method_name', lambda: [C._C__m.__name__, C._C__m.__qualname__])
rec('bound_method_name', lambda: [C()._C__m.__name__, C()._C__m.__qualname__])
# the display-name table must not rename a def that was written pre-mangled --
# un-mangling the selector would turn _C__lit into __lit
rec('literal_premangled_name', lambda: [C._C__lit.__name__, C._C__lit.__qualname__])


class D(C):
    pass


# an inherited private method reports the name its DEFINING class gave it
rec('inherited_private_name', lambda: D._C__m.__name__)
rec('inner_class_name', lambda: [C._C__Inner.__name__, C._C__Inner.__qualname__])
rec('inner_class_member_uses_inner_name', lambda: C._C__Inner().m())
rec('class_attr', lambda: sorted(k for k in C.__dict__ if 'cls_attr' in k))

# --- every other binding form ----------------------------------------------
rec('nonlocal', lambda: C().closure_nonlocal())
rec('lambda', lambda: C().lam())
rec('comprehension', lambda: C().comp())
rec('except_as', lambda: C().excepts())
rec('import_as', lambda: C().imports())
rec('fstring', lambda: C().fstr())
rec('default_lambda', lambda: C().dflt())
rec('del', lambda: C().deletes())


# --- THE UPSTREAM NESTING: a class defined INSIDE A FUNCTION ---------------
# test_named_expressions defines its class inside a test method.  A module-level
# class can pass while this one fails, so the exact shape is repeated here.
def _upstream():
    class Foo:
        def f(self_):
            global __x1
            __x1 = 0
            [_Foo__x1 := 1 for a in [2]]
            first = __x1
            [__x1 := 2 for a in [3]]
            return [first, __x1]
    return Foo().f() + [_Foo__x1]


rec('upstream_walrus_global', _upstream)


EXPECTED = {
    'global_key': ['_C__g'],
    'global_value': 5,
    'bare_read_is_mangled': "NameError: name '_C__helper' is not defined",
    'local_keys': ['_C__loc'],
    'two_spellings_one_local': 1,
    'param_mangled_kw_ok': 1,
    'param_raw_kw_rejected': "TypeError: C.params() got an unexpected keyword argument '__a'",
    'call_site_kw_stays_raw': "TypeError: C.params() got an unexpected keyword argument '__a'",
    'nested_def': ['__inner', 'C.nested_def.<locals>.__inner', ['_C__inner']],
    'method_name': ['__m', 'C.__m'],
    'bound_method_name': ['__m', 'C.__m'],
    'literal_premangled_name': ['_C__lit', 'C._C__lit'],
    'inherited_private_name': '__m',
    'inner_class_name': ['__Inner', 'C.__Inner'],
    'inner_class_member_uses_inner_name': "NameError: name '_Inner__q' is not defined",
    'class_attr': ['_C__cls_attr'],
    'nonlocal': 2,
    'lambda': 3,
    'comprehension': [0, 10, 20],
    'except_as': ['_C__e'],
    'import_as': ['_C__os'],
    'fstring': '4',
    'default_lambda': "NameError: name '_C__w' is not defined",
    'del': [],
    'upstream_walrus_global': [1, 2, 2],
}


if __name__ == '__main__':
    for _k in EXPECTED:
        print('%-36s %s %r' % (_k, 'OK ' if r[_k] == EXPECTED[_k] else 'DIFF', r[_k]))
