# A built-in type's __dict__, __bases__ and __base__, as CPython reports them.
#
# Three defects, each in how Grail REPORTS a built-in's shape:
#
#   * A built-in's class and static methods were missing from its __dict__
#     (str.maketrans, dict.fromkeys) or were bare functions (bytes.maketrans,
#     int.from_bytes).  CPython keeps a staticmethod / classmethod descriptor
#     there, which pickle refuses and inspect reports as a static / class
#     method.  The same class side leaked Grail's plumbing as attributes: a
#     phantom ``new'' on int, float, list and more, int's class-subscription
#     hook as ``__getitem__'', and ``__pyRaiseNew___:args'' on BaseException.
#     ``__doc__'' was a function where CPython has the docstring.
#   * bytearray reported bytes as its base -- __mro__ (bytearray, bytes,
#     object), __bases__ (bytes,) -- and so its __dict__ listed none of the
#     methods it shares with bytes (61 of CPython's 82 names were missing).
#   * __bases__ and __base__ named the kernel class a built-in is built on:
#     int.__bases__ was (Number,), tuple's (Array,), BaseException's the
#     kernel Exception.
#
# EXPECTED was generated by RUNNING CPython 3.14.6 (``--emit``).

import inspect
import pickle
import sys

r = {}


def _err(f):
    try:
        return repr(f())
    except Exception as e:
        return '%s: %s' % (type(e).__name__, e)


# --- __bases__ / __base__ / __mro__ --------------------------------------------

_types = (int, float, complex, str, bytes, bytearray, list, tuple, dict, set,
          frozenset, range, slice, memoryview, property, enumerate,
          BaseException, Exception, ValueError)
r['bases'] = repr([(t.__name__, [b.__name__ for b in t.__bases__], t.__base__.__name__)
                   for t in _types])
r['mro'] = repr([(t.__name__, [c.__name__ for c in t.__mro__]) for t in _types])


class _B(bytearray):
    pass


r['bytearray_subclass'] = repr([[c.__name__ for c in _B.__mro__],
                                [b.__name__ for b in _B.__bases__],
                                issubclass(_B, bytes), isinstance(_B(), bytes)])

# --- class and static methods in __dict__ --------------------------------------

_class_side = [(bytes, 'maketrans'), (bytearray, 'maketrans'), (str, 'maketrans'),
               (bytes, 'fromhex'), (bytearray, 'fromhex'), (float, 'fromhex'),
               (dict, 'fromkeys'), (int, 'from_bytes'), (float, '__getformat__')]
r['class_side_present'] = repr([k in t.__dict__ for t, k in _class_side])
r['staticmethod_kind'] = repr([type(t.__dict__['maketrans']) is staticmethod
                               for t in (bytes, bytearray, str)])
r['classify_kinds'] = repr([
    [a.kind for a in inspect.classify_class_attrs(t) if a.name == k][0]
    for t, k in _class_side])
r['pickle_refuses'] = repr([_err(lambda d=t.__dict__[k]: pickle.dumps(d)).split(':')[0]
                            for t, k in (_class_side[1], _class_side[6])])
r['descriptors_call'] = repr([
    str.__dict__['maketrans'].__func__('ab', 'xy') == str.maketrans('ab', 'xy'),
    dict.__dict__['fromkeys'].__get__(None, dict)('ab'),
    int.__dict__['from_bytes'].__get__(None, int)(b'\x01\x00', 'big'),
    bytearray.__dict__['fromhex'].__get__(None, bytearray)('41 42'),
])

# --- bytearray's own methods ---------------------------------------------------

_ba_names = ['count', 'decode', 'find', 'hex', 'join', 'split', 'startswith',
             'upper', '__len__', '__getitem__', '__contains__', '__add__',
             'append', 'extend', 'pop', '__setitem__']
r['bytearray_methods'] = repr([n for n in _ba_names if n not in bytearray.__dict__])
r['bytearray_method_calls'] = repr([
    bytearray.__dict__['count'](bytearray(b'abca'), b'a'),
    bytearray.__dict__['upper'](bytearray(b'ab')),
    bytearray.__dict__['__len__'](bytearray(b'abc')),
    bytearray.__dict__['__hash__'],
])

# --- Grail plumbing is not an attribute ----------------------------------------

r['no_plumbing'] = repr([
    [t.__name__ for t in (int, float, complex, list, tuple, bytes, type) if 'new' in t.__dict__],
    '__getitem__' in int.__dict__, '__getitem__' in float.__dict__,
    '__instancecheck__' in int.__dict__, '__instancecheck__' in float.__dict__,
    [k for t in (BaseException, int, str, dict) for k in t.__dict__
     if not k.isidentifier()],
])

# --- __doc__ -------------------------------------------------------------------

r['doc_is_the_docstring'] = repr([
    (t.__name__, type(t.__dict__.get('__doc__')).__name__,
     t.__dict__.get('__doc__') == t.__doc__)
    for t in (object, int, str, bytes, list, dict, set, slice, ValueError)])

EXPECTED = {
    'bases': "[('int', ['object'], 'object'), ('float', ['object'], 'object'), ('complex', ['object'], 'object'), ('str', ['object'], 'object'), ('bytes', ['object'], 'object'), ('bytearray', ['object'], 'object'), ('list', ['object'], 'object'), ('tuple', ['object'], 'object'), ('dict', ['object'], 'object'), ('set', ['object'], 'object'), ('frozenset', ['object'], 'object'), ('range', ['object'], 'object'), ('slice', ['object'], 'object'), ('memoryview', ['object'], 'object'), ('property', ['object'], 'object'), ('enumerate', ['object'], 'object'), ('BaseException', ['object'], 'object'), ('Exception', ['BaseException'], 'BaseException'), ('ValueError', ['Exception'], 'Exception')]",
    'bytearray_method_calls': "[2, bytearray(b'AB'), 3, None]",
    'bytearray_methods': '[]',
    'bytearray_subclass': "[['_B', 'bytearray', 'object'], ['bytearray'], False, False]",
    'class_side_present': '[True, True, True, True, True, True, True, True, True]',
    'classify_kinds': "['static method', 'static method', 'static method', 'class method', 'class method', 'class method', 'class method', 'class method', 'class method']",
    'descriptors_call': "[True, {'a': None, 'b': None}, 256, bytearray(b'AB')]",
    'doc_is_the_docstring': "[('object', 'str', True), ('int', 'str', True), ('str', 'str', True), ('bytes', 'str', True), ('list', 'str', True), ('dict', 'str', True), ('set', 'str', True), ('slice', 'str', True), ('ValueError', 'str', True)]",
    'mro': "[('int', ['int', 'object']), ('float', ['float', 'object']), ('complex', ['complex', 'object']), ('str', ['str', 'object']), ('bytes', ['bytes', 'object']), ('bytearray', ['bytearray', 'object']), ('list', ['list', 'object']), ('tuple', ['tuple', 'object']), ('dict', ['dict', 'object']), ('set', ['set', 'object']), ('frozenset', ['frozenset', 'object']), ('range', ['range', 'object']), ('slice', ['slice', 'object']), ('memoryview', ['memoryview', 'object']), ('property', ['property', 'object']), ('enumerate', ['enumerate', 'object']), ('BaseException', ['BaseException', 'object']), ('Exception', ['Exception', 'BaseException', 'object']), ('ValueError', ['ValueError', 'Exception', 'BaseException', 'object'])]",
    'no_plumbing': '[[], False, False, False, False, []]',
    'pickle_refuses': "['TypeError', 'TypeError']",
    'staticmethod_kind': '[True, True, True]',
}


if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        for k in sorted(EXPECTED):
            print('%-4s %s' % ('OK' if r[k] == EXPECTED[k] else 'FAIL', k))
