# AN EMPTY CELL.
#
# ``def f(): print(a)`` followed by ``f.__closure__[0]`` BEFORE ``a`` is
# assigned is CPython's empty cell, and it is the shape test_funcattrs uses to
# build one.  Reading it is a ValueError; its repr says ``empty``; and it sorts
# before every filled cell.
#
# Grail recognised only two ways for a cell to be empty -- no reader at all, and
# a standalone ``types.CellType()`` holding the private marker -- and not this
# one.  A closure cell's reader is compiled as an ordinary local read, so
# evaluating an unassigned binding raised UnboundLocalError, and that escaped
# from everywhere emptiness has to be decided: from ``cell_contents`` (where
# CPython raises ValueError), from ``repr`` (which must never raise at all), and
# from every comparison, because each one has to ask whether the cell is empty
# before it can answer.
#
# A KNOWN DEVIATION this fixture is careful to avoid tripping over, because it
# would otherwise make these checks read as passing for the wrong reason:
# Grail stamps ``__closure__`` per DEF SITE rather than per activation, so a
# helper called twice hands back the FIRST call's cells both times --
#
#     def mk(v):
#         def f(): return a
#         a = v
#         return f
#     mk(10).__closure__[0].cell_contents   # 10, correctly
#     mk(20).__closure__[0].cell_contents   # 10 in Grail, 20 in CPython
#
# -- while ``mk(20)()`` itself still answers 20, so the closure SEMANTICS are
# right and only the reflection lies.  Fixing it needs either weak-keyed storage
# (this GemStone has none) or building the cells lazily from the block's captured
# frame; see CellEmptinessTestCase.  Every probe below therefore builds its
# cells at ONE def site, entered once.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- reading an empty cell --------------------------------------------------

def _read_before_assignment():
    def f():
        print(a)
    c = f.__closure__[0]
    try:
        c.cell_contents
        out = 'accepted'
    except BaseException as e:
        out = '%s: %s' % (type(e).__name__, e)
    a = 12
    return out


def _read_after_assignment():
    def f():
        print(a)
    a = 12
    return f.__closure__[0].cell_contents


def _repr_does_not_raise():
    def f():
        print(a)
    c = f.__closure__[0]
    out = repr(c).endswith(': empty>')
    a = 12
    return out


def _the_same_cell_fills_in():
    # One cell object, read twice across the assignment: empty, then filled.
    # A cell tracks its binding rather than snapshotting it, so emptiness is a
    # question about NOW, not a property fixed when the cell was made.
    def f():
        print(a)
    c = f.__closure__[0]
    before = 'empty' if _is_empty(c) else 'filled'
    a = 12
    return (before, c.cell_contents)


def _is_empty(c):
    try:
        c.cell_contents
    except ValueError:
        return True
    return False


# --- comparisons have to decide emptiness first -----------------------------

def _empty_equals_empty():
    def f():
        print(a)

    def g():
        print(b)
    out = f.__closure__[0] == g.__closure__[0]
    a = 1
    b = 2
    return out


def _empty_sorts_before_filled():
    def f():
        print(a)

    def g():
        print(b)
    b = 'saturday'
    out = (f.__closure__[0] < g.__closure__[0],
           g.__closure__[0] > f.__closure__[0])
    a = 1
    return out


def _filled_cells_compare_by_contents():
    def f():
        print(a)

    def g():
        print(b)
    a = 2
    b = 3
    return (f.__closure__[0] < g.__closure__[0],
            f.__closure__[0] == g.__closure__[0])


def _int_and_float_cells_are_equal():
    # Nothing cell-specific: CPython defers wholly to the contents, and -36 ==
    # -36.0 is ordinary numeric equality.
    def f():
        print(a)

    def g():
        print(b)
    a = -36
    b = -36.0
    return f.__closure__[0] == g.__closure__[0]


# --- a standalone cell is still empty its own way ---------------------------

def _standalone_empty():
    import types
    c = types.CellType()
    try:
        c.cell_contents
        return 'accepted'
    except BaseException as e:
        return '%s: %s' % (type(e).__name__, e)


def _standalone_holding_none():
    # None is a VALUE a cell may hold, and CPython tells that apart from empty.
    import types
    return types.CellType(None).cell_contents


rec('read_before_assignment', _read_before_assignment)
rec('read_after_assignment', _read_after_assignment)
rec('repr_does_not_raise', _repr_does_not_raise)
rec('the_same_cell_fills_in', _the_same_cell_fills_in)
rec('empty_equals_empty', _empty_equals_empty)
rec('empty_sorts_before_filled', _empty_sorts_before_filled)
rec('filled_cells_compare_by_contents', _filled_cells_compare_by_contents)
rec('int_and_float_cells_are_equal', _int_and_float_cells_are_equal)
rec('standalone_empty', _standalone_empty)
rec('standalone_holding_none', _standalone_holding_none)


EXPECTED = {
    'empty_equals_empty': True,
    'empty_sorts_before_filled': (True, True),
    'filled_cells_compare_by_contents': (True, False),
    'int_and_float_cells_are_equal': True,
    'read_after_assignment': 12,
    'read_before_assignment': 'ValueError: Cell is empty',
    'repr_does_not_raise': True,
    'standalone_empty': 'ValueError: Cell is empty',
    'standalone_holding_none': None,
    'the_same_cell_fills_in': ('empty', 12),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-36s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
