# The closure-cell and code TYPES -- ``types.CellType`` / ``types.CodeType``,
# and the cell protocol reachable through them.
#
# Grail has had real cell and code objects for a long time: ``f.__closure__``
# hands back PyCells that read and write the enclosing binding, and
# ``f.__code__`` answers a PyCode with co_name / co_filename / co_varnames.
# What it did not have was the NAMES for them.  ``types.CellType`` and
# ``types.CodeType`` were empty stub classes, so:
#
#   * ``isinstance(c, types.CellType)`` was False about a real cell, and
#     ``type(f.__code__)`` printed ``<class 'PyCode'>`` where CPython prints
#     ``<class 'code'>``;
#   * ``types.CellType(1)`` built an inert stub instance with no cell_contents
#     at all, so the standard way to construct a cell did not work.
#
# This is the same shape as types.TracebackType before it was converted, and
# the same test types.py's own header sets for which stubs are worth
# converting: the stub stood in for a missing name, not a missing feature.
#
# A cell built by ``types.CellType(...)`` closes over NOTHING, so it needs
# somewhere of its own to keep its value; those are the cells exercised here.
# They are also the only ones that can be emptied -- see the SUnit peer for why
# ``del`` on a *closure* cell is refused rather than emptied in Grail.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import types

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- the cell type has a name, and it is the right one ----------------------

def _a_real_closure_cell():
    def outer():
        captured = 1

        def inner():
            return captured
        return inner
    return outer().__closure__[0]


rec('cell_type_name', lambda: type(_a_real_closure_cell()).__name__)
rec('cell_type_module', lambda: type(_a_real_closure_cell()).__module__)
rec('cell_isinstance', lambda: isinstance(_a_real_closure_cell(), types.CellType))
rec('cell_type_is', lambda: type(_a_real_closure_cell()) is types.CellType)


# --- constructing one -------------------------------------------------------

rec('ctor_value', lambda: types.CellType(1).cell_contents)
rec('ctor_none_is_not_empty', lambda: types.CellType(None).cell_contents)
rec('ctor_empty_reads', lambda: types.CellType().cell_contents)
rec('ctor_isinstance', lambda: isinstance(types.CellType(1), types.CellType))


# --- writing and clearing ---------------------------------------------------

def _set_contents():
    c = types.CellType(1)
    c.cell_contents = 9
    return c.cell_contents


def _del_then_read():
    c = types.CellType(1)
    del c.cell_contents
    return c.cell_contents


def _refill_after_del():
    c = types.CellType(1)
    del c.cell_contents
    c.cell_contents = 4
    return c.cell_contents


rec('set_contents', _set_contents)
rec('del_then_read', _del_then_read)
rec('refill_after_del', _refill_after_del)


# --- comparison -------------------------------------------------------------
#
# CPython's cell_richcompare sorts an empty cell BEFORE every filled one and
# otherwise defers entirely to the contents, which is why the -36 / -36.0 case
# is true: that is int/float equality, nothing cell-specific.

rec('lt_by_contents', lambda: types.CellType(2) < types.CellType(3))
rec('gt_by_contents', lambda: types.CellType(3) > types.CellType(2))
rec('eq_across_numeric_types', lambda: types.CellType(-36) == types.CellType(-36.0))
rec('empty_lt_filled', lambda: types.CellType() < types.CellType('saturday'))
rec('empty_eq_empty', lambda: types.CellType() == types.CellType())
rec('filled_gt_empty', lambda: types.CellType(True) > types.CellType())
rec('ne_by_contents', lambda: types.CellType(1) != types.CellType(2))
rec('le_equal', lambda: types.CellType(1) <= types.CellType(1))
rec('ge_equal', lambda: types.CellType(1) >= types.CellType(1))


# --- the code type ----------------------------------------------------------

def _plain():
    pass


rec('code_type_name', lambda: type(_plain.__code__).__name__)
rec('code_type_module', lambda: type(_plain.__code__).__module__)
rec('code_isinstance', lambda: isinstance(_plain.__code__, types.CodeType))
rec('code_type_is', lambda: type(_plain.__code__) is types.CodeType)


EXPECTED = {
    'cell_isinstance': True,
    'cell_type_is': True,
    'cell_type_module': 'builtins',
    'cell_type_name': 'cell',
    'code_isinstance': True,
    'code_type_is': True,
    'code_type_module': 'builtins',
    'code_type_name': 'code',
    'ctor_empty_reads': 'ValueError: Cell is empty',
    'ctor_isinstance': True,
    'ctor_none_is_not_empty': None,
    'ctor_value': 1,
    'del_then_read': 'ValueError: Cell is empty',
    'empty_eq_empty': True,
    'empty_lt_filled': True,
    'eq_across_numeric_types': True,
    'filled_gt_empty': True,
    'ge_equal': True,
    'gt_by_contents': True,
    'le_equal': True,
    'lt_by_contents': True,
    'ne_by_contents': True,
    'refill_after_del': 4,
    'set_contents': 9,
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
