# ``alias = method'' in a class body binds the SAME function object under a
# second name -- that is all CPython does, and everything below follows from it:
# ``C.alias is C.m'', ``C.alias.__name__ == 'm''', the two __dict__ entries are
# one object, and a LATER class-body statement can read the alias name like any
# other binding.
#
# Grail compiles such an alias as a real delegating METHOD instead, because a
# class-attribute callable is invisible to operator dispatch (``a < b'' sends
# #__lt__:, which resolves only to compiled methods) and mis-binds when read
# through an instance.  That is the right call for dispatch and the wrong one
# for identity -- a delegating method is a different object -- and the alias
# name was, additionally, missing from every class-body read path, so a later
# statement naming it raised NameError at class-init time.  test_reprlib failed
# to import for exactly that reason.
#
# The two halves are tested together because the fix has to keep both true at
# once: the alias reads as the ORIGINAL function object, and the compiled
# forwarder stays, so ``<'' and ``!='' still find a method.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = type(e).__name__ + ': ' + str(e)[:70]


# --- identity: an alias IS the original function ----------------------------

class Ident:
    def m(self):
        return 'm'

    alias = m

    def two(self, a, b):
        return a + b

    two_alias = two


rec('alias_is_m', lambda: Ident.alias is Ident.m)
rec('alias_name', lambda: Ident.alias.__name__)
rec('dict_entries_identical',
    lambda: Ident.__dict__['alias'] is Ident.__dict__['m'])
rec('alias_call_via_class', lambda: Ident.alias(Ident()))
rec('alias_call_via_instance', lambda: Ident().alias())
# An alias of a method that takes arguments -- the delegating form Grail emits
# has to carry the original's arity, so a wrong one shows up here.
rec('alias_with_args', lambda: Ident().two_alias(3, 4))
rec('alias_with_args_via_class', lambda: Ident.two_alias(Ident(), 3, 4))


# --- the NameError: a LATER class-body statement reads the alias name --------
#
# This is what kept test_reprlib from importing at all.  The alias binds a
# class-body name, but it is neither a def nor a class attribute in Grail's
# accounting, so the read fell through to the module and raised.

class LaterRead:
    def m(self):
        return 'm'

    wrapped = m
    wrapper = staticmethod(wrapped)
    in_tuple = (wrapped,)

    def use(self):
        return 'use'

    used = use
    listed = [used]


rec('later_read_staticmethod', lambda: LaterRead.wrapper(LaterRead()))
rec('later_read_in_tuple', lambda: LaterRead.in_tuple[0](LaterRead()))
rec('later_read_in_list', lambda: LaterRead.listed[0](LaterRead()))
rec('later_read_tuple_identity', lambda: LaterRead.in_tuple[0] is LaterRead.m)


# --- operator dispatch must still find a method ------------------------------
#
# The whole reason Grail compiles an alias as a method: ``a < b'' does not go
# through attribute lookup.  ``__ne__ = __lt__ = __le__ = __gt__ = __ge__ =
# __eq__'' is verbatim from test_heapq's CmpErr.

class AlwaysEq:
    def __eq__(self, other):
        return 'called'

    __ne__ = __lt__ = __le__ = __gt__ = __ge__ = __eq__

    __hash__ = object.__hash__


_a, _b = AlwaysEq(), AlwaysEq()
rec('op_eq', lambda: _a == _b)
rec('op_ne', lambda: _a != _b)
rec('op_lt', lambda: _a < _b)
rec('op_le', lambda: _a <= _b)
rec('op_gt', lambda: _a > _b)
rec('op_ge', lambda: _a >= _b)
# ...and each of the chained names is still the SAME object as __eq__.
rec('chain_all_identical',
    lambda: all(getattr(AlwaysEq, n) is AlwaysEq.__eq__
                for n in ('__ne__', '__lt__', '__le__', '__gt__', '__ge__')))


# --- inheritance -------------------------------------------------------------

class Base:
    def m(self):
        return 'base'

    alias = m


class InheritsAlias(Base):
    pass


class OverridesAlias(Base):
    def alias(self):
        return 'override'


class OverridesOriginal(Base):
    def m(self):
        return 'sub-m'


rec('inherited_alias_call', lambda: InheritsAlias().alias())
# The override must WIN -- a redirect that ignored the subclass's own def would
# answer 'base' here, and nothing would say so.
rec('overridden_alias_call', lambda: OverridesAlias().alias())
rec('overridden_alias_not_base',
    lambda: OverridesAlias.alias is not Base.m)
# CPython's alias is a snapshot of the function object taken at class-body time,
# so overriding the ORIGINAL in a subclass does NOT move the alias with it.
rec('override_original_alias_still_base', lambda: OverridesOriginal().alias())
rec('override_original_m', lambda: OverridesOriginal().m())


# --- forms that must NOT become aliases --------------------------------------

def _decorate(fn):
    fn.decorated = True
    return fn


class NotAliases:
    def plain(self):
        return 'plain'

    # A SELF-alias binds nothing new.
    plain = plain

    @_decorate
    def deco(self):
        return 'deco'

    # ``b = a'' where a is DECORATED must bind the decorator's result, which in
    # CPython has already replaced the def by the time the assignment runs.
    deco_alias = deco

    @staticmethod
    def stat():
        return 'stat'

    stat_alias = stat

    def varargs(self, *a, **kw):
        return ('varargs', a, kw)

    varargs_alias = varargs


rec('self_alias_call', lambda: NotAliases().plain())
rec('deco_alias_call', lambda: NotAliases().deco())
rec('deco_alias_is_deco', lambda: NotAliases.deco_alias is NotAliases.deco)
rec('deco_alias_carries_attr', lambda: NotAliases.deco_alias.decorated)
rec('static_alias_call', lambda: NotAliases.stat_alias())
rec('static_alias_is_stat', lambda: NotAliases.stat_alias is NotAliases.stat)
rec('varargs_alias_call', lambda: NotAliases().varargs_alias(1, k=2))
rec('varargs_alias_is_varargs',
    lambda: NotAliases.varargs_alias is NotAliases.varargs)


# --- __hash__ = <sibling method> is a real hash function ---------------------
#
# A class that defines __eq__ and nothing else is unhashable; aliasing a real
# method onto __hash__ opts back IN, and the implicit unhashable-__hash__ must
# not overwrite the alias.

class HashAlias:
    def __eq__(self, other):
        return self is other

    def _h(self):
        return 42

    __hash__ = _h


rec('hash_alias_value', lambda: hash(HashAlias()))
rec('hash_alias_is_h', lambda: HashAlias.__hash__ is HashAlias._h)
rec('hash_alias_in_set', lambda: len({HashAlias(), HashAlias()}))


EXPECTED = {
    'alias_call_via_class': 'm',
    'alias_call_via_instance': 'm',
    'alias_is_m': True,
    'alias_name': 'm',
    'alias_with_args': 7,
    'alias_with_args_via_class': 7,
    'chain_all_identical': True,
    'deco_alias_call': 'deco',
    'deco_alias_carries_attr': True,
    'deco_alias_is_deco': True,
    'dict_entries_identical': True,
    'hash_alias_in_set': 2,
    'hash_alias_is_h': True,
    'hash_alias_value': 42,
    'inherited_alias_call': 'base',
    'later_read_in_list': 'use',
    'later_read_in_tuple': 'm',
    'later_read_staticmethod': 'm',
    'later_read_tuple_identity': True,
    'op_eq': 'called',
    'op_ge': 'called',
    'op_gt': 'called',
    'op_le': 'called',
    'op_lt': 'called',
    'op_ne': 'called',
    'override_original_alias_still_base': 'base',
    'override_original_m': 'sub-m',
    'overridden_alias_call': 'override',
    'overridden_alias_not_base': True,
    'self_alias_call': 'plain',
    'static_alias_call': 'stat',
    'static_alias_is_stat': True,
    'varargs_alias_call': ('varargs', (1,), {'k': 2}),
    'varargs_alias_is_varargs': True,
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-34s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
