# repr() of a CLASS -- CPython's type_repr.
#
#     <class 'module.QualName'>      when __module__ is set and is not builtins
#     <class 'QualName'>             otherwise
#
# Grail had no such branch, so every class object fell through to the INSTANCE
# repr, where ``self.__class__'' is the METACLASS and its qualname carries a
# trailing ``class'':
#
#     repr(int)     -- '<Integer class object at 0x112>'
#     repr(Static)  -- '<Static class object at 0xac6244>'
#
# Three separate faults in one string.  The SHAPE is wrong.  There is an
# ADDRESS, where a class has stable identity and CPython prints none -- so the
# text was not even reproducible between runs.  And for every builtin it was the
# SMALLTALK name: ``int'' announced itself as ``Integer'', ``str'' as
# ``Unicode7''.
#
# This is not an obscure corner: it is what ``print(type(x))'' shows, what
# ``%s'' % cls and an f-string on a class produce, and what most type-error
# messages are built from.  The address made all of that unstable as well as
# wrong, which is why the checks below compare exact strings rather than
# matching a pattern.
#
# THE MODULE IS OMITTED FOR ``builtins'' EXACTLY.  That is the whole reason
# ``int'' is ``<class 'int'>'' while a class defined here carries its module,
# and a fix that always qualified would get every builtin wrong in a new way.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}

# This file is RUN as __main__ under CPython and IMPORTED as ``class_repr''
# under Grail, so its own module name differs between the two.  Every recorded
# string is normalised to ``<mod>'' so the EXPECTED table can be committed --
# the module qualifier is exactly what is under test, so it cannot simply be
# dropped.
MOD = __name__


def _norm(v):
    if isinstance(v, str):
        return v.replace("'" + MOD + ".", "'<mod>.").replace('<' + MOD + '.',
                                                             '<<mod>.')
    if isinstance(v, tuple):
        return tuple(_norm(x) for x in v)
    return v


def rec(k, fn):
    try:
        r[k] = _norm(fn())
    except BaseException as e:
        r[k] = type(e).__name__ + ': ' + str(e)[:60]


class Static:
    class Inner:
        pass


class Sub(Static):
    pass


class Meta(type):
    pass


class WithMeta(metaclass=Meta):
    pass


class ReprMeta(type):
    def __repr__(cls):
        return '<metaclass repr for %s>' % cls.__name__


class Custom(metaclass=ReprMeta):
    pass


class OwnRepr:
    """An INSTANCE repr must not be mistaken for the class's own."""

    def __repr__(self):
        return '<an OwnRepr instance>'


# --- builtins: no module qualifier -------------------------------------------

rec('int', lambda: repr(int))
rec('str', lambda: repr(str))
rec('list', lambda: repr(list))
rec('dict', lambda: repr(dict))
rec('bool', lambda: repr(bool))
rec('type_itself', lambda: repr(type))
rec('object_itself', lambda: repr(object))
rec('Exception', lambda: repr(Exception))
rec('ValueError', lambda: repr(ValueError))
# type(x) is the class, so this is the same string by another route -- and it is
# the spelling that made the old output visible in practice.
rec('type_of_an_int', lambda: repr(type(3)))
rec('type_of_a_str', lambda: str(type('x')))


# --- classes defined here: module-qualified ----------------------------------

rec('own_class', lambda: repr(Static))
rec('own_subclass', lambda: repr(Sub))
# __qualname__, not __name__: a nested class reads Outer.Inner.
rec('nested_class_uses_qualname', lambda: repr(Static.Inner))
rec('class_with_metaclass', lambda: repr(WithMeta))
rec('the_metaclass', lambda: repr(Meta))


# --- the spellings that go through the same code -----------------------------

rec('percent_s', lambda: '%s' % (Static,))
rec('fstring', lambda: '%s' % Static)
rec('str_of_class', lambda: str(Static))
rec('format', lambda: format(Static))
rec('in_a_list', lambda: repr([int, Static]))
rec('in_a_dict_value', lambda: repr({'k': int}))


# --- what must NOT change ----------------------------------------------------
#
# A user METACLASS that defines __repr__ still wins: repr(C) is
# type(C).__repr__(C), so the metaclass method is found first and the default
# never runs.
rec('metaclass_repr_wins', lambda: repr(Custom))

# An INSTANCE keeps the instance repr -- both the default one, which DOES carry
# an address, and a user-defined __repr__.  Confusing the two is the exact
# mistake being fixed, in the other direction.
rec('instance_with_own_repr', lambda: repr(OwnRepr()))
rec('instance_default_repr_shape',
    lambda: (repr(Static()).startswith('<' + MOD + '.Static object at 0x'),
             repr(Static()).endswith('>')))
# ...and an instance of a builtin is unaffected.
rec('instance_of_builtin', lambda: repr(3))
rec('instance_of_list', lambda: repr([1, 2]))

# type(x) for an instance answers the class, so these two differ by design.
rec('class_and_instance_differ',
    lambda: repr(Static) != repr(Static()))


EXPECTED = {
    'Exception': "<class 'Exception'>",
    'ValueError': "<class 'ValueError'>",
    'bool': "<class 'bool'>",
    'class_and_instance_differ': True,
    'class_with_metaclass': "<class '<mod>.WithMeta'>",
    'dict': "<class 'dict'>",
    'format': "<class '<mod>.Static'>",
    'fstring': "<class '<mod>.Static'>",
    'in_a_dict_value': "{'k': <class 'int'>}",
    'in_a_list': "[<class 'int'>, <class '<mod>.Static'>]",
    'instance_default_repr_shape': (True, True),
    'instance_of_builtin': '3',
    'instance_of_list': '[1, 2]',
    'instance_with_own_repr': '<an OwnRepr instance>',
    'int': "<class 'int'>",
    'list': "<class 'list'>",
    'metaclass_repr_wins': '<metaclass repr for Custom>',
    'nested_class_uses_qualname': "<class '<mod>.Static.Inner'>",
    'object_itself': "<class 'object'>",
    'own_class': "<class '<mod>.Static'>",
    'own_subclass': "<class '<mod>.Sub'>",
    'percent_s': "<class '<mod>.Static'>",
    'str': "<class 'str'>",
    'str_of_class': "<class '<mod>.Static'>",
    'the_metaclass': "<class '<mod>.Meta'>",
    'type_itself': "<class 'type'>",
    'type_of_a_str': "<class 'str'>",
    'type_of_an_int': "<class 'int'>",
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-32s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
