"""Issue #1218: a callable stored as a CLASS ATTRIBUTE under a protocol dunder
must be called the way CPython's special-method lookup calls it -- looked up on
the type, then bound by the descriptor protocol -- whatever the protocol and
however the value got onto the class.

Every case stores one kind of value under one dunder and exercises the implicit
protocol (``o + 1'', ``len(o)'', ``bool(o)'', ...), once in the class body and
once with setattr after the class exists.  The kinds differ in whether CPython
passes the instance:

    func, lambda, plainfn   functions: bound, the instance comes first
    classm                  bound to the CLASS
    static                  a staticmethod: the arguments alone
    bound                   a method ALREADY bound (``__len__ = lst.__len__''):
                            not a descriptor, the arguments alone
    callobj                 a callable instance: not a descriptor either

Each value reports how many arguments it received (``enc''), so passing the
instance wrongly -- or failing to -- changes the answer.  Grail used to prepend
the instance to every one of them, and several protocols (len, bool, unary
operators, __index__, int, float, a setattr __getitem__/__call__/...) never
looked at a class attribute at all; ``bool(o)'' silently answered True.

GENERATED by scripts/generate_class_attr_dunder_fixture.py -- edit that and
rerun it under CPython rather than editing this file.  The class statements
are written out one per case, because a
class-body assignment and a setattr store are different code paths and a loop
over ``type(...)'' would exercise neither.  EXPECTED is CPython 3.14's output.
"""

import io


def enc(r, n):
    # Encode the argument count into a value the protocol still accepts, so a
    # wrongly bound (or unbound) call shows up in the result.
    if r == 'v':
        return (r, n)
    if r is True or r is False:
        return n == 0
    if isinstance(r, int):
        return r + 100 * n
    if isinstance(r, float):
        return r + 100 * n
    if isinstance(r, str):
        return r + str(n)
    return r


class Ret:
    def __init__(self, r):
        self.r = r

    def m(self, *a):
        return enc(self.r, len(a))


class CallObj:
    def __init__(self, r):
        self.r = r

    def __call__(self, *a):
        return enc(self.r, len(a))


def mkfunc(r):
    def f(*a):
        return enc(r, len(a))
    return f


def _setitem(o):
    o[0] = 1
    return 'set'


def _with(o):
    with o as v:
        return v


RESULTS = {}


def run(label, thunk):
    try:
        r = thunk()
    except Exception as e:
        r = type(e).__name__
    RESULTS[label] = repr(r)


# ---- generated cases ----
class B1:
    __add__ = mkfunc('v')
run('body    __add__ func', lambda: (lambda o: o + 1)(B1()))
class S1:
    pass
S1.__add__ = mkfunc('v')
run('setattr __add__ func', lambda: (lambda o: o + 1)(S1()))
class B2:
    __add__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __add__ lambda', lambda: (lambda o: o + 1)(B2()))
class S2:
    pass
S2.__add__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __add__ lambda', lambda: (lambda o: o + 1)(S2()))
class H3:
    def f(*a):
        return enc('v', len(a))
class B3:
    __add__ = H3.f
run('body    __add__ plainfn', lambda: (lambda o: o + 1)(B3()))
class S3:
    pass
S3.__add__ = H3.f
run('setattr __add__ plainfn', lambda: (lambda o: o + 1)(S3()))
class B4:
    __add__ = classmethod(mkfunc('v'))
run('body    __add__ classm', lambda: (lambda o: o + 1)(B4()))
class S4:
    pass
S4.__add__ = classmethod(mkfunc('v'))
run('setattr __add__ classm', lambda: (lambda o: o + 1)(S4()))
class B5:
    __add__ = staticmethod(mkfunc('v'))
run('body    __add__ static', lambda: (lambda o: o + 1)(B5()))
class S5:
    pass
S5.__add__ = staticmethod(mkfunc('v'))
run('setattr __add__ static', lambda: (lambda o: o + 1)(S5()))
class B6:
    __add__ = Ret('v').m
run('body    __add__ bound', lambda: (lambda o: o + 1)(B6()))
class S6:
    pass
S6.__add__ = Ret('v').m
run('setattr __add__ bound', lambda: (lambda o: o + 1)(S6()))
class B7:
    __add__ = CallObj('v')
run('body    __add__ callobj', lambda: (lambda o: o + 1)(B7()))
class S7:
    pass
S7.__add__ = CallObj('v')
run('setattr __add__ callobj', lambda: (lambda o: o + 1)(S7()))
class B8:
    __radd__ = mkfunc('v')
run('body    __radd__ func', lambda: (lambda o: 1 + o)(B8()))
class S8:
    pass
S8.__radd__ = mkfunc('v')
run('setattr __radd__ func', lambda: (lambda o: 1 + o)(S8()))
class B9:
    __radd__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __radd__ lambda', lambda: (lambda o: 1 + o)(B9()))
class S9:
    pass
S9.__radd__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __radd__ lambda', lambda: (lambda o: 1 + o)(S9()))
class H10:
    def f(*a):
        return enc('v', len(a))
class B10:
    __radd__ = H10.f
run('body    __radd__ plainfn', lambda: (lambda o: 1 + o)(B10()))
class S10:
    pass
S10.__radd__ = H10.f
run('setattr __radd__ plainfn', lambda: (lambda o: 1 + o)(S10()))
class B11:
    __radd__ = classmethod(mkfunc('v'))
run('body    __radd__ classm', lambda: (lambda o: 1 + o)(B11()))
class S11:
    pass
S11.__radd__ = classmethod(mkfunc('v'))
run('setattr __radd__ classm', lambda: (lambda o: 1 + o)(S11()))
class B12:
    __radd__ = staticmethod(mkfunc('v'))
run('body    __radd__ static', lambda: (lambda o: 1 + o)(B12()))
class S12:
    pass
S12.__radd__ = staticmethod(mkfunc('v'))
run('setattr __radd__ static', lambda: (lambda o: 1 + o)(S12()))
class B13:
    __radd__ = Ret('v').m
run('body    __radd__ bound', lambda: (lambda o: 1 + o)(B13()))
class S13:
    pass
S13.__radd__ = Ret('v').m
run('setattr __radd__ bound', lambda: (lambda o: 1 + o)(S13()))
class B14:
    __radd__ = CallObj('v')
run('body    __radd__ callobj', lambda: (lambda o: 1 + o)(B14()))
class S14:
    pass
S14.__radd__ = CallObj('v')
run('setattr __radd__ callobj', lambda: (lambda o: 1 + o)(S14()))
class B15:
    __lt__ = mkfunc('v')
run('body    __lt__ func', lambda: (lambda o: o < 1)(B15()))
class S15:
    pass
S15.__lt__ = mkfunc('v')
run('setattr __lt__ func', lambda: (lambda o: o < 1)(S15()))
class B16:
    __lt__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __lt__ lambda', lambda: (lambda o: o < 1)(B16()))
class S16:
    pass
S16.__lt__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __lt__ lambda', lambda: (lambda o: o < 1)(S16()))
class H17:
    def f(*a):
        return enc('v', len(a))
class B17:
    __lt__ = H17.f
run('body    __lt__ plainfn', lambda: (lambda o: o < 1)(B17()))
class S17:
    pass
S17.__lt__ = H17.f
run('setattr __lt__ plainfn', lambda: (lambda o: o < 1)(S17()))
class B18:
    __lt__ = classmethod(mkfunc('v'))
run('body    __lt__ classm', lambda: (lambda o: o < 1)(B18()))
class S18:
    pass
S18.__lt__ = classmethod(mkfunc('v'))
run('setattr __lt__ classm', lambda: (lambda o: o < 1)(S18()))
class B19:
    __lt__ = staticmethod(mkfunc('v'))
run('body    __lt__ static', lambda: (lambda o: o < 1)(B19()))
class S19:
    pass
S19.__lt__ = staticmethod(mkfunc('v'))
run('setattr __lt__ static', lambda: (lambda o: o < 1)(S19()))
class B20:
    __lt__ = Ret('v').m
run('body    __lt__ bound', lambda: (lambda o: o < 1)(B20()))
class S20:
    pass
S20.__lt__ = Ret('v').m
run('setattr __lt__ bound', lambda: (lambda o: o < 1)(S20()))
class B21:
    __lt__ = CallObj('v')
run('body    __lt__ callobj', lambda: (lambda o: o < 1)(B21()))
class S21:
    pass
S21.__lt__ = CallObj('v')
run('setattr __lt__ callobj', lambda: (lambda o: o < 1)(S21()))
class B22:
    __eq__ = mkfunc('v')
run('body    __eq__ func', lambda: (lambda o: o == 1)(B22()))
class S22:
    pass
S22.__eq__ = mkfunc('v')
run('setattr __eq__ func', lambda: (lambda o: o == 1)(S22()))
class B23:
    __eq__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __eq__ lambda', lambda: (lambda o: o == 1)(B23()))
class S23:
    pass
S23.__eq__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __eq__ lambda', lambda: (lambda o: o == 1)(S23()))
class H24:
    def f(*a):
        return enc('v', len(a))
class B24:
    __eq__ = H24.f
run('body    __eq__ plainfn', lambda: (lambda o: o == 1)(B24()))
class S24:
    pass
S24.__eq__ = H24.f
run('setattr __eq__ plainfn', lambda: (lambda o: o == 1)(S24()))
class B25:
    __eq__ = classmethod(mkfunc('v'))
run('body    __eq__ classm', lambda: (lambda o: o == 1)(B25()))
class S25:
    pass
S25.__eq__ = classmethod(mkfunc('v'))
run('setattr __eq__ classm', lambda: (lambda o: o == 1)(S25()))
class B26:
    __eq__ = staticmethod(mkfunc('v'))
run('body    __eq__ static', lambda: (lambda o: o == 1)(B26()))
class S26:
    pass
S26.__eq__ = staticmethod(mkfunc('v'))
run('setattr __eq__ static', lambda: (lambda o: o == 1)(S26()))
class B27:
    __eq__ = Ret('v').m
run('body    __eq__ bound', lambda: (lambda o: o == 1)(B27()))
class S27:
    pass
S27.__eq__ = Ret('v').m
run('setattr __eq__ bound', lambda: (lambda o: o == 1)(S27()))
class B28:
    __eq__ = CallObj('v')
run('body    __eq__ callobj', lambda: (lambda o: o == 1)(B28()))
class S28:
    pass
S28.__eq__ = CallObj('v')
run('setattr __eq__ callobj', lambda: (lambda o: o == 1)(S28()))
class B29:
    __call__ = mkfunc('v')
run('body    __call__ func', lambda: (lambda o: o())(B29()))
class S29:
    pass
S29.__call__ = mkfunc('v')
run('setattr __call__ func', lambda: (lambda o: o())(S29()))
class B30:
    __call__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __call__ lambda', lambda: (lambda o: o())(B30()))
class S30:
    pass
S30.__call__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __call__ lambda', lambda: (lambda o: o())(S30()))
class H31:
    def f(*a):
        return enc('v', len(a))
class B31:
    __call__ = H31.f
run('body    __call__ plainfn', lambda: (lambda o: o())(B31()))
class S31:
    pass
S31.__call__ = H31.f
run('setattr __call__ plainfn', lambda: (lambda o: o())(S31()))
class B32:
    __call__ = classmethod(mkfunc('v'))
run('body    __call__ classm', lambda: (lambda o: o())(B32()))
class S32:
    pass
S32.__call__ = classmethod(mkfunc('v'))
run('setattr __call__ classm', lambda: (lambda o: o())(S32()))
class B33:
    __call__ = staticmethod(mkfunc('v'))
run('body    __call__ static', lambda: (lambda o: o())(B33()))
class S33:
    pass
S33.__call__ = staticmethod(mkfunc('v'))
run('setattr __call__ static', lambda: (lambda o: o())(S33()))
class B34:
    __call__ = Ret('v').m
run('body    __call__ bound', lambda: (lambda o: o())(B34()))
class S34:
    pass
S34.__call__ = Ret('v').m
run('setattr __call__ bound', lambda: (lambda o: o())(S34()))
class B35:
    __call__ = CallObj('v')
run('body    __call__ callobj', lambda: (lambda o: o())(B35()))
class S35:
    pass
S35.__call__ = CallObj('v')
run('setattr __call__ callobj', lambda: (lambda o: o())(S35()))
class B36:
    __getitem__ = mkfunc('v')
run('body    __getitem__ func', lambda: (lambda o: o[0])(B36()))
class S36:
    pass
S36.__getitem__ = mkfunc('v')
run('setattr __getitem__ func', lambda: (lambda o: o[0])(S36()))
class B37:
    __getitem__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __getitem__ lambda', lambda: (lambda o: o[0])(B37()))
class S37:
    pass
S37.__getitem__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __getitem__ lambda', lambda: (lambda o: o[0])(S37()))
class H38:
    def f(*a):
        return enc('v', len(a))
class B38:
    __getitem__ = H38.f
run('body    __getitem__ plainfn', lambda: (lambda o: o[0])(B38()))
class S38:
    pass
S38.__getitem__ = H38.f
run('setattr __getitem__ plainfn', lambda: (lambda o: o[0])(S38()))
class B39:
    __getitem__ = classmethod(mkfunc('v'))
run('body    __getitem__ classm', lambda: (lambda o: o[0])(B39()))
class S39:
    pass
S39.__getitem__ = classmethod(mkfunc('v'))
run('setattr __getitem__ classm', lambda: (lambda o: o[0])(S39()))
class B40:
    __getitem__ = staticmethod(mkfunc('v'))
run('body    __getitem__ static', lambda: (lambda o: o[0])(B40()))
class S40:
    pass
S40.__getitem__ = staticmethod(mkfunc('v'))
run('setattr __getitem__ static', lambda: (lambda o: o[0])(S40()))
class B41:
    __getitem__ = Ret('v').m
run('body    __getitem__ bound', lambda: (lambda o: o[0])(B41()))
class S41:
    pass
S41.__getitem__ = Ret('v').m
run('setattr __getitem__ bound', lambda: (lambda o: o[0])(S41()))
class B42:
    __getitem__ = CallObj('v')
run('body    __getitem__ callobj', lambda: (lambda o: o[0])(B42()))
class S42:
    pass
S42.__getitem__ = CallObj('v')
run('setattr __getitem__ callobj', lambda: (lambda o: o[0])(S42()))
class B43:
    __setitem__ = mkfunc('v')
run('body    __setitem__ func', lambda: (lambda o: _setitem(o))(B43()))
class S43:
    pass
S43.__setitem__ = mkfunc('v')
run('setattr __setitem__ func', lambda: (lambda o: _setitem(o))(S43()))
class B44:
    __setitem__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __setitem__ lambda', lambda: (lambda o: _setitem(o))(B44()))
class S44:
    pass
S44.__setitem__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __setitem__ lambda', lambda: (lambda o: _setitem(o))(S44()))
class H45:
    def f(*a):
        return enc('v', len(a))
class B45:
    __setitem__ = H45.f
run('body    __setitem__ plainfn', lambda: (lambda o: _setitem(o))(B45()))
class S45:
    pass
S45.__setitem__ = H45.f
run('setattr __setitem__ plainfn', lambda: (lambda o: _setitem(o))(S45()))
class B46:
    __setitem__ = classmethod(mkfunc('v'))
run('body    __setitem__ classm', lambda: (lambda o: _setitem(o))(B46()))
class S46:
    pass
S46.__setitem__ = classmethod(mkfunc('v'))
run('setattr __setitem__ classm', lambda: (lambda o: _setitem(o))(S46()))
class B47:
    __setitem__ = staticmethod(mkfunc('v'))
run('body    __setitem__ static', lambda: (lambda o: _setitem(o))(B47()))
class S47:
    pass
S47.__setitem__ = staticmethod(mkfunc('v'))
run('setattr __setitem__ static', lambda: (lambda o: _setitem(o))(S47()))
class B48:
    __setitem__ = Ret('v').m
run('body    __setitem__ bound', lambda: (lambda o: _setitem(o))(B48()))
class S48:
    pass
S48.__setitem__ = Ret('v').m
run('setattr __setitem__ bound', lambda: (lambda o: _setitem(o))(S48()))
class B49:
    __setitem__ = CallObj('v')
run('body    __setitem__ callobj', lambda: (lambda o: _setitem(o))(B49()))
class S49:
    pass
S49.__setitem__ = CallObj('v')
run('setattr __setitem__ callobj', lambda: (lambda o: _setitem(o))(S49()))
class B50:
    __contains__ = mkfunc(True)
run('body    __contains__ func', lambda: (lambda o: 1 in o)(B50()))
class S50:
    pass
S50.__contains__ = mkfunc(True)
run('setattr __contains__ func', lambda: (lambda o: 1 in o)(S50()))
class B51:
    __contains__ = (lambda r: lambda *a: enc(r, len(a)))(True)
run('body    __contains__ lambda', lambda: (lambda o: 1 in o)(B51()))
class S51:
    pass
S51.__contains__ = (lambda r: lambda *a: enc(r, len(a)))(True)
run('setattr __contains__ lambda', lambda: (lambda o: 1 in o)(S51()))
class H52:
    def f(*a):
        return enc(True, len(a))
class B52:
    __contains__ = H52.f
run('body    __contains__ plainfn', lambda: (lambda o: 1 in o)(B52()))
class S52:
    pass
S52.__contains__ = H52.f
run('setattr __contains__ plainfn', lambda: (lambda o: 1 in o)(S52()))
class B53:
    __contains__ = classmethod(mkfunc(True))
run('body    __contains__ classm', lambda: (lambda o: 1 in o)(B53()))
class S53:
    pass
S53.__contains__ = classmethod(mkfunc(True))
run('setattr __contains__ classm', lambda: (lambda o: 1 in o)(S53()))
class B54:
    __contains__ = staticmethod(mkfunc(True))
run('body    __contains__ static', lambda: (lambda o: 1 in o)(B54()))
class S54:
    pass
S54.__contains__ = staticmethod(mkfunc(True))
run('setattr __contains__ static', lambda: (lambda o: 1 in o)(S54()))
class B55:
    __contains__ = Ret(True).m
run('body    __contains__ bound', lambda: (lambda o: 1 in o)(B55()))
class S55:
    pass
S55.__contains__ = Ret(True).m
run('setattr __contains__ bound', lambda: (lambda o: 1 in o)(S55()))
class B56:
    __contains__ = CallObj(True)
run('body    __contains__ callobj', lambda: (lambda o: 1 in o)(B56()))
class S56:
    pass
S56.__contains__ = CallObj(True)
run('setattr __contains__ callobj', lambda: (lambda o: 1 in o)(S56()))
class B57:
    __len__ = mkfunc(3)
run('body    __len__ func', lambda: (lambda o: len(o))(B57()))
class S57:
    pass
S57.__len__ = mkfunc(3)
run('setattr __len__ func', lambda: (lambda o: len(o))(S57()))
class B58:
    __len__ = (lambda r: lambda *a: enc(r, len(a)))(3)
run('body    __len__ lambda', lambda: (lambda o: len(o))(B58()))
class S58:
    pass
S58.__len__ = (lambda r: lambda *a: enc(r, len(a)))(3)
run('setattr __len__ lambda', lambda: (lambda o: len(o))(S58()))
class H59:
    def f(*a):
        return enc(3, len(a))
class B59:
    __len__ = H59.f
run('body    __len__ plainfn', lambda: (lambda o: len(o))(B59()))
class S59:
    pass
S59.__len__ = H59.f
run('setattr __len__ plainfn', lambda: (lambda o: len(o))(S59()))
class B60:
    __len__ = classmethod(mkfunc(3))
run('body    __len__ classm', lambda: (lambda o: len(o))(B60()))
class S60:
    pass
S60.__len__ = classmethod(mkfunc(3))
run('setattr __len__ classm', lambda: (lambda o: len(o))(S60()))
class B61:
    __len__ = staticmethod(mkfunc(3))
run('body    __len__ static', lambda: (lambda o: len(o))(B61()))
class S61:
    pass
S61.__len__ = staticmethod(mkfunc(3))
run('setattr __len__ static', lambda: (lambda o: len(o))(S61()))
class B62:
    __len__ = Ret(3).m
run('body    __len__ bound', lambda: (lambda o: len(o))(B62()))
class S62:
    pass
S62.__len__ = Ret(3).m
run('setattr __len__ bound', lambda: (lambda o: len(o))(S62()))
class B63:
    __len__ = CallObj(3)
run('body    __len__ callobj', lambda: (lambda o: len(o))(B63()))
class S63:
    pass
S63.__len__ = CallObj(3)
run('setattr __len__ callobj', lambda: (lambda o: len(o))(S63()))
class B64:
    __bool__ = mkfunc(False)
run('body    __bool__ func', lambda: (lambda o: bool(o))(B64()))
class S64:
    pass
S64.__bool__ = mkfunc(False)
run('setattr __bool__ func', lambda: (lambda o: bool(o))(S64()))
class B65:
    __bool__ = (lambda r: lambda *a: enc(r, len(a)))(False)
run('body    __bool__ lambda', lambda: (lambda o: bool(o))(B65()))
class S65:
    pass
S65.__bool__ = (lambda r: lambda *a: enc(r, len(a)))(False)
run('setattr __bool__ lambda', lambda: (lambda o: bool(o))(S65()))
class H66:
    def f(*a):
        return enc(False, len(a))
class B66:
    __bool__ = H66.f
run('body    __bool__ plainfn', lambda: (lambda o: bool(o))(B66()))
class S66:
    pass
S66.__bool__ = H66.f
run('setattr __bool__ plainfn', lambda: (lambda o: bool(o))(S66()))
class B67:
    __bool__ = classmethod(mkfunc(False))
run('body    __bool__ classm', lambda: (lambda o: bool(o))(B67()))
class S67:
    pass
S67.__bool__ = classmethod(mkfunc(False))
run('setattr __bool__ classm', lambda: (lambda o: bool(o))(S67()))
class B68:
    __bool__ = staticmethod(mkfunc(False))
run('body    __bool__ static', lambda: (lambda o: bool(o))(B68()))
class S68:
    pass
S68.__bool__ = staticmethod(mkfunc(False))
run('setattr __bool__ static', lambda: (lambda o: bool(o))(S68()))
class B69:
    __bool__ = Ret(False).m
run('body    __bool__ bound', lambda: (lambda o: bool(o))(B69()))
class S69:
    pass
S69.__bool__ = Ret(False).m
run('setattr __bool__ bound', lambda: (lambda o: bool(o))(S69()))
class B70:
    __bool__ = CallObj(False)
run('body    __bool__ callobj', lambda: (lambda o: bool(o))(B70()))
class S70:
    pass
S70.__bool__ = CallObj(False)
run('setattr __bool__ callobj', lambda: (lambda o: bool(o))(S70()))
class B71:
    __iter__ = mkfunc(iter([]))
run('body    __iter__ func', lambda: (lambda o: type(iter(o)).__name__)(B71()))
class S71:
    pass
S71.__iter__ = mkfunc(iter([]))
run('setattr __iter__ func', lambda: (lambda o: type(iter(o)).__name__)(S71()))
class B72:
    __iter__ = (lambda r: lambda *a: enc(r, len(a)))(iter([]))
run('body    __iter__ lambda', lambda: (lambda o: type(iter(o)).__name__)(B72()))
class S72:
    pass
S72.__iter__ = (lambda r: lambda *a: enc(r, len(a)))(iter([]))
run('setattr __iter__ lambda', lambda: (lambda o: type(iter(o)).__name__)(S72()))
class H73:
    def f(*a):
        return enc(iter([]), len(a))
class B73:
    __iter__ = H73.f
run('body    __iter__ plainfn', lambda: (lambda o: type(iter(o)).__name__)(B73()))
class S73:
    pass
S73.__iter__ = H73.f
run('setattr __iter__ plainfn', lambda: (lambda o: type(iter(o)).__name__)(S73()))
class B74:
    __iter__ = classmethod(mkfunc(iter([])))
run('body    __iter__ classm', lambda: (lambda o: type(iter(o)).__name__)(B74()))
class S74:
    pass
S74.__iter__ = classmethod(mkfunc(iter([])))
run('setattr __iter__ classm', lambda: (lambda o: type(iter(o)).__name__)(S74()))
class B75:
    __iter__ = staticmethod(mkfunc(iter([])))
run('body    __iter__ static', lambda: (lambda o: type(iter(o)).__name__)(B75()))
class S75:
    pass
S75.__iter__ = staticmethod(mkfunc(iter([])))
run('setattr __iter__ static', lambda: (lambda o: type(iter(o)).__name__)(S75()))
class B76:
    __iter__ = Ret(iter([])).m
run('body    __iter__ bound', lambda: (lambda o: type(iter(o)).__name__)(B76()))
class S76:
    pass
S76.__iter__ = Ret(iter([])).m
run('setattr __iter__ bound', lambda: (lambda o: type(iter(o)).__name__)(S76()))
class B77:
    __iter__ = CallObj(iter([]))
run('body    __iter__ callobj', lambda: (lambda o: type(iter(o)).__name__)(B77()))
class S77:
    pass
S77.__iter__ = CallObj(iter([]))
run('setattr __iter__ callobj', lambda: (lambda o: type(iter(o)).__name__)(S77()))
class B78:
    __next__ = mkfunc('v')
run('body    __next__ func', lambda: (lambda o: next(o))(B78()))
class S78:
    pass
S78.__next__ = mkfunc('v')
run('setattr __next__ func', lambda: (lambda o: next(o))(S78()))
class B79:
    __next__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __next__ lambda', lambda: (lambda o: next(o))(B79()))
class S79:
    pass
S79.__next__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __next__ lambda', lambda: (lambda o: next(o))(S79()))
class H80:
    def f(*a):
        return enc('v', len(a))
class B80:
    __next__ = H80.f
run('body    __next__ plainfn', lambda: (lambda o: next(o))(B80()))
class S80:
    pass
S80.__next__ = H80.f
run('setattr __next__ plainfn', lambda: (lambda o: next(o))(S80()))
class B81:
    __next__ = classmethod(mkfunc('v'))
run('body    __next__ classm', lambda: (lambda o: next(o))(B81()))
class S81:
    pass
S81.__next__ = classmethod(mkfunc('v'))
run('setattr __next__ classm', lambda: (lambda o: next(o))(S81()))
class B82:
    __next__ = staticmethod(mkfunc('v'))
run('body    __next__ static', lambda: (lambda o: next(o))(B82()))
class S82:
    pass
S82.__next__ = staticmethod(mkfunc('v'))
run('setattr __next__ static', lambda: (lambda o: next(o))(S82()))
class B83:
    __next__ = Ret('v').m
run('body    __next__ bound', lambda: (lambda o: next(o))(B83()))
class S83:
    pass
S83.__next__ = Ret('v').m
run('setattr __next__ bound', lambda: (lambda o: next(o))(S83()))
class B84:
    __next__ = CallObj('v')
run('body    __next__ callobj', lambda: (lambda o: next(o))(B84()))
class S84:
    pass
S84.__next__ = CallObj('v')
run('setattr __next__ callobj', lambda: (lambda o: next(o))(S84()))
class B85:
    __reversed__ = mkfunc(iter([]))
run('body    __reversed__ func', lambda: (lambda o: type(reversed(o)).__name__)(B85()))
class S85:
    pass
S85.__reversed__ = mkfunc(iter([]))
run('setattr __reversed__ func', lambda: (lambda o: type(reversed(o)).__name__)(S85()))
class B86:
    __reversed__ = (lambda r: lambda *a: enc(r, len(a)))(iter([]))
run('body    __reversed__ lambda', lambda: (lambda o: type(reversed(o)).__name__)(B86()))
class S86:
    pass
S86.__reversed__ = (lambda r: lambda *a: enc(r, len(a)))(iter([]))
run('setattr __reversed__ lambda', lambda: (lambda o: type(reversed(o)).__name__)(S86()))
class H87:
    def f(*a):
        return enc(iter([]), len(a))
class B87:
    __reversed__ = H87.f
run('body    __reversed__ plainfn', lambda: (lambda o: type(reversed(o)).__name__)(B87()))
class S87:
    pass
S87.__reversed__ = H87.f
run('setattr __reversed__ plainfn', lambda: (lambda o: type(reversed(o)).__name__)(S87()))
class B88:
    __reversed__ = classmethod(mkfunc(iter([])))
run('body    __reversed__ classm', lambda: (lambda o: type(reversed(o)).__name__)(B88()))
class S88:
    pass
S88.__reversed__ = classmethod(mkfunc(iter([])))
run('setattr __reversed__ classm', lambda: (lambda o: type(reversed(o)).__name__)(S88()))
class B89:
    __reversed__ = staticmethod(mkfunc(iter([])))
run('body    __reversed__ static', lambda: (lambda o: type(reversed(o)).__name__)(B89()))
class S89:
    pass
S89.__reversed__ = staticmethod(mkfunc(iter([])))
run('setattr __reversed__ static', lambda: (lambda o: type(reversed(o)).__name__)(S89()))
class B90:
    __reversed__ = Ret(iter([])).m
run('body    __reversed__ bound', lambda: (lambda o: type(reversed(o)).__name__)(B90()))
class S90:
    pass
S90.__reversed__ = Ret(iter([])).m
run('setattr __reversed__ bound', lambda: (lambda o: type(reversed(o)).__name__)(S90()))
class B91:
    __reversed__ = CallObj(iter([]))
run('body    __reversed__ callobj', lambda: (lambda o: type(reversed(o)).__name__)(B91()))
class S91:
    pass
S91.__reversed__ = CallObj(iter([]))
run('setattr __reversed__ callobj', lambda: (lambda o: type(reversed(o)).__name__)(S91()))
class B92:
    __repr__ = mkfunc('r')
run('body    __repr__ func', lambda: (lambda o: repr(o))(B92()))
class S92:
    pass
S92.__repr__ = mkfunc('r')
run('setattr __repr__ func', lambda: (lambda o: repr(o))(S92()))
class B93:
    __repr__ = (lambda r: lambda *a: enc(r, len(a)))('r')
run('body    __repr__ lambda', lambda: (lambda o: repr(o))(B93()))
class S93:
    pass
S93.__repr__ = (lambda r: lambda *a: enc(r, len(a)))('r')
run('setattr __repr__ lambda', lambda: (lambda o: repr(o))(S93()))
class H94:
    def f(*a):
        return enc('r', len(a))
class B94:
    __repr__ = H94.f
run('body    __repr__ plainfn', lambda: (lambda o: repr(o))(B94()))
class S94:
    pass
S94.__repr__ = H94.f
run('setattr __repr__ plainfn', lambda: (lambda o: repr(o))(S94()))
class B95:
    __repr__ = classmethod(mkfunc('r'))
run('body    __repr__ classm', lambda: (lambda o: repr(o))(B95()))
class S95:
    pass
S95.__repr__ = classmethod(mkfunc('r'))
run('setattr __repr__ classm', lambda: (lambda o: repr(o))(S95()))
class B96:
    __repr__ = staticmethod(mkfunc('r'))
run('body    __repr__ static', lambda: (lambda o: repr(o))(B96()))
class S96:
    pass
S96.__repr__ = staticmethod(mkfunc('r'))
run('setattr __repr__ static', lambda: (lambda o: repr(o))(S96()))
class B97:
    __repr__ = Ret('r').m
run('body    __repr__ bound', lambda: (lambda o: repr(o))(B97()))
class S97:
    pass
S97.__repr__ = Ret('r').m
run('setattr __repr__ bound', lambda: (lambda o: repr(o))(S97()))
class B98:
    __repr__ = CallObj('r')
run('body    __repr__ callobj', lambda: (lambda o: repr(o))(B98()))
class S98:
    pass
S98.__repr__ = CallObj('r')
run('setattr __repr__ callobj', lambda: (lambda o: repr(o))(S98()))
class B99:
    __str__ = mkfunc('s')
run('body    __str__ func', lambda: (lambda o: str(o))(B99()))
class S99:
    pass
S99.__str__ = mkfunc('s')
run('setattr __str__ func', lambda: (lambda o: str(o))(S99()))
class B100:
    __str__ = (lambda r: lambda *a: enc(r, len(a)))('s')
run('body    __str__ lambda', lambda: (lambda o: str(o))(B100()))
class S100:
    pass
S100.__str__ = (lambda r: lambda *a: enc(r, len(a)))('s')
run('setattr __str__ lambda', lambda: (lambda o: str(o))(S100()))
class H101:
    def f(*a):
        return enc('s', len(a))
class B101:
    __str__ = H101.f
run('body    __str__ plainfn', lambda: (lambda o: str(o))(B101()))
class S101:
    pass
S101.__str__ = H101.f
run('setattr __str__ plainfn', lambda: (lambda o: str(o))(S101()))
class B102:
    __str__ = classmethod(mkfunc('s'))
run('body    __str__ classm', lambda: (lambda o: str(o))(B102()))
class S102:
    pass
S102.__str__ = classmethod(mkfunc('s'))
run('setattr __str__ classm', lambda: (lambda o: str(o))(S102()))
class B103:
    __str__ = staticmethod(mkfunc('s'))
run('body    __str__ static', lambda: (lambda o: str(o))(B103()))
class S103:
    pass
S103.__str__ = staticmethod(mkfunc('s'))
run('setattr __str__ static', lambda: (lambda o: str(o))(S103()))
class B104:
    __str__ = Ret('s').m
run('body    __str__ bound', lambda: (lambda o: str(o))(B104()))
class S104:
    pass
S104.__str__ = Ret('s').m
run('setattr __str__ bound', lambda: (lambda o: str(o))(S104()))
class B105:
    __str__ = CallObj('s')
run('body    __str__ callobj', lambda: (lambda o: str(o))(B105()))
class S105:
    pass
S105.__str__ = CallObj('s')
run('setattr __str__ callobj', lambda: (lambda o: str(o))(S105()))
class B106:
    __format__ = mkfunc('f')
run('body    __format__ func', lambda: (lambda o: format(o, 'x'))(B106()))
class S106:
    pass
S106.__format__ = mkfunc('f')
run('setattr __format__ func', lambda: (lambda o: format(o, 'x'))(S106()))
class B107:
    __format__ = (lambda r: lambda *a: enc(r, len(a)))('f')
run('body    __format__ lambda', lambda: (lambda o: format(o, 'x'))(B107()))
class S107:
    pass
S107.__format__ = (lambda r: lambda *a: enc(r, len(a)))('f')
run('setattr __format__ lambda', lambda: (lambda o: format(o, 'x'))(S107()))
class H108:
    def f(*a):
        return enc('f', len(a))
class B108:
    __format__ = H108.f
run('body    __format__ plainfn', lambda: (lambda o: format(o, 'x'))(B108()))
class S108:
    pass
S108.__format__ = H108.f
run('setattr __format__ plainfn', lambda: (lambda o: format(o, 'x'))(S108()))
class B109:
    __format__ = classmethod(mkfunc('f'))
run('body    __format__ classm', lambda: (lambda o: format(o, 'x'))(B109()))
class S109:
    pass
S109.__format__ = classmethod(mkfunc('f'))
run('setattr __format__ classm', lambda: (lambda o: format(o, 'x'))(S109()))
class B110:
    __format__ = staticmethod(mkfunc('f'))
run('body    __format__ static', lambda: (lambda o: format(o, 'x'))(B110()))
class S110:
    pass
S110.__format__ = staticmethod(mkfunc('f'))
run('setattr __format__ static', lambda: (lambda o: format(o, 'x'))(S110()))
class B111:
    __format__ = Ret('f').m
run('body    __format__ bound', lambda: (lambda o: format(o, 'x'))(B111()))
class S111:
    pass
S111.__format__ = Ret('f').m
run('setattr __format__ bound', lambda: (lambda o: format(o, 'x'))(S111()))
class B112:
    __format__ = CallObj('f')
run('body    __format__ callobj', lambda: (lambda o: format(o, 'x'))(B112()))
class S112:
    pass
S112.__format__ = CallObj('f')
run('setattr __format__ callobj', lambda: (lambda o: format(o, 'x'))(S112()))
class B113:
    __hash__ = mkfunc(7)
run('body    __hash__ func', lambda: (lambda o: hash(o))(B113()))
class S113:
    pass
S113.__hash__ = mkfunc(7)
run('setattr __hash__ func', lambda: (lambda o: hash(o))(S113()))
class B114:
    __hash__ = (lambda r: lambda *a: enc(r, len(a)))(7)
run('body    __hash__ lambda', lambda: (lambda o: hash(o))(B114()))
class S114:
    pass
S114.__hash__ = (lambda r: lambda *a: enc(r, len(a)))(7)
run('setattr __hash__ lambda', lambda: (lambda o: hash(o))(S114()))
class H115:
    def f(*a):
        return enc(7, len(a))
class B115:
    __hash__ = H115.f
run('body    __hash__ plainfn', lambda: (lambda o: hash(o))(B115()))
class S115:
    pass
S115.__hash__ = H115.f
run('setattr __hash__ plainfn', lambda: (lambda o: hash(o))(S115()))
class B116:
    __hash__ = classmethod(mkfunc(7))
run('body    __hash__ classm', lambda: (lambda o: hash(o))(B116()))
class S116:
    pass
S116.__hash__ = classmethod(mkfunc(7))
run('setattr __hash__ classm', lambda: (lambda o: hash(o))(S116()))
class B117:
    __hash__ = staticmethod(mkfunc(7))
run('body    __hash__ static', lambda: (lambda o: hash(o))(B117()))
class S117:
    pass
S117.__hash__ = staticmethod(mkfunc(7))
run('setattr __hash__ static', lambda: (lambda o: hash(o))(S117()))
class B118:
    __hash__ = Ret(7).m
run('body    __hash__ bound', lambda: (lambda o: hash(o))(B118()))
class S118:
    pass
S118.__hash__ = Ret(7).m
run('setattr __hash__ bound', lambda: (lambda o: hash(o))(S118()))
class B119:
    __hash__ = CallObj(7)
run('body    __hash__ callobj', lambda: (lambda o: hash(o))(B119()))
class S119:
    pass
S119.__hash__ = CallObj(7)
run('setattr __hash__ callobj', lambda: (lambda o: hash(o))(S119()))
class B120:
    __neg__ = mkfunc('v')
run('body    __neg__ func', lambda: (lambda o: -o)(B120()))
class S120:
    pass
S120.__neg__ = mkfunc('v')
run('setattr __neg__ func', lambda: (lambda o: -o)(S120()))
class B121:
    __neg__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __neg__ lambda', lambda: (lambda o: -o)(B121()))
class S121:
    pass
S121.__neg__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __neg__ lambda', lambda: (lambda o: -o)(S121()))
class H122:
    def f(*a):
        return enc('v', len(a))
class B122:
    __neg__ = H122.f
run('body    __neg__ plainfn', lambda: (lambda o: -o)(B122()))
class S122:
    pass
S122.__neg__ = H122.f
run('setattr __neg__ plainfn', lambda: (lambda o: -o)(S122()))
class B123:
    __neg__ = classmethod(mkfunc('v'))
run('body    __neg__ classm', lambda: (lambda o: -o)(B123()))
class S123:
    pass
S123.__neg__ = classmethod(mkfunc('v'))
run('setattr __neg__ classm', lambda: (lambda o: -o)(S123()))
class B124:
    __neg__ = staticmethod(mkfunc('v'))
run('body    __neg__ static', lambda: (lambda o: -o)(B124()))
class S124:
    pass
S124.__neg__ = staticmethod(mkfunc('v'))
run('setattr __neg__ static', lambda: (lambda o: -o)(S124()))
class B125:
    __neg__ = Ret('v').m
run('body    __neg__ bound', lambda: (lambda o: -o)(B125()))
class S125:
    pass
S125.__neg__ = Ret('v').m
run('setattr __neg__ bound', lambda: (lambda o: -o)(S125()))
class B126:
    __neg__ = CallObj('v')
run('body    __neg__ callobj', lambda: (lambda o: -o)(B126()))
class S126:
    pass
S126.__neg__ = CallObj('v')
run('setattr __neg__ callobj', lambda: (lambda o: -o)(S126()))
class B127:
    __abs__ = mkfunc('v')
run('body    __abs__ func', lambda: (lambda o: abs(o))(B127()))
class S127:
    pass
S127.__abs__ = mkfunc('v')
run('setattr __abs__ func', lambda: (lambda o: abs(o))(S127()))
class B128:
    __abs__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __abs__ lambda', lambda: (lambda o: abs(o))(B128()))
class S128:
    pass
S128.__abs__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __abs__ lambda', lambda: (lambda o: abs(o))(S128()))
class H129:
    def f(*a):
        return enc('v', len(a))
class B129:
    __abs__ = H129.f
run('body    __abs__ plainfn', lambda: (lambda o: abs(o))(B129()))
class S129:
    pass
S129.__abs__ = H129.f
run('setattr __abs__ plainfn', lambda: (lambda o: abs(o))(S129()))
class B130:
    __abs__ = classmethod(mkfunc('v'))
run('body    __abs__ classm', lambda: (lambda o: abs(o))(B130()))
class S130:
    pass
S130.__abs__ = classmethod(mkfunc('v'))
run('setattr __abs__ classm', lambda: (lambda o: abs(o))(S130()))
class B131:
    __abs__ = staticmethod(mkfunc('v'))
run('body    __abs__ static', lambda: (lambda o: abs(o))(B131()))
class S131:
    pass
S131.__abs__ = staticmethod(mkfunc('v'))
run('setattr __abs__ static', lambda: (lambda o: abs(o))(S131()))
class B132:
    __abs__ = Ret('v').m
run('body    __abs__ bound', lambda: (lambda o: abs(o))(B132()))
class S132:
    pass
S132.__abs__ = Ret('v').m
run('setattr __abs__ bound', lambda: (lambda o: abs(o))(S132()))
class B133:
    __abs__ = CallObj('v')
run('body    __abs__ callobj', lambda: (lambda o: abs(o))(B133()))
class S133:
    pass
S133.__abs__ = CallObj('v')
run('setattr __abs__ callobj', lambda: (lambda o: abs(o))(S133()))
class B134:
    __invert__ = mkfunc('v')
run('body    __invert__ func', lambda: (lambda o: ~o)(B134()))
class S134:
    pass
S134.__invert__ = mkfunc('v')
run('setattr __invert__ func', lambda: (lambda o: ~o)(S134()))
class B135:
    __invert__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __invert__ lambda', lambda: (lambda o: ~o)(B135()))
class S135:
    pass
S135.__invert__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __invert__ lambda', lambda: (lambda o: ~o)(S135()))
class H136:
    def f(*a):
        return enc('v', len(a))
class B136:
    __invert__ = H136.f
run('body    __invert__ plainfn', lambda: (lambda o: ~o)(B136()))
class S136:
    pass
S136.__invert__ = H136.f
run('setattr __invert__ plainfn', lambda: (lambda o: ~o)(S136()))
class B137:
    __invert__ = classmethod(mkfunc('v'))
run('body    __invert__ classm', lambda: (lambda o: ~o)(B137()))
class S137:
    pass
S137.__invert__ = classmethod(mkfunc('v'))
run('setattr __invert__ classm', lambda: (lambda o: ~o)(S137()))
class B138:
    __invert__ = staticmethod(mkfunc('v'))
run('body    __invert__ static', lambda: (lambda o: ~o)(B138()))
class S138:
    pass
S138.__invert__ = staticmethod(mkfunc('v'))
run('setattr __invert__ static', lambda: (lambda o: ~o)(S138()))
class B139:
    __invert__ = Ret('v').m
run('body    __invert__ bound', lambda: (lambda o: ~o)(B139()))
class S139:
    pass
S139.__invert__ = Ret('v').m
run('setattr __invert__ bound', lambda: (lambda o: ~o)(S139()))
class B140:
    __invert__ = CallObj('v')
run('body    __invert__ callobj', lambda: (lambda o: ~o)(B140()))
class S140:
    pass
S140.__invert__ = CallObj('v')
run('setattr __invert__ callobj', lambda: (lambda o: ~o)(S140()))
class B141:
    __mul__ = mkfunc('v')
run('body    __mul__ func', lambda: (lambda o: o * 2)(B141()))
class S141:
    pass
S141.__mul__ = mkfunc('v')
run('setattr __mul__ func', lambda: (lambda o: o * 2)(S141()))
class B142:
    __mul__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __mul__ lambda', lambda: (lambda o: o * 2)(B142()))
class S142:
    pass
S142.__mul__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __mul__ lambda', lambda: (lambda o: o * 2)(S142()))
class H143:
    def f(*a):
        return enc('v', len(a))
class B143:
    __mul__ = H143.f
run('body    __mul__ plainfn', lambda: (lambda o: o * 2)(B143()))
class S143:
    pass
S143.__mul__ = H143.f
run('setattr __mul__ plainfn', lambda: (lambda o: o * 2)(S143()))
class B144:
    __mul__ = classmethod(mkfunc('v'))
run('body    __mul__ classm', lambda: (lambda o: o * 2)(B144()))
class S144:
    pass
S144.__mul__ = classmethod(mkfunc('v'))
run('setattr __mul__ classm', lambda: (lambda o: o * 2)(S144()))
class B145:
    __mul__ = staticmethod(mkfunc('v'))
run('body    __mul__ static', lambda: (lambda o: o * 2)(B145()))
class S145:
    pass
S145.__mul__ = staticmethod(mkfunc('v'))
run('setattr __mul__ static', lambda: (lambda o: o * 2)(S145()))
class B146:
    __mul__ = Ret('v').m
run('body    __mul__ bound', lambda: (lambda o: o * 2)(B146()))
class S146:
    pass
S146.__mul__ = Ret('v').m
run('setattr __mul__ bound', lambda: (lambda o: o * 2)(S146()))
class B147:
    __mul__ = CallObj('v')
run('body    __mul__ callobj', lambda: (lambda o: o * 2)(B147()))
class S147:
    pass
S147.__mul__ = CallObj('v')
run('setattr __mul__ callobj', lambda: (lambda o: o * 2)(S147()))
class B148:
    __rmul__ = mkfunc('v')
run('body    __rmul__ func', lambda: (lambda o: 2 * o)(B148()))
class S148:
    pass
S148.__rmul__ = mkfunc('v')
run('setattr __rmul__ func', lambda: (lambda o: 2 * o)(S148()))
class B149:
    __rmul__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __rmul__ lambda', lambda: (lambda o: 2 * o)(B149()))
class S149:
    pass
S149.__rmul__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __rmul__ lambda', lambda: (lambda o: 2 * o)(S149()))
class H150:
    def f(*a):
        return enc('v', len(a))
class B150:
    __rmul__ = H150.f
run('body    __rmul__ plainfn', lambda: (lambda o: 2 * o)(B150()))
class S150:
    pass
S150.__rmul__ = H150.f
run('setattr __rmul__ plainfn', lambda: (lambda o: 2 * o)(S150()))
class B151:
    __rmul__ = classmethod(mkfunc('v'))
run('body    __rmul__ classm', lambda: (lambda o: 2 * o)(B151()))
class S151:
    pass
S151.__rmul__ = classmethod(mkfunc('v'))
run('setattr __rmul__ classm', lambda: (lambda o: 2 * o)(S151()))
class B152:
    __rmul__ = staticmethod(mkfunc('v'))
run('body    __rmul__ static', lambda: (lambda o: 2 * o)(B152()))
class S152:
    pass
S152.__rmul__ = staticmethod(mkfunc('v'))
run('setattr __rmul__ static', lambda: (lambda o: 2 * o)(S152()))
class B153:
    __rmul__ = Ret('v').m
run('body    __rmul__ bound', lambda: (lambda o: 2 * o)(B153()))
class S153:
    pass
S153.__rmul__ = Ret('v').m
run('setattr __rmul__ bound', lambda: (lambda o: 2 * o)(S153()))
class B154:
    __rmul__ = CallObj('v')
run('body    __rmul__ callobj', lambda: (lambda o: 2 * o)(B154()))
class S154:
    pass
S154.__rmul__ = CallObj('v')
run('setattr __rmul__ callobj', lambda: (lambda o: 2 * o)(S154()))
class B155:
    __index__ = mkfunc(1)
run('body    __index__ func', lambda: (lambda o: [10, 20][o])(B155()))
class S155:
    pass
S155.__index__ = mkfunc(1)
run('setattr __index__ func', lambda: (lambda o: [10, 20][o])(S155()))
class B156:
    __index__ = (lambda r: lambda *a: enc(r, len(a)))(1)
run('body    __index__ lambda', lambda: (lambda o: [10, 20][o])(B156()))
class S156:
    pass
S156.__index__ = (lambda r: lambda *a: enc(r, len(a)))(1)
run('setattr __index__ lambda', lambda: (lambda o: [10, 20][o])(S156()))
class H157:
    def f(*a):
        return enc(1, len(a))
class B157:
    __index__ = H157.f
run('body    __index__ plainfn', lambda: (lambda o: [10, 20][o])(B157()))
class S157:
    pass
S157.__index__ = H157.f
run('setattr __index__ plainfn', lambda: (lambda o: [10, 20][o])(S157()))
class B158:
    __index__ = classmethod(mkfunc(1))
run('body    __index__ classm', lambda: (lambda o: [10, 20][o])(B158()))
class S158:
    pass
S158.__index__ = classmethod(mkfunc(1))
run('setattr __index__ classm', lambda: (lambda o: [10, 20][o])(S158()))
class B159:
    __index__ = staticmethod(mkfunc(1))
run('body    __index__ static', lambda: (lambda o: [10, 20][o])(B159()))
class S159:
    pass
S159.__index__ = staticmethod(mkfunc(1))
run('setattr __index__ static', lambda: (lambda o: [10, 20][o])(S159()))
class B160:
    __index__ = Ret(1).m
run('body    __index__ bound', lambda: (lambda o: [10, 20][o])(B160()))
class S160:
    pass
S160.__index__ = Ret(1).m
run('setattr __index__ bound', lambda: (lambda o: [10, 20][o])(S160()))
class B161:
    __index__ = CallObj(1)
run('body    __index__ callobj', lambda: (lambda o: [10, 20][o])(B161()))
class S161:
    pass
S161.__index__ = CallObj(1)
run('setattr __index__ callobj', lambda: (lambda o: [10, 20][o])(S161()))
class B162:
    __int__ = mkfunc(5)
run('body    __int__ func', lambda: (lambda o: int(o))(B162()))
class S162:
    pass
S162.__int__ = mkfunc(5)
run('setattr __int__ func', lambda: (lambda o: int(o))(S162()))
class B163:
    __int__ = (lambda r: lambda *a: enc(r, len(a)))(5)
run('body    __int__ lambda', lambda: (lambda o: int(o))(B163()))
class S163:
    pass
S163.__int__ = (lambda r: lambda *a: enc(r, len(a)))(5)
run('setattr __int__ lambda', lambda: (lambda o: int(o))(S163()))
class H164:
    def f(*a):
        return enc(5, len(a))
class B164:
    __int__ = H164.f
run('body    __int__ plainfn', lambda: (lambda o: int(o))(B164()))
class S164:
    pass
S164.__int__ = H164.f
run('setattr __int__ plainfn', lambda: (lambda o: int(o))(S164()))
class B165:
    __int__ = classmethod(mkfunc(5))
run('body    __int__ classm', lambda: (lambda o: int(o))(B165()))
class S165:
    pass
S165.__int__ = classmethod(mkfunc(5))
run('setattr __int__ classm', lambda: (lambda o: int(o))(S165()))
class B166:
    __int__ = staticmethod(mkfunc(5))
run('body    __int__ static', lambda: (lambda o: int(o))(B166()))
class S166:
    pass
S166.__int__ = staticmethod(mkfunc(5))
run('setattr __int__ static', lambda: (lambda o: int(o))(S166()))
class B167:
    __int__ = Ret(5).m
run('body    __int__ bound', lambda: (lambda o: int(o))(B167()))
class S167:
    pass
S167.__int__ = Ret(5).m
run('setattr __int__ bound', lambda: (lambda o: int(o))(S167()))
class B168:
    __int__ = CallObj(5)
run('body    __int__ callobj', lambda: (lambda o: int(o))(B168()))
class S168:
    pass
S168.__int__ = CallObj(5)
run('setattr __int__ callobj', lambda: (lambda o: int(o))(S168()))
class B169:
    __float__ = mkfunc(2.5)
run('body    __float__ func', lambda: (lambda o: float(o))(B169()))
class S169:
    pass
S169.__float__ = mkfunc(2.5)
run('setattr __float__ func', lambda: (lambda o: float(o))(S169()))
class B170:
    __float__ = (lambda r: lambda *a: enc(r, len(a)))(2.5)
run('body    __float__ lambda', lambda: (lambda o: float(o))(B170()))
class S170:
    pass
S170.__float__ = (lambda r: lambda *a: enc(r, len(a)))(2.5)
run('setattr __float__ lambda', lambda: (lambda o: float(o))(S170()))
class H171:
    def f(*a):
        return enc(2.5, len(a))
class B171:
    __float__ = H171.f
run('body    __float__ plainfn', lambda: (lambda o: float(o))(B171()))
class S171:
    pass
S171.__float__ = H171.f
run('setattr __float__ plainfn', lambda: (lambda o: float(o))(S171()))
class B172:
    __float__ = classmethod(mkfunc(2.5))
run('body    __float__ classm', lambda: (lambda o: float(o))(B172()))
class S172:
    pass
S172.__float__ = classmethod(mkfunc(2.5))
run('setattr __float__ classm', lambda: (lambda o: float(o))(S172()))
class B173:
    __float__ = staticmethod(mkfunc(2.5))
run('body    __float__ static', lambda: (lambda o: float(o))(B173()))
class S173:
    pass
S173.__float__ = staticmethod(mkfunc(2.5))
run('setattr __float__ static', lambda: (lambda o: float(o))(S173()))
class B174:
    __float__ = Ret(2.5).m
run('body    __float__ bound', lambda: (lambda o: float(o))(B174()))
class S174:
    pass
S174.__float__ = Ret(2.5).m
run('setattr __float__ bound', lambda: (lambda o: float(o))(S174()))
class B175:
    __float__ = CallObj(2.5)
run('body    __float__ callobj', lambda: (lambda o: float(o))(B175()))
class S175:
    pass
S175.__float__ = CallObj(2.5)
run('setattr __float__ callobj', lambda: (lambda o: float(o))(S175()))
class B176:
    __enter__ = mkfunc('v')
    __exit__ = lambda *a: False
run('body    __enter__ func', lambda: (lambda o: _with(o))(B176()))
class S176:
    __exit__ = lambda *a: False
S176.__enter__ = mkfunc('v')
run('setattr __enter__ func', lambda: (lambda o: _with(o))(S176()))
class B177:
    __enter__ = (lambda r: lambda *a: enc(r, len(a)))('v')
    __exit__ = lambda *a: False
run('body    __enter__ lambda', lambda: (lambda o: _with(o))(B177()))
class S177:
    __exit__ = lambda *a: False
S177.__enter__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __enter__ lambda', lambda: (lambda o: _with(o))(S177()))
class H178:
    def f(*a):
        return enc('v', len(a))
class B178:
    __enter__ = H178.f
    __exit__ = lambda *a: False
run('body    __enter__ plainfn', lambda: (lambda o: _with(o))(B178()))
class S178:
    __exit__ = lambda *a: False
S178.__enter__ = H178.f
run('setattr __enter__ plainfn', lambda: (lambda o: _with(o))(S178()))
class B179:
    __enter__ = classmethod(mkfunc('v'))
    __exit__ = lambda *a: False
run('body    __enter__ classm', lambda: (lambda o: _with(o))(B179()))
class S179:
    __exit__ = lambda *a: False
S179.__enter__ = classmethod(mkfunc('v'))
run('setattr __enter__ classm', lambda: (lambda o: _with(o))(S179()))
class B180:
    __enter__ = staticmethod(mkfunc('v'))
    __exit__ = lambda *a: False
run('body    __enter__ static', lambda: (lambda o: _with(o))(B180()))
class S180:
    __exit__ = lambda *a: False
S180.__enter__ = staticmethod(mkfunc('v'))
run('setattr __enter__ static', lambda: (lambda o: _with(o))(S180()))
class B181:
    __enter__ = Ret('v').m
    __exit__ = lambda *a: False
run('body    __enter__ bound', lambda: (lambda o: _with(o))(B181()))
class S181:
    __exit__ = lambda *a: False
S181.__enter__ = Ret('v').m
run('setattr __enter__ bound', lambda: (lambda o: _with(o))(S181()))
class B182:
    __enter__ = CallObj('v')
    __exit__ = lambda *a: False
run('body    __enter__ callobj', lambda: (lambda o: _with(o))(B182()))
class S182:
    __exit__ = lambda *a: False
S182.__enter__ = CallObj('v')
run('setattr __enter__ callobj', lambda: (lambda o: _with(o))(S182()))
class B183:
    __getattr__ = mkfunc('v')
run('body    __getattr__ func', lambda: (lambda o: o.zz_missing)(B183()))
class S183:
    pass
S183.__getattr__ = mkfunc('v')
run('setattr __getattr__ func', lambda: (lambda o: o.zz_missing)(S183()))
class B184:
    __getattr__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('body    __getattr__ lambda', lambda: (lambda o: o.zz_missing)(B184()))
class S184:
    pass
S184.__getattr__ = (lambda r: lambda *a: enc(r, len(a)))('v')
run('setattr __getattr__ lambda', lambda: (lambda o: o.zz_missing)(S184()))
class H185:
    def f(*a):
        return enc('v', len(a))
class B185:
    __getattr__ = H185.f
run('body    __getattr__ plainfn', lambda: (lambda o: o.zz_missing)(B185()))
class S185:
    pass
S185.__getattr__ = H185.f
run('setattr __getattr__ plainfn', lambda: (lambda o: o.zz_missing)(S185()))
class B186:
    __getattr__ = classmethod(mkfunc('v'))
run('body    __getattr__ classm', lambda: (lambda o: o.zz_missing)(B186()))
class S186:
    pass
S186.__getattr__ = classmethod(mkfunc('v'))
run('setattr __getattr__ classm', lambda: (lambda o: o.zz_missing)(S186()))
class B187:
    __getattr__ = staticmethod(mkfunc('v'))
run('body    __getattr__ static', lambda: (lambda o: o.zz_missing)(B187()))
class S187:
    pass
S187.__getattr__ = staticmethod(mkfunc('v'))
run('setattr __getattr__ static', lambda: (lambda o: o.zz_missing)(S187()))
class B188:
    __getattr__ = Ret('v').m
run('body    __getattr__ bound', lambda: (lambda o: o.zz_missing)(B188()))
class S188:
    pass
S188.__getattr__ = Ret('v').m
run('setattr __getattr__ bound', lambda: (lambda o: o.zz_missing)(S188()))
class B189:
    __getattr__ = CallObj('v')
run('body    __getattr__ callobj', lambda: (lambda o: o.zz_missing)(B189()))
class S189:
    pass
S189.__getattr__ = CallObj('v')
run('setattr __getattr__ callobj', lambda: (lambda o: o.zz_missing)(S189()))


# The issue's own end-to-end case: CPython 3.14's iterparse builds its iterator
# class with ``__next__ = gen.__next__''.
def _iterparse():
    import xml.etree.ElementTree as ET
    return [(ev, el.tag) for ev, el in ET.iterparse(io.BytesIO(b"<a><b/></a>"))]


run('issue   ET.iterparse', _iterparse)


# object's OWN method stored under its own name is the default, not an
# override -- the protocol must not call it as one (it would call itself).
class ObjStrBody:
    __str__ = object.__str__
    __format__ = object.__format__
    def __repr__(self):
        return 'objdefault'
class ObjStrSet:
    def __repr__(self):
        return 'objdefault'
ObjStrSet.__str__ = object.__str__
ObjStrSet.__format__ = object.__format__
run('body    str object.default', lambda: str(ObjStrBody()))
run('body    format object.default', lambda: format(ObjStrBody()))
run('setattr str object.default', lambda: str(ObjStrSet()))
run('setattr format object.default', lambda: format(ObjStrSet()))


EXPECTED = {
    'body    __add__ func': "('v', 2)",
    'setattr __add__ func': "('v', 2)",
    'body    __add__ lambda': "('v', 2)",
    'setattr __add__ lambda': "('v', 2)",
    'body    __add__ plainfn': "('v', 2)",
    'setattr __add__ plainfn': "('v', 2)",
    'body    __add__ classm': "('v', 2)",
    'setattr __add__ classm': "('v', 2)",
    'body    __add__ static': "('v', 1)",
    'setattr __add__ static': "('v', 1)",
    'body    __add__ bound': "('v', 1)",
    'setattr __add__ bound': "('v', 1)",
    'body    __add__ callobj': "('v', 1)",
    'setattr __add__ callobj': "('v', 1)",
    'body    __radd__ func': "('v', 2)",
    'setattr __radd__ func': "('v', 2)",
    'body    __radd__ lambda': "('v', 2)",
    'setattr __radd__ lambda': "('v', 2)",
    'body    __radd__ plainfn': "('v', 2)",
    'setattr __radd__ plainfn': "('v', 2)",
    'body    __radd__ classm': "('v', 2)",
    'setattr __radd__ classm': "('v', 2)",
    'body    __radd__ static': "('v', 1)",
    'setattr __radd__ static': "('v', 1)",
    'body    __radd__ bound': "('v', 1)",
    'setattr __radd__ bound': "('v', 1)",
    'body    __radd__ callobj': "('v', 1)",
    'setattr __radd__ callobj': "('v', 1)",
    'body    __lt__ func': "('v', 2)",
    'setattr __lt__ func': "('v', 2)",
    'body    __lt__ lambda': "('v', 2)",
    'setattr __lt__ lambda': "('v', 2)",
    'body    __lt__ plainfn': "('v', 2)",
    'setattr __lt__ plainfn': "('v', 2)",
    'body    __lt__ classm': "('v', 2)",
    'setattr __lt__ classm': "('v', 2)",
    'body    __lt__ static': "('v', 1)",
    'setattr __lt__ static': "('v', 1)",
    'body    __lt__ bound': "('v', 1)",
    'setattr __lt__ bound': "('v', 1)",
    'body    __lt__ callobj': "('v', 1)",
    'setattr __lt__ callobj': "('v', 1)",
    'body    __eq__ func': "('v', 2)",
    'setattr __eq__ func': "('v', 2)",
    'body    __eq__ lambda': "('v', 2)",
    'setattr __eq__ lambda': "('v', 2)",
    'body    __eq__ plainfn': "('v', 2)",
    'setattr __eq__ plainfn': "('v', 2)",
    'body    __eq__ classm': "('v', 2)",
    'setattr __eq__ classm': "('v', 2)",
    'body    __eq__ static': "('v', 1)",
    'setattr __eq__ static': "('v', 1)",
    'body    __eq__ bound': "('v', 1)",
    'setattr __eq__ bound': "('v', 1)",
    'body    __eq__ callobj': "('v', 1)",
    'setattr __eq__ callobj': "('v', 1)",
    'body    __call__ func': "('v', 1)",
    'setattr __call__ func': "('v', 1)",
    'body    __call__ lambda': "('v', 1)",
    'setattr __call__ lambda': "('v', 1)",
    'body    __call__ plainfn': "('v', 1)",
    'setattr __call__ plainfn': "('v', 1)",
    'body    __call__ classm': "('v', 1)",
    'setattr __call__ classm': "('v', 1)",
    'body    __call__ static': "('v', 0)",
    'setattr __call__ static': "('v', 0)",
    'body    __call__ bound': "('v', 0)",
    'setattr __call__ bound': "('v', 0)",
    'body    __call__ callobj': "('v', 0)",
    'setattr __call__ callobj': "('v', 0)",
    'body    __getitem__ func': "('v', 2)",
    'setattr __getitem__ func': "('v', 2)",
    'body    __getitem__ lambda': "('v', 2)",
    'setattr __getitem__ lambda': "('v', 2)",
    'body    __getitem__ plainfn': "('v', 2)",
    'setattr __getitem__ plainfn': "('v', 2)",
    'body    __getitem__ classm': "('v', 2)",
    'setattr __getitem__ classm': "('v', 2)",
    'body    __getitem__ static': "('v', 1)",
    'setattr __getitem__ static': "('v', 1)",
    'body    __getitem__ bound': "('v', 1)",
    'setattr __getitem__ bound': "('v', 1)",
    'body    __getitem__ callobj': "('v', 1)",
    'setattr __getitem__ callobj': "('v', 1)",
    'body    __setitem__ func': "'set'",
    'setattr __setitem__ func': "'set'",
    'body    __setitem__ lambda': "'set'",
    'setattr __setitem__ lambda': "'set'",
    'body    __setitem__ plainfn': "'set'",
    'setattr __setitem__ plainfn': "'set'",
    'body    __setitem__ classm': "'set'",
    'setattr __setitem__ classm': "'set'",
    'body    __setitem__ static': "'set'",
    'setattr __setitem__ static': "'set'",
    'body    __setitem__ bound': "'set'",
    'setattr __setitem__ bound': "'set'",
    'body    __setitem__ callobj': "'set'",
    'setattr __setitem__ callobj': "'set'",
    'body    __contains__ func': 'False',
    'setattr __contains__ func': 'False',
    'body    __contains__ lambda': 'False',
    'setattr __contains__ lambda': 'False',
    'body    __contains__ plainfn': 'False',
    'setattr __contains__ plainfn': 'False',
    'body    __contains__ classm': 'False',
    'setattr __contains__ classm': 'False',
    'body    __contains__ static': 'False',
    'setattr __contains__ static': 'False',
    'body    __contains__ bound': 'False',
    'setattr __contains__ bound': 'False',
    'body    __contains__ callobj': 'False',
    'setattr __contains__ callobj': 'False',
    'body    __len__ func': '103',
    'setattr __len__ func': '103',
    'body    __len__ lambda': '103',
    'setattr __len__ lambda': '103',
    'body    __len__ plainfn': '103',
    'setattr __len__ plainfn': '103',
    'body    __len__ classm': '103',
    'setattr __len__ classm': '103',
    'body    __len__ static': '3',
    'setattr __len__ static': '3',
    'body    __len__ bound': '3',
    'setattr __len__ bound': '3',
    'body    __len__ callobj': '3',
    'setattr __len__ callobj': '3',
    'body    __bool__ func': 'False',
    'setattr __bool__ func': 'False',
    'body    __bool__ lambda': 'False',
    'setattr __bool__ lambda': 'False',
    'body    __bool__ plainfn': 'False',
    'setattr __bool__ plainfn': 'False',
    'body    __bool__ classm': 'False',
    'setattr __bool__ classm': 'False',
    'body    __bool__ static': 'True',
    'setattr __bool__ static': 'True',
    'body    __bool__ bound': 'True',
    'setattr __bool__ bound': 'True',
    'body    __bool__ callobj': 'True',
    'setattr __bool__ callobj': 'True',
    'body    __iter__ func': "'list_iterator'",
    'setattr __iter__ func': "'list_iterator'",
    'body    __iter__ lambda': "'list_iterator'",
    'setattr __iter__ lambda': "'list_iterator'",
    'body    __iter__ plainfn': "'list_iterator'",
    'setattr __iter__ plainfn': "'list_iterator'",
    'body    __iter__ classm': "'list_iterator'",
    'setattr __iter__ classm': "'list_iterator'",
    'body    __iter__ static': "'list_iterator'",
    'setattr __iter__ static': "'list_iterator'",
    'body    __iter__ bound': "'list_iterator'",
    'setattr __iter__ bound': "'list_iterator'",
    'body    __iter__ callobj': "'list_iterator'",
    'setattr __iter__ callobj': "'list_iterator'",
    'body    __next__ func': "('v', 1)",
    'setattr __next__ func': "('v', 1)",
    'body    __next__ lambda': "('v', 1)",
    'setattr __next__ lambda': "('v', 1)",
    'body    __next__ plainfn': "('v', 1)",
    'setattr __next__ plainfn': "('v', 1)",
    'body    __next__ classm': "('v', 1)",
    'setattr __next__ classm': "('v', 1)",
    'body    __next__ static': "('v', 0)",
    'setattr __next__ static': "('v', 0)",
    'body    __next__ bound': "('v', 0)",
    'setattr __next__ bound': "('v', 0)",
    'body    __next__ callobj': "('v', 0)",
    'setattr __next__ callobj': "('v', 0)",
    'body    __reversed__ func': "'list_iterator'",
    'setattr __reversed__ func': "'list_iterator'",
    'body    __reversed__ lambda': "'list_iterator'",
    'setattr __reversed__ lambda': "'list_iterator'",
    'body    __reversed__ plainfn': "'list_iterator'",
    'setattr __reversed__ plainfn': "'list_iterator'",
    'body    __reversed__ classm': "'list_iterator'",
    'setattr __reversed__ classm': "'list_iterator'",
    'body    __reversed__ static': "'list_iterator'",
    'setattr __reversed__ static': "'list_iterator'",
    'body    __reversed__ bound': "'list_iterator'",
    'setattr __reversed__ bound': "'list_iterator'",
    'body    __reversed__ callobj': "'list_iterator'",
    'setattr __reversed__ callobj': "'list_iterator'",
    'body    __repr__ func': "'r1'",
    'setattr __repr__ func': "'r1'",
    'body    __repr__ lambda': "'r1'",
    'setattr __repr__ lambda': "'r1'",
    'body    __repr__ plainfn': "'r1'",
    'setattr __repr__ plainfn': "'r1'",
    'body    __repr__ classm': "'r1'",
    'setattr __repr__ classm': "'r1'",
    'body    __repr__ static': "'r0'",
    'setattr __repr__ static': "'r0'",
    'body    __repr__ bound': "'r0'",
    'setattr __repr__ bound': "'r0'",
    'body    __repr__ callobj': "'r0'",
    'setattr __repr__ callobj': "'r0'",
    'body    __str__ func': "'s1'",
    'setattr __str__ func': "'s1'",
    'body    __str__ lambda': "'s1'",
    'setattr __str__ lambda': "'s1'",
    'body    __str__ plainfn': "'s1'",
    'setattr __str__ plainfn': "'s1'",
    'body    __str__ classm': "'s1'",
    'setattr __str__ classm': "'s1'",
    'body    __str__ static': "'s0'",
    'setattr __str__ static': "'s0'",
    'body    __str__ bound': "'s0'",
    'setattr __str__ bound': "'s0'",
    'body    __str__ callobj': "'s0'",
    'setattr __str__ callobj': "'s0'",
    'body    __format__ func': "'f2'",
    'setattr __format__ func': "'f2'",
    'body    __format__ lambda': "'f2'",
    'setattr __format__ lambda': "'f2'",
    'body    __format__ plainfn': "'f2'",
    'setattr __format__ plainfn': "'f2'",
    'body    __format__ classm': "'f2'",
    'setattr __format__ classm': "'f2'",
    'body    __format__ static': "'f1'",
    'setattr __format__ static': "'f1'",
    'body    __format__ bound': "'f1'",
    'setattr __format__ bound': "'f1'",
    'body    __format__ callobj': "'f1'",
    'setattr __format__ callobj': "'f1'",
    'body    __hash__ func': '107',
    'setattr __hash__ func': '107',
    'body    __hash__ lambda': '107',
    'setattr __hash__ lambda': '107',
    'body    __hash__ plainfn': '107',
    'setattr __hash__ plainfn': '107',
    'body    __hash__ classm': '107',
    'setattr __hash__ classm': '107',
    'body    __hash__ static': '7',
    'setattr __hash__ static': '7',
    'body    __hash__ bound': '7',
    'setattr __hash__ bound': '7',
    'body    __hash__ callobj': '7',
    'setattr __hash__ callobj': '7',
    'body    __neg__ func': "('v', 1)",
    'setattr __neg__ func': "('v', 1)",
    'body    __neg__ lambda': "('v', 1)",
    'setattr __neg__ lambda': "('v', 1)",
    'body    __neg__ plainfn': "('v', 1)",
    'setattr __neg__ plainfn': "('v', 1)",
    'body    __neg__ classm': "('v', 1)",
    'setattr __neg__ classm': "('v', 1)",
    'body    __neg__ static': "('v', 0)",
    'setattr __neg__ static': "('v', 0)",
    'body    __neg__ bound': "('v', 0)",
    'setattr __neg__ bound': "('v', 0)",
    'body    __neg__ callobj': "('v', 0)",
    'setattr __neg__ callobj': "('v', 0)",
    'body    __abs__ func': "('v', 1)",
    'setattr __abs__ func': "('v', 1)",
    'body    __abs__ lambda': "('v', 1)",
    'setattr __abs__ lambda': "('v', 1)",
    'body    __abs__ plainfn': "('v', 1)",
    'setattr __abs__ plainfn': "('v', 1)",
    'body    __abs__ classm': "('v', 1)",
    'setattr __abs__ classm': "('v', 1)",
    'body    __abs__ static': "('v', 0)",
    'setattr __abs__ static': "('v', 0)",
    'body    __abs__ bound': "('v', 0)",
    'setattr __abs__ bound': "('v', 0)",
    'body    __abs__ callobj': "('v', 0)",
    'setattr __abs__ callobj': "('v', 0)",
    'body    __invert__ func': "('v', 1)",
    'setattr __invert__ func': "('v', 1)",
    'body    __invert__ lambda': "('v', 1)",
    'setattr __invert__ lambda': "('v', 1)",
    'body    __invert__ plainfn': "('v', 1)",
    'setattr __invert__ plainfn': "('v', 1)",
    'body    __invert__ classm': "('v', 1)",
    'setattr __invert__ classm': "('v', 1)",
    'body    __invert__ static': "('v', 0)",
    'setattr __invert__ static': "('v', 0)",
    'body    __invert__ bound': "('v', 0)",
    'setattr __invert__ bound': "('v', 0)",
    'body    __invert__ callobj': "('v', 0)",
    'setattr __invert__ callobj': "('v', 0)",
    'body    __mul__ func': "('v', 2)",
    'setattr __mul__ func': "('v', 2)",
    'body    __mul__ lambda': "('v', 2)",
    'setattr __mul__ lambda': "('v', 2)",
    'body    __mul__ plainfn': "('v', 2)",
    'setattr __mul__ plainfn': "('v', 2)",
    'body    __mul__ classm': "('v', 2)",
    'setattr __mul__ classm': "('v', 2)",
    'body    __mul__ static': "('v', 1)",
    'setattr __mul__ static': "('v', 1)",
    'body    __mul__ bound': "('v', 1)",
    'setattr __mul__ bound': "('v', 1)",
    'body    __mul__ callobj': "('v', 1)",
    'setattr __mul__ callobj': "('v', 1)",
    'body    __rmul__ func': "('v', 2)",
    'setattr __rmul__ func': "('v', 2)",
    'body    __rmul__ lambda': "('v', 2)",
    'setattr __rmul__ lambda': "('v', 2)",
    'body    __rmul__ plainfn': "('v', 2)",
    'setattr __rmul__ plainfn': "('v', 2)",
    'body    __rmul__ classm': "('v', 2)",
    'setattr __rmul__ classm': "('v', 2)",
    'body    __rmul__ static': "('v', 1)",
    'setattr __rmul__ static': "('v', 1)",
    'body    __rmul__ bound': "('v', 1)",
    'setattr __rmul__ bound': "('v', 1)",
    'body    __rmul__ callobj': "('v', 1)",
    'setattr __rmul__ callobj': "('v', 1)",
    'body    __index__ func': "'IndexError'",
    'setattr __index__ func': "'IndexError'",
    'body    __index__ lambda': "'IndexError'",
    'setattr __index__ lambda': "'IndexError'",
    'body    __index__ plainfn': "'IndexError'",
    'setattr __index__ plainfn': "'IndexError'",
    'body    __index__ classm': "'IndexError'",
    'setattr __index__ classm': "'IndexError'",
    'body    __index__ static': '20',
    'setattr __index__ static': '20',
    'body    __index__ bound': '20',
    'setattr __index__ bound': '20',
    'body    __index__ callobj': '20',
    'setattr __index__ callobj': '20',
    'body    __int__ func': '105',
    'setattr __int__ func': '105',
    'body    __int__ lambda': '105',
    'setattr __int__ lambda': '105',
    'body    __int__ plainfn': '105',
    'setattr __int__ plainfn': '105',
    'body    __int__ classm': '105',
    'setattr __int__ classm': '105',
    'body    __int__ static': '5',
    'setattr __int__ static': '5',
    'body    __int__ bound': '5',
    'setattr __int__ bound': '5',
    'body    __int__ callobj': '5',
    'setattr __int__ callobj': '5',
    'body    __float__ func': '102.5',
    'setattr __float__ func': '102.5',
    'body    __float__ lambda': '102.5',
    'setattr __float__ lambda': '102.5',
    'body    __float__ plainfn': '102.5',
    'setattr __float__ plainfn': '102.5',
    'body    __float__ classm': '102.5',
    'setattr __float__ classm': '102.5',
    'body    __float__ static': '2.5',
    'setattr __float__ static': '2.5',
    'body    __float__ bound': '2.5',
    'setattr __float__ bound': '2.5',
    'body    __float__ callobj': '2.5',
    'setattr __float__ callobj': '2.5',
    'body    __enter__ func': "('v', 1)",
    'setattr __enter__ func': "('v', 1)",
    'body    __enter__ lambda': "('v', 1)",
    'setattr __enter__ lambda': "('v', 1)",
    'body    __enter__ plainfn': "('v', 1)",
    'setattr __enter__ plainfn': "('v', 1)",
    'body    __enter__ classm': "('v', 1)",
    'setattr __enter__ classm': "('v', 1)",
    'body    __enter__ static': "('v', 0)",
    'setattr __enter__ static': "('v', 0)",
    'body    __enter__ bound': "('v', 0)",
    'setattr __enter__ bound': "('v', 0)",
    'body    __enter__ callobj': "('v', 0)",
    'setattr __enter__ callobj': "('v', 0)",
    'body    __getattr__ func': "('v', 2)",
    'setattr __getattr__ func': "('v', 2)",
    'body    __getattr__ lambda': "('v', 2)",
    'setattr __getattr__ lambda': "('v', 2)",
    'body    __getattr__ plainfn': "('v', 2)",
    'setattr __getattr__ plainfn': "('v', 2)",
    'body    __getattr__ classm': "('v', 2)",
    'setattr __getattr__ classm': "('v', 2)",
    'body    __getattr__ static': "('v', 1)",
    'setattr __getattr__ static': "('v', 1)",
    'body    __getattr__ bound': "('v', 1)",
    'setattr __getattr__ bound': "('v', 1)",
    'body    __getattr__ callobj': "('v', 1)",
    'setattr __getattr__ callobj': "('v', 1)",
    'issue   ET.iterparse': "[('end', 'b'), ('end', 'a')]",
    'body    str object.default': "'objdefault'",
    'body    format object.default': "'objdefault'",
    'setattr str object.default': "'objdefault'",
    'setattr format object.default': "'objdefault'",
}


def mismatches(kind):
    """The cases for one value kind (the label's last word) whose result
    differs from CPython's, as 'label: got X, CPython Y' -- what the Smalltalk
    test case asserts is empty."""
    return ['%s: got %s, CPython %s' % (k, RESULTS.get(k), v)
            for k, v in EXPECTED.items()
            if k.split()[-1] == kind and RESULTS.get(k) != v]


if __name__ == '__main__':
    for label, expected in EXPECTED.items():
        print('%-4s %s' % ('OK' if RESULTS.get(label) == expected else 'FAIL', label))
