# A CLOSURE CELL BELONGS TO AN ACTIVATION, NOT TO A ``def``.
#
# Two calls to one factory produce two functions over two DIFFERENT bindings.
# CPython gives each its own cell; Grail gave both the FIRST call's cells:
#
#     def mk(v):
#         def f(): return a
#         a = v
#         return f
#     f1, f2 = mk(10), mk(20)
#     f1(), f2()                              #  10, 20   -- always correct
#     f2.__closure__[0].cell_contents         #  10       -- was wrong
#     f1.__closure__[0] is f2.__closure__[0]  #  True     -- was wrong
#
# Only the REFLECTION was ever affected: calling the closures always gave
# CPython's answers, because the body reads the binding directly rather than
# going through the cell.  That is what made it the quiet kind of wrong -- a
# plausible number, from a different call, with nothing raised.
#
# The cause was storage, not construction.  The def-time stamp writes through a
# table keyed by def SITE that skips repeat writes, which is right for __name__
# and __code__ (identical for every evaluation of a def) and wrong for cells.
# The fix is to stop storing them: the enclosing activation's context is on the
# function object already, so the cells are built on demand from it.
#
# That also makes a closure cell WRITABLE, which it had never been.  Assigning
# ``cell_contents`` writes the binding the defining scope and every sibling
# closure read, and deleting it unbinds the variable so the next read raises --
# both of which CPython does and test_funcattrs checks.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def mk(v):
    def f():
        return a
    a = v
    return f


def two_freevars(p, q):
    def inner():
        return (p, q)
    return inner


def L1(x):
    def L2(y):
        def L3():
            return (x, y)
        return L3
    return L2


# --- one cell per activation ------------------------------------------------

def _each_call_reports_its_own_value():
    f1, f2 = mk(10), mk(20)
    return (f1.__closure__[0].cell_contents,
            f2.__closure__[0].cell_contents)


def _calling_them_always_agreed():
    # The half that was never broken, kept as the control: if a "fix" ever
    # makes these disagree with the cells above, it broke the closure itself.
    f1, f2 = mk(10), mk(20)
    return (f1(), f2())


def _two_activations_get_two_cells():
    f1, f2 = mk(10), mk(20)
    return f1.__closure__[0] is f2.__closure__[0]


def _the_same_function_gives_the_same_cell():
    # Repeated reads give the same CELL, so code may compare cells with ``is``
    # -- test_scope does.  Building them on demand would otherwise have broken
    # that, which is why they are memoised per function object once read.
    #
    # The enclosing TUPLE is not checked here: CPython stores it on the function
    # so ``f.__closure__ is f.__closure__`` is True, while Grail rebuilds it per
    # read in ExecBlock>>__closure__ -- a shared-base method on 3.7, so out of
    # reach.  Recorded in MethodClosureCellsTestCase rather than asserted here.
    f = mk(10)
    return f.__closure__[0] is f.__closure__[0]


def _no_free_variables_means_no_closure():
    def g():
        return 1
    return g.__closure__


# --- several free variables, and several levels -----------------------------

def _two_free_variables_keep_their_order():
    fn = two_freevars(8, 9)
    return (tuple(c.cell_contents for c in fn.__closure__), fn())


def _a_variable_two_levels_up():
    a = L1(1)(2)
    b = L1(30)(40)
    return (tuple(c.cell_contents for c in a.__closure__),
            tuple(c.cell_contents for c in b.__closure__),
            a(), b())


# --- the cell is live, in both directions -----------------------------------

def _a_later_assignment_shows_through():
    # Emptiness and value alike are questions about NOW: the cell tracks the
    # binding rather than snapshotting it.
    def outer():
        def f():
            return a
        c = f.__closure__[0]
        a = 1
        first = c.cell_contents
        a = 2
        return (first, c.cell_contents)
    return outer()


def _writing_the_cell_writes_the_binding():
    def outer():
        a = 12
        def f():
            return a
        c = f.__closure__[0]
        c.cell_contents = 9
        return (c.cell_contents, f(), a)
    return outer()


def _deleting_the_cell_unbinds_the_variable():
    def outer():
        a = 12
        def f():
            return a
        c = f.__closure__[0]
        del c.cell_contents
        out = []
        # ``c.cell_contents`` is a ValueError by name; reading the unbound
        # variable is checked as an INSTANCE of NameError, which is what
        # test_funcattrs asserts.  CPython names that one NameError and Grail
        # names it UnboundLocalError -- a SUBCLASS of NameError, so both satisfy
        # the rule, and pinning the name here would assert a difference this
        # fixture is not about.
        try:
            c.cell_contents
            out.append('accepted')
        except BaseException as e:
            out.append(type(e).__name__)
        try:
            f()
            out.append('accepted')
        except BaseException as e:
            out.append(isinstance(e, NameError))
        return tuple(out)
    return outer()


rec('each_call_reports_its_own_value', _each_call_reports_its_own_value)
rec('calling_them_always_agreed', _calling_them_always_agreed)
rec('two_activations_get_two_cells', _two_activations_get_two_cells)
rec('the_same_function_gives_the_same_cell', _the_same_function_gives_the_same_cell)
rec('no_free_variables_means_no_closure', _no_free_variables_means_no_closure)
rec('two_free_variables_keep_their_order', _two_free_variables_keep_their_order)
rec('a_variable_two_levels_up', _a_variable_two_levels_up)
rec('a_later_assignment_shows_through', _a_later_assignment_shows_through)
rec('writing_the_cell_writes_the_binding', _writing_the_cell_writes_the_binding)
rec('deleting_the_cell_unbinds_the_variable', _deleting_the_cell_unbinds_the_variable)


EXPECTED = {
    'a_later_assignment_shows_through': (1, 2),
    'a_variable_two_levels_up': ((1, 2), (30, 40), (1, 2), (30, 40)),
    'calling_them_always_agreed': (10, 20),
    'deleting_the_cell_unbinds_the_variable': ('ValueError', True),
    'each_call_reports_its_own_value': (10, 20),
    'no_free_variables_means_no_closure': None,
    'the_same_function_gives_the_same_cell': True,
    'two_activations_get_two_cells': False,
    'two_free_variables_keep_their_order': ((8, 9), (8, 9)),
    'writing_the_cell_writes_the_binding': (9, 9, 9),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-40s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
