# ``code.co_flags`` -- CPython's flag word, and the rule that turns on it.
#
# The three KIND bits are what conformance actually needs: they are how CPython
# tells a plain function, a generator, a coroutine and an async generator apart.
#
#      1  CO_OPTIMIZED         32  CO_GENERATOR
#      2  CO_NEWLOCALS        128  CO_COROUTINE
#      4  CO_VARARGS          512  CO_ASYNC_GENERATOR
#      8  CO_VARKEYWORDS
#     16  CO_NESTED
#
# OPTIMIZED and NEWLOCALS are set on every function code object; the rest are
# properties of the source, so Grail knows all of them at compile time --
# ``isAsync`` from the keyword, ``isGenerator`` from a ``yield`` in the body.
#
# The attribute was missing entirely, and with it the ``f.__code__ =
# g.__code__`` rule: CPython warns when the assignment changes the KIND,
#
#     DeprecationWarning: Assigning a code object of non-matching type is
#     deprecated (e.g., from a generator to a plain function)
#
# because a function's calling protocol is fixed at definition -- a generator's
# caller expects an iterator back, a coroutine's an awaitable -- so installing
# code of another kind leaves the two disagreeing and the failure appears at the
# next call rather than at the assignment.  It is a warning and not a refusal:
# the assignment still happens.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import warnings

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def kinds():
    def plain():
        pass

    def generator():
        yield

    async def async_generator():
        yield

    async def coroutine(x):
        await x
    return plain, generator, async_generator, coroutine


def shapes():
    def bare():
        pass

    def varargs(*a):
        pass

    def varkeywords(**k):
        pass

    def both(*a, **k):
        pass
    return bare, varargs, varkeywords, both


def top_level():
    pass


# --- the flag word ----------------------------------------------------------

def _the_four_kinds():
    return tuple(f.__code__.co_flags for f in kinds())


def _the_four_kinds_are_all_distinct():
    # What the rule below is stated in terms of: if any two collided, a
    # mismatched assignment between them could not be detected at all.
    return len({f.__code__.co_flags for f in kinds()}) == 4


def _parameter_shape_bits():
    return tuple(f.__code__.co_flags for f in shapes())


def _nesting_is_a_flag():
    # A def inside a def carries CO_NESTED; a module-level one does not.  Both
    # appear above, so the difference has to be real rather than assumed.
    def inner():
        pass
    return (top_level().__class__ is type(None),
            top_level.__code__.co_flags,
            inner.__code__.co_flags)


# --- the assignment rule ----------------------------------------------------

def _assign_across_kinds_warns():
    plain, generator, _agen, _coro = kinds()
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        generator.__code__ = plain.__code__
    return (len(caught),
            caught[0].category is DeprecationWarning,
            'code object of non-matching type' in str(caught[0].message))


def _every_mismatched_pair_warns():
    # test_funcattrs walks all twelve ordered pairs; so does this, because a
    # rule that fired for one direction only would still pass a single case.
    out = []
    for i in range(4):
        for j in range(4):
            if i == j:
                continue
            src = kinds()[i]
            dst = kinds()[j]
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter('always')
                dst.__code__ = src.__code__
            out.append(len(caught) == 1
                       and caught[0].category is DeprecationWarning)
    return (len(out), all(out))


def _same_kind_does_not_warn():
    # The guard against a rule that warns on everything: two plain functions
    # differ in their parameter-shape bits and must go through in silence.
    _bare, varargs, varkeywords, _both = shapes()
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter('always')
        varargs.__code__ = varkeywords.__code__
    return len(caught)


def _the_assignment_still_happens():
    # A warning, not a refusal.
    plain, generator, _agen, _coro = kinds()
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        generator.__code__ = plain.__code__
    return generator.__code__.co_flags == plain.__code__.co_flags


rec('the_four_kinds', _the_four_kinds)
rec('the_four_kinds_are_all_distinct', _the_four_kinds_are_all_distinct)
rec('parameter_shape_bits', _parameter_shape_bits)
rec('nesting_is_a_flag', _nesting_is_a_flag)
rec('assign_across_kinds_warns', _assign_across_kinds_warns)
rec('every_mismatched_pair_warns', _every_mismatched_pair_warns)
rec('same_kind_does_not_warn', _same_kind_does_not_warn)
rec('the_assignment_still_happens', _the_assignment_still_happens)


EXPECTED = {
    'assign_across_kinds_warns': (1, True, True),
    'every_mismatched_pair_warns': (12, True),
    'nesting_is_a_flag': (True, 3, 19),
    'parameter_shape_bits': (19, 23, 27, 31),
    'same_kind_does_not_warn': 0,
    'the_assignment_still_happens': True,
    'the_four_kinds': (19, 51, 531, 147),
    'the_four_kinds_are_all_distinct': True,
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-36s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
