# TWO REFLECTION GAPS IN test_funcattrs, both of the same shape: Grail HAS the
# object and only the way to name it was missing.
#
# 1. ``code.co_freevars`` did not exist.  Grail computes a def's free-variable
#    set at compile time -- it is what ``__closure__`` and ``locals()`` are both
#    built from -- but never stamped it onto the code object.  The field is not
#    decoration: CPython states the ``f.__code__ = g.__code__`` rule in terms of
#    it, and refuses the assignment when the two disagree, because a function's
#    cells and its code would then be describing different closures.  Without
#    co_freevars that rule cannot even be written, so every such assignment was
#    accepted and the damage surfaced at the next call.
#
# 2. ``types.MethodType`` was an empty stub.  Every other name in Grail's
#    ``types`` is a stub on purpose -- a stub is the honest answer for a name
#    that only appears in an ``isinstance`` test, since Grail has no public class
#    object matching CPython's.  This one is different because it is CALLED, to
#    bind a function to an object after the fact.  Calling the stub answered
#    something that was not callable, and invoking it raised a raw Smalltalk
#    MessageNotUnderstood rather than any Python error -- uncatchable from
#    Python, and in the conformance harness it voids the scoring of every test
#    after it in the module.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import types

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- co_freevars ------------------------------------------------------------

def _freevars_of_a_closure():
    num_one, num_two = 7, 8

    def none():
        pass

    def one():
        return num_one

    def two():
        return (num_one, num_two)
    return (none.__code__.co_freevars,
            one.__code__.co_freevars,
            two.__code__.co_freevars)


def _freevars_are_sorted_and_match_the_closure():
    # co_freevars and __closure__ are built from the SAME set, so their lengths
    # cannot drift -- which is what makes the assignment rule below checkable.
    beta, alpha = 1, 2

    def f():
        return (alpha, beta)
    return (f.__code__.co_freevars, len(f.__closure__))


def _the_code_type_is_the_code_type():
    def f():
        pass
    return type(f.__code__) is types.CodeType


# --- the __code__ assignment rule -------------------------------------------

def _same_free_var_count_is_allowed():
    num_one, num_two = 7, 8

    def c():
        return num_one

    def d():
        return num_two
    d.__code__ = c.__code__
    return c.__code__ == d.__code__


def _fewer_free_vars_is_refused():
    num_one = 7

    def b():
        return 12

    def c():
        return num_one
    b.__code__ = c.__code__
    return 'accepted'


def _more_free_vars_is_refused():
    num_one, num_two = 7, 8

    def d():
        return num_two

    def e():
        return (num_one, num_two)
    e.__code__ = d.__code__
    return 'accepted'


def _a_non_code_object_is_still_a_type_error():
    # The type check owns that error; the free-variable rule must not restate
    # it as a ValueError.
    def f():
        pass
    f.__code__ = 7
    return 'accepted'


# --- types.MethodType -------------------------------------------------------

class _Holder:
    pass


def _binds_a_function_to_an_object():
    h = _Holder()
    h.length = types.MethodType(len, [1, 2, 3])
    return h.length()


def _passes_further_arguments_through():
    def add(obj, n):
        return obj + n
    return types.MethodType(add, 40)(2)


def _carries_func_and_self():
    def fn(obj):
        return obj
    h = _Holder()
    m = types.MethodType(fn, h)
    return (m.__func__ is fn, m.__self__ is h)


def _has_no_attribute_storage():
    m = types.MethodType(len, [])
    out = []
    try:
        m.unknown_attr
        out.append('accepted')
    except BaseException as e:
        out.append(type(e).__name__)
    try:
        m.unknown_attr = 2
        out.append('accepted')
    except BaseException as e:
        out.append(type(e).__name__)
    try:
        del m.unknown_attr
        out.append('accepted')
    except BaseException as e:
        out.append(type(e).__name__)
    return tuple(out)


rec('freevars_of_a_closure', _freevars_of_a_closure)
rec('freevars_are_sorted_and_match_the_closure', _freevars_are_sorted_and_match_the_closure)
rec('the_code_type_is_the_code_type', _the_code_type_is_the_code_type)
rec('same_free_var_count_is_allowed', _same_free_var_count_is_allowed)
rec('fewer_free_vars_is_refused', _fewer_free_vars_is_refused)
rec('more_free_vars_is_refused', _more_free_vars_is_refused)
rec('a_non_code_object_is_still_a_type_error', _a_non_code_object_is_still_a_type_error)
rec('binds_a_function_to_an_object', _binds_a_function_to_an_object)
rec('passes_further_arguments_through', _passes_further_arguments_through)
rec('carries_func_and_self', _carries_func_and_self)
rec('has_no_attribute_storage', _has_no_attribute_storage)


EXPECTED = {
    'a_non_code_object_is_still_a_type_error': 'TypeError: __code__ must be set to a code object',
    'binds_a_function_to_an_object': 3,
    'carries_func_and_self': (True, True),
    'fewer_free_vars_is_refused': 'ValueError: b() requires a code object with 0 free vars, not 1',
    'freevars_are_sorted_and_match_the_closure': (('alpha', 'beta'), 2),
    'freevars_of_a_closure': ((), ('num_one',), ('num_one', 'num_two')),
    'has_no_attribute_storage': ('AttributeError', 'AttributeError', 'AttributeError'),
    'more_free_vars_is_refused': 'ValueError: e() requires a code object with 2 free vars, not 1',
    'passes_further_arguments_through': 42,
    'same_free_var_count_is_allowed': True,
    'the_code_type_is_the_code_type': True,
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-44s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
