# A COROUTINE THAT SUSPENDS -- the mechanism an event loop is made of.
#
# `await x` is not "run x and take its value".  When x's `__await__` YIELDS,
# that yield travels out through every enclosing await to whoever is driving
# the outermost coroutine, and what the driver sends back becomes the value of
# the yield inside x.  PEP 492 defines await by REUSING PEP 380's yield-from
# delegation, so send / throw / close forwarding come with it -- and those are
# not decoration: cancellation IS throw() arriving at the innermost suspension
# point, and a loop shutting a task down IS close() running its `finally`.
#
# This is the whole basis of asyncio.  `asyncio.Future.__await__` is
# `yield self`: the loop receives the future at its own send(), registers a
# callback, and resumes the coroutine when the future resolves.  A runtime that
# cannot propagate that yield cannot host a loop no matter how much of asyncio
# is vendored on top of it.
#
# Grail could not.  `await` was driven by a CLASS-side helper with no reference
# to the awaiting coroutine, so it could only run the awaited object inline to
# completion, and it drove only objects that were already generator-shaped --
# a custom `__await__` was never consulted at all, so `await Sleeper()`
# evaluated to the Sleeper OBJECT.  See PythonGenerator >> ___grailAwait___:.
#
# Every check below is plain CPython: driving a coroutine by hand with
# send() / throw() / close() is public, documented behaviour, which is what
# makes this file usable as ground truth rather than a description of Grail.
#
# TWO GRAIL DEVIATIONS ARE DELIBERATELY NOT PROBED HERE, because CPython
# raises TypeError for both and Grail passes them through on purpose (a great
# deal of shipped library code awaits values Grail resolves synchronously):
# `await <plain value>` and `await <plain generator>`.  They are pinned on the
# Smalltalk side instead, in CoroutineSuspensionTestCase.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def drive(c):
    """Run a coroutine that never suspends; answer what it returned."""
    try:
        c.send(None)
        return 'did not finish'
    except StopIteration as e:
        return e.value


# --- the straight-line cases must keep working -----------------------------

def _no_suspension():
    async def plain():
        return 42
    return drive(plain())


def _await_chain():
    async def inner():
        return 7

    async def outer():
        return await inner() + 1
    return drive(outer())


def _coroutine_is_its_own_awaitable():
    # A coroutine has no __await__ of its own to consult in CPython -- it IS
    # the awaitable.  Awaiting one twice is an error, which is what pins that
    # the first await consumed it rather than copying it.
    async def once():
        return 'ran'

    async def caller(c):
        return await c
    c = once()
    first = drive(caller(c))
    second = drive(caller(c))
    return (first, second)


def _exception_propagates_out_of_an_await():
    async def boom():
        raise ValueError('from inside')

    async def caller():
        return await boom()
    try:
        drive(caller())
        return 'no exception'
    except ValueError as e:
        return ('ValueError', str(e))


# --- suspension: one await -------------------------------------------------

class Sleeper:
    """The minimal custom awaitable: parks once, reports what it was sent."""

    def __await__(self):
        sent = yield 'suspend-me'
        return ('resumed-with', sent)


def _suspend_and_resume():
    async def f():
        return await Sleeper()
    c = f()
    parked = c.send(None)          # the yield travels out to us
    try:
        c.send('loop-value')       # ...and our value goes back in
        return (parked, 'did not finish')
    except StopIteration as e:
        return (parked, e.value)


def _suspension_travels_out_through_nested_awaits():
    # THE PROPERTY THAT MATTERS: two awaits deep, one driver.  A loop only ever
    # holds the outermost coroutine, so a suspension anywhere below it has to
    # arrive at that one send().
    async def mid():
        return await Sleeper()

    async def top():
        return await mid()
    c = top()
    parked = c.send(None)
    try:
        c.send('deep')
        return (parked, 'did not finish')
    except StopIteration as e:
        return (parked, e.value)


class Multi:
    """Parks twice, so a driver has to step it more than once."""

    def __await__(self):
        a = yield 'first'
        b = yield 'second'
        return (a, b)


def _multiple_suspensions():
    async def f():
        return await Multi()
    c = f()
    seen = [c.send(None)]
    seen.append(c.send('A'))
    try:
        c.send('B')
        return (seen, 'did not finish')
    except StopIteration as e:
        return (seen, e.value)


def _await_after_a_suspension():
    # Suspending must not break the coroutine's own control flow afterwards.
    async def inner():
        return 'inner'

    async def f():
        parked = await Sleeper()
        rest = await inner()
        return (parked, rest)
    c = f()
    first = c.send(None)
    try:
        c.send('x')
        return (first, 'did not finish')
    except StopIteration as e:
        return (first, e.value)


# --- throw() and close() reach the suspension point ------------------------

class Catcher:
    def __await__(self):
        try:
            yield 'parked'
        except ValueError as e:
            return ('caught', str(e))
        return 'not thrown'


def _throw_arrives_at_the_suspension():
    # This is cancellation.  asyncio cancels a task by throwing CancelledError
    # at wherever it is parked; if throw() hit the OUTER coroutine instead, a
    # cancelled task could never clean up at the right place.
    async def f():
        return await Catcher()
    c = f()
    parked = c.send(None)
    try:
        c.throw(ValueError('cancel'))
        return (parked, 'did not finish')
    except StopIteration as e:
        return (parked, e.value)


def _throw_propagates_when_not_caught():
    async def f():
        return await Sleeper()
    c = f()
    c.send(None)
    try:
        c.throw(KeyError('nope'))
        return 'did not raise'
    except KeyError as e:
        return ('KeyError', str(e))


def _close_runs_the_finally_at_the_suspension():
    # A loop shutting down closes its pending coroutines; each one's `finally`
    # has to run, which only happens if close() reaches the suspension point.
    log = []

    class Cleans:
        def __await__(self):
            try:
                yield 'parked'
            finally:
                log.append('cleaned')

    async def f():
        return await Cleans()
    c = f()
    c.send(None)
    c.close()
    return log


# --- async with, over the suspension boundary ------------------------------

def _async_with():
    class ACtx:
        async def __aenter__(self):
            return 'in'

        async def __aexit__(self, *a):
            return False

    async def f():
        async with ACtx() as v:
            return v
    return drive(f())


def _async_with_suspending_inside():
    class ACtx:
        async def __aenter__(self):
            return 'in'

        async def __aexit__(self, *a):
            return False

    async def f():
        async with ACtx() as v:
            parked = await Sleeper()
            return (v, parked)
    c = f()
    first = c.send(None)
    try:
        c.send('mid-context')
        return (first, 'did not finish')
    except StopIteration as e:
        return (first, e.value)


# --- the payoff: a miniature event loop ------------------------------------
#
# Nothing framework-specific, and no asyncio import -- just the shape asyncio
# itself uses.  If this runs, Grail can host a loop.

class Future:
    """asyncio.Future's essential three lines."""

    def __init__(self):
        self.done = False
        self.result = None

    def set_result(self, v):
        self.done = True
        self.result = v

    def __await__(self):
        if not self.done:
            yield self          # hand ourselves to the loop and park
        return self.result


class Loop:
    """Round-robin scheduler over coroutines parked on Futures."""

    def __init__(self):
        self.ready = []         # (coro, value_to_send)
        self.waiting = []       # (future, coro)
        self.results = {}

    def spawn(self, name, coro):
        self.ready.append((name, coro, None))

    def run(self):
        steps = 0
        while self.ready or self.waiting:
            steps += 1
            if steps > 100:
                raise RuntimeError('loop did not converge')
            while self.ready:
                name, coro, value = self.ready.pop(0)
                try:
                    parked_on = coro.send(value)
                except StopIteration as e:
                    self.results[name] = e.value
                    continue
                self.waiting.append((parked_on, name, coro))
            # Nothing runnable: resolve one pending future, as I/O completing.
            if self.waiting:
                fut, name, coro = self.waiting.pop(0)
                if not fut.done:
                    fut.set_result('io:' + name)
                self.ready.append((name, coro, None))
        return self.results


def _mini_event_loop():
    async def fetch(tag):
        f = Future()
        got = await f
        return tag + '/' + got

    async def task(tag):
        a = await fetch(tag + 'A')
        b = await fetch(tag + 'B')
        return (a, b)

    loop = Loop()
    loop.spawn('one', task('1'))
    loop.spawn('two', task('2'))
    out = loop.run()
    return sorted(out.items())


def _loop_interleaves_two_tasks():
    # Two tasks must make progress alternately, not one-then-the-other -- which
    # is only observable because each suspension really does return control.
    order = []

    async def worker(tag):
        for i in range(3):
            f = Future()
            order.append((tag, i))
            await f
        return tag

    loop = Loop()
    loop.spawn('a', worker('a'))
    loop.spawn('b', worker('b'))
    loop.run()
    return order


def _two_tasks_park_inside_except_handlers():
    """The canonical asyncio retry idiom, run by TWO tasks at once.

    ``except X: await ...`` and then loop back into the same try is how every
    socket coroutine in an event loop is written -- retry until the operation
    stops answering "not ready".  Two tasks doing it simultaneously is not an
    edge case either: it is the ordinary state of a server, where every
    connection runs the same code, so both are parked inside a handler of the
    SAME try.

    Grail kept "which except handler bodies am I inside" in one SESSION-wide
    stack, and a coroutine is a generator running on its own forked process --
    a second call stack.  So the task that resumed first unwound the OTHER
    task's entry and left its own behind.  From then on its own try site looked
    permanently "already handling", and the shield that stops a handler's
    exception reaching its siblings refused EVERY later clause -- a bare
    ``except BaseException`` included.  The next exception did not go to the
    wrong clause, it escaped uncaught.

    Measured as an ASGI server dying on its first request: connect() answered
    EISCONN straight past an ``except OSError`` written to catch exactly that.
    Fixed by saving and restoring that bookkeeping across every suspension, the
    way the currently-handled exception already was -- see BaseException
    >> ___captureHandlerState___.

    The answer pins both tasks: each must see its own ValueError then its own KeyError, and
    neither may report 'ESCAPED'.
    """
    async def retrier(tag):
        got = []
        for n in (0, 1):
            try:
                if n == 0:
                    raise ValueError('first')
                raise KeyError('second')
            except ValueError:
                got.append('ValueError')
                await Future()          # park INSIDE the handler
            except KeyError:
                got.append('KeyError')
        return (tag, got)

    loop = Loop()
    loop.spawn('a', retrier('a'))
    loop.spawn('b', retrier('b'))
    results = loop.run()
    return [results[k] for k in ('a', 'b')]


def _a_task_parked_in_a_handler_does_not_shield_a_plain_caller():
    """The same leak seen from the other side: a coroutine parked inside its
    handler must not shield a SYNCHRONOUS try that runs while it is parked."""
    out = []

    async def parker():
        try:
            raise ValueError('inner')
        except ValueError:
            out.append('parked')
            await Future()
        return 'resumed'

    loop = Loop()
    loop.spawn('p', parker())
    # Drive one step, so the coroutine is parked inside its handler.
    name, coro, value = loop.ready.pop(0)
    parked_on = coro.send(value)
    # Now an ordinary try/except, two clauses, in this stack.
    try:
        raise KeyError('mine')
    except ValueError:
        out.append('WRONG-ValueError')
    except KeyError:
        out.append('mine-KeyError')
    parked_on.set_result(None)
    try:
        coro.send(None)
    except StopIteration as e:
        out.append(e.value)
    return out


def _async_with_waits_for_a_suspending_aenter():
    """``async with`` MUST suspend when __aenter__ does.

    Grail's with-statement codegen drove __aenter__ through the CLASS-side
    ``PythonCoroutine ___grailAwait___:``, which has no reference to the
    awaiting coroutine.  That helper can only send() once: if the coroutine
    RETURNS, the value is right, but if it SUSPENDS the helper answers None and
    the statement carries on into its body.

    So an ``async with`` over a manager that blocks ran its body WITHOUT having
    entered.  On an asyncio.Lock under contention that meant the critical
    section ran unlocked and __aexit__ then raised "Lock is not acquired"; two
    of three tasks got None out of ``async with barrier as i``.  With no
    contention __aenter__ never suspends, which is why it went unnoticed --
    it took upstream's test_locks, where contention is the point.

    The fix gives AsyncWithAst the same two-emit rule AwaitAst already had:
    inside a wrapped body, drive through ``___gen___`` so the suspension can
    travel out.  See PythonAst/AsyncWithAst >> ___awaitPrefix___.

    Recorded here as the ORDER of events, because that is what distinguishes
    the bug from the fix: the body must not appear before the aenter finishes.
    """
    order = []

    class Blocking:
        def __init__(self, gate):
            self.gate = gate

        async def __aenter__(self):
            order.append('aenter-start')
            await self.gate
            order.append('aenter-done')
            return 'VALUE'

        async def __aexit__(self, *args):
            order.append('aexit')
            return False

    async def user(gate):
        async with Blocking(gate) as v:
            order.append(('body', v))
        return v

    gate = Future()
    loop = Loop()
    loop.spawn('u', user(gate))
    results = loop.run()
    return order, results['u']


rec('no_suspension', _no_suspension)
rec('await_chain', _await_chain)
rec('coroutine_is_its_own_awaitable', _coroutine_is_its_own_awaitable)
rec('exception_propagates_out_of_an_await',
    _exception_propagates_out_of_an_await)
rec('suspend_and_resume', _suspend_and_resume)
rec('suspension_travels_out_through_nested_awaits',
    _suspension_travels_out_through_nested_awaits)
rec('multiple_suspensions', _multiple_suspensions)
rec('await_after_a_suspension', _await_after_a_suspension)
rec('throw_arrives_at_the_suspension', _throw_arrives_at_the_suspension)
rec('throw_propagates_when_not_caught', _throw_propagates_when_not_caught)
rec('close_runs_the_finally_at_the_suspension',
    _close_runs_the_finally_at_the_suspension)
rec('async_with', _async_with)
rec('async_with_suspending_inside', _async_with_suspending_inside)
rec('mini_event_loop', _mini_event_loop)
rec('loop_interleaves_two_tasks', _loop_interleaves_two_tasks)
rec('async_with_waits_for_a_suspending_aenter',
    _async_with_waits_for_a_suspending_aenter)
rec('two_tasks_park_inside_except_handlers',
    _two_tasks_park_inside_except_handlers)
rec('a_task_parked_in_a_handler_does_not_shield_a_plain_caller',
    _a_task_parked_in_a_handler_does_not_shield_a_plain_caller)


EXPECTED = {
    'a_task_parked_in_a_handler_does_not_shield_a_plain_caller': ['parked', 'mine-KeyError', 'resumed'],
    'async_with': 'in',
    'async_with_waits_for_a_suspending_aenter': (['aenter-start', 'aenter-done', ('body', 'VALUE'), 'aexit'], 'VALUE'),
    'async_with_suspending_inside': ('suspend-me', ('in', ('resumed-with', 'mid-context'))),
    'await_after_a_suspension': ('suspend-me', (('resumed-with', 'x'), 'inner')),
    'await_chain': 8,
    'close_runs_the_finally_at_the_suspension': ['cleaned'],
    'coroutine_is_its_own_awaitable': 'RuntimeError: cannot reuse already awaited coroutine',
    'exception_propagates_out_of_an_await': ('ValueError', 'from inside'),
    'loop_interleaves_two_tasks': [('a', 0), ('b', 0), ('a', 1), ('b', 1), ('a', 2), ('b', 2)],
    'mini_event_loop': [('one', ('1A/io:one', '1B/io:one')), ('two', ('2A/io:two', '2B/io:two'))],
    'multiple_suspensions': (['first', 'second'], ('A', 'B')),
    'no_suspension': 42,
    'suspend_and_resume': ('suspend-me', ('resumed-with', 'loop-value')),
    'suspension_travels_out_through_nested_awaits': ('suspend-me', ('resumed-with', 'deep')),
    'two_tasks_park_inside_except_handlers': [('a', ['ValueError', 'KeyError']), ('b', ['ValueError', 'KeyError'])],
    'throw_arrives_at_the_suspension': ('parked', ('caught', 'cancel')),
    'throw_propagates_when_not_caught': ('KeyError', "'nope'"),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-46s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
