# ``__module__'' on a class built by type(name, bases, ns).
#
# A class STATEMENT gets its module at compile time.  A class built at runtime
# has only the stack to ask, and CPython's type_new stamps __module__ from the
# CALLER's globals -- ``PyEval_GetGlobals()['__name__']'' -- whenever the
# namespace did not supply one.
#
# Grail stamped nothing, and the result read two different ways depending on the
# bases, NEITHER of them right:
#
#     type('X', ()).__module__        -- AttributeError
#     type('X', (Base,)).__module__   -- a raw Smalltalk nil, surfacing in
#                                        Python as <UndefinedObject object at ...>
#
# The second is the worse one.  The base's accessor pair is inherited but the
# subclass's own slot was never set, so the read SUCCEEDS and answers an object
# no Python code can do anything with -- not an error anyone could catch, and
# not a value anyone could use.
#
# It also decides repr: a class with no module reprs as ``<class 'X'>'' where
# CPython says ``<class 'mod.X'>''.
#
# THE CALLER IS THE ANSWER, NOT THE BASE.  Subclassing collections.OrderedDict
# here gives a class whose __module__ is THIS module, not ``collections'' --
# which is the rule a naive "inherit it from the base" fix would get wrong, and
# which is why the base below is deliberately one from another module.
#
# The two call sites are pinned separately because they reach the answer by
# different routes: a call inside a FUNCTION is found by walking the frame
# chain, while a call at MODULE LEVEL has no frame at all -- Grail does not
# represent a module body as a Python frame -- and falls back to the import
# stack.  They must agree, and only a test says so.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import collections

r = {}

# Run as __main__ under CPython, imported as ``dynamic_class_module'' here --
# see class_repr.py for why the module name has to be normalised out.
MOD = __name__


def _norm(v):
    if isinstance(v, str):
        return v.replace(MOD, '<mod>')
    if isinstance(v, tuple):
        return tuple(_norm(x) for x in v)
    return v


def rec(k, fn):
    try:
        r[k] = _norm(fn())
    except BaseException as e:
        r[k] = type(e).__name__ + ': ' + str(e)[:60]


class Base:
    pass


# --- built at MODULE LEVEL ---------------------------------------------------

NoBases = type('NoBases', (), {})
WithBase = type('WithBase', (Base,), {'x': 1})
FromOtherModule = type('FromOtherModule', (collections.OrderedDict,), {})
Explicit = type('Explicit', (), {'__module__': 'somewhere.else'})


def _build_in_a_function():
    return type('InAFunction', (), {})


InAFunction = _build_in_a_function()


rec('no_bases', lambda: NoBases.__module__)
rec('with_base', lambda: WithBase.__module__)
# THE ONE THAT SEPARATES "caller" FROM "base": OrderedDict lives in collections,
# and the class built from it belongs to whoever built it.
rec('base_from_another_module_does_not_win',
    lambda: FromOtherModule.__module__)
rec('built_inside_a_function', lambda: InAFunction.__module__)
# A namespace that supplies __module__ keeps it -- CPython stamps only when the
# key is absent.
rec('explicit_module_is_kept', lambda: Explicit.__module__)


# --- it is in the class dict, not merely readable ----------------------------

rec('in_the_class_dict', lambda: '__module__' in NoBases.__dict__)
rec('dict_value', lambda: NoBases.__dict__['__module__'])


# --- what it decides ---------------------------------------------------------

rec('repr_is_qualified', lambda: repr(NoBases))
rec('repr_with_base', lambda: repr(WithBase))
rec('instance_repr_is_qualified',
    lambda: repr(NoBases()).startswith('<' + MOD + '.NoBases object at 0x'))


# --- the rest of the class is unchanged --------------------------------------
#
# Stamping __module__ must not disturb the namespace it was added beside.

rec('name', lambda: NoBases.__name__)
rec('qualname', lambda: NoBases.__qualname__)
rec('namespace_value_survives', lambda: WithBase.x)
rec('base_is_kept', lambda: WithBase.__bases__[0].__name__)
rec('subclass_check', lambda: issubclass(WithBase, Base))
rec('instance_is_usable', lambda: isinstance(WithBase(), Base))


EXPECTED = {
    'base_from_another_module_does_not_win': '<mod>',
    'base_is_kept': 'Base',
    'built_inside_a_function': '<mod>',
    'dict_value': '<mod>',
    'explicit_module_is_kept': 'somewhere.else',
    'in_the_class_dict': True,
    'instance_is_usable': True,
    'instance_repr_is_qualified': True,
    'name': 'NoBases',
    'namespace_value_survives': 1,
    'no_bases': '<mod>',
    'qualname': 'NoBases',
    'repr_is_qualified': "<class '<mod>.NoBases'>",
    'repr_with_base': "<class '<mod>.WithBase'>",
    'subclass_check': True,
    'with_base': '<mod>',
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-40s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
