# AN EVENT LOOP -- asyncio actually running coroutines.
#
# `asyncio` was an 84-line stub whose stated contract was that anything which
# would actually RUN a coroutine raises NotImplementedError. It could not have
# been more than that: a loop works by receiving a suspension from a coroutine,
# and until `await` delegated (PythonGenerator >> ___grailAwait___:) there was
# no way for one to arrive.
#
# The chain, in the order it had to be built:
#
#   1. `await` delegates, so a coroutine can suspend and the yield reaches its
#      driver.  asyncio.Future.__await__ is literally `yield self`.
#   2. `async for` consults __aiter__/__anext__; async generators exist.
#   3. this: a ready queue, a timer heap, Future, Task, sleep, run.
#
# Everything below is ordinary CPython asyncio -- no Grail-specific spelling --
# which is what makes this file usable as ground truth rather than a
# description of what Grail happens to do.
#
# THE PROBE THAT MATTERS MOST is `two_tasks_interleave`. Everything else could
# pass on a runtime that ran each coroutine straight through to completion;
# interleaving can only happen if a suspension really returns control to the
# scheduler and the scheduler really resumes someone else.
#
# NOT COVERED HERE: I/O. Nothing below opens a socket -- this file is about
# scheduling. The loop's I/O half (add_reader, sock_recv, sock_accept,
# sock_sendall, and a wait that happens inside `select`) has its own fixture,
# tests/python/asyncio_io.py.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import asyncio

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- the basics -----------------------------------------------------------

def _run_returns_the_result():
    async def add(a, b):
        return a + b
    return asyncio.run(add(2, 3))


def _run_propagates_an_exception():
    async def boom():
        raise ValueError('from the coroutine')
    try:
        asyncio.run(boom())
        return 'no exception'
    except ValueError as e:
        return ('ValueError', str(e))


def _sleep_zero_yields_without_a_timer():
    async def f():
        await asyncio.sleep(0)
        return 'resumed'
    return asyncio.run(f())


def _sleep_returns_its_result_argument():
    async def f():
        return await asyncio.sleep(0, 'the result')
    return asyncio.run(f())


def _a_real_sleep_actually_waits():
    # Deliberately not asserting a duration -- that would be a flaky clock
    # test.  What is asserted is that the coroutine resumes AFTER the delay
    # rather than being abandoned on the timer heap.
    async def f():
        await asyncio.sleep(0.01)
        return 'woke'
    return asyncio.run(f())


# --- the property a straight-through runtime cannot fake ------------------

def _two_tasks_interleave():
    """THE TEST THIS FILE EXISTS FOR.

    Two tasks that each yield three times must alternate. A runtime that ran
    each coroutine to completion would answer the same VALUES and the wrong
    ORDER, which is why the order is what is recorded.
    """
    async def main():
        order = []

        async def worker(tag):
            for _ in range(3):
                order.append(tag)
                await asyncio.sleep(0)
            return tag

        first = asyncio.create_task(worker('a'))
        second = asyncio.create_task(worker('b'))
        done = [await first, await second]
        return (order, done)
    return asyncio.run(main())


def _a_task_runs_without_being_awaited():
    # create_task schedules; it does not need the creator to await it. That is
    # the difference between a task and a bare coroutine.
    async def main():
        seen = []

        async def side():
            seen.append('ran')
        asyncio.create_task(side())
        await asyncio.sleep(0)
        await asyncio.sleep(0)
        return seen
    return asyncio.run(main())


# --- futures --------------------------------------------------------------

def _a_future_is_resolved_by_a_timer():
    async def main():
        loop = asyncio.get_running_loop()
        fut = loop.create_future()
        loop.call_later(0.01, fut.set_result, 'resolved')
        return await fut
    return asyncio.run(main())


def _a_future_carries_an_exception():
    async def main():
        loop = asyncio.get_running_loop()
        fut = loop.create_future()
        loop.call_soon(fut.set_exception, KeyError('stored'))
        try:
            await fut
            return 'no exception'
        except KeyError as e:
            return ('KeyError', str(e))
    return asyncio.run(main())


def _an_already_done_future_is_awaited_without_suspending():
    async def main():
        loop = asyncio.get_running_loop()
        fut = loop.create_future()
        fut.set_result('immediate')
        return await fut
    return asyncio.run(main())


def _call_soon_runs_in_order():
    async def main():
        loop = asyncio.get_running_loop()
        seen = []
        loop.call_soon(seen.append, 1)
        loop.call_soon(seen.append, 2)
        loop.call_soon(seen.append, 3)
        await asyncio.sleep(0)
        await asyncio.sleep(0)
        return seen
    return asyncio.run(main())


def _timers_fire_in_deadline_order_not_scheduling_order():
    async def main():
        loop = asyncio.get_running_loop()
        seen = []
        loop.call_later(0.03, seen.append, 'late')
        loop.call_later(0.01, seen.append, 'early')
        await asyncio.sleep(0.05)
        return seen
    return asyncio.run(main())


def _a_cancelled_timer_does_not_fire():
    async def main():
        loop = asyncio.get_running_loop()
        seen = []
        handle = loop.call_later(0.01, seen.append, 'should not run')
        handle.cancel()
        await asyncio.sleep(0.03)
        return seen
    return asyncio.run(main())


# --- gather ---------------------------------------------------------------

def _gather_answers_in_argument_order():
    # Not completion order: callers index results against their inputs, so
    # completion order would be a quiet correctness bug. The sleeps are chosen
    # so completion order is the REVERSE of argument order.
    async def main():
        async def f(n, delay):
            await asyncio.sleep(delay)
            return n
        return await asyncio.gather(f(1, 0.03), f(2, 0.02), f(3, 0.01))
    return asyncio.run(main())


def _gather_with_return_exceptions():
    async def main():
        async def ok():
            return 'fine'

        async def bad():
            raise RuntimeError('nope')
        got = await asyncio.gather(ok(), bad(), return_exceptions=True)
        return [got[0], type(got[1]).__name__, str(got[1])]
    return asyncio.run(main())


# --- cancellation ---------------------------------------------------------

def _cancel_is_delivered_at_the_suspension_point():
    """Cancellation is not a flag -- CancelledError is raised INSIDE the
    coroutine, where it was parked, so the `finally` runs where it was
    written."""
    async def main():
        log = []

        async def forever():
            try:
                while True:
                    await asyncio.sleep(0.01)
            except asyncio.CancelledError:
                log.append('caught')
                raise
            finally:
                log.append('cleaned')

        task = asyncio.create_task(forever())
        await asyncio.sleep(0)
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            log.append('propagated')
        return (log, task.cancelled())
    return asyncio.run(main())


def _a_task_that_swallows_cancellation_still_finishes():
    async def main():
        async def stubborn():
            try:
                await asyncio.sleep(0.01)
            except asyncio.CancelledError:
                return 'swallowed'
        task = asyncio.create_task(stubborn())
        await asyncio.sleep(0)
        task.cancel()
        return await task
    return asyncio.run(main())


def _cancelled_error_is_not_an_exception_subclass():
    # It descends from BaseException so `except Exception` around a task body
    # cannot swallow a cancellation.
    return (issubclass(asyncio.CancelledError, BaseException),
            issubclass(asyncio.CancelledError, Exception))


# --- the loop accessors ---------------------------------------------------

def _get_running_loop_raises_outside_a_loop():
    # The canonical "am I in async code?" test. Raising is the contract --
    # asgiref.local and friends branch on the exception.
    try:
        asyncio.get_running_loop()
        return 'no exception'
    except RuntimeError as e:
        return ('RuntimeError', str(e))


def _get_running_loop_inside_answers_the_running_one():
    async def main():
        loop = asyncio.get_running_loop()
        return (loop.is_running(), loop is asyncio.get_event_loop())
    return asyncio.run(main())


def _run_refuses_to_nest():
    async def main():
        async def inner():
            return 1
        try:
            asyncio.run(inner())
            return 'no exception'
        except RuntimeError:
            return 'RuntimeError'
    return asyncio.run(main())


def _all_tasks_sees_a_pending_task():
    async def main():
        async def waiter():
            await asyncio.sleep(0.02)
        task = asyncio.create_task(waiter())
        await asyncio.sleep(0)
        count = len(asyncio.all_tasks())
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass
        # main itself is a task too, so a pending child makes it 2.
        return count >= 2
    return asyncio.run(main())


def _ensure_future_wraps_a_coroutine_and_passes_a_future_through():
    async def main():
        async def f():
            return 'wrapped'
        task = asyncio.ensure_future(f())
        same = asyncio.ensure_future(task)
        return (await task, same is task)
    return asyncio.run(main())


# --- the whole stack together --------------------------------------------

def _an_async_generator_runs_on_the_loop():
    async def main():
        async def ticker(n):
            for i in range(n):
                await asyncio.sleep(0)
                yield i
        out = []
        async for v in ticker(3):
            out.append(v)
        return out
    return asyncio.run(main())


def _an_async_generator_that_raises_propagates_out_of_run():
    """The path that used to die as an uncatchable Smalltalk error.

    The exception is raised inside the generator's forked body, stored on a
    future, and RE-RAISED later by Future.result() -- at which point the
    original raise's handler frame is on a different, finished process. That
    is the ordinary asyncio pattern and it reported `ImproperOperation: cannot
    find handler frame for exception` for 24 tests of test_asyncgen.
    """
    async def main():
        async def gen():
            yield 1
            await asyncio.sleep(0.01)
            yield 2
            1 / 0
            yield 3
        out = []
        async for v in gen():
            out.append(v)
        return out
    try:
        asyncio.run(main())
        return 'no exception'
    except ZeroDivisionError as e:
        return ('ZeroDivisionError', str(e))


def _aclose_on_the_loop_runs_the_finally():
    async def main():
        log = []

        async def gen():
            try:
                yield 1
                yield 2
            finally:
                log.append('cleaned')
        agen = gen()
        first = await agen.__anext__()
        await agen.aclose()
        return (first, log)
    return asyncio.run(main())


def _aiter_and_anext_builtins():
    async def main():
        async def gen():
            yield 'x'
            yield 'y'
        agen = gen()
        it = aiter(agen)
        first = await anext(it)
        return (it is agen, first)
    return asyncio.run(main())


rec('run_returns_the_result', _run_returns_the_result)
rec('run_propagates_an_exception', _run_propagates_an_exception)
rec('sleep_zero_yields_without_a_timer', _sleep_zero_yields_without_a_timer)
rec('sleep_returns_its_result_argument', _sleep_returns_its_result_argument)
rec('a_real_sleep_actually_waits', _a_real_sleep_actually_waits)
rec('two_tasks_interleave', _two_tasks_interleave)
rec('a_task_runs_without_being_awaited', _a_task_runs_without_being_awaited)
rec('a_future_is_resolved_by_a_timer', _a_future_is_resolved_by_a_timer)
rec('a_future_carries_an_exception', _a_future_carries_an_exception)
rec('an_already_done_future_is_awaited_without_suspending',
    _an_already_done_future_is_awaited_without_suspending)
rec('call_soon_runs_in_order', _call_soon_runs_in_order)
rec('timers_fire_in_deadline_order_not_scheduling_order',
    _timers_fire_in_deadline_order_not_scheduling_order)
rec('a_cancelled_timer_does_not_fire', _a_cancelled_timer_does_not_fire)
rec('gather_answers_in_argument_order', _gather_answers_in_argument_order)
rec('gather_with_return_exceptions', _gather_with_return_exceptions)
rec('cancel_is_delivered_at_the_suspension_point',
    _cancel_is_delivered_at_the_suspension_point)
rec('a_task_that_swallows_cancellation_still_finishes',
    _a_task_that_swallows_cancellation_still_finishes)
rec('cancelled_error_is_not_an_exception_subclass',
    _cancelled_error_is_not_an_exception_subclass)
rec('get_running_loop_raises_outside_a_loop',
    _get_running_loop_raises_outside_a_loop)
rec('get_running_loop_inside_answers_the_running_one',
    _get_running_loop_inside_answers_the_running_one)
rec('run_refuses_to_nest', _run_refuses_to_nest)
rec('all_tasks_sees_a_pending_task', _all_tasks_sees_a_pending_task)
rec('ensure_future_wraps_a_coroutine_and_passes_a_future_through',
    _ensure_future_wraps_a_coroutine_and_passes_a_future_through)
rec('an_async_generator_runs_on_the_loop', _an_async_generator_runs_on_the_loop)
rec('an_async_generator_that_raises_propagates_out_of_run',
    _an_async_generator_that_raises_propagates_out_of_run)
rec('aclose_on_the_loop_runs_the_finally', _aclose_on_the_loop_runs_the_finally)
rec('aiter_and_anext_builtins', _aiter_and_anext_builtins)


EXPECTED = {
    'a_cancelled_timer_does_not_fire': [],
    'a_future_carries_an_exception': ('KeyError', "'stored'"),
    'a_future_is_resolved_by_a_timer': 'resolved',
    'a_real_sleep_actually_waits': 'woke',
    'a_task_runs_without_being_awaited': ['ran'],
    'a_task_that_swallows_cancellation_still_finishes': 'swallowed',
    'aclose_on_the_loop_runs_the_finally': (1, ['cleaned']),
    'aiter_and_anext_builtins': (True, 'x'),
    'all_tasks_sees_a_pending_task': True,
    'an_already_done_future_is_awaited_without_suspending': 'immediate',
    'an_async_generator_runs_on_the_loop': [0, 1, 2],
    'an_async_generator_that_raises_propagates_out_of_run': ('ZeroDivisionError', 'division by zero'),
    'call_soon_runs_in_order': [1, 2, 3],
    'cancel_is_delivered_at_the_suspension_point': (['caught', 'cleaned', 'propagated'], True),
    'cancelled_error_is_not_an_exception_subclass': (True, False),
    'ensure_future_wraps_a_coroutine_and_passes_a_future_through': ('wrapped', True),
    'gather_answers_in_argument_order': [1, 2, 3],
    'gather_with_return_exceptions': ['fine', 'RuntimeError', 'nope'],
    'get_running_loop_inside_answers_the_running_one': (True, True),
    'get_running_loop_raises_outside_a_loop': ('RuntimeError', 'no running event loop'),
    'run_propagates_an_exception': ('ValueError', 'from the coroutine'),
    'run_refuses_to_nest': 'RuntimeError',
    'run_returns_the_result': 5,
    'sleep_returns_its_result_argument': 'the result',
    'sleep_zero_yields_without_a_timer': 'resumed',
    'timers_fire_in_deadline_order_not_scheduling_order': ['early', 'late'],
    'two_tasks_interleave': (['a', 'b', 'a', 'b', 'a', 'b'], ['a', 'b']),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-58s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
