# PEP 654 ``except*'' and the ExceptionGroup primitives it stands on.
#
# Grail had no except-star at all, and the way it failed hid that: the parser
# read ``except* T'' as ``except (*T)'' -- a STARRED EXPRESSION -- so the error
# reported at runtime was "TypeError: *-unpack in call sites is not yet
# supported", naming neither ``except'' nor exception groups.
#
# The semantics are genuinely different from ``except'', which is why this gets
# its own emitted shape rather than an extra flag on the existing one:
#
#   * EVERY matching clause runs.  Plain ``except'' picks the first match and
#     the rest are alternatives; ``except*'' SPLITS the raised group and hands
#     each clause its own share, so a group holding a ValueError and a
#     TypeError runs both clauses.
#   * The bound name is always an ExceptionGroup, even when what was raised was
#     a single bare exception.
#   * Whatever no clause claimed propagates afterwards.  But if the raised
#     exception was NOT a group and nothing matched, the ORIGINAL propagates --
#     not the wrapper this machinery built to match against.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def call(fn):
    """Record the return value, or the exception type and message."""
    try:
        return repr(fn())
    except BaseException as e:
        return type(e).__name__ + ': ' + str(e)


# --- the ExceptionGroup primitives ------------------------------------------

_eg = ExceptionGroup("eg", [ValueError("v"), TypeError("t")])
_nested = ExceptionGroup("out", [ValueError("a"),
                                 ExceptionGroup("in", [TypeError("b"), ValueError("c")])])

r['subgroup'] = call(lambda: _eg.subgroup(ValueError))
r['subgroup_no_match'] = call(lambda: _eg.subgroup(KeyError))
r['split'] = call(lambda: _eg.split(ValueError))
r['derive'] = call(lambda: _eg.derive([TypeError()]))

# split/subgroup RECURSE, keeping the surrounding structure: a nested group
# contributes to a side only through its own matching leaves, and is dropped
# from a side it contributes nothing to.
r['nested_subgroup'] = call(lambda: _nested.subgroup(ValueError))
r['nested_split'] = call(lambda: _nested.split(TypeError))

# The condition may be a type, a tuple of types, or a predicate.
r['predicate_condition'] = call(lambda: _eg.subgroup(lambda e: isinstance(e, TypeError)))
r['tuple_condition'] = call(lambda: _eg.subgroup((ValueError, TypeError)))


# --- except* semantics ------------------------------------------------------

def _both_clauses():
    out = []
    try:
        raise ExceptionGroup("eg", [ValueError("v"), TypeError("t")])
    except* ValueError as g:
        out.append(('V', [type(x).__name__ for x in g.exceptions]))
    except* TypeError as g:
        out.append(('T', [type(x).__name__ for x in g.exceptions]))
    return out


r['every_matching_clause_runs'] = call(_both_clauses)


def _unmatched_propagates():
    try:
        raise ExceptionGroup("eg", [ValueError("v"), TypeError("t")])
    except* ValueError as g:
        pass


r['unmatched_part_propagates'] = call(_unmatched_propagates)


def _bare_is_wrapped():
    out = []
    try:
        raise ValueError("plain")
    except* ValueError as g:
        out.append((type(g).__name__, [type(x).__name__ for x in g.exceptions]))
    return out


r['bare_exception_is_wrapped'] = call(_bare_is_wrapped)


def _bare_no_match():
    # The original ValueError must come back OUT, not the group built to match
    # against it.
    try:
        raise ValueError("plain")
    except* TypeError as g:
        pass


r['bare_unmatched_keeps_identity'] = call(_bare_no_match)


def _no_exception():
    try:
        x = 1
    except* ValueError as g:
        x = 2
    return x


r['no_exception_raised'] = call(_no_exception)


def _with_finally():
    out = []
    try:
        raise ExceptionGroup("eg", [ValueError()])
    except* ValueError as g:
        out.append('handled')
    finally:
        out.append('finally')
    return out


r['finally_still_runs'] = call(_with_finally)


def _handler_raises():
    try:
        raise ExceptionGroup("eg", [ValueError()])
    except* ValueError as g:
        raise KeyError("from handler")


r['handler_raise_propagates'] = call(_handler_raises)


def _nested_group_caught():
    out = []
    try:
        raise ExceptionGroup("out", [ExceptionGroup("in", [ValueError("deep")])])
    except* ValueError as g:
        out.append([type(x).__name__ for x in g.exceptions])
    return out


r['nested_group_is_matched'] = call(_nested_group_caught)


def _bare_raise_regroups():
    # A bare ``raise'' inside an except* block re-raises the group being
    # handled.  When what was raised was ALREADY a group, that is the group
    # itself, which is the case pinned here.
    try:
        raise ExceptionGroup("eg", [ValueError("v")])
    except* ValueError as g:
        raise


r['bare_raise_regroups'] = call(_bare_raise_regroups)

# KNOWN DEVIATION, deliberately not asserted here.  When the raised exception
# was NAKED, CPython's bare ``raise'' re-raises the WRAPPER group it built for
# matching, while Grail re-raises the original exception:
#
#     try: raise Exception(42)
#     except* Exception as e: raise
#     # CPython -> ExceptionGroup ( 1 sub-exception)
#     # Grail   -> Exception: 42
#
# The emitted bare raise is ``___ex pass'', which is GemStone re-signalling the
# LIVE exception; re-raising the wrapper instead would mean not using pass at
# all.  test_traceback's test_exception_group_wrapped_naked covers it.


# --- the ``as'' name obeys ``global'' ---------------------------------------
#
# The binding goes through the same module-scope-aware store every other
# binding form uses.  A bare assignment breaks here exactly as it did there: a
# global-declared name has no Smalltalk temp, so it names an undefined symbol.

def _global_binding():
    # NB no ``return'' inside the except* block: CPython makes return/break/
    # continue a SyntaxError there, since the block may run more than once.
    seen = []
    global caught_group
    try:
        raise ExceptionGroup("eg", [ValueError("v")])
    except* ValueError as caught_group:
        seen.append(globals().get('caught_group') is not None)
    return seen


r['as_name_honours_global'] = call(_global_binding)


# --- return / break / continue cannot escape an except* block ---------------
#
# CPython makes all three a SyntaxError there, and the reason is the semantics:
# the block may run MORE THAN ONCE for one raised group (once per matching
# clause) and the remainder still has to propagate afterwards, so there is no
# coherent answer to what a ``return'' out of the middle of it should do.
#
# The exemptions matter as much as the rejections, and each is exempt for its
# own reason -- so they are pinned individually rather than assumed.

def _flow(src):
    try:
        compile(src, '<test string>', 'exec')
        return 'ok'
    except SyntaxError as e:
        return 'SyntaxError: ' + str(e.msg)


r['flow_return'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n        return 1\n")
r['flow_break'] = _flow(
    "def f():\n    for i in [1]:\n        try:\n            pass\n"
    "        except* ValueError as e:\n            break\n")
r['flow_continue'] = _flow(
    "def f():\n    for i in [1]:\n        try:\n            pass\n"
    "        except* ValueError as e:\n            continue\n")

# A nested TRY introduces neither a scope nor a loop, so a return inside it
# still escapes the except* block.
r['flow_nested_try'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n"
    "        try:\n            return 1\n        except ValueError:\n            pass\n")

# Exempt: a nested def/lambda -- the return belongs to THAT function.
r['flow_nested_def'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n"
    "        def g():\n            return 1\n")
r['flow_lambda'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n        h = lambda: 1\n")

# Exempt: a loop written INSIDE the block is its own break target.
r['flow_inner_loop_break'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n"
    "        for i in [1]:\n            break\n")

# Exempt: the try BODY, ``else'' and ``finally'' are not the handler.
r['flow_try_body'] = _flow(
    "def f():\n    try:\n        return 1\n    except* ValueError as e:\n        pass\n")
r['flow_else'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n        pass\n"
    "    else:\n        return 1\n")
r['flow_finally'] = _flow(
    "def f():\n    try:\n        pass\n    except* ValueError as e:\n        pass\n"
    "    finally:\n        return 1\n")

# And a PLAIN except is unaffected -- the rule is specific to except*.
r['flow_plain_except'] = _flow(
    "def f():\n    try:\n        pass\n    except ValueError as e:\n        return 1\n")


EXPECTED = {
    'as_name_honours_global': '[True]',
    'bare_exception_is_wrapped': "[('ExceptionGroup', ['ValueError'])]",
    'bare_raise_regroups': 'ExceptionGroup: eg (1 sub-exception)',
    'bare_unmatched_keeps_identity': 'ValueError: plain',
    'derive': "ExceptionGroup('eg', [TypeError()])",
    'every_matching_clause_runs': "[('V', ['ValueError']), ('T', ['TypeError'])]",
    'finally_still_runs': "['handled', 'finally']",
    'flow_break': "SyntaxError: 'break', 'continue' and 'return' cannot appear in an except* block",
    'flow_continue': "SyntaxError: 'break', 'continue' and 'return' cannot appear in an except* block",
    'flow_else': 'ok',
    'flow_finally': 'ok',
    'flow_inner_loop_break': 'ok',
    'flow_lambda': 'ok',
    'flow_nested_def': 'ok',
    'flow_nested_try': "SyntaxError: 'break', 'continue' and 'return' cannot appear in an except* block",
    'flow_plain_except': 'ok',
    'flow_return': "SyntaxError: 'break', 'continue' and 'return' cannot appear in an except* block",
    'flow_try_body': 'ok',
    'handler_raise_propagates': "KeyError: 'from handler'",
    'nested_group_is_matched': "[['ExceptionGroup']]",
    'nested_split': "(ExceptionGroup('out', [ExceptionGroup('in', [TypeError('b')])]), ExceptionGroup('out', [ValueError('a'), ExceptionGroup('in', [ValueError('c')])]))",
    'nested_subgroup': "ExceptionGroup('out', [ValueError('a'), ExceptionGroup('in', [ValueError('c')])])",
    'no_exception_raised': '1',
    'predicate_condition': "ExceptionGroup('eg', [TypeError('t')])",
    'split': "(ExceptionGroup('eg', [ValueError('v')]), ExceptionGroup('eg', [TypeError('t')]))",
    'subgroup': "ExceptionGroup('eg', [ValueError('v')])",
    'subgroup_no_match': 'None',
    'tuple_condition': "ExceptionGroup('eg', [ValueError('v'), TypeError('t')])",
    'unmatched_part_propagates': 'ExceptionGroup: eg (1 sub-exception)',
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-32s %s %s' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
