# ``__module__'' on a class whose module has to be INFERRED -- GemTalk/Grail#1134.
#
# A class statement is told its module.  Three other paths have to work it out,
# and each one answered AttributeError:
#
#   * the Enum FUNCTIONAL API -- ``Enum('F', 'A B')'' -- which CPython's
#     _create_ stamps from the caller's frame when ``module='' is omitted;
#   * type() and the functional API called from EVALUATED code (exec, the REPL,
#     an embedder's doit), whose frames have no file sys.modules could match --
#     CPython reads the caller's GLOBALS, so ``__name__'' there is the answer;
#   * classes Grail's native modules build from Smalltalk (enum.FlagBoundary,
#     enum.EnumCheck, json.JSONEncoder), which CPython defines in a module and
#     Grail never said which.
#
# The exec() cases are the doit route in miniature: globals that carry a
# ``__name__'' name the module, and globals that do NOT stamp nothing at all --
# not the module that called exec(), which is where a frame walk that kept
# going outward would land.
#
# EXPECTED was generated by RUNNING CPython 3.14.

import enum
import json

r = {}

# Run as __main__ under CPython, imported as ``functional_enum_module'' here --
# see class_repr.py for why the module name has to be normalised out.
MOD = __name__


def _norm(v):
    if isinstance(v, str):
        return v.replace(MOD, '<mod>')
    return v


def rec(k, fn):
    try:
        r[k] = _norm(fn())
    except BaseException as e:
        r[k] = type(e).__name__ + ': ' + str(e)[:60]


# --- the functional API ------------------------------------------------------

AtModuleLevel = enum.Enum('AtModuleLevel', 'A B')
StrAtModuleLevel = enum.StrEnum('StrAtModuleLevel', [('A', 'a')])
Explicit = enum.Enum('Explicit', 'A B', module='somewhere.else')


def _build_in_a_function():
    return enum.Enum('InAFunction', 'A B')


InAFunction = _build_in_a_function()

rec('functional_at_module_level', lambda: AtModuleLevel.__module__)
rec('functional_strenum', lambda: StrAtModuleLevel.__module__)
rec('functional_in_a_function', lambda: InAFunction.__module__)
rec('functional_explicit_module_is_kept', lambda: Explicit.__module__)
rec('functional_repr_is_qualified', lambda: repr(AtModuleLevel))
rec('functional_member_is_unchanged', lambda: repr(AtModuleLevel.B))


# --- evaluated code: the caller's GLOBALS decide -----------------------------

def _exec(src, g):
    exec(src, g)
    return g['C']


rec('exec_type_names_its_globals',
    lambda: _exec("C = type('C', (), {})", {'__name__': 'evaluated'}).__module__)
rec('exec_enum_names_its_globals',
    lambda: _exec("import enum\nC = enum.Enum('C', 'A')",
                  {'__name__': 'evaluated'}).__module__)
rec('exec_in_a_function_names_its_globals',
    lambda: _exec("def f():\n    return type('C', (), {})\nC = f()",
                  {'__name__': 'evaluated'}).__module__)
# No __name__ in the globals: CPython stamps NOTHING, so the read raises -- and
# in particular does not answer this module, the one that called exec().
rec('exec_without_a_name_stamps_nothing',
    lambda: '__module__' in _exec("C = type('C', (), {})", {}).__dict__)


# --- classes native modules define -------------------------------------------

rec('flag_boundary', lambda: enum.FlagBoundary.__module__)
rec('enum_check', lambda: enum.EnumCheck.__module__)
rec('flag_boundary_member', lambda: repr(enum.STRICT))
rec('json_encoder', lambda: json.JSONEncoder.__module__)


EXPECTED = {
    'enum_check': 'enum',
    'exec_enum_names_its_globals': 'evaluated',
    'exec_in_a_function_names_its_globals': 'evaluated',
    'exec_type_names_its_globals': 'evaluated',
    'exec_without_a_name_stamps_nothing': False,
    'flag_boundary': 'enum',
    'flag_boundary_member': "<FlagBoundary.STRICT: 'strict'>",
    'functional_at_module_level': '<mod>',
    'functional_explicit_module_is_kept': 'somewhere.else',
    'functional_in_a_function': '<mod>',
    'functional_member_is_unchanged': '<AtModuleLevel.B: 2>',
    'functional_repr_is_qualified': "<enum 'AtModuleLevel'>",
    'functional_strenum': '<mod>',
    'json_encoder': 'json.encoder',
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-40s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
