# The WRITE guards on a function's attributes -- the rules CPython's func_set_*
# enforce, and which Grail did not enforce at all.
#
# Every write to a function attribute was accepted, including the ones that leave
# the object incoherent.  ``f.__name__ = 7`` put an integer where every
# traceback, repr and pickle expects a string; ``f.__closure__ = ()`` discarded
# the cells the body reads.  None of it raised, and the damage surfaced later,
# somewhere else -- which is the whole reason CPython checks at the point of
# assignment.
#
# TWO KINDS OF RULE, and CPython uses a DIFFERENT exception for each, so they are
# not interchangeable:
#
#   * READ-ONLY (__closure__, __globals__, __builtins__) -> AttributeError,
#     because the attribute has no setter at all;
#   * TYPE-CHECKED (__name__, __qualname__, __code__, __defaults__) -> TypeError,
#     because there IS a setter and the value is what is wrong.
#
# test_funcattrs checks BOTH DIRECTIONS for each -- its cannot_set_attr helper
# fails unless setattr and delattr each raise -- so the delete paths are covered
# here too.  They are not all the same: deleting __defaults__ is LEGAL and clears
# them to None, while deleting __name__ is a TypeError.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def make():
    a = 12

    def f():
        print(a)
    return f


# --- the writes that must still WORK ----------------------------------------

def _rename():
    f = make()
    f.__name__ = 'c'
    f.__name__ = 'd'
    return f.__name__


def _requalify():
    f = make()
    f.__qualname__ = 'c'
    return f.__qualname__


rec('rename', _rename)
rec('requalify', _requalify)


# --- type-checked: a non-string name is a TypeError -------------------------

def _name_to_int():
    make().__name__ = 7


def _qualname_to_int():
    make().__qualname__ = 7


def _del_name():
    del make().__name__


def _del_qualname():
    del make().__qualname__


rec('name_to_int', _name_to_int)
rec('qualname_to_int', _qualname_to_int)
rec('del_name', _del_name)
rec('del_qualname', _del_qualname)


# --- read-only: __closure__ / __globals__ have no setter at all -------------

def _set_closure():
    f = make()
    f.__closure__ = f.__closure__


def _del_closure():
    del make().__closure__


def _set_globals():
    f = make()
    f.__globals__ = {}


def _del_globals():
    del make().__globals__


rec('set_closure', _set_closure)
rec('del_closure', _del_closure)
rec('set_globals', _set_globals)
rec('del_globals', _del_globals)


# --- type-checked: __code__ and __defaults__ --------------------------------

def _code_to_int():
    make().__code__ = 7


def _defaults_to_int():
    make().__defaults__ = 7


def _defaults_to_tuple():
    f = make()
    f.__defaults__ = (1, 2)
    return f.__defaults__


def _del_defaults():
    """Deleting defaults is LEGAL -- it clears them to None."""
    f = make()
    f.__defaults__ = (1, 2)
    del f.__defaults__
    return f.__defaults__


rec('code_to_int', _code_to_int)
rec('defaults_to_int', _defaults_to_int)
rec('defaults_to_tuple', _defaults_to_tuple)
rec('del_defaults', _del_defaults)


EXPECTED = {
    'code_to_int': 'TypeError: __code__ must be set to a code object',
    'defaults_to_int': 'TypeError: __defaults__ must be set to a tuple object',
    'defaults_to_tuple': (1, 2),
    'del_closure': 'AttributeError: readonly attribute',
    'del_defaults': None,
    'del_globals': 'AttributeError: readonly attribute',
    'del_name': 'TypeError: __name__ must be set to a string object',
    'del_qualname': 'TypeError: __qualname__ must be set to a string object',
    'name_to_int': 'TypeError: __name__ must be set to a string object',
    'qualname_to_int': 'TypeError: __qualname__ must be set to a string object',
    'rename': 'd',
    'requalify': 'c',
    'set_closure': 'AttributeError: readonly attribute',
    'set_globals': 'AttributeError: readonly attribute',
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-22s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
