# ``func.__defaults__`` -- the evaluated defaults of the TRAILING positional
# parameters, or None when the def declares none.
#
# It was an AttributeError for EVERY function, though it is an attribute every
# Python function has and one that inspect and functools both read.
#
# It is synthesised rather than stored, and deliberately not faked.  Answering
# None unconditionally would have closed test_funcattrs' test_blank_func_defaults
# on the spot -- and made ``def f(a=1, b=2)`` report None as well, trading a
# visible failure for a quiet lie in the far more common case.  What makes None
# honest for a def with no defaults is that the same walk finds the real values
# when there are some.
#
# The values are already computed: Grail emits a def with defaults inside a
# wrapper block that evaluates each one ONCE, so the default is a temp and the
# attribute only has to find it.  ``closes_over_a_mutable`` checks that -- the
# tuple holds the SAME object the call binds, not a re-evaluation, which is the
# difference that matters for a mutable or side-effecting default.
#
# ASSIGNMENT WRITES THROUGH to those temps, so it changes what the next call
# binds.  Read and write had to land together: making the attribute merely
# readable would have turned a write-only attribute into a LYING one, reporting
# a default that was not in effect.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- reading, across the parameter kinds ------------------------------------

def _no_parameters_at_all():
    def f():
        return 3
    return f.__defaults__


def _parameters_but_no_defaults():
    def f(a, b):
        return a + b
    return f.__defaults__


def _one_default():
    def f(a=1):
        return a
    return f.__defaults__


def _two_defaults():
    def f(a=1, b=2):
        return a + b
    return f.__defaults__


def _only_the_trailing_parameters():
    # CPython pairs defaults with the LAST positional parameters, so a def with
    # three parameters and one default reports a one-tuple.
    def f(x, y, b=5):
        return (x, y, b)
    return f.__defaults__


def _keyword_only_defaults_are_not_here():
    # They belong to __kwdefaults__, which is a separate attribute.
    def f(*, k=3):
        return k
    return f.__defaults__


def _positional_and_keyword_only_together():
    def f(a=1, *, k=3):
        return (a, k)
    return f.__defaults__


def _closes_over_a_mutable():
    # The default is evaluated ONCE, at def time, and __defaults__ reports that
    # very object -- not a re-evaluation of the expression.
    z = ['shared']

    def f(a=z):
        return a
    return (f.__defaults__[0] is z, f() is z)


# --- writing, and deleting --------------------------------------------------

def _assignment_reads_back():
    def f(a=1):
        return a
    f.__defaults__ = (9,)
    return f.__defaults__


def _assignment_changes_what_the_call_binds():
    # The half that makes the attribute worth having: a default that reads back
    # but does not take effect is worse than no attribute at all.
    def f(a=1, b=2):
        return a + b
    f.__defaults__ = (10, 20)
    return (f.__defaults__, f(), f(1), f(1, 2))


def _deleting_clears_them():
    def f(a=1):
        return a
    del f.__defaults__
    return f.__defaults__


def _a_non_tuple_is_refused():
    def f(a=1):
        return a
    f.__defaults__ = 7
    return 'accepted'


rec('no_parameters_at_all', _no_parameters_at_all)
rec('parameters_but_no_defaults', _parameters_but_no_defaults)
rec('one_default', _one_default)
rec('two_defaults', _two_defaults)
rec('only_the_trailing_parameters', _only_the_trailing_parameters)
rec('keyword_only_defaults_are_not_here', _keyword_only_defaults_are_not_here)
rec('positional_and_keyword_only_together', _positional_and_keyword_only_together)
rec('closes_over_a_mutable', _closes_over_a_mutable)
rec('assignment_reads_back', _assignment_reads_back)
rec('assignment_changes_what_the_call_binds', _assignment_changes_what_the_call_binds)
rec('deleting_clears_them', _deleting_clears_them)
rec('a_non_tuple_is_refused', _a_non_tuple_is_refused)


EXPECTED = {
    'a_non_tuple_is_refused': 'TypeError: __defaults__ must be set to a tuple object',
    'assignment_changes_what_the_call_binds': ((10, 20), 30, 21, 3),
    'assignment_reads_back': (9,),
    'closes_over_a_mutable': (True, True),
    'deleting_clears_them': None,
    'keyword_only_defaults_are_not_here': None,
    'no_parameters_at_all': None,
    'one_default': (1,),
    'only_the_trailing_parameters': (5,),
    'parameters_but_no_defaults': None,
    'positional_and_keyword_only_together': (1,),
    'two_defaults': (1, 2),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-42s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
