# ``__builtins__'' -- the module-level name, and the function attribute.
#
# Grail had NEITHER.  A bare ``__builtins__'' raised
# ``NameError: name '__builtins__' is not defined'', and ``f.__builtins__''
# raised AttributeError, even though both names were already listed as
# read-only in the write guards -- so assignment was refused for an attribute
# that could not be read.  test_funcattrs.test___builtins__ died on its very
# first line.
#
# THE VALUE DEPENDS ON HOW THE MODULE IS RUN, which is why ``_as_namespace''
# below is not incidental.  CPython's import machinery writes ``__builtins__''
# into every module's globals, but the value is the builtins MODULE in
# ``__main__'' and the builtins module's DICT in an imported module.  This file
# is BOTH: the fixture gate runs it as __main__, and Smalltalk imports it under
# its own name.  So every check that reads the bare name states the invariant
# that holds in both roles rather than the one this run happens to be in --
# upstream's test___builtins__ opens by branching on __name__ for the same
# reason, and a first draft here that skipped the step read DIFF under the gate
# on three checks out of twelve.
#
# IDENTITY IS THE POINT, NOT EQUALITY.  Every check here is ``is''.  A copy of
# the builtins namespace would satisfy an == comparison and still be the wrong
# object: the attribute exists so that code can ask which builtins a function
# resolves its free names against, and a snapshot stops answering that the
# moment either side changes.  Upstream asserts it with assertIs throughout.
#
# NOT COVERED, and deliberately -- see the test.test_funcattrs entry in
# scripts/cpython_suite_skips.txt.  Upstream's test goes on to build a function
# with ``type(func)(func.__code__, ns)'' and call it.  Grail compiles Python to
# Smalltalk methods and keeps no bytecode, so a code object carries no
# instructions to re-enter, and a compiled method resolves its globals against
# the module it was compiled in rather than against a dict handed over later.
# Neither half of that constructor can be honoured, so it is skipped rather
# than faked.  What IS reachable is everything above it, which is what this
# file pins.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import builtins

# The one namespace every check below compares against.  Taken from the
# builtins MODULE rather than from the bare ``__builtins__'' name, so it is the
# same object whichever way this file is being run -- the bare name is what
# varies, and normalising it here would hide the very thing worth checking.
builtins_dict = builtins.__dict__


def _as_namespace(x):
    """The builtins NAMESPACE behind ``x``, whichever form ``x`` takes.

    ``__builtins__`` is the builtins module in __main__ and that module's dict
    in an imported module.  Every check that reads the bare name (or a
    function's globals, which holds whatever the name held) goes through this,
    so the check states the invariant that holds in BOTH roles instead of
    pinning the one this file happened to be run in.  An earlier draft compared
    the raw name and read DIFF under the fixture gate for that reason alone.
    """
    return x if isinstance(x, dict) else x.__dict__


r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except Exception as e:                      # noqa: BLE001 - the type IS the result
        r[k] = type(e).__name__


def module_level(s):
    return len(s)


def make_nested():
    def nested(s):
        return len(s)
    return nested


nested_fn = make_nested()
a_lambda = (lambda: 0)


class K:
    def meth(self):
        pass


# --- the module-level name resolves, and is the builtins namespace ----------
# The bare name is what Grail lacked outright: it raised NameError.  Both
# checks are identity against the real builtins namespace, so neither can be
# satisfied by a lookalike dict.
rec('bare_name_is_builtins_namespace',
    lambda: _as_namespace(__builtins__) is builtins_dict)
rec('globals_entry_is_bare_name',
    lambda: globals()['__builtins__'] is __builtins__)

# --- every flavour of callable reports the same object ----------------------
# Grail represents these with three different classes (BoundMethod for a
# module-level def, ExecBlock for a nested def and a lambda, and a bound method
# for K().meth), and the attribute had to be added to each.  One check per
# class, because a fix to one says nothing about the others.
rec('module_level_func', lambda: module_level.__builtins__ is builtins_dict)
rec('nested_func', lambda: nested_fn.__builtins__ is builtins_dict)
rec('lambda_func', lambda: a_lambda.__builtins__ is builtins_dict)
rec('unbound_method', lambda: K.meth.__builtins__ is builtins_dict)
rec('bound_method', lambda: K().meth.__builtins__ is builtins_dict)

# --- the function attribute agrees with the function's own globals ----------
rec('agrees_with_own_globals',
    lambda: module_level.__builtins__
    is _as_namespace(module_level.__globals__['__builtins__']))


# --- read-only in both directions -------------------------------------------
# A getter and no setter, so assignment AND deletion are AttributeError.
# Deletion needs naming separately: these are slot names rather than __dict__
# entries, so a ``del'' that found nothing could quietly succeed.
def _set(obj):
    def go():
        setattr(obj, '__builtins__', 2)
        return 'no raise'
    return go


def _del(obj):
    def go():
        delattr(obj, '__builtins__')
        return 'no raise'
    return go


rec('set_on_module_level', _set(module_level))
rec('del_on_module_level', _del(module_level))
rec('set_on_nested', _set(nested_fn))
rec('del_on_nested', _del(nested_fn))


EXPECTED = {
    'bare_name_is_builtins_namespace': True,
    'globals_entry_is_bare_name': True,
    'module_level_func': True,
    'nested_func': True,
    'lambda_func': True,
    'unbound_method': True,
    'bound_method': True,
    'agrees_with_own_globals': True,
    'set_on_module_level': 'AttributeError',
    'del_on_module_level': 'AttributeError',
    'set_on_nested': 'AttributeError',
    'del_on_nested': 'AttributeError',
}


if __name__ == '__main__':
    for _k in EXPECTED:
        print('%-32s %s %r' % (_k, 'OK ' if r[_k] == EXPECTED[_k] else 'DIFF', r[_k]))
