# Writing to function and method attributes.
#
# CPython guards these; Grail guarded NONE of them, and accepted every write
# below -- including the ones that leave the object incoherent:
#
#     f.__name__ = 7        put an integer where every traceback, repr and
#                           pickle expects a string
#     f.__code__ = 7        replaced the code object with a number
#     f.__closure__ = ()    discarded the cells the body reads
#     m.x = 1               vanished: methods have no attribute storage, so the
#                           value was written somewhere nothing reads back
#
# None of it raised.  The damage surfaced later, somewhere else, as a type error
# about a value nobody could trace to the assignment that produced it.
#
# THE TWO EXCEPTION TYPES ARE NOT INTERCHANGEABLE.  CPython uses AttributeError
# when the attribute has no setter at all (__closure__, __globals__,
# __builtins__) and TypeError when there IS a setter and the value was the wrong
# shape (__name__, __code__, __defaults__, __dict__).  Code branches on the
# difference, and test_funcattrs checks BOTH assignment and DELETION of every
# read-only name -- its cannot_set_attr helper fails unless each raises.
#
# A BOUND METHOD IS NOT A FUNCTION.  ``F.a'' is a plain function and takes
# attributes; ``F().a'' is a bound method and takes none.  Grail represents both
# with one class, so telling them apart is the substance of the fix rather than
# a detail of it -- a first attempt that rejected writes on both broke every
# ``f.attr = v'' in the corpus.
#
# NOT COVERED: a CLOSURE (a nested def or lambda) is an ExecBlock, a GemStone
# KERNEL class whose Grail extensions are filed into the shared extent by
# install_base.sh rather than per user.  Those keep the old permissive
# behaviour; only module-level and class-level functions are guarded here.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        fn()
        r[k] = 'no error'
    except BaseException as e:
        r[k] = type(e).__name__


class F:
    def a(self):
        pass


def b():
    return 3


f = F()


# --- read-only: AttributeError, both directions ------------------------------

rec('set_closure', lambda: setattr(b, '__closure__', ()))
rec('del_closure', lambda: delattr(b, '__closure__'))
rec('set_globals', lambda: setattr(b, '__globals__', 2))
rec('del_globals', lambda: delattr(b, '__globals__'))


# --- type-checked: TypeError -------------------------------------------------

rec('name_to_int', lambda: setattr(b, '__name__', 7))
rec('qualname_to_int', lambda: setattr(b, '__qualname__', 7))
rec('dict_to_none', lambda: setattr(b, '__dict__', None))
rec('code_to_int', lambda: setattr(b, '__code__', 7))
rec('defaults_to_int', lambda: setattr(b, '__defaults__', 7))
# A function's layout is fixed, so __class__ assignment is refused outright.
rec('class_on_function', lambda: setattr(b, '__class__', F))


# --- a BOUND method has no attribute storage at all --------------------------

rec('method_custom_attr', lambda: setattr(f.a, 'known_attr', 7))
rec('method_self', lambda: setattr(f.a, '__self__', f))
rec('method_func', lambda: setattr(f.a, '__func__', b))
rec('method_del_self', lambda: delattr(f.a, '__self__'))


# --- what must KEEP working --------------------------------------------------
#
# These are the guard against over-applying the rule: every one of them is a
# legal write that a blanket rejection would break, and a function carrying
# attributes is how functools.wraps, dataclasses and every decorator work.

rec('name_to_str', lambda: setattr(b, '__name__', 'renamed'))
rec('custom_attr_on_function', lambda: setattr(b, 'known_attr', 7))
rec('doc', lambda: setattr(b, '__doc__', 'hi'))
rec('defaults_to_tuple', lambda: setattr(b, '__defaults__', (1,)))
# ...and the UNBOUND form is a plain function, so it takes attributes too.
rec('custom_attr_on_unbound', lambda: setattr(F.a, 'known_attr', 7))

# The writes that succeeded must have actually LANDED -- ``no error'' only says
# nothing raised, which a guard that silently dropped the write would also say.
def val(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = type(e).__name__


val('name_took', lambda: b.__name__)
val('custom_attr_took', lambda: b.known_attr)
val('defaults_took', lambda: b.__defaults__)

# LAST, and deliberately so: assigning a fresh __dict__ REPLACES the function's
# attribute storage, so it wipes ``known_attr''.  Ordering it before the reads
# above made the fixture assert that side effect by accident -- and Grail and
# CPython differ on it, which is a separate question from whether the write is
# allowed.  Only the allowed/refused answer belongs here.
rec('dict_to_dict', lambda: setattr(b, '__dict__', {'z': 1}))


EXPECTED = {
    'class_on_function': 'TypeError',
    'code_to_int': 'TypeError',
    'custom_attr_on_function': 'no error',
    'custom_attr_on_unbound': 'no error',
    'custom_attr_took': 7,
    'defaults_to_int': 'TypeError',
    'defaults_to_tuple': 'no error',
    'defaults_took': (1,),
    'del_closure': 'AttributeError',
    'del_globals': 'AttributeError',
    'dict_to_dict': 'no error',
    'dict_to_none': 'TypeError',
    'doc': 'no error',
    'method_custom_attr': 'AttributeError',
    'method_del_self': 'AttributeError',
    'method_func': 'AttributeError',
    'method_self': 'AttributeError',
    'name_to_int': 'TypeError',
    'name_to_str': 'no error',
    'name_took': 'renamed',
    'qualname_to_int': 'TypeError',
    'set_closure': 'AttributeError',
    'set_globals': 'AttributeError',
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
