# A function's ``__dict__'' and ``__doc__'' -- the two attributes that are
# mappings-or-strings rather than plain values, and the ones whose WRITE and
# DELETE paths have rules of their own.
#
# Grail got the reads right and the writes wrong, mostly in silence:
#
# 1. ``f.__dict__ = d'' DID NOTHING VISIBLE.  ``__dict__'' is a slot name, so the
#    assignment was routed into the slot table -- a namespace the ``__dict__''
#    reader never consults, since it answers the attribute table directly.  The
#    write succeeded, raised nothing, and changed nothing: reading ``f.__dict__''
#    afterwards showed the assigned dict NESTED under a '__dict__' key, and
#    ``f.known_attr'' was still an AttributeError.
#
# 2. NO TYPE CHECK came with it, so ``f.__dict__ = None'' was accepted just as
#    quietly, leaving a function whose __dict__ could not be read back as a
#    mapping.
#
# 3. ``del f.__dict__'' answered AttributeError where CPython answers TypeError.
#    The distinction matters: the attribute EXISTS and is writable, so what is
#    refused is the deletion -- an AttributeError reads as though functions have
#    no __dict__ at all.
#
# 4. ``del f.__doc__'' answered ``AttributeError: __doc__''.  CPython RESETS the
#    docstring to None rather than removing anything, which is why every function
#    still has a __doc__ afterwards.
#
# The assignment is by IDENTITY, not by merge: CPython leaves ``f.__dict__ is d''
# true, so later mutations of d show through f.  That is what makes the
# distinction in (1) observable rather than academic.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

from collections import UserDict

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def make():
    """A nested def, which is the shape test_funcattrs uses for self.b."""
    def b():
        return 3
    return b


# --- __dict__ starts empty and collects user attributes ---------------------

rec('dict_initially_empty', lambda: make().__dict__)


def _setattr_shows_up():
    f = make()
    f.known_attr = 7
    return f.__dict__


rec('setattr_in_dict', _setattr_shows_up)


# --- assigning __dict__ REPLACES it, by identity ----------------------------

def _assign_dict():
    f = make()
    d = {'known_attr': 7}
    f.__dict__ = d
    return (f.__dict__ is d, f.known_attr, f.__dict__['known_attr'])


def _assignment_is_live():
    """Identity, not a copy: mutating d afterwards must show through f."""
    f = make()
    d = {}
    f.__dict__ = d
    d['later'] = 5
    return (f.later, f.__dict__ is d)


rec('assign_dict', _assign_dict)
rec('assignment_is_live', _assignment_is_live)


# --- and is type-checked ----------------------------------------------------

def _assign_none():
    make().__dict__ = None


def _assign_int():
    make().__dict__ = 7


def _assign_userdict():
    """A MAPPING that is not a dict is still refused -- CPython wants the real
    type, and names the offending one in the message."""
    make().__dict__ = UserDict({'known_attr': 7})


rec('assign_none', _assign_none)
rec('assign_int', _assign_int)
rec('assign_userdict', _assign_userdict)


# --- __dict__ cannot be deleted ---------------------------------------------

def _delete_dict():
    del make().__dict__


rec('delete_dict', _delete_dict)


# --- __doc__ ----------------------------------------------------------------

rec('doc_initially_none', lambda: make().__doc__)


def _set_doc():
    f = make()
    f.__doc__ = 'A test method that does nothing'
    return f.__doc__


def _delete_doc():
    """Deleting a docstring RESETS it to None; it does not remove an attribute."""
    f = make()
    f.__doc__ = 'The docstring'
    del f.__doc__
    return f.__doc__


def _delete_doc_twice():
    f = make()
    del f.__doc__
    del f.__doc__
    return f.__doc__


rec('set_doc', _set_doc)
rec('delete_doc', _delete_doc)
rec('delete_doc_twice', _delete_doc_twice)


# --- the docstring of a def that HAS one ------------------------------------

def _literal_docstring():
    def g():
        """documented"""
        return 1
    return g.__doc__


rec('literal_docstring', _literal_docstring)


EXPECTED = {
    'assign_dict': (True, 7, 7),
    'assign_int': "TypeError: __dict__ must be set to a dictionary, not a 'int'",
    'assign_none': "TypeError: __dict__ must be set to a dictionary, not a 'NoneType'",
    'assign_userdict': "TypeError: __dict__ must be set to a dictionary, not a 'UserDict'",
    'assignment_is_live': (5, True),
    'delete_dict': 'TypeError: cannot delete __dict__',
    'delete_doc': None,
    'delete_doc_twice': None,
    'dict_initially_empty': {},
    'doc_initially_none': None,
    'literal_docstring': 'documented',
    'set_doc': 'A test method that does nothing',
    'setattr_in_dict': {'known_attr': 7},
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-24s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
