# What a debugger sees while a generator is running.
#
# ``inspect.stack()'' is how a debugger, a logging filter, or a test asks "who
# is calling me".  Grail answered ``[]'' -- not a wrong stack, no stack at all --
# so every such caller silently took its "I cannot tell" branch.
#
# The interesting half is the GENERATOR.  Grail runs a generator body on its own
# forked GsProcess, so the body's stack ends at the fork and contains nothing of
# the consumer driving it: a walk from inside ``gen'' saw ``gen'' itself and
# stopped, where CPython -- which has one stack for all of it -- sees the
# delegating generators and the caller underneath them.  ``yield from'' makes
# that visible, because a delegating generator is supposed to be TRANSPARENT in
# every other respect, and a debugger that cannot see ``spam'' cannot tell you
# which delegation you are in.  That is test_yield_from's
# test_delegator_is_visible_to_debugger, and it is checked here at three depths.
#
# WHY THE PREFIXES AND NOT THE WHOLE LIST: a module BODY is not a frame in Grail
# (module-level ``sys._getframe(0)'' reports the stack is not deep enough), so
# Grail's stack ends one entry earlier than CPython's '<module>'.  Comparing a
# prefix compares everything this fixture is about and nothing it is not.  The
# same fixture run under CPython therefore has to pass, which is the gate.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import inspect

r = {}


def call_stack():
    return [f[3] for f in inspect.stack()]


def gen():
    yield call_stack()
    yield call_stack()


def spam(g):
    yield from g


def eggs(g):
    yield from g


def drive():
    """Every measurement is taken from inside a function, never at module
    level, so the '<module>' frame CPython has and Grail does not never
    reaches a comparison."""
    out = {}

    # No delegation: the generator's OWN frame, which Grail also lacked --
    # the body is a block and the ``def'' that built it already returned.
    out['plain'] = next(gen())[:3]

    # One delegation.
    out['one'] = next(spam(gen()))[:4]

    # Two, nested: order matters, not just membership.
    out['two'] = next(spam(eggs(gen())))[:5]

    # A RESUMED generator, not just a freshly started one.  The link to the
    # consumer is re-read on every resume, so a version that recorded it once
    # at start-up passes the tests above and fails this one.
    g = spam(gen())
    next(g)
    out['resumed'] = next(g)[:4]

    # A generator driven from a NESTED function: the caller's own frame is a
    # nested def, resolved by a different rule than a module-level one.
    def inner_driver():
        return next(spam(gen()))[:5]

    out['nested_caller'] = inner_driver()

    # A plain call chain, for contrast: no generator, no process boundary.
    out['no_generator'] = call_stack()[:2]
    return out


_m = drive()
r.update(_m)

# Order, stated as an invariant rather than as a list, so it holds however deep
# the enclosing runner's stack happens to be.
_two = r['two']
r['gen_inside_eggs'] = _two.index('gen') < _two.index('eggs')
r['eggs_inside_spam'] = _two.index('eggs') < _two.index('spam')
r['no_duplicate_frames'] = len(set(_two)) == len(_two)

# currentframe() names its CALLER, and is not None -- it used to be a hardcoded
# None, which reads as "no frame" rather than "unsupported".
def _who():
    f = inspect.currentframe()
    return None if f is None else f.f_code.co_name


r['currentframe_names_caller'] = _who()

# A FrameInfo is indexable and unpackable, because callers destructure it.
_fi = drive.__class__ and inspect.stack()
r['stack_is_list'] = isinstance(_fi, list)


EXPECTED = {
    'currentframe_names_caller': '_who',
    'eggs_inside_spam': True,
    'gen_inside_eggs': True,
    'nested_caller': ['call_stack', 'gen', 'spam', 'inner_driver', 'drive'],
    'no_duplicate_frames': True,
    'no_generator': ['call_stack', 'drive'],
    'one': ['call_stack', 'gen', 'spam', 'drive'],
    'plain': ['call_stack', 'gen', 'drive'],
    'resumed': ['call_stack', 'gen', 'spam', 'drive'],
    'stack_is_list': True,
    'two': ['call_stack', 'gen', 'eggs', 'spam', 'drive'],
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
