# An exception raised where there is nowhere to raise it TO.
#
# ``gen.close()`` on a generator suspended in ``yield from`` has to shut the
# SUB-iterator down first, which means looking up its ``close`` attribute.  PEP
# 380 says a missing one is skipped.  It does not say what happens when the
# lookup itself FAILS -- an object whose __getattr__ raises -- and that case has
# no good answer available to it:
#
#   * it cannot propagate.  A GeneratorExit is already unwinding the delegating
#     generator and has to carry on out, or ``close()'' stops answering None and
#     starts raising.
#   * it cannot be dropped.  That is what Grail used to do, and the failure was
#     then unobservable by any means at all.
#
# CPython's answer is sys.unraisablehook: report it out of band.  The default
# hook prints to stderr; a test installs its own and inspects what arrived.
# That is the whole of what test.support.catch_unraisable_exception does, and
# it is why test_yield_from's test_broken_getattr_handling used to score an
# ERROR here -- cm.unraisable stayed None, so reading .exc_type off it raised
# AttributeError.
#
# THE TWO WAYS CPython FILLS THE HOOK ARGUMENT ARE NOT INTERCHANGEABLE.
# PyErr_WriteUnraisable sets ``object'' and leaves ``err_msg'' None;
# PyErr_FormatUnraisable does the reverse, putting the object's repr INSIDE the
# message.  3.14 uses the format variant here, so a hook that prints
# ``args.object'' prints None and the identity is in ``err_msg''.  Getting that
# backwards looks right until someone reads the report.
#
# NOT COVERED: every other CPython caller of the hook is a FINALIZER -- __del__,
# GC, buffered-file close -- and Grail has no finalizer machinery, so this is
# the one path that reaches it.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import sys

r = {}

MOD = __name__


def _norm(s):
    """Strip the two things that legitimately differ between runs: the module
    name (this file is loaded as '__main__' by the fixture gate and under its
    own name by the SUnit peer) and the object's address."""
    if s is None:
        return None
    s = s.replace(MOD + '.', '<mod>.')
    i = s.find(' at 0x')
    if i != -1:
        j = s.find('>', i)
        s = s[:i] + ' at 0xX' + s[j:]
    return s


class Broken:
    """A sub-iterator whose every attribute lookup raises."""

    def __iter__(self):
        return self

    def __next__(self):
        return 1

    def __getattr__(self, attr):
        1 / 0


class Fine:
    """The control: a sub-iterator with no close at all, which is skipped."""

    def __iter__(self):
        return self

    def __next__(self):
        return 2


def delegating(sub):
    yield from sub


# --- the hook is installed by assignment, and really is called --------------

caught = []
old = sys.unraisablehook
sys.unraisablehook = caught.append
try:
    gi = delegating(Broken())
    r['first_value'] = next(gi)
    # close() must still answer None: the reporting is out of band, and the
    # GeneratorExit it injected is absorbed exactly as it always was.
    r['close_returns'] = gi.close()
    r['hook_calls'] = len(caught)

    # ...and the control case must NOT call the hook.  Without this, a hook
    # that fired on every delegated close would look identical above.
    before = len(caught)
    gj = delegating(Fine())
    r['fine_value'] = next(gj)
    r['fine_close_returns'] = gj.close()
    r['fine_hook_calls'] = len(caught) - before
finally:
    sys.unraisablehook = old

# The hook is restorable, which is what makes it usable from a context manager.
r['hook_restored'] = sys.unraisablehook is old


# --- what arrived ------------------------------------------------------------

u = caught[0] if caught else None
r['exc_type_is_zero_division'] = u is not None and u.exc_type is ZeroDivisionError
r['exc_value_is_instance'] = u is not None and isinstance(u.exc_value, ZeroDivisionError)
r['exc_value_message'] = str(u.exc_value) if u is not None else None
# The object goes in the MESSAGE for this caller, so ``object'' is None and
# err_msg names both what happened and to what.
r['object_is_none'] = u is not None and u.object is None
r['err_msg'] = _norm(u.err_msg) if u is not None else None
# Every field is readable, including the ones that are None: an ABSENT
# attribute would raise where CPython answers None.
r['has_all_fields'] = u is not None and all(
    hasattr(u, n) for n in
    ('exc_type', 'exc_value', 'exc_traceback', 'err_msg', 'object'))


# --- the delegating generator is left properly closed ------------------------

r['closed_is_exhausted'] = False
try:
    next(gi)
except StopIteration:
    r['closed_is_exhausted'] = True


EXPECTED = {
    'close_returns': None,
    'closed_is_exhausted': True,
    'err_msg': 'Exception ignored while closing generator <<mod>.Broken object at 0xX>',
    'exc_type_is_zero_division': True,
    'exc_value_is_instance': True,
    'exc_value_message': 'division by zero',
    'fine_close_returns': None,
    'fine_hook_calls': 0,
    'fine_value': 2,
    'first_value': 1,
    'has_all_fields': True,
    'hook_calls': 1,
    'hook_restored': True,
    'object_is_none': True,
}

if __name__ == '__main__':
    import sys as _s
    if '--emit' in _s.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
