"""A runtime shadow of a builtin in a module's globals -- CPython's LOAD_GLOBAL.

``LOAD_GLOBAL`` reads the module's OWN globals first and only then builtins, so
writing ``globals()['len'] = f`` at run time shadows the builtin for every
function in that module -- including functions COMPILED BEFORE the write.

Grail classified a bare name at COMPILE time: a name the module never assigned
statically became a direct send to the builtins singleton, so the write landed
in the namespace (``'len' in globals()`` answered True) and nothing ever
consulted it.  That was test_dynamic's test_globals_shadow_builtins.

THE THREE OVERRIDE ROUTES ARE DIFFERENT MECHANISMS and all three are checked
here, because only the middle one was broken:
  * a STATIC module-level ``len = ...``  -- compile-time, always worked;
  * a RUNTIME ``globals()['len'] = ...`` -- this fixture's subject;
  * ``builtins.len = ...``               -- handled by ___syncBuiltinOverride___:,
    which recompiles the builtins class's selector surface, and which cannot
    serve the globals case because the shadow belongs to ONE module while the
    builtins singleton is shared by every module.

EXPECTED was generated by RUNNING CPython 3.14.6.
"""

import builtins

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except Exception as e:                      # noqa: BLE001 - the type IS the result
        r[k] = type(e).__name__


def uses_len():
    return len([1, 2, 3])


def uses_sorted():
    # the varargs/kwargs emit path, not the fixed-arity one
    return sorted([3, 1, 2], reverse=True)


# --- baseline ---------------------------------------------------------------
rec('baseline_len', uses_len)
rec('baseline_sorted', uses_sorted)

# --- a runtime globals shadow is seen by an ALREADY-COMPILED function --------
globals()['len'] = lambda x: 7
rec('shadowed_len', uses_len)
rec('shadow_is_in_globals', lambda: 'len' in globals())
# module-local: the builtin itself is untouched, so other modules are unaffected
rec('builtin_len_unaffected', lambda: builtins.len([1, 2, 3]))
del globals()['len']
rec('after_del_len', uses_len)

# --- the same, on the kwargs (varargs) emit path -----------------------------
globals()['sorted'] = lambda x, reverse=False: 'shadowed'
rec('shadowed_sorted', uses_sorted)
del globals()['sorted']
rec('after_del_sorted', uses_sorted)

# --- a builtins rebinding still works (the mechanism that already existed) ---
_real = builtins.len
builtins.len = lambda x: 4
rec('builtins_patched_len', uses_len)
builtins.len = _real
rec('after_restore_len', uses_len)


# --- a LOCAL of the same name still wins over both ---------------------------
def local_wins():
    len = lambda x: 99                          # noqa: E731 - the shadowing IS the test
    return len([1, 2, 3])


rec('local_shadow', local_wins)


EXPECTED = {
    'baseline_len': 3,
    'baseline_sorted': [3, 2, 1],
    'shadowed_len': 7,
    'shadow_is_in_globals': True,
    'builtin_len_unaffected': 3,
    'after_del_len': 3,
    'shadowed_sorted': 'shadowed',
    'after_del_sorted': [3, 2, 1],
    'builtins_patched_len': 4,
    'after_restore_len': 3,
    'local_shadow': 99,
}


if __name__ == '__main__':
    for _k in EXPECTED:
        print('%-26s %s %r' % (_k, 'OK ' if r[_k] == EXPECTED[_k] else 'DIFF', r[_k]))
