# ``global x'' is a SyntaxError when x is already a parameter of, bound in, or
# read in the SAME function scope.  CPython rejects all four at compile time in
# symtable.c, each with its own message; Grail accepted every one silently, so
# code CPython refuses to compile ran here with the name quietly meaning
# something other than what it says.
#
# The risk in this check is FALSE POSITIVES, not false negatives: a scope test
# that is too eager rejects working modules at import time.  So the legal forms
# below matter more than the illegal ones --
#
#   * ``global'' at MODULE level is legal and a no-op,
#   * a CLASS body may declare it (Grail already relies on this: it rebinds the
#     module's name and leaves the class without the attribute),
#   * declaring BEFORE any use is the normal, correct spelling,
#   * and an inner function has its own scope, so an outer binding of the same
#     name does not poison it.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def check(src):
    """Compile src, reporting the SyntaxError message or 'ok'."""
    try:
        compile(src, '<test string>', 'exec')
        return 'ok'
    except SyntaxError as e:
        return 'SyntaxError: ' + str(e.msg)
    except BaseException as e:
        return type(e).__name__ + ': ' + str(e)[:60]


# --- the four rejections ----------------------------------------------------

r['parameter'] = check(
    "def fn(name_param):\n"
    "    global name_param\n")

r['assigned_before'] = check(
    "def fn():\n"
    "    name_assign = 1\n"
    "    global name_assign\n")

r['used_before'] = check(
    "def fn():\n"
    "    print(name_use)\n"
    "    global name_use\n")

# An annotation without a value BINDS NOTHING, so it never reaches the write
# set -- yet it still makes a later ``global'' an error, with its own wording.
# That is why annotated names need tracking separate from writes.
r['annotated_before'] = check(
    "def fn():\n"
    "    name_annot: int\n"
    "    global name_annot\n")

# --- the legal forms that must keep compiling -------------------------------

r['module_level'] = check(
    "global mod_ok\n"
    "mod_ok = 1\n")

r['class_body'] = check(
    "x = 1\n"
    "class C:\n"
    "    global x\n"
    "    x = 2\n")

r['declared_first'] = check(
    "def fn():\n"
    "    global ok1\n"
    "    ok1 = 1\n"
    "    return ok1\n")

r['declared_first_then_read'] = check(
    "def fn():\n"
    "    global ok2\n"
    "    print(ok2)\n")

# A binding in the OUTER function must not make the INNER declaration illegal:
# the check is per-scope, and reusing the enclosing scope's sets would reject
# this.
r['inner_scope_is_separate'] = check(
    "def outer():\n"
    "    shared = 1\n"
    "    def inner():\n"
    "        global shared\n"
    "        shared = 2\n"
    "    return inner\n")

# Same name declared global in two sibling scopes.
r['sibling_scopes'] = check(
    "def a():\n"
    "    global s\n"
    "    s = 1\n"
    "def b():\n"
    "    global s\n"
    "    s = 2\n")

# A parameter of the OUTER function, declared global in the inner one.
r['outer_param_inner_global'] = check(
    "def outer(p):\n"
    "    def inner():\n"
    "        global p\n"
    "        p = 1\n"
    "    return inner\n")

# Multiple names in one statement: the first legal, the second illegal.
r['multiple_names'] = check(
    "def fn():\n"
    "    b = 1\n"
    "    global a, b\n")

# A comprehension target is scoped to the comprehension, not the function, so
# it must not count as a binding of the enclosing scope.
r['comprehension_target'] = check(
    "def fn():\n"
    "    [c for c in range(3)]\n"
    "    global c\n")

# A read inside a NESTED def belongs to that def's scope, not this one.  This
# is the false positive the CPython corpus caught: test_builtin declares
# ``global all, any, tuple'' after several nested defs that CALL all/any/tuple,
# and rejecting it made the whole module fail to import.  Grail propagates free
# names OUT of a nested scope into the enclosing read set (for closures and
# locals()), so the enclosing read set is transitive and cannot answer this.
r['nested_def_read'] = check(
    "def fn():\n"
    "    def inner():\n"
    "        return all([1])\n"
    "    global all\n"
    "    all = lambda x: 'all'\n")

# ...and the same through a genexp inside the nested def, which is the exact
# shape test_builtin uses.
r['nested_def_genexp_read'] = check(
    "def fn():\n"
    "    def inner():\n"
    "        return all(x for x in [1])\n"
    "    global all\n"
    "    all = lambda x: 'all'\n")


EXPECTED = {
    'annotated_before': "SyntaxError: annotated name 'name_annot' can't be global",
    'assigned_before': "SyntaxError: name 'name_assign' is assigned to before global declaration",
    'class_body': 'ok',
    'comprehension_target': 'ok',
    'declared_first': 'ok',
    'declared_first_then_read': 'ok',
    'inner_scope_is_separate': 'ok',
    'module_level': 'ok',
    'multiple_names': "SyntaxError: name 'b' is assigned to before global declaration",
    'nested_def_genexp_read': 'ok',
    'nested_def_read': 'ok',
    'outer_param_inner_global': 'ok',
    'parameter': "SyntaxError: name 'name_param' is parameter and global",
    'sibling_scopes': 'ok',
    'used_before': "SyntaxError: name 'name_use' is used prior to global declaration",
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %s' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
