# A METHOD DELEGATES TO ITS FUNCTION.
#
# CPython has two objects here and Grail has two objects here, but Grail had
# them wired as one.  ``F.a`` is the FUNCTION -- writable, with a ``__dict__``,
# the thing a decorator tags.  ``fi.a`` is a bound METHOD -- no storage of its
# own, and every attribute it reports it reports by asking the function.
#
# Grail's bound method answered ``self`` for ``__func__``, so the method WAS its
# own function.  Every rule that distinguishes the two then collapsed in the
# same direction: an attribute set on the function was invisible through any
# instance, ``m.__dict__`` was a flat AttributeError, ``m.__doc__`` ignored an
# assigned docstring, and ``fi.a.__func__.__dict__ = d`` raised from the METHOD
# (which correctly has no __dict__) instead of writing to the function.
#
# The two ends of that are one idiom -- a decorator tags the function, an
# instance reads the tag -- and they disagreed.  Nothing raised at the point of
# the write, so the loss surfaced later as a missing attribute.
#
# The other half is that a FUNCTION's ``__dict__`` can be REPLACED, and CPython
# installs the caller's own mapping: ``f.__dict__ = d`` then ``f.__dict__ is d``.
# Grail stored a dynamic slot that happened to be spelled ``__dict__`` and left
# the real attribute storage untouched, so the mapping was never consulted again.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def fresh():
    class F:
        def a(self):
            pass
    return F, F()


# --- __func__ is the function, not the method -------------------------------

def _func_is_the_class_handle():
    F, fi = fresh()
    return fi.a.__func__ is F.a


def _self_is_the_receiver():
    F, fi = fresh()
    return fi.a.__self__ is fi


# --- reads delegate ---------------------------------------------------------

def _doc_assigned_on_the_function():
    F, fi = fresh()
    F.a.__doc__ = 'A test method that does nothing'
    return fi.a.__doc__


def _doc_absent_is_none():
    F, fi = fresh()
    return fi.a.__doc__


def _attr_set_on_the_function():
    F, fi = fresh()
    F.a.known_attr = 7
    return fi.a.known_attr


def _attr_never_set():
    # The exception TYPE only.  CPython reports the miss against the FUNCTION
    # (``'function' object has no attribute ...'') because that is where the
    # lookup ended, and Grail agrees on the object but spells its type name
    # ``UnboundMethod''.  That naming is a separate, pre-existing difference --
    # ``type(F.a).__name__`` is ``UnboundMethod`` in Grail throughout -- and is
    # not what this fixture is about; asserting the message here would pin it.
    F, fi = fresh()
    try:
        fi.a.no_such_attr
    except BaseException as e:
        return type(e).__name__
    return 'accepted'


def _dict_is_the_functions_dict():
    F, fi = fresh()
    return fi.a.__dict__ is F.a.__dict__


def _dict_sees_a_later_write():
    F, fi = fresh()
    F.a.tagged = 'yes'
    return fi.a.__dict__['tagged']


def _dir_of_the_method_lists_it():
    F, fi = fresh()
    F.a.known_attr = 7
    return 'known_attr' in dir(fi.a)


# --- writes on the METHOD do not happen -------------------------------------

def _set_arbitrary_on_method():
    F, fi = fresh()
    fi.a.known_attr = 7
    return 'accepted'


def _del_arbitrary_on_method():
    F, fi = fresh()
    F.a.known_attr = 7
    del fi.a.known_attr
    return 'accepted'


def _set_doc_on_method():
    F, fi = fresh()
    fi.a.__doc__ = 'nope'
    return 'accepted'


def _set_class_on_method():
    F, fi = fresh()
    setattr(fi.a, '__class__', F)
    return 'accepted'


def _del_class_on_method():
    F, fi = fresh()
    delattr(fi.a, '__class__')
    return 'accepted'


# --- replacing a FUNCTION's __dict__ ----------------------------------------

def _replace_installs_that_mapping():
    F, fi = fresh()
    d = {'known_attr': 7}
    F.a.__dict__ = d
    return F.a.__dict__ is d


def _replace_is_visible_from_the_method():
    F, fi = fresh()
    d = {'known_attr': 7}
    F.a.__dict__ = d
    return fi.a.__dict__ is d


def _read_goes_through_the_replacement():
    F, fi = fresh()
    F.a.__dict__ = {'known_attr': 7}
    return (F.a.known_attr, fi.a.known_attr)


def _write_goes_through_the_replacement():
    F, fi = fresh()
    d = {}
    F.a.__dict__ = d
    F.a.later = 'set'
    return d['later']


def _delete_goes_through_the_replacement():
    F, fi = fresh()
    d = {'gone': 1}
    F.a.__dict__ = d
    del F.a.gone
    return 'gone' in d


def _replace_with_a_non_dict():
    F, fi = fresh()

    class NotADict(dict.__class__ if False else object):
        pass
    F.a.__dict__ = NotADict()
    return 'accepted'


def _delete_the_dict():
    F, fi = fresh()
    del F.a.__dict__
    return 'accepted'


def _rename_the_function_to_an_int():
    F, fi = fresh()
    F.a.__name__ = 7
    return 'accepted'


rec('func_is_the_class_handle', _func_is_the_class_handle)
rec('self_is_the_receiver', _self_is_the_receiver)
rec('doc_assigned_on_the_function', _doc_assigned_on_the_function)
rec('doc_absent_is_none', _doc_absent_is_none)
rec('attr_set_on_the_function', _attr_set_on_the_function)
rec('attr_never_set', _attr_never_set)
rec('dict_is_the_functions_dict', _dict_is_the_functions_dict)
rec('dict_sees_a_later_write', _dict_sees_a_later_write)
rec('dir_of_the_method_lists_it', _dir_of_the_method_lists_it)
rec('set_arbitrary_on_method', _set_arbitrary_on_method)
rec('del_arbitrary_on_method', _del_arbitrary_on_method)
rec('set_doc_on_method', _set_doc_on_method)
rec('set_class_on_method', _set_class_on_method)
rec('del_class_on_method', _del_class_on_method)
rec('replace_installs_that_mapping', _replace_installs_that_mapping)
rec('replace_is_visible_from_the_method', _replace_is_visible_from_the_method)
rec('read_goes_through_the_replacement', _read_goes_through_the_replacement)
rec('write_goes_through_the_replacement', _write_goes_through_the_replacement)
rec('delete_goes_through_the_replacement', _delete_goes_through_the_replacement)
rec('replace_with_a_non_dict', _replace_with_a_non_dict)
rec('delete_the_dict', _delete_the_dict)
rec('rename_the_function_to_an_int', _rename_the_function_to_an_int)


EXPECTED = {
    'attr_never_set': 'AttributeError',
    'attr_set_on_the_function': 7,
    'del_arbitrary_on_method': "AttributeError: 'method' object has no attribute 'known_attr' and no __dict__ for setting new attributes",
    'del_class_on_method': "TypeError: can't delete __class__ attribute",
    'delete_goes_through_the_replacement': False,
    'delete_the_dict': 'TypeError: cannot delete __dict__',
    'dict_is_the_functions_dict': True,
    'dict_sees_a_later_write': 'yes',
    'dir_of_the_method_lists_it': True,
    'doc_absent_is_none': None,
    'doc_assigned_on_the_function': 'A test method that does nothing',
    'func_is_the_class_handle': True,
    'read_goes_through_the_replacement': (7, 7),
    'rename_the_function_to_an_int': 'TypeError: __name__ must be set to a string object',
    'replace_installs_that_mapping': True,
    'replace_is_visible_from_the_method': True,
    'replace_with_a_non_dict': "TypeError: __dict__ must be set to a dictionary, not a 'NotADict'",
    'self_is_the_receiver': True,
    'set_arbitrary_on_method': "AttributeError: 'method' object has no attribute 'known_attr' and no __dict__ for setting new attributes",
    'set_class_on_method': 'TypeError: __class__ assignment only supported for mutable types or ModuleType subclasses',
    'set_doc_on_method': "AttributeError: attribute '__doc__' of 'method' objects is not writable",
    'write_goes_through_the_replacement': 'set',
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-38s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
