"""Module ``__doc__`` -- the module's own docstring, never Object's.

This docstring is itself the fixture: the first check below reads it back.

THE BUG THIS PINS was not a missing attribute but a WRONG ANSWER, which is why
it survived so long.  ``module >> __doc__`` ended in ``^ super __doc__``, which
climbs the Smalltalk superclass chain to Object, so EVERY module in the corpus
reported

    'The base class of the class hierarchy.\\n\\nWhen called, it accepts no ...'

as its docstring -- including modules whose real docstring was sitting unread in
the source file.  Nothing raised, and the value was a plausible non-empty
string, so no read-based smoke test would notice.  Two causes, both needed
fixing: the compiler never extracted a module-level docstring at all (ModuleAst
had no ``___docString___``, unlike ClassDefAst and FunctionDefAst), and the
accessor inherited one when the namespace had none.

NONE IS A REAL ANSWER.  A module with no docstring HAS ``__doc__`` and its value
is None -- distinct from not having the attribute, and distinct from inheriting
somebody else's.  Grail reaches None for three separate reasons, all correct:
the source opens with a ``#`` comment rather than a string (Grail's own
``types.py`` and ``operator.py``), or the module is implemented in Smalltalk and
has no Python source to read (``json``, ``string``), or it genuinely has none
(``enum``, in CPython too).

EXPECTED was generated by RUNNING CPython 3.14.6.
"""

import textwrap

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except Exception as e:                      # noqa: BLE001 - the type IS the result
        r[k] = type(e).__name__


def _has(ns, name):
    # Grail's module namespaces are keyed by Symbol, so compare as strings.
    return name in set(str(k) for k in ns)


# --- this module reads back its own docstring -------------------------------
rec('own_doc_is_a_string', lambda: isinstance(__doc__, str))
rec('own_doc_first_line',
    lambda: __doc__.splitlines()[0] if isinstance(__doc__, str) else None)
rec('own_doc_in_namespace', lambda: _has(globals(), '__doc__'))

# --- THE REGRESSION: a module must never report Object's docstring ----------
# Stated as a property rather than against a literal, so it keeps working if
# GemStone's Object docstring is ever reworded.  ``object.__doc__`` is the exact
# string every module used to answer.
rec('own_doc_is_not_objects', lambda: __doc__ != object.__doc__)
rec('imported_doc_is_not_objects', lambda: textwrap.__doc__ != object.__doc__)

# --- an imported module reports ITS docstring, by value ---------------------
# textwrap is a .py module in both CPython's stdlib and Grail's, with the same
# one-line docstring, so this compares a real value rather than a shape.
rec('imported_doc_value', lambda: textwrap.__doc__)
rec('imported_doc_in_namespace', lambda: _has(vars(textwrap), '__doc__'))


# --- a module with no docstring answers None --------------------------------
# Not absent, and not inherited.  enum has no module docstring in CPython, and
# Grail's enum.py has none either, so this is a genuine agreement rather than a
# coincidence of ports.
def _enum_doc():
    import enum
    return enum.__doc__


rec('no_docstring_is_none', lambda: _enum_doc() is None)


EXPECTED = {
    'own_doc_is_a_string': True,
    'own_doc_first_line': "Module ``__doc__`` -- the module's own docstring, never Object's.",
    'own_doc_in_namespace': True,
    'own_doc_is_not_objects': True,
    'imported_doc_is_not_objects': True,
    'imported_doc_value': 'Text wrapping and filling.\n',
    'imported_doc_in_namespace': True,
    'no_docstring_is_none': True,
}


if __name__ == '__main__':
    for _k in EXPECTED:
        print('%-28s %s %r' % (_k, 'OK ' if r[_k] == EXPECTED[_k] else 'DIFF', r[_k]))
