"""PEP 451 ``__spec__`` -- the canonical record the other attributes derive from.

Before this, ``mod.__spec__`` was None on EVERY module in Grail, and the four
module-creation paths each wrote ``__name__``, ``__package__``, ``__file__``,
``__loader__`` and ``__path__`` independently. Now one ModuleSpec is built per
module and ``importlib class >> ___initModuleAttrsFrom___:on:`` -- CPython's
``_init_module_attrs`` -- derives the rest from it.

WHY THE DERIVATION MATTERS, rather than just having a spec: CPython treats a
mirror that disagrees with its spec as a bug, and warns about it
(``__package__ != __spec__.parent`` is a DeprecationWarning in 3.14). The
consistency checks below are that invariant, and they are the point of the
change; a spec that merely existed alongside independently-written attributes
would pass a "is it not None" check and still be able to drift.

ONE TYPE. ``importlib/__init__.py`` used to define its own four-slot
``_ModuleSpec``. With the machinery building real specs, a second class of the
same name would make ``isinstance(mod.__spec__, ModuleSpec)`` false; the .py now
takes the Smalltalk class instead, so the machinery's specs, the facade's
``spec_from_file_location`` and ``mod.__spec__`` are one type.

EXPECTED was generated by RUNNING CPython 3.14.6.
"""

import textwrap

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except Exception as e:                      # noqa: BLE001 - the type IS the result
        r[k] = type(e).__name__


_s = textwrap.__spec__

# --- a real spec exists, and is the right kind of object --------------------
rec('spec_is_not_none', lambda: _s is not None)
rec('spec_type_name', lambda: type(_s).__name__)
rec('spec_name', lambda: _s.name)

# --- THE INVARIANT: every mirror agrees with the spec it came from ----------
# CPython derives each of these in _init_module_attrs and warns when one drifts.
rec('file_is_spec_origin', lambda: textwrap.__file__ == _s.origin)
rec('package_is_spec_parent', lambda: textwrap.__package__ == _s.parent)
rec('loader_is_spec_loader', lambda: textwrap.__loader__ is _s.loader)

# --- a file-backed module has a location ------------------------------------
rec('has_location', lambda: _s.has_location)
rec('parent_of_top_level_is_empty', lambda: _s.parent == '')

# --- a submodule's parent is its package ------------------------------------
def _submodule_parent():
    import test.test_funcattrs as t
    return t.__spec__.parent


rec('submodule_parent', _submodule_parent)


EXPECTED = {
    'spec_is_not_none': True,
    'spec_type_name': 'ModuleSpec',
    'spec_name': 'textwrap',
    'file_is_spec_origin': True,
    'package_is_spec_parent': True,
    'loader_is_spec_loader': True,
    'has_location': True,
    'parent_of_top_level_is_empty': True,
    'submodule_parent': 'test',
}


# --- documented divergences: CPython is EXPECTED to disagree ----------------
# ``spec.cached`` names the compiled bytecode file. CPython computes a path for
# any source module (without checking it exists); Grail compiles to Smalltalk
# methods and writes no .pyc, so it is always None -- which is also what keeps
# ``module.__cached__`` absent, since _init_module_attrs sets that attribute
# only when spec.cached is not None. See ModuleSpec's class comment.
rec('cached_is_none', lambda: _s.cached is None)

GRAIL_ONLY = {
    'cached_is_none': True,
}


if __name__ == '__main__':
    for _k in EXPECTED:
        print('%-30s %s %r' % (_k, 'OK ' if r[_k] == EXPECTED[_k] else 'DIFF', r[_k]))
    for _k in GRAIL_ONLY:
        # XFAIL: CPython disagreeing here is the documented, expected outcome.
        # XPASS (it agreeing) means the divergence is gone and this note is
        # stale -- the fixture gate treats that as a failure, deliberately.
        _tag = 'XPASS' if r[_k] == GRAIL_ONLY[_k] else 'XFAIL'
        print('%-30s %s %r' % (_k, _tag, r[_k]))
