# CPython's NON-BLOCKING socket contract, and the OSError fields that report it.
#
# CPython has THREE timeout states, not two: `settimeout(None)` blocks,
# `settimeout(n)` blocks for n seconds and then raises TimeoutError, and
# `settimeout(0)` -- equivalently `setblocking(False)` -- does not wait at all
# and raises BlockingIOError.  Grail had the third state right in every respect
# but the exception: it raised TimeoutError there too.
#
# WHY THAT ONE SUBSTITUTION MATTERS.  TimeoutError and BlockingIOError are
# SIBLINGS under OSError, not one under the other, so this idiom --
#
#     try:
#         data = sock.recv(n)
#     except (BlockingIOError, InterruptedError):
#         <wait for readiness, then retry>
#
# -- silently could not work.  It is the idiom EVERY non-blocking reader is
# written in, including two places in Grail's own vendored CPython socket.py and
# asyncio's sock_recv / sock_accept.  The retry branch was unreachable and the
# error escaped as a timeout instead.
#
# The second half is the reporting side.  `except OSError as e: e.errno` is how
# Python code tells one OS error from another, and Grail's OSError only had an
# `errno` when the constructor was handed CPython's (errno, strerror) form.
# Every OSError Grail's socket layer raises is the ONE-argument form, so reading
# `.errno` inside the handler raised AttributeError -- which is why the
# `e.errno in (EAGAIN, EWOULDBLOCK)` test in the vendored socket.py could never
# run either.  A 2..5-argument OSError also stringified as its args TUPLE rather
# than CPython's `[Errno n] strerror`.
#
# PLATFORM NOTE: nothing here records a raw errno NUMBER.  errno.EAGAIN is 35 on
# BSD/macOS and 11 on Linux, so the checks compare against `errno.EAGAIN`
# instead -- which is the comparison real code makes, and is what has to hold
# for Grail's socket layer and its errno module to agree.  Where a number does
# appear it is one this file supplied itself.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import errno
import socket

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


def _pair():
    """A connected (server-side, client-side) pair over loopback."""
    srv = socket.socket()
    srv.bind(('127.0.0.1', 0))
    srv.listen(1)
    cli = socket.socket()
    cli.connect(srv.getsockname())
    conn, _addr = srv.accept()
    srv.close()
    return conn, cli


def _listener():
    srv = socket.socket()
    srv.bind(('127.0.0.1', 0))
    srv.listen(1)
    return srv


# --- the three states are three, and are distinguishable -------------------

def three_states():
    s = socket.socket()
    out = [s.gettimeout(), s.getblocking()]
    s.settimeout(2.5)
    out += [s.gettimeout(), s.getblocking()]
    s.setblocking(False)
    out += [s.gettimeout(), s.getblocking()]
    s.settimeout(None)
    out += [s.gettimeout(), s.getblocking()]
    s.close()
    return out


rec('three_states', three_states)


def timeouts_are_floats():
    """CPython stores whatever it is given as a float, so an int comes back
    as one.  Reading back a different TYPE than CPython reports is enough to
    make a `gettimeout() == 0` style test disagree by accident."""
    s = socket.socket()
    s.settimeout(1)
    got = s.gettimeout()
    s.close()
    return (got, isinstance(got, float))


rec('timeouts_are_floats', timeouts_are_floats)


# --- what a non-blocking call raises ----------------------------------------

def recv_nonblocking_raises_blocking_io_error():
    conn, cli = _pair()
    conn.setblocking(False)
    try:
        conn.recv(100)
        return 'no error'
    except BlockingIOError as e:
        return ('BlockingIOError', e.errno == errno.EAGAIN)
    finally:
        conn.close()
        cli.close()


rec('recv_nonblocking_raises_blocking_io_error',
    recv_nonblocking_raises_blocking_io_error)


def accept_nonblocking_raises_blocking_io_error():
    srv = _listener()
    srv.setblocking(False)
    try:
        srv.accept()
        return 'no error'
    except BlockingIOError as e:
        return ('BlockingIOError', e.errno == errno.EAGAIN)
    finally:
        srv.close()


rec('accept_nonblocking_raises_blocking_io_error',
    accept_nonblocking_raises_blocking_io_error)


def a_positive_timeout_still_raises_timeout_error():
    """The state that DOES wait keeps its own exception.  Collapsing the two
    the other way round would be just as wrong."""
    conn, cli = _pair()
    conn.settimeout(0.05)
    try:
        conn.recv(100)
        return 'no error'
    except TimeoutError as e:
        return ('TimeoutError', str(e), isinstance(e, BlockingIOError))
    finally:
        conn.close()
        cli.close()


rec('a_positive_timeout_still_raises_timeout_error',
    a_positive_timeout_still_raises_timeout_error)


def a_timeout_too_small_to_measure_is_still_a_timeout():
    """0.0001s rounds to zero MILLISECONDS, which is the unit GemStone's
    readiness primitive takes -- but it is still the blocking-with-a-timeout
    state, not non-blocking mode.  Deciding from the rounded value would
    reintroduce exactly the confusion this change removes, in the other
    direction."""
    conn, cli = _pair()
    conn.settimeout(0.0001)
    try:
        conn.recv(100)
        return 'no error'
    except BlockingIOError:
        return 'BlockingIOError'
    except TimeoutError:
        return 'TimeoutError'
    finally:
        conn.close()
        cli.close()


rec('a_timeout_too_small_to_measure_is_still_a_timeout',
    a_timeout_too_small_to_measure_is_still_a_timeout)


def the_two_are_siblings_not_parent_and_child():
    """Which is precisely why substituting one for the other is invisible to
    the type system and fatal to the idiom below."""
    return (issubclass(BlockingIOError, OSError),
            issubclass(TimeoutError, OSError),
            issubclass(TimeoutError, BlockingIOError),
            issubclass(BlockingIOError, TimeoutError))


rec('the_two_are_siblings_not_parent_and_child',
    the_two_are_siblings_not_parent_and_child)


# --- THE HEADLINE: the retry idiom, run as written -------------------------

def the_retry_idiom_works():
    """A non-blocking read that waits for readiness and retries -- the shape of
    every selector-driven reader, and of asyncio's sock_recv.  Before the fix
    the `except` clause did not match, so the first attempt escaped as a
    TimeoutError and nothing retried."""
    conn, cli = _pair()
    conn.setblocking(False)
    trace = []
    try:
        for _attempt in range(10):
            try:
                trace.append(conn.recv(100))
                break
            except (BlockingIOError, InterruptedError):
                trace.append('not ready')
                # A real loop waits on readiness here; this one prods the peer
                # into sending so the retry has something to find.
                cli.sendall(b'payload')
                import select
                select.select([conn], [], [], 2.0)
        return trace
    finally:
        conn.close()
        cli.close()


rec('the_retry_idiom_works', the_retry_idiom_works)


def a_nonblocking_send_that_fits_still_sends():
    """The guard must not refuse a write that would have succeeded."""
    conn, cli = _pair()
    conn.setblocking(False)
    try:
        n = conn.send(b'four')
        return (n, cli.recv(4))
    finally:
        conn.close()
        cli.close()


rec('a_nonblocking_send_that_fits_still_sends',
    a_nonblocking_send_that_fits_still_sends)


# --- the reporting side: OSError's fields ----------------------------------

def errno_defaults_to_none_not_attribute_error():
    """Grail's socket layer raises single-message OSErrors, so this is the
    common case, not the exotic one: reading `.errno` in the handler must
    answer None rather than raising from inside it."""
    e = OSError('a message with no errno')
    return (e.errno, e.strerror, e.filename, e.filename2)


rec('errno_defaults_to_none_not_attribute_error',
    errno_defaults_to_none_not_attribute_error)


def a_closed_socket_reports_an_oserror_whose_errno_reads():
    conn, cli = _pair()
    conn.close()
    cli.close()
    try:
        conn.recv(1)
        return 'no error'
    except OSError as e:
        # The VALUE is platform- and implementation-specific; that reading it
        # answers at all is not.
        return ('OSError', e.errno is None or isinstance(e.errno, int))


rec('a_closed_socket_reports_an_oserror_whose_errno_reads',
    a_closed_socket_reports_an_oserror_whose_errno_reads)


def str_of_an_errno_oserror():
    """`[Errno n] strerror`, not the args tuple."""
    return (str(OSError(35, 'Resource temporarily unavailable')),
            str(OSError(2, 'No such file', 'f.txt')),
            str(OSError(2, 'No such file', 'f.txt', None, 'g.txt')),
            str(OSError('just a message')),
            str(OSError()))


rec('str_of_an_errno_oserror', str_of_an_errno_oserror)


def str_falls_back_outside_the_errno_form():
    """Arity gates the whole thing: one argument is not the (errno, strerror)
    form and renders as BaseException would."""
    return str(OSError('x'))


rec('str_falls_back_outside_the_errno_form', str_falls_back_outside_the_errno_form)


def more_than_five_arguments():
    """CPython does no unpacking at all above five arguments and keeps args
    whole, so str() is the tuple.  GRAIL DIFFERS: its exception constructors
    accept at most five positional arguments, so this raises TypeError before
    the question of unpacking arises -- which makes the `> 5` branch of
    OSError >> ___args___: unreachable from Python today.  Pinned rather than
    quietly worked around; the Smalltalk test records Grail's answer."""
    return str(OSError(1, 2, 3, 4, 5, 6))


rec('more_than_five_arguments', more_than_five_arguments)


def none_is_not_absent():
    """A field supplied AS None is not the same as one never supplied: CPython
    tests the slot for presence, not for truth, so `[Errno 2] None` is the
    right answer here."""
    return (str(OSError(2, None)), str(OSError(None, 'msg')))


rec('none_is_not_absent', none_is_not_absent)


def filename_is_kept_only_when_supplied():
    """And filename2 only INSIDE that test, so a None filename discards both --
    the same test that decides whether args is truncated to a pair."""
    a = OSError(2, 'm', None, None, 'g')
    b = OSError(2, 'm', 'f', None, 'g')
    return (a.filename, a.filename2, a.args, b.filename, b.filename2, b.args)


rec('filename_is_kept_only_when_supplied', filename_is_kept_only_when_supplied)


def args_truncation_follows_filename_not_arity():
    """`OSError(2, 'm', None).args` keeps all three; supplying a real filename
    is what cuts args down to (errno, strerror)."""
    return (OSError(2, 'm', None).args, OSError(2, 'm', 'f').args,
            OSError(2, 'm').args, OSError('m').args)


rec('args_truncation_follows_filename_not_arity',
    args_truncation_follows_filename_not_arity)


def errno_is_a_data_attribute_not_a_method():
    """`e.errno`, not `e.errno()`.  A BoundMethod here would be TRUTHY, so
    `if e.errno:` would take the wrong branch rather than fail loudly."""
    e = OSError(35, 'msg')
    return (e.errno, e.strerror, bool(OSError('x').errno))


rec('errno_is_a_data_attribute_not_a_method', errno_is_a_data_attribute_not_a_method)


EXPECTED = {
    'a_closed_socket_reports_an_oserror_whose_errno_reads': ('OSError', True),
    'a_nonblocking_send_that_fits_still_sends': (4, b'four'),
    'a_positive_timeout_still_raises_timeout_error': ('TimeoutError', 'timed out', False),
    'a_timeout_too_small_to_measure_is_still_a_timeout': 'TimeoutError',
    'accept_nonblocking_raises_blocking_io_error': ('BlockingIOError', True),
    'args_truncation_follows_filename_not_arity': ((2, 'm', None), (2, 'm'), (2, 'm'), ('m',)),
    'errno_defaults_to_none_not_attribute_error': (None, None, None, None),
    'errno_is_a_data_attribute_not_a_method': (35, 'msg', False),
    'filename_is_kept_only_when_supplied': (None, None, (2, 'm', None, None, 'g'), 'f', 'g', (2, 'm')),
    'none_is_not_absent': ('[Errno 2] None', '[Errno None] msg'),
    'recv_nonblocking_raises_blocking_io_error': ('BlockingIOError', True),
    'more_than_five_arguments': '(1, 2, 3, 4, 5, 6)',
    'str_falls_back_outside_the_errno_form': 'x',
    'str_of_an_errno_oserror': ('[Errno 35] Resource temporarily unavailable', "[Errno 2] No such file: 'f.txt'", "[Errno 2] No such file: 'f.txt' -> 'g.txt'", 'just a message', ''),
    'the_retry_idiom_works': ['not ready', b'payload'],
    'the_two_are_siblings_not_parent_and_child': (True, True, False, False),
    'three_states': [None, True, 2.5, True, 0.0, False, None, True],
    'timeouts_are_floats': (1.0, True),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-52s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
