# os.listdir and the os.path predicates -- exists / isdir / isfile / islink --
# on the filenames and file types that used to be answered wrongly.
#
# THE FILENAME BUG WAS A WRONG ANSWER, NOT A MISSING ONE.  GsFile expands ``$''
# in every path handed to its file primitives, so ``exists('dir/a$b')'' asked
# about ``dir/a'' -- and with a file of that name beside it, answered TRUE about
# a DIFFERENT FILE.  Reading, stat'ing and removing all followed it there.  A
# name containing a ``$'' was also absent from os.listdir entirely, because the
# public directory listing expands the path as a shell PATTERN.
#
#   dir/a      contains 'decoy!'      -- 6 bytes
#   dir/a$b    is empty               -- 0 bytes
#
# so the sizes below say which file was actually reached, where a boolean could
# not.  ``*'' and ``~'' are checked alongside it: neither was ever expanded, and
# a fix that started expanding them would be the same bug wearing a new hat.
#
# THE FILE-TYPE BUG WAS QUIETER.  isfile answered ``not a directory'', so a
# fifo, a socket or a device answered TRUE where CPython says False -- isfile
# means REGULAR file.  A fifo is the easiest of the three to make portably.
#
# Both are fixed the same way: every predicate now rests on stat, which is the
# one GsFile primitive that does not expand the path and which reports the file
# TYPE rather than a directory yes/no.
#
# WHAT IS STILL NOT FIXED, because there is no non-expanding primitive to call:
# CREATING or REMOVING a ``$'' path.  open('dir/a$b','w') still writes to
# 'dir/a'.  So the two ``$'' files below are made through the shell, and what
# this fixture pins is the READING side -- that such a file is listed, and that
# every predicate and stat answer about it rather than about its truncation.
#
# NOT COVERED HERE: an unreadable directory now raises PermissionError, where
# the old listing could not tell EACCES from an empty result.  It is left out
# because chmod 000 does not stop root, so the case would answer differently
# depending on who runs the suite.  Verified by hand instead.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import os
import tempfile

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = type(e).__name__


ROOT = tempfile.mkdtemp(prefix='grail_ospath_')
J = os.path.join


def _write(path, text):
    f = open(path, 'w')
    f.write(text)
    f.close()


# ``a'' is the DECOY: it is what ``a$b'' collapses to when the path is expanded.
_write(J(ROOT, 'a'), 'decoy!')
# The ``$'' files are created THROUGH THE SHELL, not through open(): Grail's
# open() goes to a GsFile primitive that expands the path, so ``open('a$b','w')''
# creates ``a'' -- it overwrites the decoy and no ``a$b'' ever appears.  That
# residual gap is below this module (see the header) and is the reason the
# creation side is not asserted here; what IS asserted is that once such a file
# exists, listdir sees it and every predicate answers about IT.
os.system("printf '' > '" + J(ROOT, 'a$b') + "'")
os.system("printf 'x' > '" + J(ROOT, 'has$HOMEin') + "'")
_write(J(ROOT, 'star*x'), 'x')
_write(J(ROOT, 'tilde~x'), 'x')
os.mkdir(J(ROOT, 'sub'))
os.symlink('sub', J(ROOT, 'link'))
os.symlink('nowhere', J(ROOT, 'broken'))
os.system('mkfifo ' + J(ROOT, 'fifo'))


# --- a ``$'' in a filename ---------------------------------------------------

rec('listdir_includes_dollar_names', lambda: sorted(os.listdir(ROOT)))
rec('dollar_exists', lambda: os.path.exists(J(ROOT, 'a$b')))
rec('dollar_isfile', lambda: os.path.isfile(J(ROOT, 'a$b')))
rec('dollar_isdir', lambda: os.path.isdir(J(ROOT, 'a$b')))
rec('dollar_islink', lambda: os.path.islink(J(ROOT, 'a$b')))
# THE ONE THAT MATTERS: the size says which file was reached.  0 is ``a$b'';
# 6 would be the decoy ``a'', which is what an expanded path resolves to.
rec('dollar_stat_reaches_the_right_file',
    lambda: os.stat(J(ROOT, 'a$b')).st_size)
rec('decoy_is_a_different_file', lambda: os.stat(J(ROOT, 'a')).st_size)
# ``$HOMEin'' is not ``$HOME'' + ``in'' to a shell -- it is one undefined
# variable, so an expanding path lost the whole name.
rec('dollar_home_like_name', lambda: os.stat(J(ROOT, 'has$HOMEin')).st_size)

# ...and the characters that were never expanded must stay unexpanded.
rec('star_is_literal', lambda: os.path.isfile(J(ROOT, 'star*x')))
rec('tilde_is_literal', lambda: os.path.isfile(J(ROOT, 'tilde~x')))
rec('star_is_not_a_glob', lambda: os.path.exists(J(ROOT, '*')))


# --- isfile means REGULAR file -----------------------------------------------

rec('fifo_exists', lambda: os.path.exists(J(ROOT, 'fifo')))
rec('fifo_is_not_a_file', lambda: os.path.isfile(J(ROOT, 'fifo')))
rec('fifo_is_not_a_dir', lambda: os.path.isdir(J(ROOT, 'fifo')))
rec('fifo_is_not_a_link', lambda: os.path.islink(J(ROOT, 'fifo')))
rec('fifo_is_listed', lambda: 'fifo' in os.listdir(ROOT))
rec('fifo_can_be_removed', lambda: os.remove(J(ROOT, 'fifo')))
rec('fifo_is_gone', lambda: os.path.exists(J(ROOT, 'fifo')))

rec('dir_is_not_a_file', lambda: os.path.isfile(J(ROOT, 'sub')))
rec('dir_is_a_dir', lambda: os.path.isdir(J(ROOT, 'sub')))
rec('file_is_not_a_dir', lambda: os.path.isdir(J(ROOT, 'a')))


# --- the predicates and symlinks ---------------------------------------------
#
# exists / isdir / isfile FOLLOW links; islink does not.

rec('link_exists', lambda: os.path.exists(J(ROOT, 'link')))
rec('link_is_a_dir', lambda: os.path.isdir(J(ROOT, 'link')))
rec('link_is_a_link', lambda: os.path.islink(J(ROOT, 'link')))
# A DANGLING link: islink is true, exists is FALSE -- exists follows, and there
# is nothing at the far end.  A predicate built on "can I stat it" without
# lstat would get this backwards.
rec('broken_link_is_a_link', lambda: os.path.islink(J(ROOT, 'broken')))
rec('broken_link_does_not_exist', lambda: os.path.exists(J(ROOT, 'broken')))
rec('broken_link_is_not_a_file', lambda: os.path.isfile(J(ROOT, 'broken')))
rec('broken_link_is_listed', lambda: 'broken' in os.listdir(ROOT))


# --- a missing path is never an error for a predicate ------------------------

rec('missing_exists', lambda: os.path.exists(J(ROOT, 'nope')))
rec('missing_isfile', lambda: os.path.isfile(J(ROOT, 'nope')))
rec('missing_isdir', lambda: os.path.isdir(J(ROOT, 'nope')))
rec('missing_islink', lambda: os.path.islink(J(ROOT, 'nope')))
# ...whereas stat DOES raise, which is the difference between the two families.
rec('missing_stat_raises', lambda: os.stat(J(ROOT, 'nope')))


EXPECTED = {
    'broken_link_does_not_exist': False,
    'broken_link_is_a_link': True,
    'broken_link_is_listed': True,
    'broken_link_is_not_a_file': False,
    'decoy_is_a_different_file': 6,
    'dir_is_a_dir': True,
    'dir_is_not_a_file': False,
    'dollar_exists': True,
    'dollar_home_like_name': 1,
    'dollar_isdir': False,
    'dollar_isfile': True,
    'dollar_islink': False,
    'dollar_stat_reaches_the_right_file': 0,
    'fifo_can_be_removed': None,
    'fifo_exists': True,
    'fifo_is_gone': False,
    'fifo_is_listed': True,
    'fifo_is_not_a_dir': False,
    'fifo_is_not_a_file': False,
    'fifo_is_not_a_link': False,
    'file_is_not_a_dir': False,
    'link_exists': True,
    'link_is_a_dir': True,
    'link_is_a_link': True,
    'listdir_includes_dollar_names': ['a', 'a$b', 'broken', 'fifo',
                                      'has$HOMEin', 'link', 'star*x', 'sub',
                                      'tilde~x'],
    'missing_exists': False,
    'missing_isdir': False,
    'missing_isfile': False,
    'missing_islink': False,
    'missing_stat_raises': 'FileNotFoundError',
    'star_is_literal': True,
    'star_is_not_a_glob': False,
    'tilde_is_literal': True,
}


def _unlink(path):
    """os.remove, falling back to the shell.  Under CPython the fallback never
    runs; under Grail it is what removes a ``$'' path, whose removal goes to the
    same expanding primitive as its creation.  Stated here rather than hidden,
    because a teardown that silently left files behind is how the os.walk work
    started."""
    try:
        os.remove(path)
    except OSError:
        os.system("rm -f '" + path + "'")


def _teardown():
    for dirpath, dirnames, filenames in os.walk(ROOT, topdown=False):
        for name in filenames:
            _unlink(J(dirpath, name))
        for name in dirnames:
            p = J(dirpath, name)
            _unlink(p) if os.path.islink(p) else os.rmdir(p)
    os.rmdir(ROOT)


_teardown()


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-38s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
