# os.scandir / DirEntry, and os.symlink / os.readlink.
#
# Two gaps that showed up while adding os.walk.  Neither was wrong -- both were
# simply absent -- so what is asserted here is CPython's contract rather than a
# correction to some previous answer.
#
# WHAT IS EASY TO GET WRONG IN scandir IS THE SYMLINK DEFAULTS.  is_dir() and
# is_file() FOLLOW symlinks by default, so a symlink to a directory answers True
# to is_dir(); is_dir(follow_symlinks=False) answers False for the same entry,
# because with following off a symlink is only ever a symlink.  is_symlink()
# takes no such argument at all -- asking whether something IS a link cannot
# follow it -- and inode() does not follow either.  And follow_symlinks is
# KEYWORD-ONLY: is_dir(False) is a TypeError, not "don't follow".
#
# scandir also returns an object that is BOTH an iterator and a context manager,
# because ``with os.scandir(p) as it:'' is the spelling CPython's own library
# uses.  A plain generator would satisfy every other case here and fail that one.
#
# FOR symlink THE POINT IS THAT src NEED NOT EXIST.  A dangling symlink is legal
# POSIX and legal CPython, and test code creates them deliberately; readlink then
# answers the target VERBATIM, unresolved.  The two errors are asymmetric on
# purpose: readlink on something that is not a link is EINVAL, not ENOENT --
# "there is something there and it is not a link" is a different fact from
# "there is nothing there", and callers branch on it.
#
# Grail has no symlink primitive (GsFile can TEST for one but not make one), so
# os.symlink runs ``ln -s''.  That is why a path containing a space, a quote and
# a command separator is exercised below: shell quoting that is merely nearly
# right turns a filename into shell syntax, and the separator makes that
# arbitrary command execution rather than a wrong answer.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import os
import tempfile

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = type(e).__name__


ROOT = tempfile.mkdtemp(prefix='grail_scandir_')
J = os.path.join

os.mkdir(J(ROOT, 'd'))
f = open(J(ROOT, 'f.txt'), 'w')
f.write('x')
f.close()
os.symlink('d', J(ROOT, 'lnk'))


def entry(name):
    for e in os.scandir(ROOT):
        if e.name == name:
            return e
    raise LookupError(name)


# --- scandir: the iterator ---------------------------------------------------

rec('names', lambda: sorted(e.name for e in os.scandir(ROOT)))
rec('scandir_type', lambda: type(os.scandir(ROOT)).__name__)
rec('entry_type', lambda: type(entry('f.txt')).__name__)
rec('entry_module', lambda: type(entry('f.txt')).__module__)
rec('entry_repr', lambda: repr(entry('f.txt')))
rec('is_a_DirEntry', lambda: isinstance(entry('d'), os.DirEntry))


def as_context_manager():
    with os.scandir(ROOT) as it:
        return sorted(e.name for e in it)


rec('context_manager', as_context_manager)


def closed_iterator():
    it = os.scandir(ROOT)
    it.close()
    return list(it)


rec('closed_iterator_is_exhausted', closed_iterator)
rec('close_is_idempotent', lambda: [os.scandir(ROOT).close(),
                                    os.scandir(ROOT).close()] and 'ok')


# --- scandir: the entries ----------------------------------------------------

rec('path_is_joined', lambda: entry('f.txt').path == J(ROOT, 'f.txt'))
rec('entry_is_path_like', lambda: os.path.basename(os.fspath(entry('f.txt'))))
rec('dir_is_dir', lambda: entry('d').is_dir())
rec('dir_is_not_file', lambda: entry('d').is_file())
rec('file_is_file', lambda: entry('f.txt').is_file())
rec('file_is_not_dir', lambda: entry('f.txt').is_dir())
rec('inode_is_positive', lambda: entry('f.txt').inode() > 0)
rec('is_junction_is_false_on_posix', lambda: entry('d').is_junction())


# --- scandir: the symlink defaults, which are the easy part to get wrong -----

rec('link_is_dir_by_default', lambda: entry('lnk').is_dir())
rec('link_is_not_dir_without_following',
    lambda: entry('lnk').is_dir(follow_symlinks=False))
rec('link_is_a_symlink', lambda: entry('lnk').is_symlink())
rec('link_is_not_file_either_way',
    lambda: (entry('lnk').is_file(),
             entry('lnk').is_file(follow_symlinks=False)))
# stat FOLLOWS by default and so reports the directory; stat(follow_symlinks=
# False) is an lstat and reports the link itself.
rec('link_stat_reports_the_target',
    lambda: entry('lnk').stat().st_mode & 0o170000 == 0o040000)
rec('link_lstat_reports_the_link',
    lambda: entry('lnk').stat(follow_symlinks=False).st_mode & 0o170000 == 0o120000)
# follow_symlinks is KEYWORD-ONLY.
rec('positional_follow_symlinks_is_an_error',
    lambda: entry('d').is_dir(False))


# --- scandir: errors, inherited from listdir ---------------------------------

rec('scandir_missing', lambda: os.scandir(J(ROOT, 'nope')))
rec('scandir_on_a_file', lambda: os.scandir(J(ROOT, 'f.txt')))


# --- symlink / readlink ------------------------------------------------------

rec('symlink_returns_none', lambda: os.symlink('f.txt', J(ROOT, 'rel')))
rec('relative_target_is_verbatim', lambda: os.readlink(J(ROOT, 'rel')))
rec('relative_link_resolves', lambda: os.path.isfile(J(ROOT, 'rel')))

rec('absolute_symlink', lambda: os.symlink(J(ROOT, 'd'), J(ROOT, 'abs')))
rec('absolute_target_is_verbatim',
    lambda: os.readlink(J(ROOT, 'abs')) == J(ROOT, 'd'))
rec('absolute_link_resolves', lambda: os.path.isdir(J(ROOT, 'abs')))

# A DANGLING symlink is legal: src is not required to exist.
rec('dangling_symlink', lambda: os.symlink('nowhere', J(ROOT, 'dangling')))
rec('dangling_is_a_link', lambda: os.path.islink(J(ROOT, 'dangling')))
rec('dangling_does_not_exist', lambda: os.path.exists(J(ROOT, 'dangling')))
rec('dangling_target_reads_back', lambda: os.readlink(J(ROOT, 'dangling')))

# target_is_directory is a Windows argument; POSIX accepts and ignores it.
rec('target_is_directory_is_accepted',
    lambda: os.symlink(J(ROOT, 'd'), J(ROOT, 'tid'), target_is_directory=True))
rec('target_is_directory_link_works', lambda: os.path.isdir(J(ROOT, 'tid')))

# A path that is shell syntax if quoted carelessly: a space, a single quote, and
# a command separator.  NOT a ``$'': GsFile expands environment variables in
# every path it is given, so a name containing one is invisible to
# GsFile>>existsOnServer: and unremovable -- a pre-existing limitation of the
# whole os module here, well below os.symlink, and not something shell quoting
# in this one function could fix.
WEIRD = J(ROOT, "we ird'n;ame")
rec('shell_hostile_name', lambda: os.symlink('f.txt', WEIRD))
rec('shell_hostile_name_is_a_link', lambda: os.path.islink(WEIRD))
rec('shell_hostile_name_reads_back', lambda: os.readlink(WEIRD))
# ...and nothing was created by a shell re-parse of it.
rec('nothing_extra_was_created',
    lambda: sorted(e.name for e in os.scandir(ROOT)))

# --- symlink / readlink: errors ----------------------------------------------

rec('dst_already_exists', lambda: os.symlink('x', J(ROOT, 'f.txt')))
# ...including when the occupant is itself a DANGLING link, which exists() alone
# would miss.
rec('dst_is_a_dangling_link', lambda: os.symlink('x', J(ROOT, 'dangling')))
rec('missing_parent_directory',
    lambda: os.symlink('x', J(ROOT, 'no', 'such', 'dir', 'l')))
# EINVAL, not ENOENT: there IS something there, it is just not a link.
rec('readlink_on_a_regular_file', lambda: os.readlink(J(ROOT, 'f.txt')))
rec('readlink_on_a_missing_path', lambda: os.readlink(J(ROOT, 'nope')))


EXPECTED = {
    'absolute_link_resolves': True,
    'absolute_symlink': None,
    'absolute_target_is_verbatim': True,
    'close_is_idempotent': 'ok',
    'closed_iterator_is_exhausted': [],
    'context_manager': ['d', 'f.txt', 'lnk'],
    'dangling_does_not_exist': False,
    'dangling_is_a_link': True,
    'dangling_symlink': None,
    'dangling_target_reads_back': 'nowhere',
    'dir_is_dir': True,
    'dir_is_not_file': False,
    'dst_already_exists': 'FileExistsError',
    'dst_is_a_dangling_link': 'FileExistsError',
    'entry_is_path_like': 'f.txt',
    'entry_module': 'posix',
    'entry_repr': "<DirEntry 'f.txt'>",
    'entry_type': 'DirEntry',
    'file_is_file': True,
    'file_is_not_dir': False,
    'inode_is_positive': True,
    'is_a_DirEntry': True,
    'is_junction_is_false_on_posix': False,
    'link_is_a_symlink': True,
    'link_is_dir_by_default': True,
    'link_is_not_dir_without_following': False,
    'link_is_not_file_either_way': (False, False),
    'link_lstat_reports_the_link': True,
    'link_stat_reports_the_target': True,
    'missing_parent_directory': 'FileNotFoundError',
    'names': ['d', 'f.txt', 'lnk'],
    'nothing_extra_was_created': ['abs', 'd', 'dangling', 'f.txt', 'lnk',
                                  'rel', 'tid', "we ird'n;ame"],
    'path_is_joined': True,
    'positional_follow_symlinks_is_an_error': 'TypeError',
    'readlink_on_a_missing_path': 'FileNotFoundError',
    'readlink_on_a_regular_file': 'OSError',
    'relative_link_resolves': True,
    'relative_target_is_verbatim': 'f.txt',
    'scandir_missing': 'FileNotFoundError',
    'scandir_on_a_file': 'NotADirectoryError',
    'scandir_type': 'ScandirIterator',
    'shell_hostile_name': None,
    'shell_hostile_name_is_a_link': True,
    'shell_hostile_name_reads_back': 'f.txt',
    'symlink_returns_none': None,
    'target_is_directory_is_accepted': None,
    'target_is_directory_link_works': True,
}


def _teardown():
    for dirpath, dirnames, filenames in os.walk(ROOT, topdown=False):
        for name in filenames:
            os.remove(J(dirpath, name))
        for name in dirnames:
            p = J(dirpath, name)
            os.remove(p) if os.path.islink(p) else os.rmdir(p)
    os.rmdir(ROOT)


_teardown()


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-40s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
