# os.utime -- setting a file's access and modification times.
#
# WHY THIS FIXTURE READS THE TIMES BACK.  os.utime was once stubbed here as a
# NO-OP, which reached a passing acceptance run: nothing in that harness looked
# at an mtime, so "it returned None" was indistinguishable from "it worked".  A
# silent no-op is worse than the AttributeError it replaced -- it reports
# success while doing nothing -- so every positive check below asserts the value
# os.stat() answers AFTERWARDS, and one of them (mtime_moved_off_creation)
# exists purely so that a no-op implementation scores a DIFF rather than an OK.
#
# GemStone exposes no utimes(2), so os.utime runs touch(1).  Two things about
# that are load-bearing and are checked here rather than assumed:
#
#   * TIMEZONE.  The obvious spelling, ``touch -t CCYYMMDDhhmm.ss'', is defined
#     in LOCAL time; using it stamped a time eight hours off UTC on the machine
#     this was written on, and the size of that error moves with DST.  Grail
#     formats the instant as ``YYYY-MM-DDThh:mm:ssZ'' and passes ``-d'', which
#     both BSD touch and GNU touch read as UTC.  The timestamps below are spread
#     across summer, winter and pre-1970 on purpose: a local-time conversion
#     gets at least one of them wrong on any machine that observes DST.
#
#   * SHELL QUOTING.  A downloaded filename is attacker-influenced text going
#     into a command line.  The name exercised below holds a space, a single
#     quote and a semicolon, and the check is not only that the file keeps its
#     times but that the command the semicolon would have started did not run.
#
# WHOLE SECONDS.  os.stat here answers an int st_mtime where CPython answers a
# float (GsFileStat exposes whole seconds only), and os.utime floors to match.
# So the checks compare math.floor(st_mtime), which is true under CPython too,
# and NOT st_mtime itself.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import math
import os
import tempfile
import time

r = {}
g = {}


def rec(k, fn, into=None):
    d = r if into is None else into
    try:
        d[k] = fn()
    except BaseException as e:
        d[k] = type(e).__name__


ROOT = tempfile.mkdtemp(prefix='grail_utime_')
J = os.path.join

P = J(ROOT, 'f.txt')
_f = open(P, 'w')
_f.write('x')
_f.close()

TARGET = J(ROOT, 'target.txt')
_f = open(TARGET, 'w')
_f.write('y')
_f.close()
LINK = J(ROOT, 'lnk')
os.symlink('target.txt', LINK)

# A name a shell would re-parse: space, single quote, semicolon.  MARKER is the
# file the embedded command would create if the quoting were merely nearly
# right.  It has to be a bare relative name -- a filename cannot hold a '/' --
# so it is hunted for afterwards in every directory the command could plausibly
# have run in.
MARKER = 'grail_utime_pwned_marker'
HOSTILE = J(ROOT, "od'd ; touch %s ; x.txt" % MARKER)
_f = open(HOSTILE, 'w')
_f.write('z')
_f.close()

PWNED_DIRS = [ROOT, tempfile.gettempdir(), os.getcwd()]

# 2024-07-03T02:13:20Z (northern summer) and 2024-01-01T00:00:00Z (winter):
# a conversion that leaks the local zone cannot get both of these right on a
# machine that observes DST.
SUMMER = 1720001600
WINTER = 1704067200
# 1960-05-06T07:08:09Z -- before the epoch, where a truncating division would
# land on the wrong day.
PRE_EPOCH = -304707111


def mtime(p):
    return math.floor(os.stat(p).st_mtime)


def atime(p):
    return math.floor(os.stat(p).st_atime)


# --- the times are really set ------------------------------------------------

_creation_mtime = mtime(P)
rec('returns_none', lambda: os.utime(P, (SUMMER, WINTER)))
rec('atime_read_back', lambda: atime(P) == SUMMER)
rec('mtime_read_back', lambda: mtime(P) == WINTER)
# THE NO-OP DETECTOR.  A stub that returns None without doing anything leaves
# the mtime at the file's creation time, and this check -- and only this check
# -- says so in one word.
rec('mtime_moved_off_creation', lambda: mtime(P) != _creation_mtime)

rec('winter_exact', lambda: (os.utime(P, (WINTER, WINTER)), mtime(P))[1] == WINTER)
rec('summer_exact', lambda: (os.utime(P, (SUMMER, SUMMER)), mtime(P))[1] == SUMMER)
rec('pre_epoch_exact',
    lambda: (os.utime(P, (PRE_EPOCH, PRE_EPOCH)), mtime(P))[1] == PRE_EPOCH)

rec('times_as_a_keyword',
    lambda: (os.utime(P, times=(WINTER, SUMMER)), atime(P), mtime(P))[1:]
    == (WINTER, SUMMER))

rec('none_means_now',
    lambda: (os.utime(P, None), abs(mtime(P) - time.time()) <= 60)[1])
rec('omitted_means_now',
    lambda: (os.utime(P), abs(mtime(P) - time.time()) <= 60)[1])


def _ns_floors():
    os.utime(P, ns=(3_500_000_000, 7_900_000_000))
    return (atime(P), mtime(P))


rec('ns_floors_to_whole_seconds', _ns_floors)


def _fractional_floors():
    os.utime(P, (SUMMER + 0.75, WINTER + 0.25))
    return (atime(P), mtime(P))


rec('fractional_seconds_floor', _fractional_floors)


# --- symlinks ----------------------------------------------------------------


def _follow_default():
    os.utime(LINK, (SUMMER, SUMMER))
    return math.floor(os.stat(LINK).st_mtime) == SUMMER


rec('default_follows_to_the_target', _follow_default)


def _no_follow():
    os.utime(LINK, (WINTER, WINTER), follow_symlinks=False)
    return (math.floor(os.lstat(LINK).st_mtime) == WINTER,
            math.floor(os.stat(TARGET).st_mtime) == SUMMER)


rec('follow_symlinks_false_stamps_the_link', _no_follow)


# --- a shell-hostile filename ------------------------------------------------


def _hostile():
    os.utime(HOSTILE, (WINTER, SUMMER))
    return (atime(HOSTILE), mtime(HOSTILE))


rec('hostile_name_keeps_its_times', _hostile)
# The times landing on the right file is already most of the proof: if the name
# had been re-parsed, touch would have been handed three fragments and stamped
# none of them.  These two say the other half -- that the command the semicolon
# introduces did not run anywhere it could be seen.
rec('no_injected_command_ran',
    lambda: [d for d in PWNED_DIRS if os.path.exists(J(d, MARKER))])
rec('nothing_extra_in_the_directory',
    lambda: sorted(os.listdir(ROOT)) == sorted(
        ['f.txt', 'target.txt', 'lnk', os.path.basename(HOSTILE)]))


# --- errors ------------------------------------------------------------------

rec('missing_path', lambda: os.utime(J(ROOT, 'nope')))
rec('times_as_a_list', lambda: os.utime(P, [SUMMER, WINTER]))
rec('times_of_three', lambda: os.utime(P, (1, 2, 3)))
rec('times_not_a_sequence', lambda: os.utime(P, 5))
rec('times_of_strings', lambda: os.utime(P, ('a', 'b')))
rec('times_and_ns_together', lambda: os.utime(P, (1, 2), ns=(1, 2)))
rec('ns_of_three', lambda: os.utime(P, ns=(1, 2, 3)))
rec('ns_of_floats', lambda: os.utime(P, ns=(1.0, 2.0)))
rec('three_positional_arguments', lambda: os.utime(P, (1, 2), 3))
rec('unexpected_keyword', lambda: os.utime(P, nosuch=1))
rec('out_of_range_timestamp', lambda: os.utime(P, (10 ** 30, 10 ** 30)))
rec('dir_fd_none_is_accepted', lambda: os.utime(P, (WINTER, WINTER), dir_fd=None))


# --- a documented Grail limitation -------------------------------------------
#
# CPython honours dir_fd for utime on Linux and macOS; Grail has no dir_fd
# anywhere, and says NotImplementedError rather than resolving the path against
# the wrong directory.  CPython is EXPECTED to disagree with this one.

rec('dir_fd', lambda: os.utime(P, (WINTER, WINTER), dir_fd=3), into=g)


EXPECTED = {
    'atime_read_back': True,
    'default_follows_to_the_target': True,
    'dir_fd_none_is_accepted': None,
    'follow_symlinks_false_stamps_the_link': (True, True),
    'fractional_seconds_floor': (1720001600, 1704067200),
    'hostile_name_keeps_its_times': (1704067200, 1720001600),
    'missing_path': 'FileNotFoundError',
    'mtime_moved_off_creation': True,
    'mtime_read_back': True,
    'no_injected_command_ran': [],
    'none_means_now': True,
    'nothing_extra_in_the_directory': True,
    'ns_floors_to_whole_seconds': (3, 7),
    'ns_of_floats': 'TypeError',
    'ns_of_three': 'TypeError',
    'omitted_means_now': True,
    'out_of_range_timestamp': 'OverflowError',
    'pre_epoch_exact': True,
    'returns_none': None,
    'summer_exact': True,
    'three_positional_arguments': 'TypeError',
    'times_and_ns_together': 'ValueError',
    'times_as_a_keyword': True,
    'times_as_a_list': 'TypeError',
    'times_not_a_sequence': 'TypeError',
    'times_of_strings': 'TypeError',
    'times_of_three': 'TypeError',
    'unexpected_keyword': 'TypeError',
    'winter_exact': True,
}


def _teardown():
    for name in os.listdir(ROOT):
        os.remove(J(ROOT, name))
    os.rmdir(ROOT)
    for d in PWNED_DIRS:
        if os.path.exists(J(d, MARKER)):
            os.remove(J(d, MARKER))


_teardown()


def dir_fd_is_not_implemented():
    return g['dir_fd'] == 'NotImplementedError'


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r.get(k) == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-42s %s %r' % (k, 'OK ' if ok else 'DIFF', r.get(k)))
        # A documented Grail limitation: CPython is expected to disagree, so
        # XFAIL is the passing outcome and XPASS means the check is stale.
        print('--- documented Grail limit: CPython is expected to differ ---')
        print('%-42s %s' % ('dir_fd_is_not_implemented',
                            'XPASS' if dir_fd_is_not_implemented() else 'XFAIL'))
        print('%d difference(s)' % bad)
