# os.walk -- the directory-tree generator -- and the two os.listdir errors it
# depends on.
#
# Grail had no os.walk at all, which is why test.test_reprlib could not clean up
# after itself: its LongNameTests tearDown walks the package it built and removes
# it bottom-up, so every suite run left the tree in the checkout.
#
# THE LAZINESS IS PART OF THE CONTRACT, not an optimisation.  With topdown true
# the caller may prune the walk by mutating ``dirnames'' IN PLACE between yields
# (``dirs.remove('__pycache__')''), which a materialised list could not offer --
# it would have finished recursing before the caller saw anything.  The
# ``pruned'' case below is what proves os.walk is a real generator.
#
# The three OTHER things that are easy to get subtly wrong:
#
#   * a symlink to a directory belongs in ``dirnames'' (is_dir follows links)
#     but is NOT descended into unless followlinks is true;
#   * bottom-up fixes its descend list BEFORE yielding anything, so mutating
#     dirnames there has no effect -- CPython documents this;
#   * a directory that cannot be listed is SKIPPED, not yielded empty, and its
#     error goes to onerror, which may re-raise to abort the walk.
#
# ORDER AMONG SIBLINGS IS NOT ASSERTED.  It follows the filesystem's listing
# order, which Grail (GsFile) and CPython (scandir) need not agree on, so the
# triples are compared SORTED and the topdown/bottom-up distinction is checked
# as an ordering INVARIANT instead -- parent before child, or child before
# parent.  Asserting the literal sequence would be testing the filesystem.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import os
import tempfile

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = type(e).__name__ + ': ' + str(e)[:70]


# --- build the tree ----------------------------------------------------------
#
#   root/f0.txt
#   root/a/f1.txt
#   root/a/aa/f2.txt
#   root/a/ab/
#   root/b/f3.txt
#   root/b/lnk -> ../a          (a symlink TO A DIRECTORY)

ROOT = tempfile.mkdtemp(prefix='grail_os_walk_')


def _mkfile(path):
    f = open(path, 'w')
    f.write('x')
    f.close()


for d in ('a', 'a/aa', 'a/ab', 'b'):
    os.mkdir(os.path.join(ROOT, d))
for f in ('f0.txt', 'a/f1.txt', 'a/aa/f2.txt', 'b/f3.txt'):
    _mkfile(os.path.join(ROOT, f))
os.symlink('../a', os.path.join(ROOT, 'b', 'lnk'))


def _rel(p):
    if p == ROOT:
        return '.'
    if p.startswith(ROOT + '/'):
        return p[len(ROOT) + 1:]
    return p


def norm(walker):
    """Triples with root-relative dirpaths and sorted name lists, SORTED --
    sibling order is the filesystem's business, not os.walk's."""
    out = [(_rel(d), sorted(dn), sorted(fn)) for d, dn, fn in walker]
    return sorted(out)


def order_of(walker):
    """Just the dirpaths, in yield order -- for the parent/child invariant."""
    return [_rel(d) for d, dn, fn in walker]


def parents_before_children(paths):
    seen = set()
    for p in paths:
        parent = '.' if '/' not in p else p.rsplit('/', 1)[0]
        if p != '.' and parent not in seen:
            return False
        seen.add(p)
    return True


# --- content -----------------------------------------------------------------

rec('topdown', lambda: norm(os.walk(ROOT)))
rec('bottomup', lambda: norm(os.walk(ROOT, topdown=False)))
# Same set of directories either way -- only the order differs.
rec('same_set_either_way',
    lambda: norm(os.walk(ROOT)) == norm(os.walk(ROOT, topdown=False)))

# --- order -------------------------------------------------------------------

rec('topdown_parents_first',
    lambda: parents_before_children(order_of(os.walk(ROOT))))
rec('bottomup_children_first',
    lambda: parents_before_children(
        list(reversed(order_of(os.walk(ROOT, topdown=False))))))
rec('topdown_root_first', lambda: order_of(os.walk(ROOT))[0])
rec('bottomup_root_last', lambda: order_of(os.walk(ROOT, topdown=False))[-1])


# --- symlinks ----------------------------------------------------------------
#
# ``lnk'' is a symlink to a directory: it is reported in dirnames either way
# (is_dir follows the link), and descended into only with followlinks=True.

rec('link_listed_as_dir',
    lambda: [dn for d, dn, fn in norm(os.walk(ROOT)) if d == 'b'][0])
rec('link_not_followed_by_default',
    lambda: [d for d, dn, fn in norm(os.walk(ROOT))if d.startswith('b/lnk')])
rec('link_followed_when_asked',
    lambda: sorted(d for d, dn, fn in norm(os.walk(ROOT, followlinks=True))
                   if d.startswith('b/lnk')))

rec('islink_on_link', lambda: os.path.islink(os.path.join(ROOT, 'b', 'lnk')))
rec('islink_on_dir', lambda: os.path.islink(os.path.join(ROOT, 'a')))
rec('islink_on_file', lambda: os.path.islink(os.path.join(ROOT, 'f0.txt')))
# islink answers False for what it cannot stat -- it never raises.
rec('islink_on_missing', lambda: os.path.islink(os.path.join(ROOT, 'nope')))


# --- pruning: the reason os.walk must be lazy --------------------------------

def prune_aa():
    out = []
    for d, dn, fn in os.walk(ROOT):
        if 'aa' in dn:
            dn.remove('aa')
        out.append((_rel(d), sorted(dn), sorted(fn)))
    return sorted(out)


rec('pruned', prune_aa)


def prune_bottom_up():
    """Mutating dirnames bottom-up has NO effect -- by the time the caller sees
    it, those directories have already been walked.  CPython documents this, and
    an implementation that re-read the list after yielding would differ here."""
    out = []
    for d, dn, fn in os.walk(ROOT, topdown=False):
        if 'aa' in dn:
            dn.remove('aa')
        out.append(_rel(d))
    return sorted(out)


rec('bottom_up_pruning_has_no_effect', prune_bottom_up)

# A generator, not a list: it is its own iterator.
rec('walk_is_its_own_iterator', lambda: iter(os.walk(ROOT)) is not None
    and hasattr(os.walk(ROOT), '__next__'))


# --- errors ------------------------------------------------------------------
#
# A directory that cannot be listed is SKIPPED, not yielded as an empty triple.

MISSING = os.path.join(ROOT, 'nope')

rec('missing_top_yields_nothing', lambda: list(os.walk(MISSING)))


def onerror_sees_it():
    seen = []
    result = list(os.walk(MISSING, onerror=lambda e: seen.append(type(e).__name__)))
    return (result, seen)


rec('onerror_is_called', onerror_sees_it)


def onerror_may_abort():
    def boom(e):
        raise e
    try:
        list(os.walk(MISSING, onerror=boom))
        return 'no error'
    except OSError as e:
        return type(e).__name__


rec('onerror_may_reraise', onerror_may_abort)

# ...and the two os.listdir errors os.walk's error handling rests on.  GsFile's
# directory listing EXPANDS A PATTERN rather than opening a directory, so before
# this both of these answered a plausible non-error: [] for a missing path, and
# ['a.txt'] for a file -- the second being the dangerous one, since a recursive
# walker reads it as a directory containing itself.
def raises(fn):
    """The exception's CLASS NAME, and whether OSError catches it.  Not its
    str(), which carries the temp-directory path and so cannot go in a
    committed EXPECTED table."""
    try:
        fn()
        return 'no error'
    except OSError as e:
        return (type(e).__name__, isinstance(e, OSError))


rec('listdir_missing', lambda: raises(lambda: os.listdir(MISSING)))
rec('listdir_on_a_file',
    lambda: raises(lambda: os.listdir(os.path.join(ROOT, 'f0.txt'))))


# --- tear the tree down with os.walk itself ----------------------------------
#
# Exactly the shape test_reprlib's tearDown uses, and the reason this work
# happened: walk bottom-up, remove files, then remove the directories.

def teardown():
    for dirpath, dirnames, filenames in os.walk(ROOT, topdown=False):
        for name in filenames:
            os.remove(os.path.join(dirpath, name))
        for name in dirnames:
            p = os.path.join(dirpath, name)
            if os.path.islink(p):
                os.remove(p)
            else:
                os.rmdir(p)
    os.rmdir(ROOT)
    return os.path.exists(ROOT)


rec('teardown_removes_the_tree', teardown)


EXPECTED = {
    'bottom_up_pruning_has_no_effect': ['.', 'a', 'a/aa', 'a/ab', 'b'],
    'bottomup': [('.', ['a', 'b'], ['f0.txt']),
                 ('a', ['aa', 'ab'], ['f1.txt']),
                 ('a/aa', [], ['f2.txt']),
                 ('a/ab', [], []),
                 ('b', ['lnk'], ['f3.txt'])],
    'bottomup_children_first': True,
    'bottomup_root_last': '.',
    'islink_on_dir': False,
    'islink_on_file': False,
    'islink_on_link': True,
    'islink_on_missing': False,
    'link_followed_when_asked': ['b/lnk', 'b/lnk/aa', 'b/lnk/ab'],
    'link_listed_as_dir': ['lnk'],
    'link_not_followed_by_default': [],
    'listdir_missing': ('FileNotFoundError', True),
    'listdir_on_a_file': ('NotADirectoryError', True),
    'missing_top_yields_nothing': [],
    'onerror_is_called': ([], ['FileNotFoundError']),
    'onerror_may_reraise': 'FileNotFoundError',
    'pruned': [('.', ['a', 'b'], ['f0.txt']),
               ('a', ['ab'], ['f1.txt']),
               ('a/ab', [], []),
               ('b', ['lnk'], ['f3.txt'])],
    'same_set_either_way': True,
    'teardown_removes_the_tree': False,
    'topdown': [('.', ['a', 'b'], ['f0.txt']),
                ('a', ['aa', 'ab'], ['f1.txt']),
                ('a/aa', [], ['f2.txt']),
                ('a/ab', [], []),
                ('b', ['lnk'], ['f3.txt'])],
    'topdown_parents_first': True,
    'topdown_root_first': '.',
    'walk_is_its_own_iterator': True,
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-34s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
