# The last runtime gaps behind CPython's test_pickle.  None is in pickle:
#
#   * A ``**'' operand that is not a mapping: CPython's TypeError starts with
#     the callee's name, ``functools.partial() argument after ** must be a
#     mapping, not list'' (test_bad_newobj_ex_args); Grail's started at
#     ``argument''.
#   * ``Sub.__new__'' for a Python subclass of a built-in was a different
#     object from ``int.__new__'' / ``tuple.__new__'' / ..., so pickle refused
#     to save ``cls.__new__'' by name (test_complex_newobj_ex).
#   * ``int.__new__(cls, ..., base=16)'' and ``Sub('FACE', base=16)'' ignored
#     the keyword; ``int.__new__(S, 'FACE', 16)'' refused three positionals;
#     ``int.__new__(str, 1)'' answered an empty str.
#   * Two threads importing one module: the second found it in sys.modules
#     half-built and took it as done (test_unpickle_module_race).
#   * ``n << 1000000'' past GemStone's integer ceiling raised an uncatchable
#     NumericError; it is now OverflowError.  Grail-only check (CPython has no
#     ceiling), so it is recorded but not compared.
#
# EXPECTED was generated by RUNNING CPython 3.14.6 (``--emit``).

import functools
import os
import pickle
import shutil
import sys
import tempfile
import threading

r = {}


def _err(f):
    try:
        return repr(f())
    except Exception as e:
        return '%s: %s' % (type(e).__name__, e)


# --- the callee's name on a ``**'' error -------------------------------------

def f(*a, **k):
    pass


class C:
    def m(self, *a, **k):
        pass

    @staticmethod
    def s(*a, **k):
        pass


class K:
    pass


_bound = C().m
_static = C.s
_part = functools.partial
_builtin_len = len


def _err_mod(fn):
    # The callee's module is this file's name -- '__main__' when run, the
    # module name when imported (the SUnit test) -- so it is written <mod>.
    return _err(fn).replace(__name__ + '.', '<mod>.')


r['kwargs_splat_callee'] = repr([
    _err_mod(lambda: f(**[])), _err_mod(lambda: f(a=1, **[])), _err_mod(lambda: f(1, *[], **[])),
    _err_mod(lambda: _bound(**[])), _err_mod(lambda: _static(**[])), _err_mod(lambda: _part(**[])),
    _err_mod(lambda: K(**[])), _err_mod(lambda: _builtin_len(**[])),
])
r['star_messages'] = repr([_err(lambda: f(1, *42)), _err(lambda: f(*[], *42))])

# --- Sub.__new__ is the built-in's -------------------------------------------

_bases = (int, float, complex, str, bytes, bytearray, tuple, list, dict, set,
          frozenset, object)
_subs = {}
for _b in _bases:
    exec('class S(_b): pass', {'_b': _b}, _subs)
    _subs[_b] = _subs.pop('S')
r['sub_new_is_builtin_new'] = repr([_subs[b].__new__ is b.__new__ for b in _bases])


class _OwnNew(int):
    def __new__(cls, v):
        return int.__new__(cls, v)


r['own_new_is_own'] = repr([_OwnNew.__new__ is int.__new__,
                            type(_OwnNew(3)).__name__, int(_OwnNew(3))])

# --- int.__new__ and keywords -------------------------------------------------

_I = _subs[int]


def _iv(f):
    try:
        v = f()
        return (type(v).__name__, int(v))
    except Exception as e:
        return '%s: %s' % (type(e).__name__, e)


r['int_new_forms'] = repr([
    _iv(lambda: int('FACE', base=16)), _iv(lambda: int.__new__(int, 'FACE', base=16)),
    _iv(lambda: int.__new__(_I, 'FACE', 16)), _iv(lambda: int.__new__(_I, 'FACE', base=16)),
    _iv(lambda: _I('FACE', base=16)), _iv(lambda: _I.__new__(_I, 'FACE', base=16)),
    _iv(lambda: int.__new__(_I)), _iv(lambda: int.__new__(_I, 5)),
    _iv(lambda: _I()), _iv(lambda: _I('101', 2)),
    _iv(lambda: functools.partial(_I.__new__, _I, 'FACE', base=16)()),
])
r['int_new_refusals'] = repr([
    _err(lambda: int.__new__(bool, 0)), _err(lambda: int.__new__(str, 1)),
    _err(lambda: int(x=1)),
])


class _Newobj(int):
    def __getnewargs_ex__(self):
        return ('%X' % self,), {'base': 16}


_x = _Newobj.__new__(_Newobj, 0xface)
r['newobj_ex_round_trips'] = repr([
    (type(y).__name__, int(y))
    for y in (pickle.loads(pickle.dumps(_x, p)) for p in range(pickle.HIGHEST_PROTOCOL + 1))])

# --- one import from two threads ----------------------------------------------

_dir = tempfile.mkdtemp()
try:
    with open(os.path.join(_dir, 'fgap_locker.py'), 'w') as _f:
        _f.write('import threading\nbarrier = threading.Barrier(2)\n')
    with open(os.path.join(_dir, 'fgap_locking.py'), 'w') as _f:
        _f.write('import fgap_locker\nfgap_locker.barrier.wait()\n'
                 'class ToBeUnpickled(object):\n    pass\n')
    with open(os.path.join(_dir, 'fgap_sync.py'), 'w') as _f:
        _f.write('import threading\nbarrier = threading.Barrier(2)\n')
    with open(os.path.join(_dir, 'fgap_a.py'), 'w') as _f:
        _f.write('import fgap_sync\nfgap_sync.barrier.wait()\nimport fgap_b\nA = 1\n')
    with open(os.path.join(_dir, 'fgap_b.py'), 'w') as _f:
        _f.write('import fgap_sync\nfgap_sync.barrier.wait()\nimport fgap_a\nB = 2\n')
    sys.path.insert(0, _dir)
    import fgap_locker
    _pickled = b'\x80\x03cfgap_locking\nToBeUnpickled\nq\x00)\x81q\x01.'
    _results = []
    _start = threading.Barrier(3)

    def _load():
        _start.wait()
        try:
            _results.append(type(pickle.loads(_pickled)).__name__)
        except Exception as e:
            _results.append('%s: %s' % (type(e).__name__, e))

    _ts = [threading.Thread(target=_load) for _ in range(2)]
    for _t in _ts:
        _t.start()
    _start.wait()
    fgap_locker.barrier.wait()
    for _t in _ts:
        _t.join()
    r['import_race'] = repr(sorted(_results))

    import fgap_sync
    _done = []

    def _imp(n):
        __import__(n)
        _done.append(n)

    _ts = [threading.Thread(target=_imp, args=(n,)) for n in ('fgap_a', 'fgap_b')]
    for _t in _ts:
        _t.start()
    for _t in _ts:
        _t.join(30)
    r['import_cycle_across_threads'] = repr([
        [_t.is_alive() for _t in _ts], sorted(_done),
        sys.modules['fgap_a'].A, sys.modules['fgap_b'].B])
finally:
    sys.path.remove(_dir)
    for _m in ('fgap_locker', 'fgap_locking', 'fgap_sync', 'fgap_a', 'fgap_b'):
        sys.modules.pop(_m, None)
    shutil.rmtree(_dir, ignore_errors=True)

# --- the integer ceiling (Grail-only: recorded, not compared) ------------------

grail_only = {}
try:
    int('deadbeeffeedface', 16) << 1000000
    grail_only['huge_shift'] = 'no error'
except OverflowError as e:
    grail_only['huge_shift'] = 'OverflowError: %s' % e

EXPECTED = {
    'import_cycle_across_threads': "[[False, False], ['fgap_a', 'fgap_b'], 1, 2]",
    'import_race': "['ToBeUnpickled', 'ToBeUnpickled']",
    'int_new_forms': "[('int', 64206), ('int', 64206), ('S', 64206), ('S', 64206), ('S', 64206), ('S', 64206), ('S', 0), ('S', 5), ('S', 0), ('S', 5), ('S', 64206)]",
    'int_new_refusals': '[\'TypeError: int.__new__(bool) is not safe, use bool.__new__()\', \'TypeError: int.__new__(str): str is not a subtype of int\', "TypeError: int() got an unexpected keyword argument \'x\'"]',
    'kwargs_splat_callee': "['TypeError: <mod>.f() argument after ** must be a mapping, not list', 'TypeError: <mod>.f() argument after ** must be a mapping, not list', 'TypeError: <mod>.f() argument after ** must be a mapping, not list', 'TypeError: <mod>.C.m() argument after ** must be a mapping, not list', 'TypeError: <mod>.C.s() argument after ** must be a mapping, not list', 'TypeError: functools.partial() argument after ** must be a mapping, not list', 'TypeError: <mod>.K() argument after ** must be a mapping, not list', 'TypeError: len() argument after ** must be a mapping, not list']",
    'newobj_ex_round_trips': "[('_Newobj', 64206), ('_Newobj', 64206), ('_Newobj', 64206), ('_Newobj', 64206), ('_Newobj', 64206), ('_Newobj', 64206)]",
    'own_new_is_own': "[False, '_OwnNew', 3]",
    'star_messages': "['TypeError: Value after * must be an iterable, not int', 'TypeError: Value after * must be an iterable, not int']",
    'sub_new_is_builtin_new': '[True, True, True, True, True, True, True, True, True, True, True, True]',
}


if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        for k in sorted(EXPECTED):
            print('%-4s %s' % ('OK' if r[k] == EXPECTED[k] else 'FAIL', k))
