# Fixture for PrintableReprAndPrintfTestCase.
#
# Three roots found closing CPython's test_format (its last 2 failures + 1
# error), plus the block of str %-format diagnostics that fixing the first of
# them exposed:
#
# 1. repr() escaped ASCII CONTROL characters only, so every other
#    non-printable code point came out verbatim -- unassigned (Cn),
#    format (Cf), private-use (Co) and the non-ASCII separators (Zs/Zl/Zp).
#    str.isprintable() had the same range-based approximation.  Both now use
#    the Unicode general category, via GemStone's libicu-backed
#    Character>>unicodeCategory.
#
# 2. Scientific-notation digits were generated by normalising the mantissa
#    into [1, 10) with repeated FLOAT division/multiplication, which lost the
#    value before rounding ran: '%.2e' % 1505.0 rounded a tie the wrong way,
#    and '%.17e' % 0.1 lost every significant digit.  %g additionally chose
#    fixed-vs-scientific from the PRE-rounding exponent.
#
# 3. bytes %-format had no %r (an alias for %a), used str's wording for a bad
#    float operand, never checked for unconsumed arguments, and could not
#    report the length of a wrong-length bytes operand to %c.
#
# 4. Reaching test_str_format's second half exposed str %-format diagnostics
#    that were missing entirely: an unknown conversion did not report its hex
#    code or index, %c accepted anything (formatting 3.14 as "3.14"!) and let
#    an out-of-range code point reach Character class>>codePoint:, whose
#    OutOfRange is a SMALLTALK error no Python ``except'' can catch -- so
#    "%c" % -1 aborted the module.  The float and int converters silently
#    PARSED a string, because GemStone's String>>asFloat/asInteger do.

out = {}


def _run(label, fn):
    try:
        out[label] = repr(fn())
    except BaseException as e:
        out[label] = "%s: %s" % (type(e).__name__, e)


# --- 1. repr() / isprintable() follow the Unicode general category ----------

# Cn (unassigned) -- the case test_format pins
_run("repr_unassigned", lambda: repr(chr(0x378)))
_run("repr_unassigned_high", lambda: repr(chr(0xe0002)))
# Cc (control) above ASCII, Cf (format), Co (private use)
_run("repr_c1_control", lambda: repr(chr(0x80)))
_run("repr_format_char", lambda: repr(chr(0x200d)))
_run("repr_private_use", lambda: repr(chr(0xe000)))
# Zs / Zl / Zp -- separators, none printable except ASCII space
_run("repr_nbsp", lambda: repr(chr(0xa0)))
_run("repr_ideographic_space", lambda: repr(chr(0x3000)))
_run("repr_line_separator", lambda: repr(chr(0x2028)))
_run("repr_para_separator", lambda: repr(chr(0x2029)))
_run("repr_ascii_space", lambda: repr(" "))

# Printable non-ASCII must stay LITERAL -- repr() is not ascii().  Compared
# inside the fixture so the expectation needs no non-ASCII source literal.
def _stays_literal(cp):
    return repr(chr(cp)) == "'" + chr(cp) + "'"


_run("repr_printable_lm", lambda: _stays_literal(0x374))
_run("repr_printable_latin", lambda: _stays_literal(0xe9))
_run("repr_printable_greek", lambda: _stays_literal(0x3b1))
_run("repr_printable_emoji", lambda: _stays_literal(0x1f600))
_run("repr_printable_cjk", lambda: _stays_literal(0x4e2d))
# ASCII control escapes keep their established spellings
_run("repr_newline", lambda: repr("\n"))
_run("repr_nul", lambda: repr(chr(0)))
_run("repr_del", lambda: repr(chr(0x7f)))
# ascii() escapes printable non-ASCII too, which is what makes it different
_run("ascii_printable_nonascii", lambda: ascii(chr(0x544)))

_run("isprintable_unassigned", lambda: chr(0x378).isprintable())
_run("isprintable_nbsp", lambda: chr(0xa0).isprintable())
_run("isprintable_format_char", lambda: chr(0x200d).isprintable())
_run("isprintable_ascii_space", lambda: " ".isprintable())
_run("isprintable_printable_lm", lambda: chr(0x374).isprintable())
_run("isprintable_empty", lambda: "".isprintable())
_run("isprintable_newline", lambda: "\n".isprintable())


# --- 2. exact scientific digits --------------------------------------------

# an exact TIE must round to even, not up
_run("sci_tie_to_even", lambda: "%.2e" % 1505.0)
_run("sci_tie_to_even_neg", lambda: "%.2e" % -1505.0)
_run("sci_tie_g", lambda: "%.3g" % 1505.0)
_run("sci_tie_g_alt", lambda: "%#.3g" % 1505.0)
_run("sci_tie_g_format", lambda: format(1505.0, ".3g"))
_run("sci_tie_g_format_alt", lambda: format(1505.0, "#.3g"))
_run("sci_tie_g6", lambda: format(12300050.0, ".6g"))
_run("sci_tie_g6_alt", lambda: format(12300050.0, "#.6g"))
# a high precision must keep the value's real digits
_run("sci_high_precision", lambda: "%.17e" % 0.1)
_run("sci_g17", lambda: format(0.1, ".17g"))
# %g picks notation from the POST-rounding exponent
_run("g_exponent_after_rounding", lambda: "%.3g" % 999.9)
_run("g_exponent_after_rounding2", lambda: "%.2g" % 999.9)
# ordinary cases must be unchanged
_run("sci_plain", lambda: "%.3e" % 1.0)
_run("sci_zero", lambda: "%.3e" % 0.0)
_run("sci_zero_g", lambda: "%.3g" % 0.0)
_run("sci_big_exponent", lambda: "%.3e" % 1e300)
_run("sci_small_exponent", lambda: "%.3e" % 1e-300)
_run("sci_denormal", lambda: "%.3e" % 5e-324)
_run("sci_half_even_down", lambda: "%.1e" % 1.25)
_run("sci_half_even_up", lambda: "%.1e" % 1.35)
_run("g_fixed_branch", lambda: "%.3g" % 0.0001505)


# --- 3. bytes %-format -----------------------------------------------------


class FakeBytes(object):
    def __bytes__(self):
        return b'123'


_run("bytes_r_is_ascii_alias", lambda: b"%r" % b"ghi")
_run("bytes_r_on_str", lambda: b"%r" % "jkl")
_run("bytes_r_escapes_nonascii", lambda: b"%r" % chr(0x544))
_run("bytes_r_on_float", lambda: b"%r" % 3.25)
_run("bytearray_r", lambda: bytearray(b"%r") % b"ghi")
_run("bytes_a_still_works", lambda: b"%a" % b"ghi")
_run("bytes_b_dunder", lambda: b"%b" % FakeBytes())
_run("bytes_float_arg_wording", lambda: b'%g' % '1')
_run("bytes_float_arg_wording_bytes", lambda: b'%g' % b'1')
_run("bytes_int_arg_wording", lambda: b'%i' % '1')
_run("bytes_leftover_args", lambda: b'no format' % 7)
_run("bytes_leftover_args_bytes", lambda: b'no format' % b'1')
_run("bytearray_leftover_args", lambda: b'no format' % bytearray(b'1'))
_run("bytes_c_wrong_length", lambda: b"%c" % b"Za")
_run("bytes_c_wrong_length_ba", lambda: b"%c" % bytearray(b"Za"))
_run("bytes_c_str", lambda: b"%c" % "Y")
_run("bytes_c_range", lambda: b"%c" % 256)
_run("bytes_unknown_conv", lambda: b"%z.1f" % 0)
_run("bytes_mapping_extra_keys_ok", lambda: b'%(a)s' % {b'a': b'1', b'b': b'2'})


# --- 4. str %-format diagnostics -------------------------------------------

_run("str_unknown_conv_index", lambda: 'abc %b' % 1)
_run("str_unknown_conv_z", lambda: '%z.1f' % 0)
# NOTE: "'%c' % -1" lives in printf_char_range.py, not here.  Before the fix it
# raised a Smalltalk OutOfRange, which aborts the whole module LOAD -- keeping
# it in this file made every other expectation here unreachable, so a
# regression in any one of them would have been indistinguishable from that one.
_run("str_c_float", lambda: '%c' % 3.14)
_run("str_c_length2", lambda: '%c' % 'ab')
_run("str_c_bytes", lambda: '%c' % b'x')
_run("str_c_ok_int", lambda: '%c' % 65)
_run("str_c_ok_char", lambda: '%c' % 'A')
_run("str_c_ok_bool", lambda: '%c' % True)
_run("str_float_conv_rejects_str", lambda: '%g' % '1')
_run("str_int_conv_rejects_str", lambda: '%i' % '1')
_run("str_hex_conv_rejects_str", lambda: '%x' % '1')
_run("str_leftover_args", lambda: 'no format' % '1')
_run("str_leftover_tuple", lambda: '%s' % ('a', 'b'))
_run("str_mapping_extra_keys_ok", lambda: '%(a)s' % {'a': 1, 'b': 2})
# the conversions that must keep working
_run("str_int_conv_float_truncates", lambda: '%d' % 3.7)
_run("str_int_conv_float_neg", lambda: '%d' % -3.7)
_run("str_float_conv_int", lambda: '%.2f' % 3)
_run("str_int_conv_bool", lambda: '%d' % True)
# a LIST on the right is ONE value; only a tuple unpacks into arguments
_run("str_s_conv_any", lambda: '%s' % [1, 2])
_run("str_list_is_one_value", lambda: '%s and %s' % ([1], [2, 3]))
_run("str_list_not_unpacked", lambda: '%s %s' % [1, 2])
_run("str_tuple_is_unpacked", lambda: '%s %s' % (1, 2))
_run("bytes_list_is_one_value", lambda: b'%b' % [b'a'])
_run("bytes_tuple_is_unpacked", lambda: b'%b %b' % (b'a', b'b'))

RESULTS = out
