# What the `raise` statement is actually defined to do.
#
# Four separate holes, all of them QUIET -- every one produced a plausible
# exception that was simply the wrong one, so nothing crashed and nothing said
# anything was amiss.
#
# 1. `raise Cls` IS `raise Cls()`.  Grail signalled the CLASS instead when
#    nothing was being handled, so a user __init__ never ran: a class whose
#    __init__ raises reported the class it was trying to build rather than the
#    error that stopped it being built.  A user __new__ never ran either, so a
#    __new__ answering something that is not an exception at all went unnoticed
#    where CPython owes a TypeError naming both classes.
#
# 2. A CLASS after `from` is instantiated too.  `raise IndexError from KeyError`
#    left __cause__ holding the KeyError CLASS -- so `isinstance(e.__cause__,
#    KeyError)` was False, and every consumer downstream got a type where it
#    expected an exception.
#
# 3. A bare `raise` re-raises whatever sys.exc_info() points at, which is a
#    property of the THREAD and not of the source text.  Grail decided it from
#    the AST, and the two disagree in both directions -- a bare raise in a
#    called function saw nothing, and one inside a `finally` re-raised the
#    handler's exception instead of the one in flight through it.
#
# 4. __context__ is set on EVERY exception raised while another is handled, not
#    only on ones a `raise` statement produced.  A NameError from an undefined
#    name, or anything raised inside a context manager's __exit__, arrived with
#    __context__ None -- and a traceback with no context loses the "During
#    handling of the above exception" half, which is the part that says why.
#
# NOT COVERED: the traceback OBJECT.  `types.TracebackType` is still a stub
# class here, so `isinstance(e.__traceback__, types.TracebackType)` is False and
# tb_next cannot be assigned.  That is a different subsystem from the raise
# statement and is left alone.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

r = {}

MOD = __name__


def _norm(s):
    """The module name differs between the fixture gate (__main__) and the
    SUnit peer (its own name), and it appears inside CPython's TypeError."""
    return None if s is None else s.replace("'" + MOD + ".", "'<mod>.")


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, _norm(str(e)))


# --- 1. `raise Cls` is `raise Cls()` ----------------------------------------

class InitRaises(Exception):
    def __init__(self):
        raise RuntimeError('from __init__')


class NewReturnsJunk(Exception):
    def __new__(cls, *a):
        return object()


def _bare_init_raises():
    raise InitRaises


def _bare_new_junk():
    raise NewReturnsJunk


rec('bare_class_init_raises', _bare_init_raises)
rec('bare_class_new_junk', _bare_new_junk)


# The same two with an exception already being HANDLED, because Grail took a
# different path in each case and only one of them was wrong.
def _handled(fn):
    def go():
        try:
            1 / 0
        except ZeroDivisionError:
            fn()
    return go


rec('handled_class_init_raises', _handled(_bare_init_raises))
rec('handled_class_new_junk', _handled(_bare_new_junk))

# ...and the CALL form, which reaches construction by a third route -- and
# whose message is CPython's OTHER one, because the diagnosis there comes from
# the value the call produced rather than from the class that was called.
def _call_new_junk():
    raise NewReturnsJunk()


rec('call_form_new_junk', _call_new_junk)


# --- 2. a class after `from` is instantiated --------------------------------

def _class_cause():
    try:
        raise IndexError from KeyError
    except IndexError as e:
        return (type(e.__cause__).__name__, isinstance(e.__cause__, KeyError))


def _cause_init_raises():
    raise IndexError from InitRaises


def _cause_new_junk():
    raise IndexError from NewReturnsJunk


rec('class_cause', _class_cause)
rec('cause_init_raises', _cause_init_raises)
rec('cause_new_junk', _cause_new_junk)


# --- 3. a bare `raise` is a runtime question --------------------------------

def _nested_reraise():
    def inner():
        raise
    try:
        raise TypeError('foo')
    except TypeError:
        inner()


def _finally_reraise():
    try:
        raise TypeError('foo')
    except TypeError:
        try:
            raise KeyError('caught')
        finally:
            raise


def _reraise_with_nothing_active():
    raise


rec('nested_reraise', _nested_reraise)
rec('finally_reraise', _finally_reraise)
rec('reraise_nothing_active', _reraise_with_nothing_active)


# --- 4. __context__ is not only for the `raise` statement -------------------

def _context_of_name_error():
    try:
        try:
            1 / 0
        except ZeroDivisionError:
            xyzzy                                    # noqa: F821
    except NameError as e:
        return type(e.__context__).__name__ if e.__context__ is not None else None


def _context_inside_exit():
    class CM:
        def __enter__(self):
            return self

        def __exit__(self, t, v, tb):
            xyzzy                                    # noqa: F821
    try:
        with CM():
            1 / 0
    except NameError as e:
        return type(e.__context__).__name__ if e.__context__ is not None else None


def _context_of_attribute_error():
    class Empty:
        pass
    try:
        try:
            1 / 0
        except ZeroDivisionError:
            Empty().nope
    except AttributeError as e:
        return type(e.__context__).__name__ if e.__context__ is not None else None


rec('context_of_name_error', _context_of_name_error)
rec('context_inside_exit', _context_inside_exit)
rec('context_of_attribute_error', _context_of_attribute_error)


# --- what must KEEP working -------------------------------------------------
#
# The guards against over-applying any of the above.  Every one of these is an
# ordinary raise that the changes route differently than before.

def _plain_class():
    try:
        raise IndexError
    except IndexError as e:
        return (type(e).__name__, isinstance(e, IndexError), e.args)


def _plain_call():
    try:
        raise KeyError('k')
    except KeyError as e:
        return (type(e).__name__, e.args, str(e))


def _instance_cause():
    c = KeyError('c')
    try:
        raise IndexError from c
    except IndexError as e:
        return e.__cause__ is c


def _from_none():
    try:
        try:
            raise TypeError('foo')
        except TypeError:
            raise ValueError() from None
    except ValueError as e:
        return (isinstance(e.__context__, TypeError), e.__cause__ is None)


def _reraise_same_object():
    first = IndexError('first')
    try:
        try:
            raise first
        except IndexError:
            raise
    except IndexError as e:
        return e is first


def _user_init_runs():
    class WithInit(Exception):
        def __init__(self, a, b):
            super().__init__(a)
            self.b = b
    try:
        raise WithInit(1, 2)
    except WithInit as e:
        return (e.args, e.b)


rec('plain_class', _plain_class)
rec('plain_call', _plain_call)
rec('instance_cause', _instance_cause)
rec('from_none', _from_none)
rec('reraise_same_object', _reraise_same_object)
rec('user_init_runs', _user_init_runs)


EXPECTED = {
    'bare_class_init_raises': 'RuntimeError: from __init__',
    'bare_class_new_junk': "TypeError: calling <class '<mod>.NewReturnsJunk'> should have returned an instance of BaseException, not <class 'object'>",
    'call_form_new_junk': 'TypeError: exceptions must derive from BaseException',
    'cause_init_raises': 'RuntimeError: from __init__',
    'cause_new_junk': "TypeError: calling <class '<mod>.NewReturnsJunk'> should have returned an instance of BaseException, not <class 'object'>",
    'class_cause': ('KeyError', True),
    'context_inside_exit': 'ZeroDivisionError',
    'context_of_attribute_error': 'ZeroDivisionError',
    'context_of_name_error': 'ZeroDivisionError',
    'finally_reraise': "KeyError: 'caught'",
    'from_none': (True, True),
    'handled_class_init_raises': 'RuntimeError: from __init__',
    'handled_class_new_junk': "TypeError: calling <class '<mod>.NewReturnsJunk'> should have returned an instance of BaseException, not <class 'object'>",
    'instance_cause': True,
    'nested_reraise': 'TypeError: foo',
    'plain_call': ('KeyError', ('k',), "'k'"),
    'plain_class': ('IndexError', True, ()),
    'reraise_nothing_active': 'RuntimeError: No active exception to reraise',
    'reraise_same_object': True,
    'user_init_runs': ((1,), 2),
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
