# ``reprlib`` and the repr of a ``range``.
#
# TWO FIXES, related only in that reprlib's own test suite is what surfaced both.
#
# 1. reprlib was a 132-line hand-written SUBSET of CPython's 231-line module, and
#    it diverged in a dozen visible ways at once: the nesting depth cut off one
#    level early, frozensets truncated differently, ``indent=`` was missing
#    entirely, Repr() took no keyword arguments, and repr_instance was not used
#    as the fallback it is meant to be.  Each is a detail of a well-specified
#    algorithm, so the module is now VENDORED from CPython 3.14.6 -- smaller to
#    maintain than a parallel implementation, and correct by construction.
#
# 2. ``repr(range(...))`` PRINTED A DIFFERENT RANGE than the one being printed.
#    Two independent bugs in one method:
#
#      * it abbreviated ``range(0, N, 1)`` to ``range(N)``, but CPython never
#        abbreviates -- repr(range) is the normalised three-field form, not the
#        constructor call that happened to be written;
#      * it computed the exclusive stop as ``to + 1``, which is the
#        inclusive-to-exclusive conversion for a POSITIVE step only.  GemStone's
#        Interval keeps an inclusive bound, so ``range(5, 0, -1)`` printed as
#        ``range(5, 2, -1)``.
#
#    The second is the one that matters: the CONTENTS were right ([5, 4, 3, 2, 1])
#    and ``.start`` / ``.stop`` / ``.step`` all reported the right values, so the
#    object was correct and only its printed form lied -- which is exactly the
#    kind of thing that survives review.  ``eval(repr(r))`` built a different
#    range.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import reprlib

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- range repr: always three fields, and the right stop --------------------

rec('range_one_arg', lambda: repr(range(1)))
rec('range_two_arg', lambda: repr(range(2, 5)))
rec('range_step', lambda: repr(range(0, 10, 2)))
rec('range_negative_step', lambda: repr(range(5, 0, -1)))
rec('range_empty', lambda: repr(range(0)))


def _round_trips():
    """The property the repr exists for: it names THIS range."""
    out = []
    for rng in (range(1), range(2, 5), range(0, 10, 2), range(5, 0, -1)):
        rebuilt = eval(repr(rng))
        out.append((list(rebuilt) == list(rng),
                    (rebuilt.start, rebuilt.stop, rebuilt.step)
                    == (rng.start, rng.stop, rng.step)))
    return out


def _repr_agrees_with_attributes():
    rng = range(5, 0, -1)
    return (repr(rng) == 'range(%d, %d, %d)' % (rng.start, rng.stop, rng.step),
            list(rng))


rec('round_trips', _round_trips)
rec('repr_agrees_with_attributes', _repr_agrees_with_attributes)


# --- reprlib: the behaviours the hand-written subset got wrong --------------

rec('nesting_depth', lambda: reprlib.repr([[[[[[[[]]]]]]]]))
rec('long_list', lambda: reprlib.repr(list(range(20))))
rec('long_string', lambda: reprlib.repr('x' * 100))
rec('deep_dict', lambda: reprlib.repr({'a': {'b': {'c': {'d': {'e': 1}}}}}))


def _keyword_construction():
    """Repr() takes its limits as keyword arguments -- the subset took none."""
    obj = reprlib.Repr(maxlist=2, maxlevel=2)
    return obj.repr([1, 2, 3, 4, 5])


def _indent_feature():
    """``indent=`` was missing entirely."""
    obj = reprlib.Repr(indent=4)
    return obj.repr([1, 'spam', {'eggs': True}])


def _invalid_indent():
    obj = reprlib.Repr(indent=-1)
    obj.repr([1, 2, 3])


rec('keyword_construction', _keyword_construction)
rec('indent_feature', _indent_feature)
rec('invalid_indent', _invalid_indent)


def _recursive_repr_guard():
    """recursive_repr short-circuits a self-referential repr.

    The wrapper is applied EXPLICITLY rather than with @-syntax, and that is not
    stylistic: Grail drops non-declarative method decorators, so an
    ``@reprlib.recursive_repr()'' on a __repr__ never takes effect and the repr
    recurses until the stack runs out.  That gap is pre-existing and unrelated to
    reprlib -- writing the probe this way keeps it a test of recursive_repr rather
    than of decorator application.  (tests/python/pkg_scaffolding/reprlib_recursive.py
    makes the same choice for the same reason.)
    """
    def plain_repr(self):
        return '<Cycle %r>' % (self.me,)

    class Cycle:
        def __init__(self):
            self.me = self
        __repr__ = reprlib.recursive_repr()(plain_repr)
    return repr(Cycle())


rec('recursive_repr_guard', _recursive_repr_guard)


EXPECTED = {
    'deep_dict': "{'a': {'b': {'c': {'d': {'e': 1}}}}}",
    'indent_feature': "[\n    1,\n    'spam',\n    {\n        'eggs': True,\n    },\n]",
    'invalid_indent': 'ValueError: Repr.indent cannot be negative int (was -1)',
    'keyword_construction': '[1, 2, ...]',
    'long_list': '[0, 1, 2, 3, 4, 5, ...]',
    'long_string': "'xxxxxxxxxxxx...xxxxxxxxxxxxx'",
    'nesting_depth': '[[[[[[[...]]]]]]]',
    'range_empty': 'range(0, 0)',
    'range_negative_step': 'range(5, 0, -1)',
    'range_one_arg': 'range(0, 1)',
    'range_step': 'range(0, 10, 2)',
    'range_two_arg': 'range(2, 5)',
    'recursive_repr_guard': '<Cycle ...>',
    'repr_agrees_with_attributes': (True, [5, 4, 3, 2, 1]),
    'round_trips': [(True, True), (True, True), (True, True), (True, True)],
}

if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-30s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
