# Runtime gaps that CPython's test_pickle exposed, beyond pickle itself.
#
# Each section is one defect.  test_pickle hit it through pickle, but none of
# them is a pickle bug, and each had a symptom of its own outside it:
#
#   * os.path's Smalltalk dirname/basename/split/splitext/normpath disagreed
#     with posixpath on ordinary inputs -- dirname('a.txt') was '.', so
#     http.server's translate_path skipped every URL component, and
#     split('/a') was ('', 'a').  A bytes argument ended the session.
#   * sys.intern answered a fresh string each call, and an instance __dict__
#     handed out a fresh key string on each read.
#   * A builtin method reached through a kernel implementation class named it:
#     str.index was 'CharacterCollection.index' in module
#     'CharacterCollection'.  A method a Python class inherits from a builtin
#     was a different object from the builtin's own.
#   * del f.__module__ raised AttributeError.
#   * os.stat_result was a plain object: not indexable, not comparable, not
#     picklable, and os.stat_result(...) could not be called.
#   * A str holding a lone surrogate had no replace / split / find / strip /
#     ... at all, and bytes(s, enc), getattr(module, s) and __import__(s)
#     each failed on one.
#   * super().m() from inside an instance override of m looped, once any
#     instance of the base had had m overridden.
#   * A @staticmethod / @classmethod read from the class __dict__ was the bare
#     function rather than the descriptor object.
#   * defaultdict and OrderedDict borrowed dict's repr, which made pprint
#     print every plain dict as a defaultdict once method identity was fixed.
#   * Error messages named the Grail class BoundMethod, and an empty attribute
#     name read "X object has no attribute (empty name)".
#   * urllib.request.urlretrieve, http.server's SimpleHTTPRequestHandler /
#     CGIHTTPRequestHandler and mimetypes.guess_file_type were missing.
#
# EXPECTED was generated by RUNNING CPython 3.14.6 (``--emit``).

import collections
import io
import os
import pickle
import sys
import tempfile
import types

r = {}


def _err(f):
    try:
        return repr(f())
    except Exception as e:
        return '%s: %s' % (type(e).__name__, e)


# --- os.path -------------------------------------------------------------------

_paths = ['', 'a', 'a.txt', '/', '//', '///', '/a', '//a', '///a', 'a/', 'a/b',
          'a/b/', 'a//b', '.', '..', '/.', '.a', 'a.', 'a.b.c', 'a/.b', '..b']
for _fn in ('dirname', 'basename', 'split', 'splitext', 'normpath'):
    r['path_' + _fn] = repr([getattr(os.path, _fn)(p) for p in _paths])
r['path_bytes'] = repr([os.path.dirname(b'a/b'), os.path.basename(b'a/b'),
                        os.path.split(b'/a'), os.path.splitext(b'x.py'),
                        os.path.normpath(b'a//./b/..')])
r['fspath_int'] = _err(lambda: os.fspath(1))


class _BadPath:
    def __fspath__(self):
        return 1


r['fspath_bad_return'] = _err(lambda: os.fspath(_BadPath()))

# --- interning -------------------------------------------------------------------

_a = ''.join(['spam', '!x'])
_b = ''.join(['spam', '!', 'x'])
r['intern_same_object'] = repr(sys.intern(_a) is sys.intern(_b))
r['intern_int'] = _err(lambda: sys.intern(1))


class _S(str):
    pass


r['intern_subclass'] = _err(lambda: sys.intern(_S('x')))


class _Obj:
    pass


_o = _Obj()
_o.attr_name = 1
r['dict_key_is_stable'] = repr(list(_o.__dict__)[0] is list(_o.__dict__)[0])
r['dict_key_is_interned'] = repr(list(_o.__dict__)[0] is sys.intern('attr_name'))

# --- builtin methods ---------------------------------------------------------------

r['builtin_qualnames'] = repr([m.__qualname__ for m in (
    str.index, set.__contains__, list.append, dict.get, frozenset.union)])
r['builtin_objclass'] = repr([str.index.__objclass__ is str,
                              list.append.__objclass__ is list])


class _T(tuple):
    pass


class _N(str):
    pass


class _L(list):
    pass


r['inherited_builtin_is_builtins'] = repr([
    _T.count is tuple.count, _N.count is str.count, _L.append is list.append])
r['pickle_builtin_methods'] = repr([
    pickle.loads(pickle.dumps(str.index))('abcd', 'c'),
    pickle.loads(pickle.dumps(_T.count))(_T((1, 2, 2)), 2)])


class _A:
    def __init__(self):
        self.a = 1


class _B:
    def __init__(self):
        self.b = 2


class _AB(_A, _B):
    def __init__(self):
        _A.__init__(self)
        _B.__init__(self)


r['explicit_base_inits'] = repr(sorted(vars(_AB()).items()))
r['python_init_qualname'] = repr(_A.__init__.__qualname__)

# --- function __module__ -------------------------------------------------------------


def _make():
    def f():
        pass
    return f


_f = _make()
del _f.__module__
r['del_function_module'] = repr(_f.__module__)

# --- os.stat_result ----------------------------------------------------------------

_st = os.stat(os.curdir)
r['stat_is_a_sequence'] = repr([len(_st), _st[0] == _st.st_mode,
                                _st[8] == int(_st.st_mtime), _st == tuple(_st)])
r['stat_names'] = repr([type(_st).__name__, type(_st).__module__,
                        type(_st.st_mtime).__name__])
_u = pickle.loads(pickle.dumps(_st))
r['stat_pickles'] = repr([_u == _st, type(_u) is type(_st),
                          _u.st_mtime == _st.st_mtime, _u.st_blksize == _st.st_blksize])
r['stat_repr_prefix'] = repr(repr(_st)[:24])
_made = os.stat_result(range(10))
r['stat_from_range'] = repr([_made.st_mtime, _made.st_blksize])
r['stat_too_short'] = _err(lambda: os.stat_result((1,) * 9))
r['stat_not_a_sequence'] = _err(lambda: os.stat_result(5))

# --- lone surrogates -------------------------------------------------------------------

_s = 'a\udc80b c'
r['surrogate_str_methods'] = ascii([
    _s.replace('b', 'X'), _s.replace('\udc80', ''), _s.split(), _s.split('\udc80'),
    _s.find('b'), _s.strip('a'), _s.partition(' '), _s.count('\udc80'),
    _s.index('c'), _s.isalpha(), _s.title(), _s.center(9, '*'), _s.zfill(8),
    _s.splitlines(), _s.removeprefix('a'), _s.expandtabs(), _s.isidentifier(),
    _s.isprintable(), _s.rsplit(' ', 1), _s.swapcase(), _s.capitalize(),
    _s.ljust(7), _s.rstrip('c'), '\udc80'.join(['x', 'y'])])
r['surrogate_translate'] = ascii([_s.translate({98: 'B', 0xdc80: 'Z', 32: None}),
                                  'ab'.translate({98: '\udc80'})])
r['surrogate_hasattr'] = repr([hasattr(_s, '__slots__'), hasattr(_s, 'upper')])
r['surrogate_bytes'] = _err(lambda: bytes('a\udbff', 'utf-8'))
_mod = sys.modules[__name__]
_name = 'g\udbff'
_mod.__dict__[_name] = 'found'
r['surrogate_getattr_module'] = repr(getattr(_mod, _name, 'MISSING'))
del _mod.__dict__[_name]
sys.modules[_name] = types.SimpleNamespace(v=3)
r['surrogate_import'] = repr(__import__(_name, level=0).v)
del sys.modules[_name]
r['surrogate_import_missing'] = ascii(_err(lambda: __import__('h\udbff', level=0)))

# --- super() past an instance override ---------------------------------------------------


class _Base:
    def load(self, pid):
        raise KeyError('base')


class _Sub(_Base):
    def load(self, pid):
        raise AssertionError('never')

    def _load(self, pid):
        try:
            super().load(pid)
        except KeyError as e:
            return 'base raised %s' % e


# Patching a PLAIN _Base instance first is what put the self-send dispatcher
# on _Base, which super() then found.
_plain = _Base()
_plain.load = lambda pid: 'patched'
_sub = _Sub()
_sub.load = _sub._load
r['super_bypasses_instance_override'] = repr([_plain.load(1), _sub.load(1)])

# --- class __dict__ descriptors ------------------------------------------------------------


class _M:
    @staticmethod
    def sm():
        return 'sm'

    @classmethod
    def cm(cls):
        return cls.__name__

    def im(self):
        return 'im'


r['class_dict_kinds'] = repr([type(_M.__dict__[n]).__name__ for n in ('sm', 'cm', 'im')])
r['class_dict_funcs'] = repr([_M.__dict__['sm'].__func__(), _M.__dict__['cm'].__func__(_M)])
r['descriptor_pickle'] = repr([_err(lambda: pickle.dumps(_M.__dict__[n])) for n in ('sm', 'cm')])

# --- collections reprs -------------------------------------------------------------------------

_dd = collections.defaultdict(list)
_dd['x'] = _dd
r['collections_reprs'] = repr([repr(collections.defaultdict(int, a=1)),
                               repr(collections.OrderedDict(a=1)),
                               repr(collections.OrderedDict()), repr(_dd),
                               collections.defaultdict.__repr__ is dict.__repr__])

# --- error messages ----------------------------------------------------------------------------


def _attr_err(o, name='spam'):
    try:
        getattr(o, name)
    except AttributeError as e:
        return str(e)


import math
r['callable_type_names'] = repr([_attr_err(math.log), _attr_err(len),
                                 _attr_err(_M.sm), _attr_err(_M.cm)])
r['empty_attribute_name'] = repr([_attr_err(math, ''), _attr_err(_Obj(), ''),
                                  _attr_err(_Obj, ''), _attr_err(1, '')])

# --- stdlib names ------------------------------------------------------------------------------

import http.server
import mimetypes
import urllib.request

r['stdlib_names'] = repr([callable(urllib.request.urlretrieve),
                          http.server.SimpleHTTPRequestHandler.__name__,
                          http.server.CGIHTTPRequestHandler.__name__,
                          mimetypes.guess_file_type('x.html')])

_root = tempfile.mkdtemp()
with open(os.path.join(_root, 'a.txt'), 'w') as _fh:
    _fh.write('hello world')
os.mkdir(os.path.join(_root, 'sub'))


class _Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, raw):
        self.rfile = io.BytesIO(raw)
        self.wfile = io.BytesIO()
        self.client_address = ('127.0.0.1', 1)
        self.server = None
        self.directory = _root

    def log_message(self, *args):
        pass


def _get(line):
    h = _Handler(line + b'\r\n\r\n')
    h.handle_one_request()
    head, _, body = h.wfile.getvalue().partition(b'\r\n\r\n')
    return head.split(b'\r\n')[0], body[:20]


r['simple_http_handler'] = repr([_get(b'GET /a.txt HTTP/1.1'), _get(b'GET /nope HTTP/1.1')[0],
                                 _get(b'GET /sub HTTP/1.1')[0]])

import shutil
shutil.rmtree(_root)

EXPECTED = {
    'builtin_objclass': '[True, True]',
    'builtin_qualnames': "['str.index', 'set.__contains__', 'list.append', 'dict.get', 'frozenset.union']",
    'callable_type_names': '["\'builtin_function_or_method\' object has no attribute \'spam\'", "\'builtin_function_or_method\' object has no attribute \'spam\'", "\'function\' object has no attribute \'spam\'", "\'function\' object has no attribute \'spam\'"]',
    'class_dict_funcs': "['sm', '_M']",
    'class_dict_kinds': "['staticmethod', 'classmethod', 'function']",
    'collections_reprs': '["defaultdict(<class \'int\'>, {\'a\': 1})", "OrderedDict({\'a\': 1})", \'OrderedDict()\', "defaultdict(<class \'list\'>, {\'x\': defaultdict(<class \'list\'>, {...})})", False]',
    'del_function_module': 'None',
    'descriptor_pickle': '["TypeError: cannot pickle \'staticmethod\' object", "TypeError: cannot pickle \'classmethod\' object"]',
    'dict_key_is_interned': 'True',
    'dict_key_is_stable': 'True',
    'empty_attribute_name': '["module \'math\' has no attribute \'\'", "\'_Obj\' object has no attribute \'\'", "type object \'_Obj\' has no attribute \'\'", "\'int\' object has no attribute \'\'"]',
    'explicit_base_inits': "[('a', 1), ('b', 2)]",
    'fspath_bad_return': 'TypeError: expected _BadPath.__fspath__() to return str or bytes, not int',
    'fspath_int': 'TypeError: expected str, bytes or os.PathLike object, not int',
    'inherited_builtin_is_builtins': '[True, True, True]',
    'intern_int': 'TypeError: intern() argument must be str, not int',
    'intern_same_object': 'True',
    'intern_subclass': "TypeError: can't intern _S",
    'path_basename': "['', 'a', 'a.txt', '', '', '', 'a', 'a', 'a', '', 'b', '', 'b', '.', '..', '.', '.a', 'a.', 'a.b.c', '.b', '..b']",
    'path_bytes': "[b'a', b'b', (b'/', b'a'), (b'x', b'.py'), b'a']",
    'path_dirname': "['', '', '', '/', '//', '///', '/', '//', '///', 'a', 'a', 'a/b', 'a', '', '', '/', '', '', '', 'a', '']",
    'path_normpath': "['.', 'a', 'a.txt', '/', '//', '/', '/a', '//a', '/a', 'a', 'a/b', 'a/b', 'a/b', '.', '..', '/', '.a', 'a.', 'a.b.c', 'a/.b', '..b']",
    'path_split': "[('', ''), ('', 'a'), ('', 'a.txt'), ('/', ''), ('//', ''), ('///', ''), ('/', 'a'), ('//', 'a'), ('///', 'a'), ('a', ''), ('a', 'b'), ('a/b', ''), ('a', 'b'), ('', '.'), ('', '..'), ('/', '.'), ('', '.a'), ('', 'a.'), ('', 'a.b.c'), ('a', '.b'), ('', '..b')]",
    'path_splitext': "[('', ''), ('a', ''), ('a', '.txt'), ('/', ''), ('//', ''), ('///', ''), ('/a', ''), ('//a', ''), ('///a', ''), ('a/', ''), ('a/b', ''), ('a/b/', ''), ('a//b', ''), ('.', ''), ('..', ''), ('/.', ''), ('.a', ''), ('a', '.'), ('a.b', '.c'), ('a/.b', ''), ('..b', '')]",
    'pickle_builtin_methods': '[2, 2]',
    'python_init_qualname': "'_A.__init__'",
    'simple_http_handler': "[(b'HTTP/1.0 200 OK', b'hello world'), b'HTTP/1.0 404 File not found', b'HTTP/1.0 301 Moved Permanently']",
    'stat_from_range': '[8, None]',
    'stat_is_a_sequence': '[10, True, True, True]',
    'stat_names': "['stat_result', 'os', 'float']",
    'stat_not_a_sequence': 'TypeError: constructor requires a sequence',
    'stat_pickles': '[True, True, True, True]',
    'stat_repr_prefix': "'os.stat_result(st_mode=1'",
    'stat_too_short': 'TypeError: os.stat_result() takes an at least 10-sequence (9-sequence given)',
    'stdlib_names': "[True, 'SimpleHTTPRequestHandler', 'CGIHTTPRequestHandler', ('text/html', None)]",
    'super_bypasses_instance_override': '[\'patched\', "base raised \'base\'"]',
    'surrogate_bytes': "UnicodeEncodeError: 'utf-8' codec can't encode character '\\udbff' in position 1: surrogates not allowed",
    'surrogate_getattr_module': "'found'",
    'surrogate_hasattr': '[False, True]',
    'surrogate_import': '3',
    'surrogate_import_missing': '"ModuleNotFoundError: No module named \'h\\\\udbff\'"',
    'surrogate_str_methods': "['a\\udc80X c', 'ab c', ['a\\udc80b', 'c'], ['a', 'b c'], 2, '\\udc80b c', ('a\\udc80b', ' ', 'c'), 1, 4, False, 'A\\udc80B C', '**a\\udc80b c**', '000a\\udc80b c', ['a\\udc80b c'], '\\udc80b c', 'a\\udc80b c', False, False, ['a\\udc80b', 'c'], 'A\\udc80B C', 'A\\udc80b c', 'a\\udc80b c  ', 'a\\udc80b ', 'x\\udc80y']",
    'surrogate_translate': "['aZBc', 'a\\udc80']",
}


if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        for k in sorted(EXPECTED):
            print('%-4s %s' % ('OK' if r[k] == EXPECTED[k] else 'FAIL', k))
