# A @staticmethod or @classmethod in a subclass overrides an ordinary method of
# its base -- for the base's own self-sends, and for reads off the class.
#
# Grail compiles both decorators onto the metaclass and a base's ``def m(self,
# ...)'' onto the base's instance side.  Two defects followed:
#
#   * the base's ``self.m(a, b)'' is a plain send to an instance, so it ran the
#     BASE's method and never the subclass's (pickle's _Unpickler.load_global
#     calls ``self.find_class(...)'' -- test_pickle test_custom_find_class);
#   * ``Sub.m(a, b)'' read the name off the class and found the base's
#     instance method first, so it raised a missing-argument TypeError.
#
# EXPECTED was generated by RUNNING CPython 3.14.6 (``--emit``).

import io
import pickle
import sys

r = {}


def _err(f):
    try:
        return repr(f())
    except Exception as e:
        return '%s: %s' % (type(e).__name__, e)


class Base:
    def find_class(self, m, n):
        return 'base'

    def load(self):
        return self.find_class('math', 'log')

    def load_kw(self):
        return self.find_class('math', n='log')

    def load_getattr(self):
        return getattr(self, 'find_class')('math', 'log')

    def zero(self):
        return 'base zero'

    def call_zero(self):
        return self.zero()


class Static(Base):
    @staticmethod
    def find_class(m, n):
        return ('static', m, n)

    @staticmethod
    def zero():
        return 'static zero'


class Klass(Base):
    @classmethod
    def find_class(cls, m, n):
        return (cls.__name__, m, n)


class Plain(Base):
    def find_class(self, m, n):
        return ('plain', m, n)


class StaticChild(Static):
    pass


class Middle(Base):
    pass


class DeepStatic(Middle):
    @staticmethod
    def find_class(m, n):
        return ('deep', m, n)


class OverStatic(Static):
    @classmethod
    def find_class(cls, m, n):
        return ('over', cls.__name__, m, n)


for _K in (Static, Klass, Plain, StaticChild, DeepStatic, OverStatic):
    _k = _K()
    r['self_send_' + _K.__name__] = repr([
        _err(_k.load), _err(_k.load_kw), _err(_k.load_getattr),
        _err(lambda: _K.find_class('a', 'b')),
        _err(lambda: _k.find_class('a', 'b'))])
r['zero_arg'] = repr([Static().call_zero(), Static.zero(), Static().zero()])
r['dict_kinds'] = repr([type(K.__dict__['find_class']).__name__
                        for K in (Static, Klass, Plain, DeepStatic, OverStatic)]
                       + ['find_class' in StaticChild.__dict__])
r['base_untouched'] = repr([Base().load(), _err(lambda: Base.find_class('a', 'b')),
                            Middle().load()])


# test_pickle's own shape: an Unpickler subclass whose find_class is static.
class _StaticUnpickler(pickle._Unpickler):
    @staticmethod
    def find_class(module_name, global_name):
        return (module_name, global_name)


class _ClassUnpickler(pickle._Unpickler):
    @classmethod
    def find_class(cls, module_name, global_name):
        return (module_name, global_name)


r['unpickler'] = repr([U(io.BytesIO(data)).load()
                       for U in (_StaticUnpickler, _ClassUnpickler)
                       for data in (b'cmath\nlog\n.', b'\x8c\x04math\x8c\x03log\x93.')])


# Redefining the class without the decorator leaves no forwarder behind.
class Redef(Base):
    @staticmethod
    def find_class(m, n):
        return 'first'


_first = Redef().load()


class Redef(Base):
    pass


r['redefined'] = repr([_first, Redef().load()])

EXPECTED = {
    'base_untouched': '[\'base\', "TypeError: Base.find_class() missing 1 required positional argument: \'n\'", \'base\']',
    'dict_kinds': "['staticmethod', 'classmethod', 'function', 'staticmethod', 'classmethod', False]",
    'redefined': "['first', 'base']",
    'self_send_DeepStatic': '["(\'deep\', \'math\', \'log\')", "(\'deep\', \'math\', \'log\')", "(\'deep\', \'math\', \'log\')", "(\'deep\', \'a\', \'b\')", "(\'deep\', \'a\', \'b\')"]',
    'self_send_Klass': '["(\'Klass\', \'math\', \'log\')", "(\'Klass\', \'math\', \'log\')", "(\'Klass\', \'math\', \'log\')", "(\'Klass\', \'a\', \'b\')", "(\'Klass\', \'a\', \'b\')"]',
    'self_send_OverStatic': '["(\'over\', \'OverStatic\', \'math\', \'log\')", "(\'over\', \'OverStatic\', \'math\', \'log\')", "(\'over\', \'OverStatic\', \'math\', \'log\')", "(\'over\', \'OverStatic\', \'a\', \'b\')", "(\'over\', \'OverStatic\', \'a\', \'b\')"]',
    'self_send_Plain': '["(\'plain\', \'math\', \'log\')", "(\'plain\', \'math\', \'log\')", "(\'plain\', \'math\', \'log\')", "TypeError: Plain.find_class() missing 1 required positional argument: \'n\'", "(\'plain\', \'a\', \'b\')"]',
    'self_send_Static': '["(\'static\', \'math\', \'log\')", "(\'static\', \'math\', \'log\')", "(\'static\', \'math\', \'log\')", "(\'static\', \'a\', \'b\')", "(\'static\', \'a\', \'b\')"]',
    'self_send_StaticChild': '["(\'static\', \'math\', \'log\')", "(\'static\', \'math\', \'log\')", "(\'static\', \'math\', \'log\')", "(\'static\', \'a\', \'b\')", "(\'static\', \'a\', \'b\')"]',
    'unpickler': "[('math', 'log'), ('math', 'log'), ('math', 'log'), ('math', 'log')]",
    'zero_arg': "['static zero', 'static zero', 'static zero']",
}


if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        for k in sorted(EXPECTED):
            print('%-4s %s' % ('OK' if r[k] == EXPECTED[k] else 'FAIL', k))
