# The struct module: layout modes, struct.error, and the buffer entry points.
#
# The load-bearing detail is that struct has TWO LAYOUT MODES and the DEFAULT
# is the one with padding.  An unprefixed format ("ci") is NATIVE: C sizes,
# C alignment.  A prefixed one ("=ci", "<ci") is STANDARD: fixed sizes, packed.
# Grail implemented only the standard sizes and applied them to native formats
# too, so every unprefixed mixed-type format produced the wrong size and the
# wrong byte layout -- silently, and in the common case rather than a corner.
#
# The other silent-wrongness cluster: pack() truncated out-of-range integers
# instead of raising, pack('f') truncated the mantissa instead of rounding to
# nearest (so a round trip returned a neighbouring float), and struct.error did
# not exist at all -- so "except struct.error:" raised AttributeError while
# "except ValueError:" wrongly caught, since CPython's struct.error subclasses
# Exception directly.
#
# EXPECTED below was generated by RUNNING CPython 3.14.6, not written by hand.

import struct

r = {}


def call(fn, *a, **kw):
    """Record either the value or the exception TYPE NAME plus message."""
    try:
        return repr(fn(*a, **kw))
    except BaseException as e:
        return type(e).__name__ + ': ' + str(e)


# --- struct.error is its own class, not ValueError --------------------------

r['error_name'] = struct.error.__name__
r['error_module'] = struct.error.__module__
r['error_is_not_valueerror'] = repr(issubclass(struct.error, ValueError))
r['error_is_exception'] = repr(issubclass(struct.error, Exception))

try:
    struct.calcsize('Z')
except struct.error as e:
    r['caught_by_struct_error'] = str(e)

# The half that a ValueError-based implementation got wrong in the other
# direction: this must NOT be caught as a ValueError.
try:
    struct.calcsize('Z')
    r['not_caught_as_valueerror'] = 'no raise'
except ValueError:
    r['not_caught_as_valueerror'] = 'wrongly caught as ValueError'
except struct.error:
    r['not_caught_as_valueerror'] = 'correct'

# --- native alignment: the default mode pads --------------------------------

r['native_ci'] = repr(struct.calcsize('ci'))
r['standard_ci'] = repr(struct.calcsize('=ci'))
r['native_pack_ci'] = repr(struct.pack('ci', b'a', 1))
r['standard_pack_ci'] = repr(struct.pack('=ci', b'a', 1))
# No TRAILING padding, unlike a C struct.
r['no_trailing_pad'] = repr(struct.calcsize('@qc'))
# A zero repeat count still aligns -- that is what "0i" is written for.
r['zero_count_aligns'] = repr(struct.calcsize('@ci0i'))

# --- native long is 8 bytes, standard long is 4 -----------------------------

r['native_long'] = repr(struct.calcsize('l'))
r['standard_long'] = repr(struct.calcsize('=l'))

# --- n/N are native-only ----------------------------------------------------

r['native_n'] = repr(struct.calcsize('@n'))
r['standard_n'] = call(struct.calcsize, '=n')
r['native_n_roundtrip'] = call(lambda: struct.unpack('@n', struct.pack('@n', -5)))

# --- out-of-range integers raise instead of truncating ----------------------

r['byte_256'] = call(struct.pack, 'B', 256)
r['byte_neg'] = call(struct.pack, 'B', -1)
r['short_big'] = call(struct.pack, 'h', 40000)
# A float is not an integer, even a whole-valued one.
r['float_for_int'] = call(struct.pack, 'i', 1.0)
# ...but bool IS an int.
r['bool_for_int'] = call(struct.pack, 'i', True)

# --- '?' packs truthiness, and any non-zero byte unpacks True ---------------

r['bool_pack_list'] = repr(struct.pack('?', []))
r['bool_pack_three'] = repr(struct.pack('?', 3))
r['bool_unpack_one'] = repr(struct.unpack('?', b'\x01'))
r['bool_unpack_seven'] = repr(struct.unpack('?', b'\x07'))
r['bool_unpack_zero'] = repr(struct.unpack('?', b'\x00'))

# --- float rounding: pack('f') rounds to NEAREST, not toward zero -----------
#
# CPython's own test_705836 exists for this: a carry out of the discarded
# mantissa bits must propagate into the exponent.  Truncating returns the
# neighbouring float instead, which round-trips to a different number.
_round_trip = []
for _base in (2, 4, 32):
    _delta = 0.5
    while _base - _delta / 2.0 != _base:
        _delta /= 2.0
    _smaller = _base - _delta
    _round_trip.append(struct.unpack('<f', struct.pack('<f', _smaller))[0])
r['float_rounds_to_nearest'] = repr(_round_trip)

r['half_size'] = repr(struct.calcsize('e'))
r['half_round_trip'] = repr(struct.unpack('e', struct.pack('e', 1.5))[0])
r['half_precision'] = repr(struct.unpack('e', struct.pack('e', 1 / 3))[0])
r['half_overflow'] = call(struct.pack, 'e', 1e5)

# NaN must survive a round trip as a NaN, not collapse to infinity.
import math
r['nan_round_trip'] = repr(math.isnan(struct.unpack('f', struct.pack('f', float('nan')))[0]))
r['inf_round_trip'] = repr(math.isinf(struct.unpack('f', struct.pack('f', float('inf')))[0]))
r['inf_sign_kept'] = repr(math.copysign(1.0, struct.unpack('f', struct.pack('f', float('inf')))[0]))

# --- Pascal strings ---------------------------------------------------------

r['pascal_pack'] = repr(struct.pack('5p', b'abc'))
r['pascal_unpack'] = repr(struct.unpack('5p', struct.pack('5p', b'abc')))
# Over-long values TRUNCATE rather than raising, and the stored length follows.
r['pascal_truncates'] = repr(struct.pack('3p', b'abcdef'))

# --- buffer entry points ----------------------------------------------------

r['iter_unpack'] = repr(list(struct.iter_unpack('h', b'\x01\x00\x02\x00')))
r['iter_unpack_ragged'] = call(lambda: list(struct.iter_unpack('h', b'\x01\x00\x02')))
r['iter_unpack_empty_fmt'] = call(lambda: list(struct.iter_unpack('', b'')))

_buf = bytearray(8)
struct.pack_into('i', _buf, 0, 7)
r['pack_into'] = repr(bytes(_buf))
r['pack_into_immutable'] = call(struct.pack_into, 'i', b'abcdefgh', 0, 7)
r['pack_into_overflow'] = call(struct.pack_into, 'i', bytearray(2), 0, 7)
# A bogus OFFSET is a TypeError, not a struct.error.
r['pack_into_bad_offset_kind'] = call(struct.pack_into, 'i', bytearray(8), None, 7).split(':')[0]

r['unpack_from'] = repr(struct.unpack_from('i', b'\x07\x00\x00\x00\xff\xff'))
r['unpack_from_offset'] = repr(struct.unpack_from('i', b'\xff\xff\x07\x00\x00\x00', 2))
r['unpack_from_negative'] = repr(struct.unpack_from('i', b'\xff\xff\x07\x00\x00\x00', -4))
r['unpack_from_short'] = call(struct.unpack_from, 'i', b'ab')
r['unpack_from_far_neg'] = call(struct.unpack_from, 'i', b'abcd', -8)

# unpack requires an EXACT buffer; a long one is an error, not a silent trim.
r['unpack_exact'] = repr(struct.unpack('i', b'\x07\x00\x00\x00'))
r['unpack_too_long'] = call(struct.unpack, 'i', b'abcdefgh')
r['unpack_not_bytes'] = call(struct.unpack, 'i', 5)

# --- format strings: bytes are accepted, NULs are not -----------------------

r['bytes_format'] = repr(struct.Struct(b'=i2H').format)
r['bytes_format_type'] = type(struct.Struct(b'=i2H').format).__name__
r['embedded_null'] = call(struct.calcsize, '2\0i')
r['repeat_no_code'] = call(struct.calcsize, '2')

# A format is ASCII-ENCODED first, so ANY code point above 127 is a
# UnicodeEncodeError naming its position -- a lone surrogate is not a special
# case, just the one Grail cannot put in a Smalltalk String.  Checking the code
# points BEFORE coercing is what keeps Grail's internal NotImplementedError
# from escaping in place of the UnicodeEncodeError CPython raises.
r['nonascii_latin1'] = call(struct.calcsize, '\xff')
r['nonascii_bmp'] = call(struct.calcsize, '\u1234')
r['lone_surrogate'] = call(struct.calcsize, '\udc00')
r['surrogate_position'] = call(struct.calcsize, 'i\udc00')
r['surrogate_in_struct'] = call(struct.Struct, '\udc00')

# --- Struct: repr and re-initialization -------------------------------------

r['struct_repr'] = repr(struct.Struct('=i2H'))
_s = struct.Struct('>h')
_s.__init__('>hh')
r['struct_reinit_format'] = repr(_s.format)
r['struct_reinit_pack'] = repr(_s.pack(1, 2))
# A REJECTED re-initialization must leave the previous format in place:
# storing before validating leaves the instance holding a format it can
# neither pack nor unpack with.
_r = struct.Struct('>hh')
r['reinit_rejected'] = call(_r.__init__, '$')
r['reinit_keeps_old_format'] = repr(_r.format)
r['reinit_still_packs'] = repr(_r.pack(1, 2))
r['bad_format_at_construction'] = call(struct.Struct, '$')
r['struct_iter_unpack'] = repr(list(struct.Struct('>h').iter_unpack(b'\x00\x01\x00\x02')))
r['struct_unpack_from_kw'] = repr(struct.Struct('i').unpack_from(b'\xff\xff\x07\x00\x00\x00', offset=2))


EXPECTED = {
    'bad_format_at_construction': 'error: bad char in struct format',
    'bool_for_int': "b'\\x01\\x00\\x00\\x00'",
    'bool_pack_list': "b'\\x00'",
    'bool_pack_three': "b'\\x01'",
    'bool_unpack_one': '(True,)',
    'bool_unpack_seven': '(True,)',
    'bool_unpack_zero': '(False,)',
    'byte_256': "error: 'B' format requires 0 <= number <= 255",
    'byte_neg': "error: 'B' format requires 0 <= number <= 255",
    'bytes_format': "'=i2H'",
    'bytes_format_type': 'str',
    'caught_by_struct_error': 'bad char in struct format',
    'embedded_null': 'error: embedded null character',
    'error_is_exception': 'True',
    'error_is_not_valueerror': 'False',
    'error_module': 'struct',
    'error_name': 'error',
    'float_for_int': 'error: required argument is not an integer',
    'float_rounds_to_nearest': '[2.0, 4.0, 32.0]',
    'half_overflow': 'OverflowError: float too large to pack with e format',
    'half_precision': '0.333251953125',
    'half_round_trip': '1.5',
    'half_size': '2',
    'inf_round_trip': 'True',
    'inf_sign_kept': '1.0',
    'iter_unpack': '[(1,), (2,)]',
    'iter_unpack_empty_fmt': 'error: cannot iteratively unpack with a struct of length 0',
    'iter_unpack_ragged': 'error: iterative unpacking requires a buffer of a multiple of 2 bytes',
    'lone_surrogate': "UnicodeEncodeError: 'ascii' codec can't encode character '\\udc00' in position 0: ordinal not in range(128)",
    'nan_round_trip': 'True',
    'native_ci': '8',
    'native_long': '8',
    'native_n': '8',
    'native_n_roundtrip': '(-5,)',
    'native_pack_ci': "b'a\\x00\\x00\\x00\\x01\\x00\\x00\\x00'",
    'no_trailing_pad': '9',
    'nonascii_bmp': "UnicodeEncodeError: 'ascii' codec can't encode character '\\u1234' in position 0: ordinal not in range(128)",
    'nonascii_latin1': "UnicodeEncodeError: 'ascii' codec can't encode character '\\xff' in position 0: ordinal not in range(128)",
    'not_caught_as_valueerror': 'correct',
    'pack_into': "b'\\x07\\x00\\x00\\x00\\x00\\x00\\x00\\x00'",
    'pack_into_bad_offset_kind': 'TypeError',
    'pack_into_immutable': 'TypeError: argument must be read-write bytes-like object, not bytes',
    'pack_into_overflow': 'error: pack_into requires a buffer of at least 4 bytes for packing 4 bytes at offset 0 (actual buffer size is 2)',
    'pascal_pack': "b'\\x03abc\\x00'",
    'pascal_truncates': "b'\\x02ab'",
    'pascal_unpack': "(b'abc',)",
    'reinit_keeps_old_format': "'>hh'",
    'reinit_rejected': 'error: bad char in struct format',
    'reinit_still_packs': "b'\\x00\\x01\\x00\\x02'",
    'repeat_no_code': 'error: repeat count given without format specifier',
    'short_big': "error: 'h' format requires -32768 <= number <= 32767",
    'standard_ci': '5',
    'standard_long': '4',
    'standard_n': 'error: bad char in struct format',
    'standard_pack_ci': "b'a\\x01\\x00\\x00\\x00'",
    'struct_iter_unpack': '[(1,), (2,)]',
    'struct_reinit_format': "'>hh'",
    'struct_reinit_pack': "b'\\x00\\x01\\x00\\x02'",
    'struct_repr': "Struct('=i2H')",
    'struct_unpack_from_kw': '(7,)',
    'surrogate_in_struct': "UnicodeEncodeError: 'ascii' codec can't encode character '\\udc00' in position 0: ordinal not in range(128)",
    'surrogate_position': "UnicodeEncodeError: 'ascii' codec can't encode character '\\udc00' in position 1: ordinal not in range(128)",
    'unpack_exact': '(7,)',
    'unpack_from': '(7,)',
    'unpack_from_far_neg': 'error: offset -8 out of range for 4-byte buffer',
    'unpack_from_negative': '(7,)',
    'unpack_from_offset': '(7,)',
    'unpack_from_short': 'error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 2)',
    'unpack_not_bytes': "TypeError: a bytes-like object is required, not 'int'",
    'unpack_too_long': 'error: unpack requires a buffer of 4 bytes',
    'zero_count_aligns': '8',
}


if __name__ == '__main__':
    import sys
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            actual = r[k]
            ok = actual == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %s' % (k, 'OK ' if ok else 'DIFF', actual))
        print('%d difference(s)' % bad)
