# ``SystemExit.code'' -- THE EXIT STATUS, AND WHERE IT COMES FROM.
#
# CPython gives SystemExit one attribute of its own, and sys.exit()'s whole
# contract is expressed through it: an int is the process status, None and 0
# both mean success, and a string is a message to print on stderr with status
# 1.  Anything that catches SystemExit to decide what to do next reads it --
# ``if e.code: ...'' in zipapp's CLI tests, ``sys.exit(main())'' wrappers,
# unittest's own runner.
#
# The rule is exactly SystemExit.__init__'s, and it is a rule about ARGS, not
# about a separate slot:
#
#     len(args) == 0  ->  code is None      (the slot is never assigned)
#     len(args) == 1  ->  code is args[0]
#     len(args) >  1  ->  code is args       (the whole tuple)
#
# so ``SystemExit(None).code is None'' while ``SystemExit(None).args == (None,)''
# -- the two are not the same question, and a derivation that confuses them
# would answer the second.
#
# ``code'' is a plain writable member in CPython (T_OBJECT), so ``e.code = 3''
# is an ordinary store and does NOT rewrite args.
#
# The bare ``sys.exit()'' matters on its own: CPython passes NO constructor
# argument, so args is the EMPTY tuple and code is None -- not ``(0,)'' and 0.
# Both mean success to a shell, so the difference is invisible until something
# reads code, and then ``e.code is None'' is the branch that gets it wrong.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import sys

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- the rule: code is derived from args ------------------------------------

def _no_argument():
    e = SystemExit()
    return (e.args, e.code)


def _one_argument():
    e = SystemExit(3)
    return (e.args, e.code)


def _string_argument():
    # A str code is a MESSAGE, not a status; CPython keeps it verbatim.
    e = SystemExit('goodbye')
    return (e.args, e.code)


def _two_arguments():
    # More than one argument makes code the whole tuple -- args itself.
    e = SystemExit(1, 2)
    return (e.args, e.code)


def _three_arguments():
    e = SystemExit('a', 'b', 'c')
    return (e.args, e.code)


def _explicit_none_argument():
    # THE CASE THAT SEPARATES "code is None" FROM "no argument was given":
    # args records the None that was passed, code reads it back.
    e = SystemExit(None)
    return (e.args, e.code)


def _zero_is_not_none():
    # 0 and None both mean success, and are still different objects.
    e = SystemExit(0)
    return (e.code, e.code is None, e.code == 0)


# --- sys.exit() is the commonest producer -----------------------------------

def _sys_exit_bare():
    try:
        sys.exit()
    except SystemExit as e:
        return (e.args, e.code, e.code is None)


def _sys_exit_zero():
    try:
        sys.exit(0)
    except SystemExit as e:
        return (e.args, e.code)


def _sys_exit_status():
    try:
        sys.exit(2)
    except SystemExit as e:
        return (e.args, e.code)


def _sys_exit_message():
    try:
        sys.exit('fatal')
    except SystemExit as e:
        return (e.args, e.code)


def _raise_statement():
    # The ``raise SystemExit(n)'' path, which constructs differently from
    # sys.exit() and must agree with it.
    try:
        raise SystemExit(7)
    except SystemExit as e:
        return (e.args, e.code)


def _raise_bare_class():
    # ``raise SystemExit'' instantiates with no arguments.
    try:
        raise SystemExit
    except SystemExit as e:
        return (e.args, e.code)


# --- code is a writable attribute, and writing it leaves args alone ---------

def _assignment_wins():
    e = SystemExit(1)
    e.code = 99
    return (e.args, e.code)


def _assignment_of_none():
    # Storing None must READ BACK as None rather than falling through to the
    # derivation, which would answer 1 here.
    e = SystemExit(1)
    e.code = None
    return (e.args, e.code)


def _assignment_without_args():
    e = SystemExit()
    e.code = 'set'
    return (e.args, e.code)


# --- inheritance ------------------------------------------------------------

def _plain_subclass():
    class Bail(SystemExit):
        pass
    e = Bail(5)
    return (e.args, e.code)


def _subclass_with_init():
    # A subclass whose __init__ forwards to super() gets code for free, because
    # code follows args and super().__init__ is what sets args.
    class Bail(SystemExit):
        def __init__(self, status):
            super().__init__(status)
            self.reason = 'because'
    e = Bail(4)
    return (e.args, e.code, e.reason)


def _still_a_baseexception_not_an_exception():
    # Why SystemExit hangs off BaseException: ``except Exception'' must NOT
    # swallow an exit request.  Nothing to do with code, and everything to do
    # with whether the code is ever read.
    return (issubclass(SystemExit, BaseException),
            issubclass(SystemExit, Exception))


# --- adding code must not disturb args / str / repr -------------------------

def _str_and_repr():
    return (str(SystemExit()), repr(SystemExit()),
            str(SystemExit(1)), repr(SystemExit(1)),
            str(SystemExit(1, 2)), repr(SystemExit(1, 2)))


rec('no_argument', _no_argument)
rec('one_argument', _one_argument)
rec('string_argument', _string_argument)
rec('two_arguments', _two_arguments)
rec('three_arguments', _three_arguments)
rec('explicit_none_argument', _explicit_none_argument)
rec('zero_is_not_none', _zero_is_not_none)
rec('sys_exit_bare', _sys_exit_bare)
rec('sys_exit_zero', _sys_exit_zero)
rec('sys_exit_status', _sys_exit_status)
rec('sys_exit_message', _sys_exit_message)
rec('raise_statement', _raise_statement)
rec('raise_bare_class', _raise_bare_class)
rec('assignment_wins', _assignment_wins)
rec('assignment_of_none', _assignment_of_none)
rec('assignment_without_args', _assignment_without_args)
rec('plain_subclass', _plain_subclass)
rec('subclass_with_init', _subclass_with_init)
rec('still_a_baseexception_not_an_exception',
    _still_a_baseexception_not_an_exception)
rec('str_and_repr', _str_and_repr)


EXPECTED = {
    'assignment_of_none': ((1,), None),
    'assignment_wins': ((1,), 99),
    'assignment_without_args': ((), 'set'),
    'explicit_none_argument': ((None,), None),
    'no_argument': ((), None),
    'one_argument': ((3,), 3),
    'plain_subclass': ((5,), 5),
    'raise_bare_class': ((), None),
    'raise_statement': ((7,), 7),
    'still_a_baseexception_not_an_exception': (True, False),
    'str_and_repr': ('', 'SystemExit()', '1', 'SystemExit(1)', '(1, 2)', 'SystemExit(1, 2)'),
    'string_argument': (('goodbye',), 'goodbye'),
    'subclass_with_init': ((4,), 4, 'because'),
    'sys_exit_bare': ((), None, True),
    'sys_exit_message': (('fatal',), 'fatal'),
    'sys_exit_status': ((2,), 2),
    'sys_exit_zero': ((0,), 0),
    'three_arguments': (('a', 'b', 'c'), ('a', 'b', 'c')),
    'two_arguments': ((1, 2), (1, 2)),
    'zero_is_not_none': (0, False, True),
}

if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-40s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
