# The traceback OBJECT -- `e.__traceback__`, and the type it is an instance of.
#
# Grail has had real traceback objects for a while: a linked list of nodes with
# tb_frame / tb_lineno / tb_next, built as an exception unwinds.  What it did
# not have was any of the things code does WITH them, and each gap was quiet in
# its own way.
#
# 1. THE TYPE HAD NO NAME.  `types.TracebackType` was an empty stub class, so
#    `isinstance(tb, types.TracebackType)` was False about an object that was
#    one -- and that check is what every traceback-handling library leads with,
#    so they all took their "this isn't a traceback" branch.  `type(tb).__name__`
#    said 'PyTraceback' where CPython says 'traceback'.
#
# 2. `with_traceback(tb)` DID NOT SURVIVE THE RAISE.  The idiom is
#    `raise X().with_traceback(tb)`, and the point of it is that the new raise
#    PREPENDS its frames to the attached chain.  Grail read the attached chain
#    as a partial unwind record, decided it was stale, and discarded it -- so
#    the traceback the caller had deliberately attached vanished at exactly the
#    raise that was supposed to use it.
#
# 3. tb_next TOOK ANYTHING.  `tb.tb_next = 'asdf'` was stored, so the failure
#    surfaced later in whichever formatter walked into a string; and
#    `tb.tb_next = tb` built a cycle, which HANGS any walker, because they all
#    loop until tb_next is None.  `del tb.tb_next` removed the slot, and an
#    absent slot reads back as AttributeError -- a third error, further away.
#
# 4. THERE WAS NO CONSTRUCTOR.  `types.TracebackType(...)` is how you build a
#    replacement node, which is how you trim frames off a chain before
#    re-raising.  The class was not callable at all.
#
# NOT FIXED, and worth stating: `tb.tb_frame is sys._getframe()`.  CPython has
# ONE mutable frame object per activation, so the traceback's frame and the
# running frame are the same object at different line numbers.  Grail
# synthesises a fresh frame from the VM's stack capture each time it is asked,
# so the two are equal in content and never identical.  That is what
# test_raise's test_attrs asserts and why it still fails; closing it needs real
# frame objects, not a change here.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import sys
import types

r = {}


def get_tb():
    try:
        raise OSError()
    except OSError as e:
        return e.__traceback__


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- 1. the type has a name, and it is the right one ------------------------

tb = get_tb()

rec('type_name', lambda: type(tb).__name__)
rec('type_module', lambda: type(tb).__module__)
rec('type_repr', lambda: repr(type(tb)))
rec('is_traceback_type', lambda: isinstance(tb, types.TracebackType))
rec('type_is_tracebacktype', lambda: type(tb) is types.TracebackType)


# --- the fields a walker reads ----------------------------------------------

rec('tb_next_of_leaf', lambda: tb.tb_next)
rec('lineno_is_int', lambda: isinstance(tb.tb_lineno, int))
rec('lasti_is_int', lambda: isinstance(tb.tb_lasti, int))
rec('frame_is_not_none', lambda: tb.tb_frame is not None)


# --- 2. with_traceback survives the raise -----------------------------------

def _accepts_traceback():
    t = get_tb()
    try:
        raise IndexError().with_traceback(t)
    except IndexError as e:
        return (e.__traceback__ is t, e.__traceback__.tb_next is t)


def _with_traceback_none():
    t = get_tb()
    e = IndexError().with_traceback(t)
    e.with_traceback(None)
    return e.__traceback__


rec('accepts_traceback', _accepts_traceback)
rec('with_traceback_none_clears', _with_traceback_none)


# --- 3. tb_next is guarded --------------------------------------------------

def _assign_str():
    get_tb().tb_next = 'asdf'


def _delete_next():
    del get_tb().tb_next


def _self_loop():
    t = get_tb()
    t.tb_next = t


def _indirect_loop():
    outer = get_tb()
    outer.tb_next = get_tb()
    outer.tb_next.tb_next = outer


rec('assign_str', _assign_str)
rec('delete_next', _delete_next)
rec('self_loop', _self_loop)
rec('indirect_loop', _indirect_loop)


# ...and the assignments that must still WORK, which is the point of the field
# being writable at all.
def _valid_assignments():
    t = get_tb()
    t.tb_next = None
    was_none = t.tb_next is None
    fresh = get_tb()
    t.tb_next = fresh
    return (was_none, t.tb_next is fresh)


rec('valid_assignments', _valid_assignments)


# --- 4. the constructor -----------------------------------------------------

def _construct():
    other = get_tb()
    frame = sys._getframe()
    node = types.TracebackType(other, frame, 1, 2)
    return (node.tb_next is other, node.tb_frame is frame,
            node.tb_lasti, node.tb_lineno,
            isinstance(node, types.TracebackType))


def _construct_none_next():
    node = types.TracebackType(None, sys._getframe(), 1, 2)
    return node.tb_next


rec('construct', _construct)
rec('construct_none_next', _construct_none_next)

rec('construct_bad_next',
    lambda: types.TracebackType('no', sys._getframe(), 1, 2))
rec('construct_bad_frame',
    lambda: types.TracebackType(None, 'no', 1, 2))
rec('construct_bad_lasti',
    lambda: types.TracebackType(None, sys._getframe(), 'no', 2))
rec('construct_bad_lineno',
    lambda: types.TracebackType(None, sys._getframe(), 1, 'nuh-uh'))


# --- what must KEEP working -------------------------------------------------
#
# The traceback is not only an object to poke at -- it is what the `traceback`
# module formats.  Renaming the type and guarding the field must not disturb
# the ordinary reporting path.

def _walk_chain():
    def leaf():
        raise ValueError('deep')

    def middle():
        leaf()

    try:
        middle()
    except ValueError as e:
        names = []
        cur = e.__traceback__
        while cur is not None:
            names.append(cur.tb_frame.f_code.co_name)
            cur = cur.tb_next
        return names


def _format_still_works():
    import traceback
    try:
        raise ValueError('formatted')
    except ValueError as e:
        text = ''.join(traceback.format_exception(type(e), e, e.__traceback__))
        return ('ValueError: formatted' in text, 'Traceback' in text)


rec('walk_chain', _walk_chain)
rec('format_still_works', _format_still_works)


EXPECTED = {
    'accepts_traceback': (False, True),
    'assign_str': "TypeError: expected traceback object, got 'str'",
    'construct': (True, True, 1, 2, True),
    'construct_bad_frame': "TypeError: traceback() argument 'tb_frame' must be frame, not str",
    'construct_bad_lasti': "TypeError: 'str' object cannot be interpreted as an integer",
    'construct_bad_lineno': "TypeError: 'str' object cannot be interpreted as an integer",
    'construct_bad_next': "TypeError: expected traceback object or None, got 'str'",
    'construct_none_next': None,
    'delete_next': "TypeError: can't delete tb_next attribute",
    'format_still_works': (True, True),
    'frame_is_not_none': True,
    'indirect_loop': 'ValueError: traceback loop detected',
    'is_traceback_type': True,
    'lasti_is_int': True,
    'lineno_is_int': True,
    'self_loop': 'ValueError: traceback loop detected',
    'tb_next_of_leaf': None,
    'type_is_tracebacktype': True,
    'type_module': 'builtins',
    'type_name': 'traceback',
    'type_repr': "<class 'traceback'>",
    'valid_assignments': (True, True),
    'walk_chain': ['_walk_chain', 'middle', 'leaf'],
    'with_traceback_none_clears': None,
}

if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-28s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
