# The `else` clause of a try statement, and the one thing that makes it
# different from just appending the code to the body.
#
# `else` exists for exactly one reason: to run code that must NOT be protected
# by the statement's own `except` clauses.  The whole idiom
#
#     try:
#         x = d[k]
#     except KeyError:
#         handle_missing()
#     else:
#         use(x)
#
# depends on it -- if `use(x)` itself raises KeyError, that is a bug in `use`,
# and it must propagate, not be mistaken for a missing key.
#
# Grail emitted the else body INSIDE the protected block, so it was just a tail
# of the try body.  Every `except` clause on the statement caught its own
# `else`, which is the failure mode `else` exists to prevent: the handler runs
# on an exception it was never meant to see, and the real error never surfaces.
# CPython's own test suite catches it -- test_exception_variations'
# test_nested_exception_in_else -- but the shape is common enough in ordinary
# code that it was silently mis-routing exceptions everywhere.
#
# The other half of the rule, and the reason this is not just "move the else
# out": `finally` DOES still cover the else.  So the else sits between the two
# -- outside the handlers, inside the ensure.
#
# EXPECTED was generated by RUNNING CPython 3.14.6.

import sys

r = {}


def rec(k, fn):
    try:
        r[k] = fn()
    except BaseException as e:
        r[k] = '%s: %s' % (type(e).__name__, e)


# --- the rule: the else is NOT protected by this statement's handlers -------

def _else_not_caught_by_own_bare_except():
    hit = []
    try:
        try:
            pass
        except:
            hit.append('inner-except')
        else:
            hit.append('inner-else')
            raise RuntimeError('from else')
    except RuntimeError:
        hit.append('outer-except')
    else:
        hit.append('outer-else')
    return hit


def _else_not_caught_by_own_typed_except():
    hit = []
    try:
        try:
            pass
        except RuntimeError:
            hit.append('inner-except')
        else:
            raise RuntimeError('from else')
    except RuntimeError:
        hit.append('outer-except')
    return hit


def _else_not_caught_by_any_of_several_handlers():
    """Not just the first clause -- the else has to escape ALL of them."""
    hit = []
    try:
        try:
            pass
        except KeyError:
            hit.append('key')
        except ValueError:
            hit.append('value')
        except Exception:
            hit.append('broad')
        else:
            raise ValueError('from else')
    except ValueError:
        hit.append('outer')
    return hit


def _else_escapes_to_the_caller():
    """With no outer try at all it must reach the caller, not vanish."""
    def inner():
        try:
            pass
        except Exception:
            return 'swallowed'
        else:
            raise IndexError('from else')

    try:
        return inner()
    except IndexError as e:
        return 'propagated: %s' % e


# --- but `finally` DOES cover the else -------------------------------------

def _finally_runs_when_else_raises():
    hit = []
    try:
        try:
            pass
        except ValueError:
            hit.append('except')
        else:
            hit.append('else')
            raise RuntimeError('from else')
        finally:
            hit.append('finally')
    except RuntimeError:
        hit.append('outer')
    return hit


def _finally_runs_after_a_quiet_else():
    hit = []
    try:
        pass
    except ValueError:
        hit.append('except')
    else:
        hit.append('else')
    finally:
        hit.append('finally')
    return hit


def _finally_raise_replaces_an_else_raise():
    """The finally covers the else, so its own raise supersedes -- and the
    displaced else exception becomes the __context__."""
    try:
        try:
            pass
        except ValueError:
            pass
        else:
            raise RuntimeError('from else')
        finally:
            raise TypeError('from finally')
    except TypeError as e:
        return (str(e), type(e.__context__).__name__, str(e.__context__))


# --- when the else runs at all ---------------------------------------------

def _else_skipped_when_body_raises():
    hit = []
    try:
        raise ValueError('body')
    except ValueError:
        hit.append('except')
    else:
        hit.append('else')
    return hit


def _else_skipped_when_body_returns():
    hit = []

    def f():
        try:
            return 'body'
        except ValueError:
            hit.append('except')
        else:
            hit.append('else')
    got = f()
    return (got, hit)


def _else_skipped_when_body_breaks():
    hit = []
    for _ in range(3):
        try:
            break
        except ValueError:
            hit.append('except')
        else:
            hit.append('else')
    return hit


def _else_skipped_when_body_continues():
    hit = []
    for i in range(3):
        try:
            if i < 2:
                continue
        except ValueError:
            hit.append('except')
        else:
            hit.append('else-%d' % i)
    return hit


def _else_skipped_when_a_handler_ran():
    """Body raised, a handler caught it -- the else must still not run."""
    hit = []
    try:
        try:
            raise KeyError('body')
        except KeyError:
            hit.append('except')
        else:
            hit.append('else')
    except KeyError:
        hit.append('outer')
    return hit


def _return_in_else():
    def f():
        try:
            pass
        except ValueError:
            return 'except'
        else:
            return 'else'
        return 'after'
    return f()


def _break_in_else():
    seen = []
    for i in range(5):
        try:
            seen.append(i)
        except ValueError:
            pass
        else:
            if i == 1:
                break
    return seen


# --- what the else can still see -------------------------------------------

def _else_sees_body_locals():
    d = {'k': 'v'}
    try:
        x = d['k']
    except KeyError:
        return 'missing'
    else:
        return 'got %s' % x


def _exc_info_in_else_is_clear():
    """The else runs on the success path, so nothing is being handled."""
    try:
        pass
    except ValueError:
        return 'except'
    else:
        return sys.exc_info()[0]


def _else_raise_has_no_context():
    """Nothing was caught, so the else's exception has no __context__."""
    try:
        try:
            pass
        except ValueError:
            pass
        else:
            raise RuntimeError('from else')
    except RuntimeError as e:
        return e.__context__


def _bare_raise_in_else():
    """No active exception on the success path -- a bare raise is a RuntimeError."""
    try:
        pass
    except ValueError:
        pass
    else:
        raise


# --- nesting ---------------------------------------------------------------

def _nested_try_inside_else_still_catches_its_own():
    """The fix must not overshoot: a try INSIDE the else keeps its handlers."""
    hit = []
    try:
        try:
            pass
        except ValueError:
            hit.append('outer-clause')
        else:
            try:
                raise ValueError('inner')
            except ValueError:
                hit.append('inner-clause')
    except ValueError:
        hit.append('escaped')
    return hit


def _else_of_an_inner_try_inside_an_outer_body():
    hit = []
    try:
        try:
            pass
        except Exception:
            hit.append('inner')
        else:
            raise TypeError('from inner else')
    except TypeError:
        hit.append('outer')
    else:
        hit.append('outer-else')
    finally:
        hit.append('outer-finally')
    return hit


# --- except* (PEP 654) has the same rule -----------------------------------

def _star_else_not_caught_by_own_handler():
    hit = []
    try:
        try:
            pass
        except* ValueError:
            hit.append('star-except')
        else:
            hit.append('star-else')
            raise ValueError('from else')
    except ValueError:
        hit.append('outer')
    return hit


def _star_else_with_finally():
    hit = []
    try:
        try:
            pass
        except* RuntimeError:
            hit.append('star-except')
        else:
            raise RuntimeError('from else')
        finally:
            hit.append('finally')
    except RuntimeError:
        hit.append('outer')
    return hit


def _star_else_skipped_when_body_raises():
    hit = []
    try:
        raise ValueError('body')
    except* ValueError:
        hit.append('star-except')
    else:
        hit.append('star-else')
    return hit


rec('else_not_caught_by_own_bare_except', _else_not_caught_by_own_bare_except)
rec('else_not_caught_by_own_typed_except', _else_not_caught_by_own_typed_except)
rec('else_not_caught_by_any_handler', _else_not_caught_by_any_of_several_handlers)
rec('else_escapes_to_the_caller', _else_escapes_to_the_caller)

rec('finally_runs_when_else_raises', _finally_runs_when_else_raises)
rec('finally_runs_after_quiet_else', _finally_runs_after_a_quiet_else)
rec('finally_raise_replaces_else_raise', _finally_raise_replaces_an_else_raise)

rec('else_skipped_when_body_raises', _else_skipped_when_body_raises)
rec('else_skipped_when_body_returns', _else_skipped_when_body_returns)
rec('else_skipped_when_body_breaks', _else_skipped_when_body_breaks)
rec('else_skipped_when_body_continues', _else_skipped_when_body_continues)
rec('else_skipped_when_handler_ran', _else_skipped_when_a_handler_ran)
rec('return_in_else', _return_in_else)
rec('break_in_else', _break_in_else)

rec('else_sees_body_locals', _else_sees_body_locals)
rec('exc_info_in_else_is_clear', _exc_info_in_else_is_clear)
rec('else_raise_has_no_context', _else_raise_has_no_context)
rec('bare_raise_in_else', _bare_raise_in_else)

rec('nested_try_inside_else', _nested_try_inside_else_still_catches_its_own)
rec('inner_else_inside_outer_body', _else_of_an_inner_try_inside_an_outer_body)

rec('star_else_not_caught_by_own_handler', _star_else_not_caught_by_own_handler)
rec('star_else_with_finally', _star_else_with_finally)
rec('star_else_skipped_when_body_raises', _star_else_skipped_when_body_raises)


EXPECTED = {
    'bare_raise_in_else': 'RuntimeError: No active exception to reraise',
    'break_in_else': [0, 1],
    'else_escapes_to_the_caller': 'propagated: from else',
    'else_not_caught_by_any_handler': ['outer'],
    'else_not_caught_by_own_bare_except': ['inner-else', 'outer-except'],
    'else_not_caught_by_own_typed_except': ['outer-except'],
    'else_raise_has_no_context': None,
    'else_sees_body_locals': 'got v',
    'else_skipped_when_body_breaks': [],
    'else_skipped_when_body_continues': ['else-2'],
    'else_skipped_when_body_raises': ['except'],
    'else_skipped_when_body_returns': ('body', []),
    'else_skipped_when_handler_ran': ['except'],
    'exc_info_in_else_is_clear': None,
    'finally_raise_replaces_else_raise': ('from finally', 'RuntimeError', 'from else'),
    'finally_runs_after_quiet_else': ['else', 'finally'],
    'finally_runs_when_else_raises': ['else', 'finally', 'outer'],
    'inner_else_inside_outer_body': ['outer', 'outer-finally'],
    'nested_try_inside_else': ['inner-clause'],
    'return_in_else': 'else',
    'star_else_not_caught_by_own_handler': ['star-else', 'outer'],
    'star_else_skipped_when_body_raises': ['star-except'],
    'star_else_with_finally': ['finally', 'outer'],
}

if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        bad = 0
        for k in sorted(EXPECTED):
            ok = r[k] == EXPECTED[k]
            bad += 0 if ok else 1
            print('%-38s %s %r' % (k, 'OK ' if ok else 'DIFF', r[k]))
        print('%d difference(s)' % bad)
