# Fixture for TwilioTier1TestCase.
#
# Exercises the vendored twilio Tier-1 surface — the parts that need
# NO outbound HTTP client:
#
#   * twilio.twiml — TwiML generation (MessagingResponse /
#     VoiceResponse on top of Grail's minimal xml.etree.ElementTree)
#   * twilio.request_validator — X-Twilio-Signature webhook
#     validation (hmac/sha1/base64 + urllib.parse._replace)
#
# All expected values were generated by running twilio 9.10.9 under
# CPython 3.13 — Grail output must match byte-for-byte.

from twilio.request_validator import RequestValidator
from twilio.twiml.messaging_response import MessagingResponse
from twilio.twiml.voice_response import VoiceResponse, Gather

# --- TwiML: messaging ---

mr = MessagingResponse()
mr.message('Hello & <world> "q"')
twiml_message = str(mr)
# '<?xml version="1.0" encoding="UTF-8"?><Response>
#  <Message>Hello &amp; &lt;world&gt; "q"</Message></Response>'

# --- TwiML: voice with nesting, attrs, camelCasing ---

vr = VoiceResponse()
vr.say('Welcome to Acme', voice='alice')
gather = Gather(num_digits=1, action='/menu', method='POST')
gather.say('Press 1 for sales')
vr.append(gather)
vr.hangup()
twiml_voice = str(vr)
# attrs sorted, num_digits -> numDigits, empty Hangup self-closes

# --- Request validation: form-POST webhook ---

validator = RequestValidator('12345')
uri = 'https://mycompany.com/myapp.php?foo=1&bar=2'
params = {
    'CallSid': 'CA1234567890ABCDE',
    'Caller': '+12349013030',
    'Digits': '1234',
    'From': '+12349013030',
    'To': '+18005551212',
}

computed_sig = validator.compute_signature(uri, params)
# '0/KCTR6DLpKmkAf8muzZqo1nDgQ='

validate_good = validator.validate(uri, params, '0/KCTR6DLpKmkAf8muzZqo1nDgQ=')
validate_bad = validator.validate(uri, params, 'WRONGSIGNATURE')

# --- Request validation: JSON body with bodySHA256 ---

json_body = '{"property": "value", "boolean": true}'
body_hash = validator.compute_hash(json_body)
# '0a1ff7634d9ab3b95db5c9a2dfe9416e41502b283a80c7cf19632632f96e6620'

json_uri = 'https://mycompany.com/myapp.php?bodySHA256=' + body_hash
validate_json = validator.validate(
    json_uri, json_body, 'y77kIzt2vzLz71DgmJGsen2scGs=')
