# The two runtime gaps behind CPython's test_zipapp.  Neither is in zipapp:
#
#   * ``stat'' was a minimal stub with no ``S_IEXEC'', which zipapp uses to
#     mark an archive with a shebang executable; ``S_IFMT'' was a constant
#     where CPython's is a function, and ``filemode'' was missing.  It is now
#     CPython's own stat.py.
#   * ``patch(..., new_callable=io.StringIO)'' raised TypeError from inside
#     MagicMock: ``new_callable'' was not a patch keyword.
#   * ``io.StringIO(initial_value=...)'' -- how patch passes its keywords on --
#     took no keywords at all, and ``StringIO(5)'' / ``StringIO(None)'' held
#     '5' / 'None'.  (newline=None, '\r' and '\r\n' translate newlines in
#     CPython; Grail's StringIO refuses them, so they are not compared.)
#
# Only platform-independent stat values are compared: _stat, where present,
# supplies some bits (S_IFWHT, the UF_ flags) from the host's headers.
#
# EXPECTED was generated by RUNNING CPython 3.14.6 (``--emit``).

import io
import stat
import sys
from unittest.mock import MagicMock, patch

r = {}


def _err(f):
    try:
        return repr(f())
    except Exception as e:
        return '%s: %s' % (type(e).__name__, e)


# --- stat ----------------------------------------------------------------------

r['stat_aliases'] = repr([stat.S_IEXEC == stat.S_IXUSR, stat.S_IREAD == stat.S_IRUSR,
                          stat.S_IWRITE == stat.S_IWUSR, stat.S_ENFMT == stat.S_ISGID,
                          oct(stat.S_IEXEC | stat.S_IREAD | stat.S_IWRITE)])
r['stat_ifmt_is_a_function'] = repr([oct(stat.S_IFMT(0o100755)), oct(stat.S_IMODE(0o100755)),
                                     stat.S_ISREG(0o100755), stat.S_ISDIR(0o040755),
                                     stat.S_ISLNK(0o120777)])
r['stat_filemode'] = repr([stat.filemode(m) for m in (
    0o100755, 0o100644, 0o040700, 0o120777, 0o104755, 0o102711, 0o041777, 0o020620,
    0o060660, 0o010600, 0o140755)])
r['stat_ifmt_constants'] = repr([oct(v) for v in (
    stat.S_IFDIR, stat.S_IFCHR, stat.S_IFBLK, stat.S_IFREG, stat.S_IFIFO,
    stat.S_IFLNK, stat.S_IFSOCK)])
r['stat_st_indices'] = repr([stat.ST_MODE, stat.ST_INO, stat.ST_DEV, stat.ST_NLINK,
                             stat.ST_UID, stat.ST_GID, stat.ST_SIZE, stat.ST_ATIME,
                             stat.ST_MTIME, stat.ST_CTIME])


# --- io.StringIO's constructor ------------------------------------------------

r['stringio_constructor'] = repr([_err(f) for f in (
    lambda: io.StringIO().getvalue(),
    lambda: io.StringIO('x').getvalue(),
    lambda: io.StringIO(initial_value='seed').getvalue(),
    lambda: io.StringIO('a', '').getvalue(),
    lambda: io.StringIO(newline='').getvalue(),
    lambda: io.StringIO(None).getvalue(),
    lambda: io.StringIO(foo=1),
    lambda: io.StringIO('a', '\n', 'x'),
    lambda: io.StringIO(newline='x'),
    lambda: io.StringIO(5),
    lambda: io.StringIO('a', initial_value='b'),
    lambda: io.StringIO(newline=5),
)])


# --- patch(..., new_callable=...) ------------------------------------------------

def _with_statement():
    with patch('sys.stdout', new_callable=io.StringIO) as out:
        print('hello')
    return [type(out).__name__, out.getvalue(), sys.stdout is not out]


r['new_callable_with'] = _err(_with_statement)


class _Cmdline:
    # The shape test_zipapp's test_info_command has: a decorated METHOD, the
    # mock handed over as a trailing argument.
    @patch('sys.stdout', new_callable=io.StringIO)
    def run(self, mock_stdout):
        print('Interpreter: <none>')
        return mock_stdout.getvalue()


r['new_callable_decorator'] = _err(lambda: _Cmdline().run())


def _keywords_go_to_the_callable():
    with patch('sys.stdout', new_callable=io.StringIO, initial_value='seed') as out:
        return out.getvalue()


r['new_callable_keywords'] = _err(_keywords_go_to_the_callable)


def _mock_class():
    with patch('sys.stdout', new_callable=MagicMock) as out:
        return [isinstance(out, MagicMock), out.called]


r['new_callable_mock_class'] = _err(_mock_class)
r['new_callable_refusals'] = repr([
    _err(lambda: patch('sys.stdout', new=1, new_callable=io.StringIO)),
    _err(lambda: patch('sys.stdout', new_callable=io.StringIO, autospec=True)),
])

# --- newline translation (Grail-only: recorded, not compared) -----------------

def _kind(f):
    try:
        f()
        return 'no error'
    except Exception as e:
        return type(e).__name__


grail_only = {}
grail_only['stringio_newline_translation'] = repr([
    _kind(lambda: io.StringIO(newline=v)) for v in (None, '\r', '\r\n')])

EXPECTED = {
    'new_callable_decorator': "'Interpreter: <none>\\n'",
    'new_callable_keywords': "'seed'",
    'new_callable_mock_class': '[True, False]',
    'new_callable_refusals': '["ValueError: Cannot use \'new\' and \'new_callable\' together", "ValueError: Cannot use \'autospec\' and \'new_callable\' together"]',
    'new_callable_with': "['StringIO', 'hello\\n', True]",
    'stat_aliases': "[True, True, True, True, '0o700']",
    'stat_filemode': "['-rwxr-xr-x', '-rw-r--r--', 'drwx------', 'lrwxrwxrwx', '-rwsr-xr-x', '-rwx--s--x', 'drwxrwxrwt', 'crw--w----', 'brw-rw----', 'prw-------', 'srwxr-xr-x']",
    'stat_ifmt_constants': "['0o40000', '0o20000', '0o60000', '0o100000', '0o10000', '0o120000', '0o140000']",
    'stat_ifmt_is_a_function': "['0o100000', '0o755', True, True, True]",
    'stat_st_indices': '[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]',
    'stringio_constructor': '["\'\'", "\'x\'", "\'seed\'", "\'a\'", "\'\'", "\'\'", "TypeError: StringIO() got an unexpected keyword argument \'foo\'", \'TypeError: StringIO() takes at most 2 arguments (3 given)\', "ValueError: illegal newline value: \'x\'", \'TypeError: initial_value must be str or None, not int\', "TypeError: argument for StringIO() given by name (\'initial_value\') and position (1)", \'TypeError: newline must be str or None, not int\']',
}


if __name__ == '__main__':
    if '--emit' in sys.argv:
        print('EXPECTED = {')
        for k in sorted(r):
            print('    %r: %r,' % (k, r[k]))
        print('}')
    else:
        for k in sorted(EXPECTED):
            print('%-4s %s' % ('OK' if r[k] == EXPECTED[k] else 'FAIL', k))
