! ------------------- Superclass check
run
Object ifNil: [self error: 'Object is not defined. Check file ordering.'].
%

! ------- PythonInstance class definition
expectvalue /Class
doit
Object subclass: 'PythonInstance'
  instVarNames: #( ___dict___ )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: Python
  options: #()
%

expectvalue /Class
doit
PythonInstance comment:
'Common base class for Python user classes generated by compileClassDef.

Python instances support arbitrary dynamic attributes: any assignment
``obj.x = y`` adds (or replaces) attribute ``x``.  Smalltalk classes
have fixed instVar layouts, so Python attributes that are not
discovered by the __init__ scan are stored in the per-instance
``___dict___`` IdentityKeyValueDictionary.

The DNU handler intercepts unknown env-1 messages and routes them:
  ``obj name:`` (1-keyword, 1 arg)   → setter:  ___dict___ at: #name put: arg.
  ``obj name``  (unary, 0 args)       → getter:  ___dict___ at: #name (or super).

Fixed instVar slots discovered at compile time still get explicit
getter/setter methods (faster path); DNU is the fallback for the rest.'
%

expectvalue /Class
doit
PythonInstance category: 'Modules'
%

! ------------------- Remove existing behavior
removeallmethods PythonInstance
removeallclassmethods PythonInstance

set compile_env: 0

category: 'Python-Attribute Access'
method: PythonInstance
___ensureDict___
	"Lazy create the per-instance attribute dictionary."

	___dict___ ifNil: [___dict___ := IdentityKeyValueDictionary new].
	^ ___dict___
%

category: 'Python-Attribute Access'
method: PythonInstance
doesNotUnderstand: aSelector args: anArray envId: envId
	"Route unknown env-1 messages through the per-instance __dict__:
	`name:` (1 arg) → setter; bare `name` (0 args) → getter.

	BEFORE treating `name:` as a setter, check whether the class
	defines a varargs `_name:kw:` form.  Grail codegen emits
	``receiver foo: arg`` for any Python call ``receiver.foo(arg)``,
	even when the target method is varargs (e.g. an `(arg=None)`
	signature compiles to `_foo:kw:`).  Without this redirect, every
	such call would be misinterpreted as a __dict__ setter — the
	re._parser.State.opengroup case, which silently dropped every
	group-open call so capture groups never registered."

	| s |
	envId = 1 ifFalse: [
		^ super doesNotUnderstand: aSelector args: anArray envId: envId
	].
	s := aSelector asString.
	s size > 0 ifTrue: [
		(s last = $:) ifTrue: [
			| selBase varargSel |
			"Strip trailing colons and look for a matching `_name:kw:`."
			selBase := s copyFrom: 1 to: s size - (s occurrencesOf: $:).
			varargSel := ('_' @env0:, selBase @env0:, ':kw:') asSymbol.
			((self @env0:class @env0:whichClassIncludesSelector: varargSel environmentId: 1) notNil) ifTrue: [
				^ self @env0:perform: varargSel
					env: 1
					withArguments: { anArray @env0:asArray. nil }
			].
			"Setter — single trailing colon, no other colons."
			((s occurrencesOf: $:) = 1 and: [anArray size = 1]) ifTrue: [
				| key |
				key := (s copyFrom: 1 to: s size - 1) asSymbol.
				self ___ensureDict___ at: key put: (anArray at: 1).
				^ anArray at: 1
			]
		] ifFalse: [
			"Unary getter."
			anArray size = 0 ifTrue: [
				(___dict___ notNil and: [___dict___ includesKey: aSelector])
					ifTrue: [^ ___dict___ at: aSelector]
			]
		]
	].
	^ super doesNotUnderstand: aSelector args: anArray envId: envId
%

category: 'Python-Attribute Access'
method: PythonInstance
cantPerform: aSymbol withArguments: anArray env: envId
	"Mirror DNU handling for explicit perform: env: calls."

	^ self doesNotUnderstand: aSymbol args: anArray envId: envId
%

set compile_env: 1

category: 'Python-Introspection'
method: PythonInstance
__dict__
	"Python ``obj.__dict__`` introspection — return the per-instance
	attribute dictionary, materializing it on first access.

	Limitation: only attributes routed through ``___dict___`` (set via
	the DNU dispatch path) appear here.  Attributes stored as actual
	Smalltalk instVars — the ones synthesized from ``self.X = …``
	writes discovered at class-compile time by AttributeAst's
	``declareInstanceVar:`` propagation — are NOT included.  Most
	downstream usage (``if 'X' in obj.__dict__:`` cached-property
	idiom in blinker) only checks for runtime-added attrs, which all
	land in ``___dict___``."

	^ self @env0:___ensureDict___
%

set compile_env: 0

category: 'Python-Introspection'
classmethod: PythonInstance
___pythonValueAttrs___
	"Selectors that ___pyAttrLoad___ should treat as *value* attribute
	reads rather than BoundMethod wraps.  ``__dict__`` is the canonical
	example — Python introspection (``if 'X' in self.__dict__:``)
	expects the dict back, not a callable that would yield the dict
	if invoked.  Returns an IdentitySet of symbols."

	^ IdentitySet new
		add: #'__dict__';
		yourself
%
