! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for BareNameManglingTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'BareNameManglingTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
BareNameManglingTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! BareNameManglingTestCase
!
! CPython's private-name mangling is LEXICAL: an identifier spelled ``__x''
! (two or more leading underscores, not ending in ``__'') anywhere inside a
! class body becomes ``_C__x'' -- method bodies, nested defs, lambdas,
! comprehensions, defaults and decorators included.
!
! Grail mangled only the attribute-shaped names and left BARE names alone, so
! ``global __x'' in a method wrote ``__x'' where CPython writes ``_C__x''.  That
! was test_named_expressions' test_named_expression_scope_mangled_names -- a
! mangling test, not a walrus test; every walrus behaviour was already right.
!
! WHY PARSE TIME.  Mangling only at the emit was tried and cannot be made
! consistent: the parser's scope sets (variables, writes, globals, parameters)
! are keyed on the name AS RECORDED, so a name mangled only at emit is looked up
! under one spelling and bound under another.  That attempt fixed ``global
! __x'' and broke a walrus targeting the pre-mangled spelling, which had
! passed.  PythonParser >> ___mangle___: now rewrites each name where it is
! recorded, so text and IR codegen both see one spelling.  The rule itself is
! AbstractNode class >> ___mangle___:forClass:, shared with codegen, and it is
! idempotent -- codegen's own mangling calls pass harmlessly over names the
! parser has already mangled.
!
! WHAT STAYS RAW, each measured on CPython 3.14.6 and pinned by a test below:
!   * a def's or class's own __name__ / __qualname__ (``C.__m'');
!   * call-site keywords -- ``self.f(__a=1)'' passes __a even inside C;
!   * the spelling QUOTED by a compile-time diagnostic (NameAst >> writtenId);
!   * everything outside a class body.
!
! The ATTRIBUTE half of the rule (``self.__x'' -> _C__x) is covered separately
! by PrivateNameManglingTestCase / tests/python/private_name_mangling.py; this
! class covers the bare-name half.
!
! Two pre-existing codegen gaps in the same rule are closed here too, because
! the fixture exposed them: a private NESTED class bound under its raw name (so
! ``C._C__Inner'' was an AttributeError), and a private method reported its
! mangled selector as __name__.
!
! Drives tests/python/bare_name_mangling.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
BareNameManglingTestCase removeAllMethods.
BareNameManglingTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: BareNameManglingTestCase
setUp
	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'bare_name_mangling' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/bare_name_mangling.py')
		name: 'bare_name_mangling'.
%

category: 'Grail-Private'
method: BareNameManglingTestCase
assertMatchesCPythonAt: key
	"Both sides through repr, so a 5 and a '5' cannot pass for each other."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testTheUpstreamWalrusGlobalCase
	"THE TEST THIS WAS FOR, in its upstream nesting -- a class defined inside a
	function, ``global __x1'' in its method, and walruses writing the global
	under both spellings.  Before the fix the pre-mangled walrus reached a
	different variable from the one ``global'' declared."

	self assertMatchesCPythonAt: 'upstream_walrus_global'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testAGlobalIsDeclaredUnderTheMangledName
	self assertMatchesCPythonAt: 'global_key'.
	self assertMatchesCPythonAt: 'global_value'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testABareReadIsMangledToo
	"The permissive direction: Grail used to FIND a module-level __helper from
	inside a class, where CPython looks up _C__helper and raises NameError."

	self assertMatchesCPythonAt: 'bare_read_is_mangled'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testLocalsUseOneSpelling
	"__x and _C__x are the SAME local -- the property whose absence broke the
	codegen-only attempt."

	self assertMatchesCPythonAt: 'local_keys'.
	self assertMatchesCPythonAt: 'two_spellings_one_local'.
	self assertMatchesCPythonAt: 'del'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testParametersAreMangledButCallKeywordsAreNot
	"A private PARAMETER is mangled (co_varnames _C__a), and a call-site
	keyword never is -- so ``self.f(__a=1)'' is a TypeError even from inside
	the class.  The keyword half is the trap: parseAtom mangles the NameAst the
	keyword is read from, so its name has to come from the raw token."

	self assertMatchesCPythonAt: 'param_mangled_kw_ok'.
	self assertMatchesCPythonAt: 'param_raw_kw_rejected'.
	self assertMatchesCPythonAt: 'call_site_kw_stays_raw'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testBindingsMangleButNamesDoNot
	"CPython mangles a def's BINDING and keeps its __name__ as written."

	self assertMatchesCPythonAt: 'nested_def'.
	self assertMatchesCPythonAt: 'method_name'.
	self assertMatchesCPythonAt: 'bound_method_name'.
	self assertMatchesCPythonAt: 'inherited_private_name'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testAWrittenPremangledNameKeepsItsSpelling
	"``def _C__lit'' is spelled exactly like a mangled ``__lit'', and CPython
	reports it as written.  This is why __name__ reads a table of the defs that
	were ACTUALLY mangled rather than un-mangling the selector."

	self assertMatchesCPythonAt: 'literal_premangled_name'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testAPrivateNestedClassBindsMangled
	"Pre-existing, closed here: ``class __Inner'' inside C was stored under its
	raw name, so C._C__Inner was an AttributeError.  Its members mangle with the
	INNER class's name."

	self assertMatchesCPythonAt: 'inner_class_name'.
	self assertMatchesCPythonAt: 'inner_class_member_uses_inner_name'.
	self assertMatchesCPythonAt: 'class_attr'.
%

category: 'Grail-Tests'
method: BareNameManglingTestCase
testEveryOtherBindingForm
	self assertMatchesCPythonAt: 'nonlocal'.
	self assertMatchesCPythonAt: 'lambda'.
	self assertMatchesCPythonAt: 'comprehension'.
	self assertMatchesCPythonAt: 'except_as'.
	self assertMatchesCPythonAt: 'import_as'.
	self assertMatchesCPythonAt: 'fstring'.
	self assertMatchesCPythonAt: 'default_lambda'.
%
