! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for CellObjectsTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'CellObjectsTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
CellObjectsTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! CellObjectsTestCase
!
! The closure-cell and code TYPES -- types.CellType / types.CodeType -- and the
! cell protocol reachable through them.
!
! Grail has had real cell and code objects for a long time: ``f.__closure__''
! hands back PyCells that read and write the enclosing binding, and
! ``f.__code__'' answers a PyCode.  What was missing was the NAMES.  Both were
! empty stub classes in types.py, so ``isinstance(c, types.CellType)'' was False
! about a real cell, ``type(f.__code__)'' printed ``<class 'PyCode'>'' where
! CPython prints ``<class 'code'>'', and ``types.CellType(1)'' built an inert
! stub with no cell_contents at all.
!
! Exactly the shape of types.TracebackType before it was converted, and the same
! test types.py's own header sets for which stubs are worth converting: the stub
! stood in for a missing NAME, not a missing feature.
!
! WHAT A STANDALONE CELL IS.  ``types.CellType(v)'' closes over nothing, so
! there is no enclosing binding for PyCell's reader/writer pair to reach; those
! cells get a private one-slot holder instead.  That is also what makes them the
! only cells that can be EMPTIED.
!
! THREE THINGS NOT FIXED, stated rather than skipped, because each is blocked on
! something outside this class:
!
! 1. ``del'' ON A CLOSURE CELL is REFUSED (ValueError) where CPython empties it.
!    A closure cell's writer reaches the enclosing Smalltalk temp, and storing
!    the empty marker there would leave the defining scope and every sibling
!    closure reading a sentinel OBJECT rather than raising -- a silent wrong
!    value in place of a clean error.  Grail cannot unbind a Smalltalk temp.
!    CPython's test then asserts the enclosing name raises NameError /
!    UnboundLocalError, which needs unbindable bindings.
!
! 2. AN EMPTY *CLOSURE* CELL is not representable.  CPython's empty_cell()
!    closes over a local assigned only in a dead branch; Grail compiles that to a
!    Smalltalk temp holding nil, which is indistinguishable from a cell holding
!    None.  (A STANDALONE empty cell is fine -- it holds a marker object that can
!    never be a Python value, which is why nil was not reused for it.)
!
! 3. TWO EVALUATIONS OF ONE DEF SHARE A CELL, so cells from
!    ``cell(2)'' / ``cell(3)'' -- test_funcattrs' own helpers, both built from
!    one def site -- read the same value, and test_comparison cannot pass however
!    correct the comparison operators are.  Root cause found and recorded in
!    PyCell's class comment: the def-site stamp goes through
!    ExecBlockAttrs>>staticSlotAt:attr:put:, keyed by ``aBlock method'' and
!    skipping repeat writes -- right for __name__/__doc__, wrong for cells, which
!    capture a particular activation.  Only REFLECTION is affected; calling the
!    closures gives CPython's answers.  The fix is per-function-object storage,
!    which is what that table exists to avoid: its own comment records a measured
!    ``VM temporary object memory is full'' at ~100k def evaluations, there being
!    no weak-keyed collection in this GemStone.  So it needs weak storage, not a
!    change here.
!
! Drives tests/python/cell_objects.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and self-verifies against it.  Closes test_funcattrs'
! test_cell_new.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
CellObjectsTestCase removeAllMethods.
CellObjectsTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: CellObjectsTestCase
setUp
	"Reload tests/python/cell_objects.py fresh each test -- the module body
	MUTATES the cells it builds (contents assigned, deleted and refilled), so a
	shared instance would be reading a previous test's edits."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'cell_objects' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/cell_objects.py')
		name: 'cell_objects'.
%

category: 'Grail-Private'
method: CellObjectsTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Types Have Names'
method: CellObjectsTestCase
testACellIsAnInstanceOfCellType
	"THE TEST THIS EXISTS FOR.  isinstance(c, types.CellType) was False about a
	genuine closure cell, which is the first thing any closure-inspecting code
	asks."

	self assertMatchesCPythonAt: 'cell_isinstance'.
	self assertMatchesCPythonAt: 'cell_type_is'.
	self assertMatchesCPythonAt: 'cell_type_name'.
	self assertMatchesCPythonAt: 'cell_type_module'.
%

category: 'Grail-Tests - The Types Have Names'
method: CellObjectsTestCase
testACodeObjectIsAnInstanceOfCodeType
	"``type(f.__code__)'' printed <class 'PyCode'> -- Grail's internal spelling
	leaking into every repr.  test_funcattrs' test___code__ compares the type
	against types.CodeType directly."

	self assertMatchesCPythonAt: 'code_isinstance'.
	self assertMatchesCPythonAt: 'code_type_is'.
	self assertMatchesCPythonAt: 'code_type_name'.
	self assertMatchesCPythonAt: 'code_type_module'.
%

category: 'Grail-Tests - Constructing A Cell'
method: CellObjectsTestCase
testCellTypeIsCallable
	"types.CellType(v) is the standard way to build a cell; the stub class was
	not callable into anything useful, so this raised or answered an object with
	no cell_contents."

	self assertMatchesCPythonAt: 'ctor_value'.
	self assertMatchesCPythonAt: 'ctor_isinstance'.
%

category: 'Grail-Tests - Constructing A Cell'
method: CellObjectsTestCase
testAnEmptyCellRaisesRatherThanAnswering
	"``types.CellType()'' is EMPTY, and reading it is a ValueError -- not None.
	The distinction is why emptiness is a dedicated marker object rather than
	nil: ``types.CellType(None)'' is a FULL cell whose contents are None, and the
	two must not collapse."

	self assertMatchesCPythonAt: 'ctor_empty_reads'.
	self assertMatchesCPythonAt: 'ctor_none_is_not_empty'.
%

category: 'Grail-Tests - Writing And Clearing'
method: CellObjectsTestCase
testWritingCellContents
	"``c.cell_contents = v''.  Without PyCell>>__setattr__ this fell through to
	the generic object path and created a DYNAMIC INSTVAR shadowing the accessor,
	so the write appeared to succeed and the next read still answered the old
	value -- test_funcattrs' test_set_cell saw ``12 != 9''."

	self assertMatchesCPythonAt: 'set_contents'.
%

category: 'Grail-Tests - Writing And Clearing'
method: CellObjectsTestCase
testClearingAndRefillingAStandaloneCell
	"``del c.cell_contents'' empties it, so the next read raises; assigning again
	refills it.  Standalone cells only -- see this class's comment for why a
	CLOSURE cell refuses the delete instead."

	self assertMatchesCPythonAt: 'del_then_read'.
	self assertMatchesCPythonAt: 'refill_after_del'.
%

category: 'Grail-Tests - Comparison'
method: CellObjectsTestCase
testCellsCompareByTheirContents
	"CPython's cell_richcompare defers entirely to the contents, which is why
	``cell(-36) == cell(-36.0)'' is true: that is int/float equality, nothing
	cell-specific."

	self assertMatchesCPythonAt: 'lt_by_contents'.
	self assertMatchesCPythonAt: 'gt_by_contents'.
	self assertMatchesCPythonAt: 'ne_by_contents'.
	self assertMatchesCPythonAt: 'eq_across_numeric_types'.
%

category: 'Grail-Tests - Comparison'
method: CellObjectsTestCase
testAnEmptyCellSortsBeforeEveryFilledOne
	"The one ordering rule that is cell-specific rather than delegated, and the
	reason the comparisons cannot simply forward to cell_contents: reading an
	empty cell raises."

	self assertMatchesCPythonAt: 'empty_lt_filled'.
	self assertMatchesCPythonAt: 'filled_gt_empty'.
	self assertMatchesCPythonAt: 'empty_eq_empty'.
%

category: 'Grail-Tests - Comparison'
method: CellObjectsTestCase
testTheDerivedComparisonsAgree
	"__le__ / __ge__ are built from __gt__ / __lt__, so they need their own check
	that the negation is the right way round."

	self assertMatchesCPythonAt: 'le_equal'.
	self assertMatchesCPythonAt: 'ge_equal'.
%
