! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for CellEmptinessTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'CellEmptinessTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
CellEmptinessTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! CellEmptinessTestCase
!
! AN EMPTY CELL -- the third way to be empty, which Grail did not recognise.
!
! ``def f(): print(a)'' followed by ``f.__closure__[0]'' BEFORE ``a'' is assigned
! is CPython's empty cell, and it is the shape test_funcattrs uses to build one.
! Reading it is a ValueError, its repr says ``empty'', and it sorts before every
! filled cell.
!
! PyCell knew two ways to be empty: no reader at all, and a standalone
! ``types.CellType()'' holding the private marker.  A closure cell's reader is
! compiled as an ordinary local read, so evaluating an UNASSIGNED binding raised
! UnboundLocalError -- and that escaped from every place emptiness has to be
! decided: from cell_contents (CPython raises ValueError), from __repr__ (which
! must never raise at all), and from all six comparisons, because each has to ask
! whether the cell is empty before it can answer anything.
!
! The three ways now funnel through ONE read, ___readOrMarker___, which answers
! the empty marker rather than propagating.  It catches NameError and nothing
! wider: UnboundLocalError is its subclass, and a free variable of an enclosing
! scope that was never bound reports the base class -- while an error from
! evaluating the binding for any OTHER reason is a real error and must not be
! reported as emptiness.
!
! EMPTINESS IS A QUESTION ABOUT NOW.  A cell tracks its binding rather than
! snapshotting it, so the same cell object reads empty before the assignment and
! filled after -- testTheSameCellFillsIn is that, and it is why the check cannot
! be done once when the cell is built.
!
! ------------------------------------------------------------------------------
! WHAT IS STILL WRONG, and why it is not fixed here.
!
! ``__closure__'' IS STAMPED PER DEF SITE, NOT PER ACTIVATION.  A helper called
! twice hands back the FIRST call's cells both times:
!
!     def mk(v):
!         def f(): return a
!         a = v
!         return f
!     f1 = mk(10); f2 = mk(20)
!     f1(), f2()                                  ->  10, 20   (correct)
!     f1.__closure__[0].cell_contents             ->  10       (correct)
!     f2.__closure__[0].cell_contents             ->  10       (CPython: 20)
!     f1.__closure__[0] is f2.__closure__[0]      ->  True     (CPython: False)
!
! So the closure SEMANTICS are right and only the REFLECTION lies -- which is the
! quiet kind of wrong: a plausible value, from a different call, with nothing
! raised.  It is why test_funcattrs' test_comparison still fails: its helpers
! ``cell(2)'' and ``cell(3)'' share one def site, so the second comparison is
! really ``2 < 2''.
!
! WHY NOT FIXED.  ExecBlockAttrs keys def-time stamps by ``aBlock method'' (the
! def site) precisely because the per-object table holds its keys STRONGLY and
! this GemStone has no weak-keyed collection -- Globals offers only
! FsFileDescriptorEphemeron and GcWeakReferences.  Storing __closure__ per
! function object would make every closure-with-free-variables immortal for the
! session, which for a gem that serves requests for hours is unbounded growth;
! trading a reflection bug for a leak is not a trade worth making.  (A 200k-
! closure simulation did fit in one session's temp cache, so the cliff is not
! near -- but "not near" is not "bounded".)  The real fix is to stop storing the
! array at all and build the cells LAZILY from the block's captured frame
! (ExecBlock carries its own ``staticLink''), which needs the free-variable slot
! indices from codegen and is a project rather than a patch.
!
! The fixture is written to avoid tripping over this rather than to hide it:
! every probe builds its cells at ONE def site, entered once, and the deviation
! is spelled out in the file header with the shape that exposes it.
! ------------------------------------------------------------------------------
!
! Drives tests/python/cell_emptiness.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and self-verifies against it.  Closes test_funcattrs'
! test_empty_cell.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
CellEmptinessTestCase removeAllMethods.
CellEmptinessTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: CellEmptinessTestCase
setUp
	"Reload tests/python/cell_emptiness.py fresh each test.  The module body runs
	every probe at import, and each probe assigns the binding its cell closes
	over before returning -- so a shared instance would let one test see another
	test's filled cell."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'cell_emptiness' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/cell_emptiness.py')
		name: 'cell_emptiness'.
%

category: 'Grail-Private'
method: CellEmptinessTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Reading An Empty Cell'
method: CellEmptinessTestCase
testReadingAnUnassignedClosureCellIsAValueError
	"THE TEST THIS EXISTS FOR.  CPython raises ValueError('Cell is empty');
	Grail let the reader's own UnboundLocalError escape, so the caller saw the
	error of the BINDING rather than the error of the CELL -- and an ``except
	ValueError'' around it, which is how the empty case is written, did not
	catch."

	self assertMatchesCPythonAt: 'read_before_assignment'.
	self assertMatchesCPythonAt: 'read_after_assignment'.
%

category: 'Grail-Tests - Reading An Empty Cell'
method: CellEmptinessTestCase
testTheSameCellFillsIn
	"Emptiness is a question about NOW.  One cell object, read either side of
	the assignment: empty, then filled.  A cell tracks its binding rather than
	snapshotting it, which is why the answer cannot be settled when the cell is
	built."

	self assertMatchesCPythonAt: 'the_same_cell_fills_in'.
%

category: 'Grail-Tests - Reading An Empty Cell'
method: CellEmptinessTestCase
testTheReprSaysEmptyAndDoesNotRaise
	"A repr must never raise, and this one did -- for exactly the cells whose
	repr is the interesting one."

	self assertMatchesCPythonAt: 'repr_does_not_raise'.
%

category: 'Grail-Tests - Comparisons Decide Emptiness First'
method: CellEmptinessTestCase
testEmptySortsBeforeEveryFilledCell
	"CPython's cell_richcompare puts an empty cell before every filled one and
	otherwise defers entirely to the contents.  Every one of those paths asks
	___isEmpty___ first, so all six comparisons raised on an unassigned
	binding."

	self assertMatchesCPythonAt: 'empty_equals_empty'.
	self assertMatchesCPythonAt: 'empty_sorts_before_filled'.
%

category: 'Grail-Tests - Comparisons Decide Emptiness First'
method: CellEmptinessTestCase
testFilledCellsCompareByTheirContents
	"The other half of the rule, and the guard against a fix that reports
	everything empty: two filled cells compare as their contents do, including
	``cell(-36) == cell(-36.0)'', which is ordinary numeric equality and nothing
	cell-specific."

	self assertMatchesCPythonAt: 'filled_cells_compare_by_contents'.
	self assertMatchesCPythonAt: 'int_and_float_cells_are_equal'.
%

category: 'Grail-Tests - The Standalone Cell Still Works'
method: CellEmptinessTestCase
testAStandaloneCellIsStillEmptyItsOwnWay
	"``types.CellType()'' is empty by holding the private marker, not by having
	an unassigned binding -- a different route to the same answer, and the
	regression guard for routing all three through one read.  And None is a
	VALUE a cell may hold, which CPython tells apart from empty."

	self assertMatchesCPythonAt: 'standalone_empty'.
	self assertMatchesCPythonAt: 'standalone_holding_none'.
%
