! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ClassAttrDunderBindingTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ClassAttrDunderBindingTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ClassAttrDunderBindingTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ClassAttrDunderBindingTestCase (issue #1218)
! Drives tests/python/class_attr_dunder_binding.py, generated by
! scripts/generate_class_attr_dunder_fixture.py, whose EXPECTED table is
! CPython 3.14's output.  Each case stores one kind of callable under one
! protocol dunder -- in the class body and with setattr -- and exercises the
! protocol; the value reports how many arguments it received, so passing the
! instance wrongly changes the answer.
!
! One test per value KIND, because the kind is what decides the binding:
! object >> ___typeAttrBound___: is the single rule, and a regression in it
! shows up as a whole kind failing across every protocol.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ClassAttrDunderBindingTestCase removeAllMethods.
ClassAttrDunderBindingTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ClassAttrDunderBindingTestCase
setUp
	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'class_attr_dunder_binding' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/class_attr_dunder_binding.py')
		name: 'class_attr_dunder_binding'.
%

category: 'Grail-Setup'
method: ClassAttrDunderBindingTestCase
tearDown
	(importlib @env1:modules) removeKey: #'class_attr_dunder_binding' ifAbsent: [].
	testModule := nil
%

category: 'Grail-Private'
method: ClassAttrDunderBindingTestCase
assertKindMatchesCPython: aKind
	"Every case of aKind agrees with CPython; the failure lists the ones that
	do not, with both answers."

	| bad |
	bad := (testModule @env1:___pyAttrLoad___: #mismatches)
		@env1:___pyCallValue___: { aKind } kw: nil.
	self
		assert: (bad @env1:__len__) = 0
		description: aKind , ': ' , (builtins @env1:instance @env1:repr: bad) asString
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testEveryCaseRan
	"The table is the CPython run's: as many results as expectations, and
	enough of them that a generator change cannot empty the test quietly."

	| results expected |
	results := testModule @env1:___pyAttrLoad___: #RESULTS.
	expected := testModule @env1:___pyAttrLoad___: #EXPECTED.
	self assert: (expected @env1:__len__) >= 383.
	self assert: (results @env1:__len__) = (expected @env1:__len__)
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testFunctionsBindTheInstance
	"A def, a lambda, and a function read off another class (Grail's
	UnboundMethod) all bind: the instance comes first."

	self assertKindMatchesCPython: 'func'.
	self assertKindMatchesCPython: 'lambda'.
	self assertKindMatchesCPython: 'plainfn'
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testClassmethodBindsTheClass
	self assertKindMatchesCPython: 'classm'
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testStaticmethodTakesTheArgumentsAlone
	self assertKindMatchesCPython: 'static'
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testBoundMethodIsNotBoundAgain
	"``__len__ = lst.__len__'', ``__next__ = gen.__next__'': already bound,
	not a descriptor, called with the arguments alone."

	self assertKindMatchesCPython: 'bound'
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testCallableInstanceIsNotBound
	self assertKindMatchesCPython: 'callobj'
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testIterparse
	"The issue's end-to-end case: CPython 3.14's ElementTree.iterparse builds
	its iterator class with ``__next__ = gen.__next__''."

	self assertKindMatchesCPython: 'ET.iterparse'
%

category: 'Grail-Tests'
method: ClassAttrDunderBindingTestCase
testObjectDefaultIsNotAnOverride
	"``__str__ = object.__str__'' names the default, which is the very method
	that looks the attribute up: called as an override it re-entered itself
	until the stack ran out (test_enum's test_object_str_override)."

	self assertKindMatchesCPython: 'object.default'
%
