! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ClassBodyMethodAliasTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ClassBodyMethodAliasTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ClassBodyMethodAliasTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ClassBodyMethodAliasTestCase
!
! ``alias = method'' in a class body binds the SAME function object under a
! second name.  Everything CPython does here follows from that one sentence:
! ``C.alias is C.m'', ``C.alias.__name__ == 'm''', the two __dict__ entries are
! one object, and a LATER class-body statement may read the alias name like any
! other binding.
!
! Grail compiles such an alias as a real delegating METHOD instead, and that is
! the RIGHT call: a class-attribute callable is invisible to operator dispatch
! (``a < b'' sends #__lt__:, which resolves only to compiled methods) and
! mis-binds when read through an instance.  It is also, on its own, the wrong
! call for identity -- a delegating method is a different object -- and the
! alias name was missing from every class-body READ path, so a later statement
! naming it raised NameError while the class was being built.
!
! THE TWO HALVES ARE TESTED TOGETHER BECAUSE THE FIX HAS TO KEEP BOTH TRUE AT
! ONCE.  The alias name now resolves to the original's function object, and the
! compiled forwarder stays -- which is what makes the identity fix free, since
! operator dispatch never goes through attribute lookup at all.
!
! Three defects, of three different severities:
!
!   * NameError at class-init time on a later read of the alias name.  Loud,
!     and fatal to a whole module: it is why test.test_reprlib scored
!     IMPORTERROR, 0 tests, with detail ``name 'wrapped' is not defined''.
!   * ``C.alias is C.m'' answered False.  SILENT -- nothing raised, ``is''
!     simply answered the wrong way, and a method pickled by reference (what
!     functools.total_ordering does) cannot round-trip when the name does not
!     resolve back to the same object.
!   * ``plain = plain'', a SELF-alias of a def, died with an OffsetError -- an
!     UNCATCHABLE Smalltalk error, not a Python one, so a Python ``except''
!     could not see it.  It is excluded from the delegating-method collection
!     (``plain ^ self plain'' would be an infinite recursion) and was excluded
!     nowhere else, so it landed on the class-ATTRIBUTE path, shadowed the
!     compiled method with a receiver-less BoundMethod, and popped a receiver
!     off an empty argument array.
!
! Drives tests/python/class_body_method_aliases.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ClassBodyMethodAliasTestCase removeAllMethods.
ClassBodyMethodAliasTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ClassBodyMethodAliasTestCase
setUp
	"Reload tests/python/class_body_method_aliases.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'class_body_method_aliases' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/class_body_method_aliases.py')
		name: 'class_body_method_aliases'.
%

category: 'Grail-Private'
method: ClassBodyMethodAliasTestCase
assertMatchesCPythonAt: key
	"Compare through repr, not asString: several answers here are booleans and
	short strings, where asString would let ``'m''' and ``m'' -- or True and
	the string 'True' -- pass for each other, and this suite is precisely about
	which OBJECT a name answers."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Identity'
method: ClassBodyMethodAliasTestCase
testAnAliasIsTheSameObjectAsTheOriginal
	"The silent half.  Nothing raised when this was wrong -- ``is'' just
	answered False -- and pickling a method BY REFERENCE (what
	functools.total_ordering's test does) can only round-trip if the
	name resolves back to the same object."

	self assertMatchesCPythonAt: 'alias_is_m'.
	self assertMatchesCPythonAt: 'dict_entries_identical'.
%

category: 'Grail-Tests - Identity'
method: ClassBodyMethodAliasTestCase
testAnAliasCarriesTheOriginalsName
	"``C.alias.__name__'' is 'm', not 'alias' -- the alias never renamed
	anything, it bound an existing function a second time."

	self assertMatchesCPythonAt: 'alias_name'.
%

category: 'Grail-Tests - Identity'
method: ClassBodyMethodAliasTestCase
testEveryNameInAChainedAliasIsTheSameObject
	"``__ne__ = __lt__ = __le__ = __gt__ = __ge__ = __eq__'' is verbatim
	from test_heapq's CmpErr.  One value AST, five names, one object."

	self assertMatchesCPythonAt: 'chain_all_identical'.
%

category: 'Grail-Tests - Calling'
method: ClassBodyMethodAliasTestCase
testAnAliasIsCallableThroughClassAndInstance
	"Both directions, because they take different paths: through the class
	the first argument IS the receiver, through the instance it is bound."

	self assertMatchesCPythonAt: 'alias_call_via_class'.
	self assertMatchesCPythonAt: 'alias_call_via_instance'.
%

category: 'Grail-Tests - Calling'
method: ClassBodyMethodAliasTestCase
testAnAliasOfAMethodWithArgumentsKeepsItsArity
	"The delegating form Grail emits has to carry the original's arity --
	a wrong one is a doesNotUnderstand, not a wrong answer."

	self assertMatchesCPythonAt: 'alias_with_args'.
	self assertMatchesCPythonAt: 'alias_with_args_via_class'.
%

category: 'Grail-Tests - Later Reads'
method: ClassBodyMethodAliasTestCase
testALaterClassBodyStatementCanReadTheAliasName
	"The loud half, and the one that cost a whole module: an alias binds a
	class-body name but is neither a def nor a class attribute in Grail's
	accounting, so the read fell through to the MODULE and raised
	``name 'wrapped' is not defined'' while the class was being built.
	test.test_reprlib scored IMPORTERROR with that exact detail."

	self assertMatchesCPythonAt: 'later_read_staticmethod'.
	self assertMatchesCPythonAt: 'later_read_in_tuple'.
	self assertMatchesCPythonAt: 'later_read_in_list'.
%

category: 'Grail-Tests - Later Reads'
method: ClassBodyMethodAliasTestCase
testALaterReadAnswersTheOriginalObjectNotTheForwarder
	"Making the read merely WORK is not enough.  Answering the alias's own
	compiled forwarder calls correctly and compares unequal -- which is the
	silent bug again, one level in.  This is why the compile context maps
	alias -> ORIGINAL name rather than collecting a set of alias names."

	self assertMatchesCPythonAt: 'later_read_tuple_identity'.
%

category: 'Grail-Tests - Operator Dispatch'
method: ClassBodyMethodAliasTestCase
testAliasedComparisonOperatorsStillDispatch
	"The reason aliases are compiled as methods at all.  ``a < b'' sends
	#__lt__: and never consults attribute lookup, so a class-attribute
	binding is invisible to it.  If the identity fix had replaced the
	forwarder instead of joining it, all six of these would fail."

	self assertMatchesCPythonAt: 'op_eq'.
	self assertMatchesCPythonAt: 'op_ne'.
	self assertMatchesCPythonAt: 'op_lt'.
	self assertMatchesCPythonAt: 'op_le'.
	self assertMatchesCPythonAt: 'op_gt'.
	self assertMatchesCPythonAt: 'op_ge'.
%

category: 'Grail-Tests - Operator Dispatch'
method: ClassBodyMethodAliasTestCase
testHashAliasedToASiblingMethodIsARealHash
	"A class that defines __eq__ and nothing else is unhashable; aliasing a
	method onto __hash__ opts back IN.  The implicit unhashable-__hash__
	Grail emits must not overwrite the alias -- if it did, hash() would
	raise rather than answer 42."

	self assertMatchesCPythonAt: 'hash_alias_value'.
	self assertMatchesCPythonAt: 'hash_alias_is_h'.
	self assertMatchesCPythonAt: 'hash_alias_in_set'.
%

category: 'Grail-Tests - Inheritance'
method: ClassBodyMethodAliasTestCase
testASubclassOverrideOfTheAliasWins
	"The check that keeps the identity fix honest.  A redirect that ignored
	the subclass's own def would answer 'base' here and nothing would say
	so; the binding is per-class, held in the class's OWN attribute store,
	so the override simply shadows it."

	self assertMatchesCPythonAt: 'inherited_alias_call'.
	self assertMatchesCPythonAt: 'overridden_alias_call'.
	self assertMatchesCPythonAt: 'overridden_alias_not_base'.
%

category: 'Grail-Tests - Inheritance'
method: ClassBodyMethodAliasTestCase
testOverridingTheOriginalDoesNotMoveTheAlias
	"An alias is a SNAPSHOT of the function object taken while the class
	body ran, not a live indirection through the name, so a subclass that
	overrides the ORIGINAL leaves the alias pointing at the base function.
	A delegating method -- ``alias ^ self m'' -- would follow the override
	and answer 'sub-m'."

	self assertMatchesCPythonAt: 'override_original_alias_still_base'.
	self assertMatchesCPythonAt: 'override_original_m'.
%

category: 'Grail-Tests - Not Aliases'
method: ClassBodyMethodAliasTestCase
testASelfAliasOfADefIsANoOp
	"``plain = plain'' died with an OffsetError -- an UNCATCHABLE Smalltalk
	error, so a Python ``except'' around the call could not see it.  It is
	excluded from the delegating-method collection on purpose (``plain ^
	self plain'' is an infinite recursion) and was excluded nowhere else,
	so it became a class ATTRIBUTE holding a receiver-less BoundMethod that
	shadowed the compiled method and popped a receiver off an empty array.

	CPython reads the name the def just bound and binds it straight back,
	so declaring no attribute for it is exact, not an approximation."

	self assertMatchesCPythonAt: 'self_alias_call'.
%

category: 'Grail-Tests - Not Aliases'
method: ClassBodyMethodAliasTestCase
testADecoratedDefIsAliasedAsItsDecoratedValue
	"``b = a'' where a is decorated must bind the DECORATOR'S RESULT --
	CPython has already replaced the def by the time the assignment runs.
	Such a def is kept off the delegating-method path for exactly this
	reason (a forwarder would call the raw compiled method), so these
	assertions also guard the boundary between the two paths."

	self assertMatchesCPythonAt: 'deco_alias_call'.
	self assertMatchesCPythonAt: 'deco_alias_is_deco'.
	self assertMatchesCPythonAt: 'deco_alias_carries_attr'.
%

category: 'Grail-Tests - Not Aliases'
method: ClassBodyMethodAliasTestCase
testStaticAndVarargsAliasesStayOnTheAttributePath
	"A @staticmethod has no receiver to bind and a varargs def has no known
	arity, so neither can be given a fixed-arity forwarder.  Both keep the
	class-attribute treatment they already had -- listed here so a later
	widening of the alias rule has to answer for them."

	self assertMatchesCPythonAt: 'static_alias_call'.
	self assertMatchesCPythonAt: 'static_alias_is_stat'.
	self assertMatchesCPythonAt: 'varargs_alias_call'.
	self assertMatchesCPythonAt: 'varargs_alias_is_varargs'.
%
