! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ClassBodyConditionalTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ClassBodyConditionalTestCase'
  instVarNames: #( probe )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ClassBodyConditionalTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ClassBodyConditionalTestCase
!
! ``def'' inside a class-body ``if''.
!
! Grail compiles a class body STRUCTURALLY -- each def becomes a real
! Smalltalk method on the generated class -- rather than executing it as a
! suite the way CPython does.  A conditional def cannot take that route: its
! existence is a runtime fact, and both branches of one ``if'' would install
! the same selector with whichever emitted last winning.  So the whole form
! was dropped, silently: the class simply had no such attribute, and the only
! symptom was an AttributeError far from the definition.
!
! ClassDefAst >> emitClassBodyIfDef:on: emits it as a VALUE instead -- the
! nested-def block form, stored in the per-class dynamic attr store that the
! guarded ASSIGNMENT case (which did already work) has always used.  A plain
! function there binds the receiver on an instance read and comes back raw on
! a class read, which is what CPython does with a function in a class
! namespace.  @staticmethod / @classmethod arrive re-classed by the parser
! rather than carrying a runtime decorator, so the wrapper that would have
! been applied structurally is applied here instead.
!
! Two consequences worth pinning, both covered below:
!   * ``self'' inside such a def is the transported ``_self'' temp, NOT the
!     Smalltalk receiver -- CallAst >> isSelfReference: has to answer false
!     for the whole emit window or the body reads the enclosing MODULE.
!   * a name bound earlier in the same branch has no accessor pair, so
!     NameAst reads it from the dynamic store, falling back to the module
!     global when the slot is nil (the branch did not run) -- which is what
!     Python's class-body lookup does once the class namespace comes up empty.
!
! Still dropped, and NOT covered here: ``for'' / ``while'' / ``try'' in a
! class body, which never had even the assignment half.  test_enum's Period
! (members generated by a loop) is the corpus example.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ClassBodyConditionalTestCase removeAllMethods.
ClassBodyConditionalTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ClassBodyConditionalTestCase
setUp
	"Reload tests/python/class_body_conditional.py fresh each test and keep
	its single probe() dict -- the class is built once at import, so every
	assertion below is a read of that one construction."

	| mods testModule |
	mods := importlib @env1:modules.
	mods removeKey: #'class_body_conditional' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir
			, '/tests/python/class_body_conditional.py')
		name: 'class_body_conditional'.
	probe := testModule @env1:probe.
%

category: 'Grail-Private'
method: ClassBodyConditionalTestCase
at: aKey
	^ probe @env1:__getitem__: aKey
%

! --- the def forms ---

category: 'Grail-Tests - Def Forms'
method: ClassBodyConditionalTestCase
testGuardedInstanceMethodBindsTheReceiver
	"The headline case, and the one that hid a second bug: emitted as a
	block, ``self'' is a transported temp, so a body reference to it read
	the enclosing MODULE instance until isSelfReference: was scoped."

	self assert: (self at: 'inst') @env0:asString equals: 'inst:Conditional:1'.
%

category: 'Grail-Tests - Def Forms'
method: ClassBodyConditionalTestCase
testGuardedStaticMethodNeverBinds
	"@staticmethod reaches codegen re-classed by the parser, not as a
	runtime decorator, so the emit has to wrap it in PyStaticMethod itself
	-- otherwise the plain function in the dynamic store would bind the
	receiver on the instance read and pass it as x."

	self assert: (self at: 'static_via_instance') @env0:asString equals: 'static:2'.
	self assert: (self at: 'static_via_class') @env0:asString equals: 'static:2'.
%

category: 'Grail-Tests - Def Forms'
method: ClassBodyConditionalTestCase
testGuardedClassMethodBindsTheOwner
	"Reached through an instance, through the class, and through a
	SUBCLASS -- the last is what distinguishes binding the owner from
	binding the defining class."

	self assert: (self at: 'cls_via_instance') @env0:asString equals: 'cls:Conditional:3'.
	self assert: (self at: 'cls_via_class') @env0:asString equals: 'cls:Conditional:3'.
	self assert: (self at: 'cls_via_subclass') @env0:asString equals: 'cls:Sub:3'.
%

category: 'Grail-Tests - Def Forms'
method: ClassBodyConditionalTestCase
testGuardedDefTakesItsDecorators
	"A genuine runtime decorator still applies: FunctionDefAst's own
	decorator chain rebinds the block temp before the store, so nothing
	special is needed here -- this pins that it stays that way."

	self assert: (self at: 'decorated') @env0:asString equals: 'deco(decorated)'.
%

category: 'Grail-Tests - Def Forms'
method: ClassBodyConditionalTestCase
testGuardedDefIsInherited
	"It lands in the per-class dynamic store, which the attribute-load path
	walks up the class chain -- so a subclass sees it."

	self assert: (self at: 'inherited') @env0:asString equals: 'inst:Sub:4'.
%

! --- which branch ran ---

category: 'Grail-Tests - Branches'
method: ClassBodyConditionalTestCase
testTheTakenBranchWins
	"``if flag:'' defines inst_meth one way and ``else:'' another.  Emitting
	both as methods would have installed one selector twice."

	self assert: (self at: 'has_inst_meth') equals: true.
	self assert: (self at: 'inst') @env0:asString equals: 'inst:Conditional:1'.
%

category: 'Grail-Tests - Branches'
method: ClassBodyConditionalTestCase
testAnUntakenBranchDefinesNothing
	self assert: (self at: 'has_not_taken') equals: false.
%

category: 'Grail-Tests - Branches'
method: ClassBodyConditionalTestCase
testTheElseBranchDefines
	self assert: (self at: 'else_meth') @env0:asString equals: 'else_meth'.
%

! --- name resolution inside the branch ---

category: 'Grail-Tests - Name Resolution'
method: ClassBodyConditionalTestCase
testABranchNameIsVisibleLaterInTheSameBranch
	"``marker = 'yes''' then ``echo = marker''.  The name has no accessor
	pair -- it is in the dynamic store -- so NameAst needs the conditional-
	name set to know where to read it.  test_functools' TestLRUC does this
	with ``module = c_functools'' and then ``@module.lru_cache()''."

	self assert: (self at: 'echo') @env0:asString equals: 'yes'.
%

category: 'Grail-Tests - Name Resolution'
method: ClassBodyConditionalTestCase
testAnUnboundNameFallsBackToTheModuleGlobal
	"``from_global = helper'' where helper is a module global, not a class
	attribute.  The dynamic-store read answers nil and the emit falls
	through -- matching Python, whose class-body lookup consults the
	enclosing scope once the class namespace comes up empty."

	self assert: (self at: 'from_global') @env0:asString
		equals: 'module-global-helper'.
%

! --- no collateral damage ---

category: 'Grail-Tests - Name Resolution'
method: ClassBodyConditionalTestCase
testAnUnguardedDefStillCompilesAsAMethod
	"The structural path is untouched for everything outside an ``if''."

	self assert: (self at: 'unconditional') @env0:asString equals: 'unconditional'.
%

set compile_env: 0
