! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for CodeFlagsTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'CodeFlagsTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
CodeFlagsTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! CodeFlagsTestCase
!
! ``code.co_flags'', and the ``f.__code__ = g.__code__'' rule that turns on it.
!
!      1  CO_OPTIMIZED         32  CO_GENERATOR
!      2  CO_NEWLOCALS        128  CO_COROUTINE
!      4  CO_VARARGS          512  CO_ASYNC_GENERATOR
!      8  CO_VARKEYWORDS
!     16  CO_NESTED
!
! The three KIND bits are the ones conformance turns on: they are how CPython
! tells a plain function, a generator, a coroutine and an async generator apart.
! Every bit above is a property of the SOURCE, so Grail knows all of them at
! compile time -- isAsync from the keyword, isGenerator from a ``yield'' in the
! body -- and the answer is exact rather than approximated.  Verified against
! CPython for all four kinds, all four parameter shapes, and nested against
! module-level: 19 / 51 / 531 / 147 and 3 for a top-level def, matching
! CPython's values bit for bit.
!
! CO_ITERABLE_COROUTINE (256) is deliberately absent: it is set by
! ``types.coroutine'' at RUN time, not by the compiler, so stamping it would be
! a claim about something Grail has not done.  CO_NOFREE (64) is deprecated in
! CPython and always clear.
!
! WHY THE FLAGS MATTER RATHER THAN BEING DECORATION.  Without them the
! ``__code__'' assignment rule cannot be stated at all.  CPython warns when the
! assignment changes the KIND,
!
!     DeprecationWarning: Assigning a code object of non-matching type is
!     deprecated (e.g., from a generator to a plain function)
!
! because a function's calling protocol is fixed at definition -- a generator's
! caller expects an iterator back, a coroutine's an awaitable -- so installing
! code of another kind leaves the two disagreeing, and the failure appears at
! the NEXT CALL rather than at the assignment that caused it.  A warning and not
! a refusal: the assignment still happens, and testTheAssignmentStillHappens is
! the half a "just raise" reading of the rule would break.
!
! ONLY THE KIND BITS ARE COMPARED.  The parameter-shape flags beside them
! legitimately differ between any two functions, so comparing whole flag words
! would warn on almost every assignment -- testSameKindDoesNotWarn is that
! guard, using two functions whose shape bits differ and whose kinds do not.
!
! ORDERED AFTER THE FREE-VARIABLE REFUSAL, because a write that is about to
! raise should not also warn about a kind it was never going to install.
!
! Drives tests/python/code_flags.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and self-verifies against it.  Closes test_funcattrs'
! test_invalid___code___assignment.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
CodeFlagsTestCase removeAllMethods.
CodeFlagsTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: CodeFlagsTestCase
setUp
	"Reload tests/python/code_flags.py fresh each test: the probes ASSIGN
	__code__ on the functions they build, so a shared instance would let one
	test read code another test installed."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'code_flags' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/code_flags.py')
		name: 'code_flags'.
%

category: 'Grail-Private'
method: CodeFlagsTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Flag Word'
method: CodeFlagsTestCase
testTheFourKinds
	"Plain function, generator, async generator and coroutine, as CPython's own
	numbers -- 19 / 51 / 531 / 147 -- rather than four values that merely differ
	from one another.  Distinctness is asserted separately because it is what
	the assignment rule is stated in terms of: two kinds that collided could
	not be told apart at all."

	self assertMatchesCPythonAt: 'the_four_kinds'.
	self assertMatchesCPythonAt: 'the_four_kinds_are_all_distinct'.
%

category: 'Grail-Tests - The Flag Word'
method: CodeFlagsTestCase
testParameterShapeAndNesting
	"``*args'', ``**kwargs'', both, and neither; and CO_NESTED set for a def
	inside a def but clear for a module-level one.  These bits are not what the
	assignment rule reads, which is exactly why they are checked -- a rule that
	compared whole flag words would trip on them."

	self assertMatchesCPythonAt: 'parameter_shape_bits'.
	self assertMatchesCPythonAt: 'nesting_is_a_flag'.
%

category: 'Grail-Tests - The Assignment Rule'
method: CodeFlagsTestCase
testAssigningAcrossKindsWarns
	"THE TEST THIS EXISTS FOR: one DeprecationWarning, carrying CPython's
	wording.  test_funcattrs matches on ``code object of non-matching type'',
	so the phrase is part of the contract rather than incidental prose."

	self assertMatchesCPythonAt: 'assign_across_kinds_warns'.
%

category: 'Grail-Tests - The Assignment Rule'
method: CodeFlagsTestCase
testEveryMismatchedPairWarns
	"All twelve ordered pairs, as test_funcattrs walks them.  A rule that fired
	in one direction only, or for one kind only, would still pass a single
	case."

	self assertMatchesCPythonAt: 'every_mismatched_pair_warns'.
%

category: 'Grail-Tests - The Assignment Rule'
method: CodeFlagsTestCase
testTheRuleDoesNotOvershoot
	"Two guards a careless reading of the rule breaks.  Same KIND must go
	through in silence even when the parameter-shape bits differ -- otherwise
	nearly every assignment warns.  And the warning is a WARNING: the
	assignment still takes effect, which is what distinguishes this from the
	free-variable rule beside it, where the write is refused outright."

	self assertMatchesCPythonAt: 'same_kind_does_not_warn'.
	self assertMatchesCPythonAt: 'the_assignment_still_happens'.
%
