! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for CodeFreevarsAndMethodTypeTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'CodeFreevarsAndMethodTypeTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
CodeFreevarsAndMethodTypeTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! CodeFreevarsAndMethodTypeTestCase
!
! Two gaps of the same shape: Grail HAS the object and only the way to NAME it
! was missing.  They are covered together because they are each too small for a
! file of their own and share that one cause.
!
! ------------------------------------------------------------------------------
! 1.  ``code.co_freevars'' did not exist.
!
! Grail computes a def's free-variable set at compile time -- it is what
! ``__closure__'' and ``locals()'' are both built from -- and never stamped it
! onto the code object.  The field is not decoration: CPython states the
! ``f.__code__ = g.__code__'' rule in terms of it and refuses the assignment
! when the two disagree,
!
!     ValueError: b() requires a code object with 0 free vars, not 1
!
! because a function's cells and its code would otherwise describe different
! closures.  Without co_freevars that rule cannot be written at all, so every
! such assignment was accepted and the damage surfaced at the next call.
!
! THE COUNT COMES FROM THE SAME SET AS THE CELLS.  FunctionDefAst stamps
! co_freevars from CallAst>>___freeVariableNamesFor___:, which is exactly what
! emitClosureCellsOn: builds __closure__ from -- so the check cannot disagree
! with the thing it protects.  A separately derived name set would have been a
! second source of truth for one fact, which is how the two drift apart.
!
! WHY THE EMITTER NEEDS TWO METHODS.  ``___setFreevars___:'' is a cascade onto a
! FINISHED PyCode, so the constructor's keyword message has to be parenthesised
! first; the emitters write straight to a stream, so the opening paren has to be
! written before the constructor and the close after it.  Emitted only when the
! def closes over something -- PyCode>>co_freevars answers an empty tuple
! otherwise, which is CPython's value and not an absence, since
! ``len(co.co_freevars)'' is how the rule is phrased.
!
! ------------------------------------------------------------------------------
! 2.  ``types.MethodType'' was an empty stub.
!
! Every OTHER name in Grail's ``types'' is a stub on purpose: a stub is the
! honest answer for a name that only ever appears in an ``isinstance'' test,
! because Grail has no public class object matching CPython's and converting one
! with no counterpart would replace an honest False with an error.
!
! This one is different because it is CALLED, to bind a function to an object
! after the fact:
!
!     self.fi.id = types.MethodType(id, self.fi)
!     self.fi.id()                       # -> id(self.fi)
!
! Calling the stub answered something that was not callable, and invoking THAT
! raised a raw Smalltalk MessageNotUnderstood rather than any Python error.
! That is the worst failure shape available: uncatchable from Python, and in the
! conformance harness a Smalltalk escape voids the scoring of the whole module
! -- test_funcattrs was reported STERROR with ZERO tests counted whenever this
! ran first.  So the value here is larger than the one test it closes.
!
! ``__slots__'' rather than a plain class body, because CPython's method type
! has no attribute storage: setting or deleting any other name is an
! AttributeError, and test_funcattrs checks both directions.  Grail's own bound
! methods remain BoundMethod; this provides the CONSTRUCTOR, which Grail had no
! spelling for at all.
!
! ------------------------------------------------------------------------------
! Drives tests/python/code_freevars_and_method_type.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and self-verifies against it.  Closes
! test_funcattrs' test___code__ and test___func___non_method.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
CodeFreevarsAndMethodTypeTestCase removeAllMethods.
CodeFreevarsAndMethodTypeTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: CodeFreevarsAndMethodTypeTestCase
setUp
	"Reload tests/python/code_freevars_and_method_type.py fresh each test: the
	module body ASSIGNS __code__ on the functions it builds, so a shared
	instance would let one test observe another's replacement."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'code_freevars_and_method_type' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/code_freevars_and_method_type.py')
		name: 'code_freevars_and_method_type'.
%

category: 'Grail-Private'
method: CodeFreevarsAndMethodTypeTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - co_freevars'
method: CodeFreevarsAndMethodTypeTestCase
testACodeObjectNamesItsFreeVariables
	"None, one and two of them -- and an empty tuple rather than an absent
	attribute for the def that closes over nothing, because
	``len(co.co_freevars)'' is how the assignment rule is phrased and a missing
	attribute would make it unwritable rather than merely unavailable."

	self assertMatchesCPythonAt: 'freevars_of_a_closure'.
%

category: 'Grail-Tests - co_freevars'
method: CodeFreevarsAndMethodTypeTestCase
testCoFreevarsAgreesWithTheClosure
	"Sorted, as CPython sorts them, and the same LENGTH as __closure__ --
	they are stamped from one set for exactly this reason.  A check derived
	separately from the cells it protects is a second source of truth for one
	fact, which is how the two come apart."

	self assertMatchesCPythonAt: 'freevars_are_sorted_and_match_the_closure'.
	self assertMatchesCPythonAt: 'the_code_type_is_the_code_type'.
%

category: 'Grail-Tests - The __code__ Assignment Rule'
method: CodeFreevarsAndMethodTypeTestCase
testAssigningCodeWithADifferentFreeVarCountIsRefused
	"THE TEST THIS EXISTS FOR, in both directions -- fewer free variables than
	the target and more.  Grail accepted either, leaving the function's cells
	and its code describing different closures, with nothing raised until the
	next call."

	self assertMatchesCPythonAt: 'fewer_free_vars_is_refused'.
	self assertMatchesCPythonAt: 'more_free_vars_is_refused'.
%

category: 'Grail-Tests - The __code__ Assignment Rule'
method: CodeFreevarsAndMethodTypeTestCase
testTheRuleDoesNotOvershoot
	"A guard that also refuses the LEGAL assignment would be worse than none:
	equal counts must still go through.  And a non-code value stays a TypeError
	about its type -- the free-variable rule must not restate that as a
	ValueError about free variables it never got to count."

	self assertMatchesCPythonAt: 'same_free_var_count_is_allowed'.
	self assertMatchesCPythonAt: 'a_non_code_object_is_still_a_type_error'.
%

category: 'Grail-Tests - types.MethodType'
method: CodeFreevarsAndMethodTypeTestCase
testMethodTypeBindsAFunctionToAnObject
	"THE OTHER TEST THIS EXISTS FOR.  ``types.MethodType(f, obj)()'' calls
	``f(obj)'', and further arguments follow the receiver.  The stub answered
	something uncallable, so invoking it raised a Smalltalk
	MessageNotUnderstood -- not catchable from Python, and enough to void the
	whole module's score in the conformance harness."

	self assertMatchesCPythonAt: 'binds_a_function_to_an_object'.
	self assertMatchesCPythonAt: 'passes_further_arguments_through'.
%

category: 'Grail-Tests - types.MethodType'
method: CodeFreevarsAndMethodTypeTestCase
testMethodTypeCarriesFuncAndSelf
	"The two attributes a bound method exposes, by identity."

	self assertMatchesCPythonAt: 'carries_func_and_self'.
%

category: 'Grail-Tests - types.MethodType'
method: CodeFreevarsAndMethodTypeTestCase
testMethodTypeHasNoAttributeStorage
	"Reading, setting and deleting an arbitrary name are all AttributeError:
	CPython's method type has no __dict__, which is why this is __slots__ rather
	than a plain class body."

	self assertMatchesCPythonAt: 'has_no_attribute_storage'.
%
