! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for DynamicClassModuleTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'DynamicClassModuleTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
DynamicClassModuleTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! DynamicClassModuleTestCase
!
! ``__module__'' on a class built by ``type(name, bases, ns)''.
!
! A class STATEMENT gets its module at compile time.  A class built at RUNTIME
! has only the stack to ask, and CPython's type_new stamps __module__ from the
! CALLER's globals whenever the namespace did not supply one.
!
! Grail stamped nothing, and the result read two different ways depending on the
! bases, NEITHER of them right:
!
!     type('X', ()).__module__        -- AttributeError
!     type('X', (Base,)).__module__   -- a raw Smalltalk nil, surfacing in
!                                        Python as <UndefinedObject object at ...>
!
! The second is the worse one, and is why this is a correctness fix rather than
! a missing feature: the base's accessor pair is INHERITED but the subclass's
! own slot was never set, so the read SUCCEEDS and answers an object no Python
! code can do anything with -- not an error anyone could catch, not a value
! anyone could use.
!
! THE CALLER IS THE ANSWER, NOT THE BASE.  The fixture subclasses
! collections.OrderedDict on purpose: the class it builds belongs to the module
! that built it, not to ``collections'', which is exactly what an "inherit it
! from the base" fix would get wrong.
!
! TWO ROUTES REACH THAT ANSWER, and both are pinned because they share nothing.
! A call inside a FUNCTION is found by walking the frame chain
! (importlib>>___callerModuleName___, which raises to read the stack the way
! sys._getframe does).  A call at MODULE LEVEL has no frame at all -- Grail does
! not represent a module body as a Python frame, and a module-level
! sys._getframe(0) says so with ``call stack is not deep enough'' -- so it falls
! back to the stack of modules whose bodies are currently executing.  The
! module-level spelling is the common one, and it is the one the frame walk
! cannot serve.
!
! Drives tests/python/dynamic_class_module.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
DynamicClassModuleTestCase removeAllMethods.
DynamicClassModuleTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: DynamicClassModuleTestCase
setUp
	"Reload tests/python/dynamic_class_module.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'dynamic_class_module' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/dynamic_class_module.py')
		name: 'dynamic_class_module'.
%

category: 'Grail-Private'
method: DynamicClassModuleTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Module Is Stamped'
method: DynamicClassModuleTestCase
testAClassBuiltAtModuleLevelGetsTheModule
	"The common spelling, and the one the frame walk CANNOT serve: a module
	body is not a Python frame here, so this answer comes from the stack of
	bodies currently executing.  With no bases it used to raise
	AttributeError."

	self assertMatchesCPythonAt: 'no_bases'.
%

category: 'Grail-Tests - The Module Is Stamped'
method: DynamicClassModuleTestCase
testAClassBuiltInsideAFunctionGetsTheModule
	"The other route -- this one IS found by walking the frame chain.  Both
	must agree, and only a test says so."

	self assertMatchesCPythonAt: 'built_inside_a_function'.
%

category: 'Grail-Tests - The Module Is Stamped'
method: DynamicClassModuleTestCase
testAClassWithABaseNoLongerAnswersARawNil
	"The silent half.  The base's accessor pair is inherited while the
	subclass's own slot stays unset, so the read SUCCEEDED and handed back a
	Smalltalk nil -- ``<UndefinedObject object at 0x101>'' -- which no Python
	code can catch or use.  An AttributeError would at least have been
	honest."

	self assertMatchesCPythonAt: 'with_base'.
%

category: 'Grail-Tests - The Module Is Stamped'
method: DynamicClassModuleTestCase
testTheCallerWinsOverTheBasesModule
	"collections.OrderedDict is the base; the class built from it belongs to
	the module that BUILT it.  This is the case an ``inherit it from the
	base'' fix would get wrong while passing everything else here."

	self assertMatchesCPythonAt: 'base_from_another_module_does_not_win'.
%

category: 'Grail-Tests - The Module Is Stamped'
method: DynamicClassModuleTestCase
testANamespaceSuppliedModuleIsKept
	"CPython stamps only when the key is ABSENT, so an explicit
	``__module__'' in the namespace survives.  This is also what makes the
	stamp free for a class statement, whose namespace always carries one --
	and why the stack is never captured on that path."

	self assertMatchesCPythonAt: 'explicit_module_is_kept'.
%

category: 'Grail-Tests - Where It Lands'
method: DynamicClassModuleTestCase
testTheModuleIsInTheClassDictNotMerelyReadable
	"``'__module__' in C.__dict__'' is how pickle and inspect ask, so being
	readable through the attribute path is not enough."

	self assertMatchesCPythonAt: 'in_the_class_dict'.
	self assertMatchesCPythonAt: 'dict_value'.
%

category: 'Grail-Tests - What It Decides'
method: DynamicClassModuleTestCase
testReprIsQualifiedOnceTheModuleIsKnown
	"A class with no module reprs as ``<class 'X'>'' where CPython says
	``<class 'mod.X'>'' -- and the instance repr is qualified by the same
	value, so both move together."

	self assertMatchesCPythonAt: 'repr_is_qualified'.
	self assertMatchesCPythonAt: 'repr_with_base'.
	self assertMatchesCPythonAt: 'instance_repr_is_qualified'.
%

category: 'Grail-Tests - Nothing Else Moves'
method: DynamicClassModuleTestCase
testTheRestOfTheClassIsUnchanged
	"Stamping __module__ adds a binding to the namespace the caller supplied,
	so the guard against disturbing what was already there belongs with it --
	the value, the bases, and both directions of the subclass relation."

	self assertMatchesCPythonAt: 'name'.
	self assertMatchesCPythonAt: 'qualname'.
	self assertMatchesCPythonAt: 'namespace_value_survives'.
	self assertMatchesCPythonAt: 'base_is_kept'.
	self assertMatchesCPythonAt: 'subclass_check'.
	self assertMatchesCPythonAt: 'instance_is_usable'.
%
