! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ExceptStarTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ExceptStarTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ExceptStarTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ExceptStarTestCase
!
! PEP 654 ``except*'' and the ExceptionGroup primitives it stands on.  Grail had
! neither, and the way it failed hid that: the parser read ``except* T'' as
! ``except (*T)'' -- a STARRED EXPRESSION -- so the runtime error was
! ``*-unpack in call sites is not yet supported'', which names neither
! ``except'' nor exception groups.  It looked like a missing call-site feature.
!
! ``except*'' is not a variant of ``except'', which is why TryAst emits a wholly
! separate shape for it rather than threading a flag through the existing one:
!
!   * EVERY matching clause runs.  Plain ``except'' picks the first match and
!     treats the rest as alternatives; ``except*'' SPLITS the raised group and
!     gives each clause its own share.  The emitted code THREADS a remainder
!     through the clauses for exactly this reason.
!   * The bound name is always an ExceptionGroup, even when a single bare
!     exception was raised.
!   * Whatever no clause claimed propagates afterwards -- except that a bare
!     (non-group) exception nothing matched propagates AS ITSELF, not as the
!     wrapper this machinery built to match against.  Returning the wrapper
!     would change what the caller catches.
!
! Drives tests/python/except_star.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ExceptStarTestCase removeAllMethods.
ExceptStarTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ExceptStarTestCase
setUp
	"Reload tests/python/except_star.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'except_star' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/except_star.py')
		name: 'except_star'.
%

category: 'Grail-Private'
method: ExceptStarTestCase
assertMatchesCPythonAt: key
	self
		assert: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key) asString
		equals: ((testModule @env1:___pyAttrLoad___: #EXPECTED)
			@env1:__getitem__: key) asString
%

category: 'Grail-Tests - Group Primitives'
method: ExceptStarTestCase
testSubgroupAndSplitSelectByCondition
	"subgroup answers the matching part or None; split answers both parts.
	except* is built on these, so they are tested directly rather than
	only through it."

	self assertMatchesCPythonAt: 'subgroup'.
	self assertMatchesCPythonAt: 'subgroup_no_match'.
	self assertMatchesCPythonAt: 'split'.
	self assertMatchesCPythonAt: 'derive'.
%

category: 'Grail-Tests - Group Primitives'
method: ExceptStarTestCase
testSplittingRecursesAndKeepsStructure
	"A group may contain groups.  Matching reaches the LEAVES wherever
	they sit while preserving the surrounding shape, and a nested group
	that contributes nothing to a side is dropped from that side rather
	than kept as an empty shell."

	self assertMatchesCPythonAt: 'nested_subgroup'.
	self assertMatchesCPythonAt: 'nested_split'.
%

category: 'Grail-Tests - Group Primitives'
method: ExceptStarTestCase
testTheConditionMayBeATypeATupleOrAPredicate
	"except* itself only ever passes a type, but PEP 654 allows all three
	and real code uses the predicate form."

	self assertMatchesCPythonAt: 'predicate_condition'.
	self assertMatchesCPythonAt: 'tuple_condition'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testEveryMatchingClauseRuns
	"THE difference from plain ``except''.  A group holding a ValueError
	and a TypeError runs BOTH clauses, each seeing only its own share --
	whereas ``except'' would run the first match and treat the second
	clause as an alternative that never fires."

	self assertMatchesCPythonAt: 'every_matching_clause_runs'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testWhatNoClauseClaimedPropagates
	self assertMatchesCPythonAt: 'unmatched_part_propagates'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testABareExceptionIsWrappedForMatching
	"``except* ValueError'' catching a plain ValueError binds an
	ExceptionGroup, not the ValueError -- the bound name is ALWAYS a
	group."

	self assertMatchesCPythonAt: 'bare_exception_is_wrapped'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testAnUnmatchedBareExceptionKeepsItsIdentity
	"The other half of the wrapping, and the one that is easy to get
	wrong: when nothing matched and the raised exception was NOT a group,
	the ORIGINAL propagates.  Handing back the wrapper would change what
	an enclosing ``except ValueError'' sees."

	self assertMatchesCPythonAt: 'bare_unmatched_keeps_identity'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testANestedGroupIsMatchedThroughItsLeaves
	self assertMatchesCPythonAt: 'nested_group_is_matched'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testABareRaiseReRaisesTheGroup
	"``except* T as g: raise''.  The emitted bare raise is ``___ex pass'',
	which is why the star emit names its exception variable ___ex and not
	something star-specific -- any other spelling left that re-raise
	pointing at an undefined symbol, and the whole method failed to
	compile.  The CPython corpus caught that, not the fixture:
	test_traceback's test_exception_group_wrapped_naked.

	A KNOWN DEVIATION is documented in the fixture beside this case: when
	the raised exception was NAKED, CPython re-raises the wrapper group it
	built for matching and Grail re-raises the original."

	self assertMatchesCPythonAt: 'bare_raise_regroups'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testTheOrdinaryPathsStillWork
	"A try whose body raises nothing, and a finally alongside except* --
	the star emit is separate from the ordinary one, so both have to be
	re-established rather than inherited."

	self assertMatchesCPythonAt: 'no_exception_raised'.
	self assertMatchesCPythonAt: 'finally_still_runs'.
	self assertMatchesCPythonAt: 'handler_raise_propagates'.
%

category: 'Grail-Tests - except star'
method: ExceptStarTestCase
testTheAsNameObeysAGlobalDeclaration
	"The binding routes through the same module-scope-aware store every
	other binding form uses.  A bare assignment fails here exactly as it
	did there -- a global-declared name has no Smalltalk temp, so it
	names an undefined symbol and the method does not compile.  This is
	test_global's test_caught_exception_group."

	self assertMatchesCPythonAt: 'as_name_honours_global'.
%

category: 'Grail-Tests - Flow Control'
method: ExceptStarTestCase
testReturnBreakAndContinueCannotEscapeTheBlock
	"CPython makes all three a SyntaxError inside except*, and the reason
	is the semantics rather than taste: the block may run MORE THAN ONCE
	for one raised group -- once per matching clause -- and the remainder
	still has to propagate afterwards, so there is no coherent answer to
	what a ``return'' out of the middle of it should do."

	self assertMatchesCPythonAt: 'flow_return'.
	self assertMatchesCPythonAt: 'flow_break'.
	self assertMatchesCPythonAt: 'flow_continue'.
%

category: 'Grail-Tests - Flow Control'
method: ExceptStarTestCase
testANestedTryDoesNotExemptAReturn
	"A nested try introduces neither a scope nor a loop, so a return
	inside it still escapes the block.  Stopping the walk at any nested
	statement -- rather than at a FUNCTION or a LOOP specifically -- would
	wrongly accept this."

	self assertMatchesCPythonAt: 'flow_nested_try'.
%

category: 'Grail-Tests - Flow Control'
method: ExceptStarTestCase
testANestedFunctionOrLoopIsExempt
	"The exemptions matter as much as the rejections, and each holds for
	its own reason: a return inside a nested def or lambda belongs to THAT
	function and never leaves the block, and a loop written INSIDE the
	block is its own break target so control stays put.  Rejecting either
	would make valid code uncompilable."

	self assertMatchesCPythonAt: 'flow_nested_def'.
	self assertMatchesCPythonAt: 'flow_lambda'.
	self assertMatchesCPythonAt: 'flow_inner_loop_break'.
%

category: 'Grail-Tests - Flow Control'
method: ExceptStarTestCase
testTheRuleAppliesOnlyToTheHandlerBody
	"The try BODY, ``else'' and ``finally'' are not the handler, and a
	PLAIN ``except'' is unaffected -- the rule is specific to except*.
	Checking the whole try statement instead of the star handlers would
	break all four."

	self assertMatchesCPythonAt: 'flow_try_body'.
	self assertMatchesCPythonAt: 'flow_else'.
	self assertMatchesCPythonAt: 'flow_finally'.
	self assertMatchesCPythonAt: 'flow_plain_except'.
%
