! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for FunctionWriteGuardsTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'FunctionWriteGuardsTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
FunctionWriteGuardsTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! FunctionWriteGuardsTestCase
!
! The WRITE guards on a function's attributes -- CPython's func_set_* rules,
! which Grail did not enforce AT ALL.
!
! Every write to a function attribute was accepted, including the ones that leave
! the object incoherent.  ``f.__name__ = 7'' put an integer where every
! traceback, repr and pickle expects a string.  ``f.__closure__ = ()'' discarded
! the cells the body reads.  ``f.__defaults__ = 7'' left a non-tuple where the
! call path expects one.  None of it raised: the write returned normally and the
! damage surfaced later, somewhere else, which is precisely why CPython checks at
! the point of assignment rather than at the point of use.
!
! TWO KINDS OF RULE, with a DIFFERENT exception each, so they are not
! interchangeable:
!
!   * READ-ONLY (__closure__, __globals__, __builtins__) -> AttributeError,
!     because the attribute has no setter at all;
!   * TYPE-CHECKED (__name__, __qualname__, __code__, __defaults__) -> TypeError,
!     because there IS a setter and the VALUE is what is wrong.
!
! DELETE IS NOT SIMPLY ``THE SAME AS SET''.  test_funcattrs checks both
! directions for every guarded attribute -- its cannot_set_attr helper fails
! unless setattr AND delattr each raise -- and the answers differ: deleting
! __name__ is a TypeError phrased as the SET message (CPython routes the delete
! through the same setter with a NULL value), while deleting __defaults__ is
! LEGAL and clears them to None.
!
! WHY THE RULES ARE DUPLICATED rather than shared with BoundMethod class>>
! ___checkFunctionAttrWritable___:writing:, which has enforced the same rules for
! METHODS all along: CPython words the read-only refusal differently for the two
! object kinds -- ``readonly attribute'' for a function, ``attribute 'x' of
! 'method' objects is not writable'' for a method -- and test_funcattrs reads
! both.  The rules are the same; only the wording is not.
!
! WHERE THIS LIVES, and why not in ExecBlock>>__setattr__ where the routing
! belongs: on a LEGACY 3.7 kernel ExecBlock.gs is filed ONCE as SHARED SystemUser
! methods by install_base.sh, so editing it means writing unmerged kernel code
! into an extent other users are working in.  ExecBlockAttrs is per-user on both
! kernels and the shared ExecBlock already delegates every attribute store and
! delete to it.  The guard sits on the RUNTIME write path only
! (slotAt:attr:put: / at:attr:put:), never on staticSlotAt:attr:put: -- the
! def-time stamps write values the compiler produced and must not be checked
! against Python's rules.
!
! Drives tests/python/function_write_guards.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and self-verifies against it.  Closes
! test_funcattrs' test___name__ and test___closure__.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
FunctionWriteGuardsTestCase removeAllMethods.
FunctionWriteGuardsTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: FunctionWriteGuardsTestCase
setUp
	"Reload tests/python/function_write_guards.py fresh each test -- the module
	body renames and re-qualifies the functions it builds, so a shared instance
	would be reading a previous test's edits."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'function_write_guards' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/function_write_guards.py')
		name: 'function_write_guards'.
%

category: 'Grail-Private'
method: FunctionWriteGuardsTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Still Legal'
method: FunctionWriteGuardsTestCase
testTheWritesTheAttributesExistForStillWork
	"A guard that also refuses the legitimate writes would be worse than none.
	Renaming a function is the whole reason __name__ has a setter --
	functools.wraps does it on every decorated function in the corpus."

	self assertMatchesCPythonAt: 'rename'.
	self assertMatchesCPythonAt: 'requalify'.
	self assertMatchesCPythonAt: 'defaults_to_tuple'.
%

category: 'Grail-Tests - Type-Checked'
method: FunctionWriteGuardsTestCase
testANonStringNameIsATypeError
	"THE TEST THIS EXISTS FOR.  ``f.__name__ = 7'' was accepted in silence,
	putting an integer where every traceback, repr and pickle expects a string --
	so the failure surfaced far from the assignment that caused it."

	self assertMatchesCPythonAt: 'name_to_int'.
	self assertMatchesCPythonAt: 'qualname_to_int'.
%

category: 'Grail-Tests - Type-Checked'
method: FunctionWriteGuardsTestCase
testCodeAndDefaultsAreTypeChecked
	"``f.__code__ = 7'' replaced the code object with a number and
	``f.__defaults__ = 7'' left a non-tuple where the call path expects one.
	Both were accepted."

	self assertMatchesCPythonAt: 'code_to_int'.
	self assertMatchesCPythonAt: 'defaults_to_int'.
%

category: 'Grail-Tests - Read-Only'
method: FunctionWriteGuardsTestCase
testTheReadOnlyAttributesRefuseBothDirections
	"__closure__ and __globals__ have no setter at all, so BOTH the write and the
	delete are AttributeError -- not TypeError, which is the answer reserved for
	attributes that have a setter and were handed the wrong value.  Assigning
	__closure__ discarded the cells the body reads, silently."

	self assertMatchesCPythonAt: 'set_closure'.
	self assertMatchesCPythonAt: 'del_closure'.
	self assertMatchesCPythonAt: 'set_globals'.
	self assertMatchesCPythonAt: 'del_globals'.
%

category: 'Grail-Tests - Delete Has Its Own Rules'
method: FunctionWriteGuardsTestCase
testDeletingANameIsATypeError
	"Phrased as the SET message, because CPython routes the delete through the
	same setter with a NULL value.  Grail answered ``AttributeError: __name__'',
	which reads as though the function had no name at all."

	self assertMatchesCPythonAt: 'del_name'.
	self assertMatchesCPythonAt: 'del_qualname'.
%

category: 'Grail-Tests - Delete Has Its Own Rules'
method: FunctionWriteGuardsTestCase
testDeletingDefaultsIsLegalAndClearsThem
	"The one guarded attribute whose delete is ALLOWED -- it clears the defaults
	to None rather than refusing.  Kept as its own test because a guard written
	as ``refuse every delete'' passes everything above and breaks exactly here."

	self assertMatchesCPythonAt: 'del_defaults'.
%
