! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for FunctionBuiltinsAttrTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'FunctionBuiltinsAttrTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
FunctionBuiltinsAttrTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! FunctionBuiltinsAttrTestCase
!
! ``__builtins__'' -- the module-level NAME, and the function ATTRIBUTE.  Grail
! had neither.  A bare ``__builtins__'' raised
!
!     NameError: name '__builtins__' is not defined
!
! and ``f.__builtins__'' raised AttributeError -- while both names were ALREADY
! listed as read-only in the write guards (BoundMethod class >>
! ___readOnlyFunctionAttrNames___, ExecBlockAttrs class >>
! ___readOnlyFunctionAttrs___).  So assignment was correctly refused for an
! attribute that could not be read at all, which is the state that makes a gap
! look like a feature.  test_funcattrs.test___builtins__ died on its first line.
!
! WHAT THE VALUE IS.  CPython's import machinery writes ``__builtins__'' into
! every module's globals; it is the builtins MODULE in __main__ and that
! module's DICT in an imported module.  Grail is only ever the second case, so
! the value is the dict -- the one memoised PyModuleDict view of the builtins
! module, which is what makes ``f.__builtins__ is __builtins__'' true rather
! than merely equal.  Upstream asserts every one of these with assertIs.
!
! STORED, WITH A COMPUTED FALLBACK.  importlib class >> ___stampBuiltinsOn___:
! writes the name into each module's namespace from registerModule:with: -- the
! one choke point every entry point that makes a module passes through -- so it
! is a real entry that ``dir(mod)'', ``vars(mod)'' and any iteration over a
! module namespace see, as in CPython.  module >> ___globalAt___:otherwise:
! ALSO answers it from a last-resort branch, which covers the modules the stamp
! cannot reach: the bootstrap set that registers before the builtins module
! exists (caught afterwards by a one-time sweep) and the launcher's own script
! module, which is created outside the import machinery.  So a READ never
! depends on the stamp having run; only membership does.
!
! A first version computed the name and stored nothing.  Every read passed, and
! the fixture passed, because a read is exactly what a computed branch serves --
! which is why the checks below test MEMBERSHIP (``_has(vars(mod), ...)'')
! rather than only reading.  A read-only implementation cannot satisfy those.
!
! THE BUILTINS MODULE ITSELF IS EXCLUDED, because CPython excludes it: measured
! on 3.14.6, ``'__builtins__' in builtins.__dict__'' is False.  Grail's first
! attempt stamped it anyway -- the guard compared the candidate against the
! builtins VIEW (a PyModuleDict) rather than against the builtins MODULE, and
! those are never identical, so the guard matched nothing.
!
! Being a last-resort branch, and the stamp declining to overwrite, is also what
! lets a module bind its own ``__builtins__'' -- how a sandbox restricts one --
! and keep that binding.
!
! THREE CALLABLE CLASSES, THREE SEPARATE ATTRIBUTES.  Grail represents a
! module-level def as a BoundMethod, a nested def or lambda as an ExecBlock
! (served by the ExecBlockAttrs side table), and ``Cls.m'' as an UnboundMethod.
! They are unrelated classes, so adding the attribute to one says nothing about
! the others -- the fixture checks all three for that reason, and caught
! UnboundMethod still answering AttributeError after the other two passed.
!
! NOT COVERED.  Upstream's test___builtins__ continues past everything here into
! ``func2 = type(func)(func.__code__, ns)'' and then CALLS func2.  Grail
! compiles Python to Smalltalk methods and keeps no bytecode, so a code object
! carries no instructions to re-enter, and a compiled method resolves its
! globals against the module it was compiled in rather than against a dict
! handed over afterwards.  Neither half is reachable, so the upstream test is
! skipped (scripts/cpython_suite_skips.txt) rather than faked, and this fixture
! pins the part that is real.  Same root cause as the test_copying___code__ skip
! in the same module.
!
! Drives tests/python/function_builtins_attr.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
FunctionBuiltinsAttrTestCase removeAllMethods.
FunctionBuiltinsAttrTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: FunctionBuiltinsAttrTestCase
setUp
	"Reload tests/python/function_builtins_attr.py fresh each test.  The module
	body mutates the functions it records (the read-only checks call setattr and
	delattr on them), so a shared instance would carry one test's writes into
	the next."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'function_builtins_attr' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/function_builtins_attr.py')
		name: 'function_builtins_attr'.
%

category: 'Grail-Private'
method: FunctionBuiltinsAttrTestCase
assertMatchesCPythonAt: key
	"Compare the fixture's recorded result against its CPython-measured
	EXPECTED entry, both through repr so a True and a 'True' cannot pass for
	each other."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Module Name'
method: FunctionBuiltinsAttrTestCase
testTheBareModuleLevelNameResolvesToTheBuiltinsNamespace
	"``__builtins__'' as a bare name raised NameError.  It is the builtins
	namespace itself, by identity -- a lookalike dict would pass an equality
	check and still be the wrong object."

	self assertMatchesCPythonAt: 'bare_name_is_builtins_namespace'.
	self assertMatchesCPythonAt: 'globals_entry_is_bare_name'.
%

category: 'Grail-Tests - Module Name'
method: FunctionBuiltinsAttrTestCase
testTheNameIsAnEntryInTheModuleNamespaceNotMerelyReadable
	"CPython's import machinery writes ``__builtins__'' into each module's
	namespace, so it is visible to dir(), vars() and any iteration -- not just
	to a read.  These check MEMBERSHIP for that reason: Grail also computes the
	name on a miss, so every read-based check here passed while nothing was
	stored, and only these can tell the two implementations apart.

	The builtins module itself is excluded, matching CPython, and that half is
	not cosmetic -- the first guard written for it compared against the module's
	PyModuleDict VIEW rather than the module, matched nothing, and stamped
	builtins along with everything else."

	self assertMatchesCPythonAt: 'present_in_own_module_dict'.
	self assertMatchesCPythonAt: 'present_in_another_module_dict'.
	self assertMatchesCPythonAt: 'readable_as_a_module_attribute'.
	self assertMatchesCPythonAt: 'builtins_module_itself_excluded'.
%

category: 'Grail-Tests - Callables'
method: FunctionBuiltinsAttrTestCase
testEveryCallableFlavourReportsTheSameBuiltinsObject
	"Three unrelated Smalltalk classes back Python's one ``function'' idea, so
	each needs the attribute in its own right: BoundMethod for a module-level
	def, ExecBlock for a nested def and a lambda, UnboundMethod for ``Cls.m''.
	UnboundMethod was missed on the first pass and this check is what found it."

	self assertMatchesCPythonAt: 'module_level_func'.
	self assertMatchesCPythonAt: 'nested_func'.
	self assertMatchesCPythonAt: 'lambda_func'.
	self assertMatchesCPythonAt: 'unbound_method'.
	self assertMatchesCPythonAt: 'bound_method'.
%

category: 'Grail-Tests - Callables'
method: FunctionBuiltinsAttrTestCase
testTheAttributeAgreesWithTheFunctionsOwnGlobals
	"CPython reads a function's builtins OUT OF its globals, so the two cannot
	disagree.  Grail's readers go through __globals__ for the same reason --
	which is also what makes a module that binds its own ``__builtins__'' report
	that binding for the functions defined in it."

	self assertMatchesCPythonAt: 'agrees_with_own_globals'.
%

category: 'Grail-Tests - Read-Only'
method: FunctionBuiltinsAttrTestCase
testTheAttributeRefusesBothAssignmentAndDeletion
	"A getter and no setter, so both directions are AttributeError.  Deletion
	needs naming separately from assignment: ``__builtins__'' is a computed
	name rather than a __dict__ entry, so a ``del'' that found nothing to
	remove could quietly succeed -- which is how the sibling read-only names
	behaved before their guards were added."

	self assertMatchesCPythonAt: 'set_on_module_level'.
	self assertMatchesCPythonAt: 'del_on_module_level'.
	self assertMatchesCPythonAt: 'set_on_nested'.
	self assertMatchesCPythonAt: 'del_on_nested'.
%
