! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for FunctionDictAndDocTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'FunctionDictAndDocTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
FunctionDictAndDocTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! FunctionDictAndDocTestCase
!
! A function's ``__dict__'' and ``__doc__'' -- the two attributes that are a
! mapping and a string rather than plain values, and whose WRITE and DELETE paths
! have rules of their own.
!
! Grail read both correctly and wrote both wrongly, mostly in SILENCE:
!
! 1. ``f.__dict__ = d'' DID NOTHING VISIBLE.  ``__dict__'' is a slot name, so the
!    assignment was routed into the slot table -- a namespace the ``__dict__''
!    READER never consults, since it answers the attribute table directly.  The
!    write succeeded, raised nothing and changed nothing: reading it back showed
!    the assigned dict NESTED under a '__dict__' key ({'__dict__': {...}}) and
!    ``f.known_attr'' was still an AttributeError.
!
! 2. NO TYPE CHECK came with it, so ``f.__dict__ = None'' was accepted just as
!    quietly, leaving a function whose __dict__ could not be read back as a
!    mapping at all.
!
! 3. ``del f.__dict__'' answered AttributeError where CPython answers TypeError.
!    The attribute EXISTS and is writable, so what is refused is the DELETION; an
!    AttributeError reads as though functions have no __dict__.
!
! 4. ``del f.__doc__'' answered ``AttributeError: __doc__''.  CPython RESETS the
!    docstring to None rather than removing anything -- func_set_doc(NULL) -- so
!    every function still has a __doc__ afterwards, and deleting twice is fine.
!
! ASSIGNMENT IS BY IDENTITY, not by merge: CPython leaves ``f.__dict__ is d''
! true, so later mutations of d show through f.  testAssignmentIsLiveNotACopy is
! what makes the distinction in (1) observable rather than academic -- a merging
! implementation passes the first read and then drifts.
!
! WHY THIS LIVES IN ExecBlockAttrs rather than ExecBlock>>__setattr__, which is
! where the routing arguably belongs: on a LEGACY 3.7 kernel ExecBlock.gs is
! filed ONCE as SHARED SystemUser methods by install_base.sh, so editing it means
! writing unmerged kernel code into an extent other users are working in.
! ExecBlockAttrs is per-user on both kernels, and the shared ExecBlock already
! delegates every attribute store and delete to it, so this placement needs no
! shared-base change and behaves identically on 3.7 and 4.0.
!
! NOT FIXED, and the reason the two FunctionDictsTest cases still fail: a
! BoundMethod has no ``__dict__'' of its own and does not proxy to its underlying
! function, so ``fi.a.__dict__'' raises where CPython answers the function's
! mapping.  ``fi.a.__doc__'' reads None for the same reason.  That is
! BoundMethod/UnboundMethod proxying -- a separate piece of work from the storage
! rules here.
!
! Drives tests/python/function_dict_and_doc.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and self-verifies against it.  Closes
! test_funcattrs' test_delete___dict__ and test_delete_docstring.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
FunctionDictAndDocTestCase removeAllMethods.
FunctionDictAndDocTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: FunctionDictAndDocTestCase
setUp
	"Reload tests/python/function_dict_and_doc.py fresh each test -- the module
	body REPLACES and deletes the __dict__ of the functions it builds, so a
	shared instance would be reading a previous test's edits."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'function_dict_and_doc' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/function_dict_and_doc.py')
		name: 'function_dict_and_doc'.
%

category: 'Grail-Private'
method: FunctionDictAndDocTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Reading __dict__'
method: FunctionDictAndDocTestCase
testTheDictStartsEmptyAndCollectsAttributes
	"The reads were already right; they are here so the write fixes cannot break
	them."

	self assertMatchesCPythonAt: 'dict_initially_empty'.
	self assertMatchesCPythonAt: 'setattr_in_dict'.
%

category: 'Grail-Tests - Assigning __dict__'
method: FunctionDictAndDocTestCase
testAssigningTheDictReplacesIt
	"THE TEST THIS EXISTS FOR.  The assignment used to land in a namespace the
	reader never consults, so it changed nothing and said nothing -- and the read
	back showed the dict nested under a '__dict__' key."

	self assertMatchesCPythonAt: 'assign_dict'.
%

category: 'Grail-Tests - Assigning __dict__'
method: FunctionDictAndDocTestCase
testAssignmentIsLiveNotACopy
	"By IDENTITY: ``f.__dict__ is d'' stays true, so mutating d afterwards shows
	through f.  This is what separates a real replacement from a merge, which
	would agree once and then drift."

	self assertMatchesCPythonAt: 'assignment_is_live'.
%

category: 'Grail-Tests - Assigning __dict__'
method: FunctionDictAndDocTestCase
testAssigningANonDictIsATypeError
	"No check ran before, so None -- or an int -- was accepted in silence,
	leaving a function whose __dict__ could not be read back as a mapping.  A
	UserDict is refused too: CPython wants the real type and names the offending
	one in the message."

	self assertMatchesCPythonAt: 'assign_none'.
	self assertMatchesCPythonAt: 'assign_int'.
	self assertMatchesCPythonAt: 'assign_userdict'.
%

category: 'Grail-Tests - Deleting'
method: FunctionDictAndDocTestCase
testTheDictCannotBeDeleted
	"TypeError, not AttributeError: the attribute exists and is writable, so what
	is refused is the DELETION.  Closes test_funcattrs' test_delete___dict__."

	self assertMatchesCPythonAt: 'delete_dict'.
%

category: 'Grail-Tests - Deleting'
method: FunctionDictAndDocTestCase
testDeletingTheDocstringResetsItToNone
	"``del f.__doc__'' does not remove an attribute -- it is func_set_doc(NULL),
	so the function still HAS a __doc__ and it reads None.  Grail raised
	``AttributeError: __doc__'' because __doc__ lives in the slot namespace and
	was never in the table the delete searched.  Deleting twice is therefore fine.
	Closes test_funcattrs' test_delete_docstring."

	self assertMatchesCPythonAt: 'delete_doc'.
	self assertMatchesCPythonAt: 'delete_doc_twice'.
%

category: 'Grail-Tests - __doc__'
method: FunctionDictAndDocTestCase
testTheOrdinaryDocstringPathIsUndisturbed
	"A function with no docstring reads None, one with a literal reads it, and an
	assignment round-trips.  Guarding the delete must not disturb any of that."

	self assertMatchesCPythonAt: 'doc_initially_none'.
	self assertMatchesCPythonAt: 'literal_docstring'.
	self assertMatchesCPythonAt: 'set_doc'.
%
