! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for FunctionalEnumModuleTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'FunctionalEnumModuleTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
FunctionalEnumModuleTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! FunctionalEnumModuleTestCase
!
! ``__module__'' on a class whose module has to be INFERRED -- GemTalk/Grail#1134.
!
! DynamicClassModuleTestCase pins type() called from a module FILE.  This pins
! the three paths that case left open, each of which answered AttributeError:
!
!   * the Enum FUNCTIONAL API with no ``module='' -- CPython's _create_ reads
!     the caller's frame, and Grail read nothing;
!   * EVALUATED code.  A doit's frames have no file sys.modules could match, so
!     importlib>>___callerModuleName___ walked right past them.  CPython reads
!     the caller's GLOBALS, and a doit frame carries its globals, so their
!     ``__name__'' is now the answer -- and globals WITHOUT one stamp nothing,
!     rather than walking on to the module that called exec();
!   * classes native modules build from Smalltalk: enum.FlagBoundary and
!     enum.EnumCheck (made by the functional API, so they now pass
!     ``module='enum''' explicitly) and json.JSONEncoder.
!
! Drives tests/python/functional_enum_module.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.7 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
FunctionalEnumModuleTestCase removeAllMethods.
FunctionalEnumModuleTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: FunctionalEnumModuleTestCase
setUp
	"Reload tests/python/functional_enum_module.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'functional_enum_module' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/functional_enum_module.py')
		name: 'functional_enum_module'.
%

category: 'Grail-Private'
method: FunctionalEnumModuleTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Functional API'
method: FunctionalEnumModuleTestCase
testAFunctionalEnumBuiltAtModuleLevelGetsTheModule
	"``Enum('F', 'A B')'' is shorthand for a class statement, which always
	knew its module.  The shorthand answered AttributeError."

	self assertMatchesCPythonAt: 'functional_at_module_level'.
	self assertMatchesCPythonAt: 'functional_strenum'.
%

category: 'Grail-Tests - The Functional API'
method: FunctionalEnumModuleTestCase
testAFunctionalEnumBuiltInsideAFunctionGetsTheModule
	"The frame-walk route, as opposed to the module-body fallback above."

	self assertMatchesCPythonAt: 'functional_in_a_function'.
%

category: 'Grail-Tests - The Functional API'
method: FunctionalEnumModuleTestCase
testAnExplicitModuleIsKept
	"``module='' was the one spelling that already worked, and the inferred
	answer must not override it."

	self assertMatchesCPythonAt: 'functional_explicit_module_is_kept'.
%

category: 'Grail-Tests - The Functional API'
method: FunctionalEnumModuleTestCase
testTheEnumItselfIsUnchanged
	self assertMatchesCPythonAt: 'functional_repr_is_qualified'.
	self assertMatchesCPythonAt: 'functional_member_is_unchanged'.
%

category: 'Grail-Tests - Evaluated Code'
method: FunctionalEnumModuleTestCase
testEvaluatedCodeTakesTheModuleFromItsGlobals
	"exec() compiles a doit, whose frames match no file in sys.modules.  The
	answer is the ``__name__'' of the globals it ran in, for type() and the
	functional API alike, and from a def the doit defined as well as from
	its top level."

	self assertMatchesCPythonAt: 'exec_type_names_its_globals'.
	self assertMatchesCPythonAt: 'exec_enum_names_its_globals'.
	self assertMatchesCPythonAt: 'exec_in_a_function_names_its_globals'.
%

category: 'Grail-Tests - Evaluated Code'
method: FunctionalEnumModuleTestCase
testGlobalsWithNoNameStampNothing
	"CPython stamps nothing when the globals have no ``__name__''.  The trap is
	the module that CALLED exec(): a walk that kept going outward would find
	it, and name a module the class was never built in."

	self assertMatchesCPythonAt: 'exec_without_a_name_stamps_nothing'.
%

category: 'Grail-Tests - Native Modules'
method: FunctionalEnumModuleTestCase
testEnumsBoundaryClassesBelongToEnum
	self assertMatchesCPythonAt: 'flag_boundary'.
	self assertMatchesCPythonAt: 'enum_check'.
	self assertMatchesCPythonAt: 'flag_boundary_member'.
%

category: 'Grail-Tests - Native Modules'
method: FunctionalEnumModuleTestCase
testJSONEncoderBelongsToJsonEncoder
	self assertMatchesCPythonAt: 'json_encoder'.
%
