! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for GeneratorUnraisableTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'GeneratorUnraisableTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
GeneratorUnraisableTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! GeneratorUnraisableTestCase
!
! An exception raised where there is nowhere to raise it TO.
!
! ``gen.close()'' on a generator suspended in ``yield from'' shuts the
! SUB-iterator down first, which means looking up its ``close'' attribute.  PEP
! 380 says a MISSING one is skipped; it does not say what happens when the
! lookup itself FAILS, and that case has no good answer available to it:
!
!   * it cannot propagate -- a GeneratorExit is already unwinding the delegating
!     generator and has to carry on out, or close() stops answering None and
!     starts raising;
!   * it cannot be dropped -- which is what Grail did, leaving the failure
!     unobservable by any means at all.
!
! CPython reports it out of band, through sys.unraisablehook.  A test installs
! its own hook and inspects what arrived, which is the whole of what
! test.support.catch_unraisable_exception does -- and why test_yield_from's
! test_broken_getattr_handling scored an ERROR rather than a failure: with no
! hook ever called, cm.unraisable stayed None and reading .exc_type off it
! raised AttributeError.
!
! THE TWO WAYS CPython FILLS THE HOOK ARGUMENT ARE NOT INTERCHANGEABLE.
! PyErr_WriteUnraisable sets ``object'' and leaves ``err_msg'' None;
! PyErr_FormatUnraisable does the reverse, putting the object's repr INSIDE the
! message.  3.14 uses the format variant here, so a hook that prints
! ``args.object'' prints None.  Getting that backwards looks right until someone
! reads the report.
!
! NOT COVERED: every other CPython caller of the hook is a FINALIZER -- __del__,
! GC, buffered-file close -- and Grail has no finalizer machinery, so this is
! the one path that reaches it.  test/support's catch_unraisable_exception says
! so in its own docstring.
!
! Drives tests/python/generator_unraisable.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
GeneratorUnraisableTestCase removeAllMethods.
GeneratorUnraisableTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: GeneratorUnraisableTestCase
setUp
	"Reload tests/python/generator_unraisable.py fresh each test -- the module
	body installs and restores sys.unraisablehook and closes the generators it
	measures, so a shared instance would be measuring a previous test's leftovers."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'generator_unraisable' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/generator_unraisable.py')
		name: 'generator_unraisable'.
%

category: 'Grail-Private'
method: GeneratorUnraisableTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Hook Runs'
method: GeneratorUnraisableTestCase
testAFailedCloseLookupReachesTheHook
	"THE TEST THIS EXISTS FOR.  The sub-iterator's __getattr__ raises
	ZeroDivisionError while ``close'' is being looked up, and that exception
	used to go nowhere at all -- no raise, no report, no record."

	self assertMatchesCPythonAt: 'hook_calls'.
	self assertMatchesCPythonAt: 'exc_type_is_zero_division'.
	self assertMatchesCPythonAt: 'exc_value_is_instance'.
	self assertMatchesCPythonAt: 'exc_value_message'.
%

category: 'Grail-Tests - The Hook Runs'
method: GeneratorUnraisableTestCase
testAnOrdinaryDelegatedCloseDoesNotReachTheHook
	"The control, and the reason the count above means anything: a sub-iterator
	with no ``close'' is SKIPPED, silently and correctly.  A hook that fired on
	every delegated close would satisfy every other test here."

	self assertMatchesCPythonAt: 'fine_hook_calls'.
	self assertMatchesCPythonAt: 'fine_value'.
	self assertMatchesCPythonAt: 'fine_close_returns'.
%

category: 'Grail-Tests - Hook Argument'
method: GeneratorUnraisableTestCase
testTheReportNamesTheObjectInTheMessage
	"CPython 3.14 uses PyErr_FormatUnraisable here, which puts the repr in
	``err_msg'' and leaves ``object'' None -- the opposite of
	PyErr_WriteUnraisable.  Both fields are checked, because filling the wrong
	one still produces a hook call and a correct exc_type."

	self assertMatchesCPythonAt: 'object_is_none'.
	self assertMatchesCPythonAt: 'err_msg'.
%

category: 'Grail-Tests - Hook Argument'
method: GeneratorUnraisableTestCase
testEveryFieldIsReadableIncludingTheEmptyOnes
	"An ABSENT attribute would raise AttributeError where CPython answers None,
	and a hook reads the fields it was not given as readily as the ones it was."

	self assertMatchesCPythonAt: 'has_all_fields'.
%

category: 'Grail-Tests - The Close Still Works'
method: GeneratorUnraisableTestCase
testCloseStillAnswersNoneAndExhaustsTheGenerator
	"The reporting is OUT OF BAND: the GeneratorExit close() injected still
	carries on out of the body, so close() answers None and the generator is
	finished.  Letting the sub-iterator's exception propagate instead would turn
	close() into a raise, which is the obvious wrong fix."

	self assertMatchesCPythonAt: 'first_value'.
	self assertMatchesCPythonAt: 'close_returns'.
	self assertMatchesCPythonAt: 'closed_is_exhausted'.
%

category: 'Grail-Tests - The Close Still Works'
method: GeneratorUnraisableTestCase
testTheHookIsAnAssignableAttribute
	"``sys.unraisablehook = h'' has to take, and has to be restorable, or a
	context manager cannot be built on it -- which is what
	test.support.catch_unraisable_exception is."

	self assertMatchesCPythonAt: 'hook_restored'.
%
