! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for GeneratorStackFrameTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'GeneratorStackFrameTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
GeneratorStackFrameTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! GeneratorStackFrameTestCase
!
! What a debugger sees while a generator is running.
!
! ``inspect.stack()'' is how a debugger, a logging filter or a test asks who is
! calling it.  Grail answered ``[]'' -- not a wrong stack but NO stack -- so
! every such caller silently took its "I cannot tell" branch.
!
! The interesting half is the GENERATOR.  A generator body runs on its own
! forked GsProcess, so the VM's stack capture ends at the fork and holds nothing
! of the consumer driving it.  Two things were missing as a result, and they are
! missing for different reasons:
!
!   * the CONSUMER's frames, because they are on another process entirely.  They
!     are readable: that process is blocked on consumerSem, and a SUSPENDED
!     process is exactly what GsProcess>>_frameContentsAt: serves.  The
!     generator now remembers which process resumed it, and the walk follows the
!     chain out through every ``yield from''.
!   * the generator's OWN frame, because the body is a BLOCK and the ``def''
!     that built it returned -- on the consumer's process -- the moment the
!     generator was constructed.  Nothing further out on this process can report
!     it, so the walk flushes what is pending when a generator section ends.
!
! ``yield from'' is what makes the first one matter: a delegating generator is
! TRANSPARENT in every other respect, so a debugger that cannot see ``spam''
! cannot tell you which delegation you are in.  That is test_yield_from's
! test_delegator_is_visible_to_debugger, checked here at three depths and once
! after a RESUME -- a version that recorded the consumer only at start-up passes
! every other test in this file.
!
! WHY THE FIXTURE COMPARES PREFIXES: a module BODY is not a frame in Grail
! (module-level ``sys._getframe(0)'' reports the stack is not deep enough), so
! Grail's stack ends one entry before CPython's '<module>'.  That gap is older
! and wider than this change, and comparing a prefix compares everything these
! tests are about and nothing they are not.
!
! Drives tests/python/generator_stack_frames.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
GeneratorStackFrameTestCase removeAllMethods.
GeneratorStackFrameTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: GeneratorStackFrameTestCase
setUp
	"Reload tests/python/generator_stack_frames.py fresh each test.  The module
	body is the measurement: every entry in ``r'' was taken while a particular
	stack was live and cannot be recomputed afterwards."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'generator_stack_frames' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/generator_stack_frames.py')
		name: 'generator_stack_frames'.
%

category: 'Grail-Private'
method: GeneratorStackFrameTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Basics'
method: GeneratorStackFrameTestCase
testThereIsAStackAtAll
	"inspect.stack() was a stub answering []; currentframe() was a hardcoded
	None.  Both read as ``there is no stack'' rather than ``stacks are not
	supported'', and a caller cannot tell the difference."

	self assertMatchesCPythonAt: 'stack_is_list'.
	self assertMatchesCPythonAt: 'currentframe_names_caller'.
	self assertMatchesCPythonAt: 'no_generator'.
%

category: 'Grail-Tests - Generator Frames'
method: GeneratorStackFrameTestCase
testAGeneratorReportsItsOwnFrame
	"``def gen(): yield f()'' walked from inside f reported ['f'] where CPython
	reports ['f', 'gen', ...].  The body is a block and its def already
	returned, so no frame on this process could name it."

	self assertMatchesCPythonAt: 'plain'.
%

category: 'Grail-Tests - Generator Frames'
method: GeneratorStackFrameTestCase
testADelegatingGeneratorIsVisible
	"THE TEST THIS EXISTS FOR -- test_yield_from's
	test_delegator_is_visible_to_debugger.  ``spam'' is on another GsProcess
	entirely, blocked waiting for the generator it delegates to."

	self assertMatchesCPythonAt: 'one'.
%

category: 'Grail-Tests - Generator Frames'
method: GeneratorStackFrameTestCase
testNestedDelegationsAppearInOrder
	"Two delegations deep, and ORDER rather than mere membership: gen inside
	eggs inside spam.  A walk that concatenated the sections the other way round
	would still contain every name."

	self assertMatchesCPythonAt: 'two'.
	self assertMatchesCPythonAt: 'gen_inside_eggs'.
	self assertMatchesCPythonAt: 'eggs_inside_spam'.
	self assertMatchesCPythonAt: 'no_duplicate_frames'.
%

category: 'Grail-Tests - Generator Frames'
method: GeneratorStackFrameTestCase
testAResumedGeneratorStillSeesItsConsumer
	"The link to the consumer is re-read on EVERY resume, because the process
	driving a generator can differ from one next() to the next.  Recording it
	once when the body is forked passes every other test in this file."

	self assertMatchesCPythonAt: 'resumed'.
%

category: 'Grail-Tests - Generator Frames'
method: GeneratorStackFrameTestCase
testTheConsumerChainIncludesNestedFunctions
	"The consumer's own frames are walked by the same rules as the current
	process's, so a nested ``def'' driving the generator is named by
	___nestedFunctionNameFor___ rather than by a Smalltalk selector -- a
	different route through the walk than a module-level def takes."

	self assertMatchesCPythonAt: 'nested_caller'.
%
