! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for GlobalsShadowBuiltinTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'GlobalsShadowBuiltinTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
GlobalsShadowBuiltinTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! GlobalsShadowBuiltinTestCase
!
! CPython's LOAD_GLOBAL reads a module's OWN globals first and only then
! builtins, so ``globals()['len'] = f'' at run time shadows the builtin for
! every function in that module -- including functions COMPILED BEFORE the
! write.
!
! Grail classified a bare name at COMPILE time.  A name the module never
! assigned statically became a direct send to the builtins singleton
! (``((Python @env0:at: #builtins) instance) len: ...''), so a later write into
! the module namespace could not be seen: it landed (``'len' in globals()''
! answered True) and nothing consulted it.  That was test_dynamic's
! test_globals_shadow_builtins -- the ONE test of its family that failed.
!
! THREE OVERRIDE ROUTES, THREE MECHANISMS, and only the middle one was broken:
!   * STATIC ``len = ...'' at module level -- resolved at compile time, always
!     worked (the name is simply a module global and never takes the builtin
!     path at all);
!   * RUNTIME ``globals()['len'] = ...'' -- this class's subject;
!   * ``builtins.len = ...'' -- already handled by builtins >>
!     ___syncBuiltinOverride___:, which captures the original method sources and
!     recompiles the builtins class's whole selector surface into forwarders.
!
! WHY THE BUILTINS MECHANISM COULD NOT BE REUSED: it rewrites the shared
! builtins singleton, and a globals() shadow belongs to ONE module.  Syncing
! builtins because module M shadowed ``len'' would change ``len'' for every
! other module in the session -- it would pass the test and break the language.
!
! THE FIX IS AT THE CALL SITE (CallAst >> printGlobalShadowProbeOn:name:then:):
! inside a user module a bare builtin call is emitted as
!     ((self @env0:dynamicInstVarAt: #'len') isNil
!         ifTrue: [ <the direct builtins send> ]
!         ifFalse: [ ... ___pyCallValue___: { args } kw: kw ])
! ``ifTrue:ifFalse:'' on literal blocks is inlined by GemStone's source
! compiler, so an unshadowed call adds one dynamic-instVar probe and an isNil
! test and NO frame -- which matters, because this is the hottest emit in the
! language and frame width is load-bearing for recursion depth.
!
! Drives tests/python/globals_shadow_builtin.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
GlobalsShadowBuiltinTestCase removeAllMethods.
GlobalsShadowBuiltinTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: GlobalsShadowBuiltinTestCase
setUp
	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'globals_shadow_builtin' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/globals_shadow_builtin.py')
		name: 'globals_shadow_builtin'.
%

category: 'Grail-Private'
method: GlobalsShadowBuiltinTestCase
assertMatchesCPythonAt: key
	"Compare the fixture's recorded result against its CPython-generated
	expectation, both through repr so a 7 and a '7' cannot pass for each other."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testTheUnshadowedCallIsUnchanged
	"The common path: no shadow, the direct builtins send, same answers as
	before the probe existed.  First because everything else is a deviation
	from it -- if this breaks, the probe broke ordinary code."

	self assertMatchesCPythonAt: 'baseline_len'.
	self assertMatchesCPythonAt: 'baseline_sorted'.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testARuntimeGlobalsShadowIsSeenByACompiledFunction
	"THE DEFECT.  ``uses_len'' is compiled before the write; CPython's
	LOAD_GLOBAL still finds the shadow, because the lookup happens per call and
	reads globals first.  Grail answered 3 where CPython answers 7 -- and the
	write was not lost, merely unread, which is what ``shadow_is_in_globals''
	pins down."

	self assertMatchesCPythonAt: 'shadowed_len'.
	self assertMatchesCPythonAt: 'shadow_is_in_globals'.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testDeletingTheShadowRestoresTheBuiltin
	"The probe reads the slot at CALL time, so removing the global has to put
	the builtin back with no recompilation.  A fix that cached the lookup would
	pass the test above and fail this one."

	self assertMatchesCPythonAt: 'after_del_len'.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testTheShadowIsModuleLocal
	"The reason the builtins-sync mechanism could not be reused.  While this
	module's ``len'' is shadowed, ``builtins.len'' itself still answers 3 -- so
	every OTHER module is unaffected.  A fix that synced the shared builtins
	singleton would make this read 7 and quietly corrupt the whole session."

	self assertMatchesCPythonAt: 'builtin_len_unaffected'.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testTheKwargsEmitPathIsProbedToo
	"``sorted(x, reverse=True)'' carries a keyword, so it takes the VARARGS
	emit (``_sorted: {args} kw: dict''), a different method from the
	fixed-arity one.  Both had to be wrapped; covering only the fixed-arity
	path would leave every kwargs-bearing builtin call unshadowable."

	self assertMatchesCPythonAt: 'shadowed_sorted'.
	self assertMatchesCPythonAt: 'after_del_sorted'.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testRebindingBuiltinsItselfStillWorks
	"The pre-existing mechanism (___syncBuiltinOverride___:), asserted here so
	the new probe cannot regress it: the probe's then-branch IS the direct send
	that sync rewrites, so the two have to compose."

	self assertMatchesCPythonAt: 'builtins_patched_len'.
	self assertMatchesCPythonAt: 'after_restore_len'.
%

category: 'Grail-Tests'
method: GlobalsShadowBuiltinTestCase
testALocalBindingStillWinsOverBoth
	"LEGB order: a real local shadows the global, which shadows the builtin.
	The probe must not reach past a local -- ___moduleGlobalShadowName___
	declines when ___localBindingShadows___: answers true."

	self assertMatchesCPythonAt: 'local_shadow'.
%
