! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for GlobalBindingFormsTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'GlobalBindingFormsTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
GlobalBindingFormsTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! GlobalBindingFormsTestCase
!
! ``global NAME'' was honoured by exactly ONE binding form -- plain assignment.
! Every other way of binding a name ignored the declaration, in one of two ways,
! and the two fail very differently:
!
!   LOUDLY: class / def / walrus / match capture emitted a bare Smalltalk
!   ``x := ...''.  A global-declared name has NO Smalltalk temp -- the parser
!   correctly does not declare one -- so that named an UNDEFINED SYMBOL and the
!   ENTIRE enclosing method failed to compile.  It surfaced as ``Grail could not
!   compile this method (codegen gap)'', a message pointing nowhere near
!   ``global'', which is why it read as five unrelated match bugs plus a class
!   bug plus a def bug rather than as one cause.
!
!   QUIETLY: import / augmented assign / annotated assign / unpacking DID take
!   the module route, but hardcoded ``self'' as the receiver.  Inside a class
!   METHOD ``self'' is the Python INSTANCE, not the module, so the value was
!   hung off the instance and globals() never saw it.  No error at all -- the
!   name simply is not there.
!
! That second half is why every form is exercised from inside a METHOD as well
! as from a plain function: at module level and in a top-level def, ``self''
! genuinely IS the module, so the receiver bug is invisible.
!
! The fix routes every binding form through one emitter
! (AbstractNode>>emitNameStoreOn:target:rhs:) and one receiver helper
! (___moduleStoreReceiverExpr___), so a new binding form cannot reintroduce
! either half independently.
!
! Drives tests/python/global_binding_forms.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
GlobalBindingFormsTestCase removeAllMethods.
GlobalBindingFormsTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: GlobalBindingFormsTestCase
setUp
	"Reload tests/python/global_binding_forms.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'global_binding_forms' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/global_binding_forms.py')
		name: 'global_binding_forms'.
%

category: 'Grail-Private'
method: GlobalBindingFormsTestCase
assertMatchesCPythonAt: key
	self
		assert: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key) asString
		equals: ((testModule @env1:___pyAttrLoad___: #EXPECTED)
			@env1:__getitem__: key) asString
%

category: 'Grail-Tests - Compiles At All'
method: GlobalBindingFormsTestCase
testAClassDefBindsTheGlobal
	"``global C'' then ``class C'' used to emit an assignment to an
	undeclared Smalltalk symbol, failing the whole method's compile."

	self assertMatchesCPythonAt: 'func_class'.
	self assertMatchesCPythonAt: 'method_class'.
%

category: 'Grail-Tests - Compiles At All'
method: GlobalBindingFormsTestCase
testAFunctionDefBindsTheGlobal
	"Same undefined-symbol failure for a nested def whose name is
	declared global -- and the module body never mentions that name, so
	the moduleVariableNames test alone could not have caught it."

	self assertMatchesCPythonAt: 'func_def'.
	self assertMatchesCPythonAt: 'method_def'.
%

category: 'Grail-Tests - Compiles At All'
method: GlobalBindingFormsTestCase
testAWalrusBindsTheGlobal
	self assertMatchesCPythonAt: 'func_walrus'.
	self assertMatchesCPythonAt: 'method_walrus'.
%

category: 'Grail-Tests - Compiles At All'
method: GlobalBindingFormsTestCase
testEveryMatchCaptureFormBindsTheGlobal
	"Sequence capture, star capture and ``as'' capture each emit their own
	bind, so each had to be routed -- one missed form is one silently
	uncompilable method."

	self assertMatchesCPythonAt: 'func_match'.
	self assertMatchesCPythonAt: 'method_match'.
	self assertMatchesCPythonAt: 'method_match_star'.
	self assertMatchesCPythonAt: 'method_match_as'.
%

category: 'Grail-Tests - Compiles At All'
method: GlobalBindingFormsTestCase
testTheTwoScopedStatementTargetsBindTheGlobal
	"``except X as e'' and ``with ... as e'' -- the two forms this file's list
	OMITTED, and they are precisely the two that share
	AbstractNode>>___emitModuleScopeStoreOf___:from:on:.  Ten binding forms were
	enumerated here and the helper's own two callers were not among them.

	The except-as gap was real and IR-only: the direct-to-IR emit assigned the
	payload to a METHOD LOCAL, because the parser records an as-name in
	body.variables even when it is declared global, so a leaf existed and the
	plain assign compiled and ran without complaint while globals() kept the
	old value.  `test.test_global test_caught_exception' read
	``KeyError: 'name_caught_exc''' on the flag-on arm of the CPython corpus.
	Both halves were needed: routing the STORE to the module then made the
	handler-body READ answer nil, since it was still reading that local.

	with-as was measured and was already correct on both paths -- asserted here
	anyway, because it is the sibling caller and the cheapest way to notice if
	one of the two ever diverges from the other again."

	self assertMatchesCPythonAt: 'method_except_as'.
	self assertMatchesCPythonAt: 'method_with_as'.
%

category: 'Grail-Tests - Receiver'
method: GlobalBindingFormsTestCase
testTheModuleReceiverIsUsedInsideAMethod
	"The QUIET half.  These forms already took the module route but
	hardcoded ``self'', which inside a method is the Python instance --
	so the value landed on the instance and globals() never saw it.  Only
	the in-a-METHOD variants can catch this: in a top-level def ``self''
	really is the module."

	self assertMatchesCPythonAt: 'method_import'.
	self assertMatchesCPythonAt: 'method_unpack'.
	self assertMatchesCPythonAt: 'method_augassign'.
	self assertMatchesCPythonAt: 'method_plain'.
%

category: 'Grail-Tests - Scope'
method: GlobalBindingFormsTestCase
testAGlobalDeclarationRebindsTheModuleName
	"The declaration must REBIND the module's existing name, not create a
	shadow that the module body cannot see."

	self assertMatchesCPythonAt: 'rebinds_module_name'.
%

category: 'Grail-Tests - Scope'
method: GlobalBindingFormsTestCase
testWithoutAGlobalDeclarationTheBindingStaysLocal
	"The guard against over-correcting: routing a binding form to the
	module unconditionally would make every function-local class leak
	into globals()."

	self assertMatchesCPythonAt: 'no_global_stays_local'.
%
