! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for GlobalSyntaxErrorsTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'GlobalSyntaxErrorsTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
GlobalSyntaxErrorsTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! GlobalSyntaxErrorsTestCase
!
! ``global x'' is a SyntaxError when x is already a PARAMETER of, BOUND in,
! READ in, or ANNOTATED in the same function scope.  CPython rejects all four
! in symtable.c, each with its own message; Grail accepted every one silently,
! so code CPython refuses to compile ran here with the name quietly meaning
! something other than what it says.
!
! THE RISK IN THIS CHECK IS FALSE POSITIVES, NOT FALSE NEGATIVES.  A missed
! rejection costs one obscure diagnostic; a check that is too eager REJECTS
! WORKING MODULES AT IMPORT TIME.  That is why the legal-form tests below
! outnumber the illegal ones, and why they are the ones worth reading.
!
! One false positive was found exactly that way, by the fixture rather than by
! inspection: ``[c for c in range(3)]'' followed by ``global c''.  A
! comprehension is its OWN SCOPE in Python 3, so its target neither binds nor
! reads in the enclosing function -- but the reads emitted inside it do land in
! the enclosing scope's readStack, so the check reported ``used prior to global
! declaration'' for code CPython accepts.  Comprehension targets are now
! excluded from the READ check only: a genuine assignment reaches the write
! set, which is tested first, so the exclusion cannot hide a real
! ``assigned to before'' error.
!
! Two of the four cases needed state the parser did not keep.  A PARAMETER
! registers through declareVariable:, which is also used for unrelated scope
! hints, so ``in variables but not in writes'' could not identify one.  An
! ANNOTATION without a value binds nothing and so never reaches the write set,
! yet still makes a later ``global'' an error -- with its own wording.
!
! Drives tests/python/global_syntax_errors.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
GlobalSyntaxErrorsTestCase removeAllMethods.
GlobalSyntaxErrorsTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: GlobalSyntaxErrorsTestCase
setUp
	"Reload tests/python/global_syntax_errors.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'global_syntax_errors' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/global_syntax_errors.py')
		name: 'global_syntax_errors'.
%

category: 'Grail-Private'
method: GlobalSyntaxErrorsTestCase
assertMatchesCPythonAt: key
	self
		assert: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key) asString
		equals: ((testModule @env1:___pyAttrLoad___: #EXPECTED)
			@env1:__getitem__: key) asString
%

category: 'Grail-Tests - Rejections'
method: GlobalSyntaxErrorsTestCase
testAParameterCannotBeDeclaredGlobal
	"Needs its own tracking: a parameter registers through
	declareVariable:, which is also used for unrelated scope hints, so
	``in variables but not in writes'' would misidentify it."

	self assertMatchesCPythonAt: 'parameter'.
%

category: 'Grail-Tests - Rejections'
method: GlobalSyntaxErrorsTestCase
testANameAssignedBeforeTheDeclarationIsRejected
	self assertMatchesCPythonAt: 'assigned_before'.
%

category: 'Grail-Tests - Rejections'
method: GlobalSyntaxErrorsTestCase
testANameReadBeforeTheDeclarationIsRejected
	self assertMatchesCPythonAt: 'used_before'.
%

category: 'Grail-Tests - Rejections'
method: GlobalSyntaxErrorsTestCase
testAnAnnotatedNameCannotBeDeclaredGlobal
	"``x: int'' with no value BINDS NOTHING, so it never reaches the
	write set -- yet it still makes a later ``global x'' an error, and
	with a different message.  That is why annotations are tracked
	separately from writes."

	self assertMatchesCPythonAt: 'annotated_before'.
%

category: 'Grail-Tests - Rejections'
method: GlobalSyntaxErrorsTestCase
testEachNameInAMultiNameDeclarationIsChecked
	"``global a, b'' where only b is already bound: the statement is
	rejected on b, so checking merely the first name would accept it."

	self assertMatchesCPythonAt: 'multiple_names'.
%

category: 'Grail-Tests - Still Legal'
method: GlobalSyntaxErrorsTestCase
testModuleLevelAndClassBodyDeclarationsStayLegal
	"At module level ``global'' is a legal no-op, and a CLASS body may
	declare it -- Grail already depends on the latter, since it rebinds
	the module's name and leaves the class without the attribute.
	Applying the function-scope rule to either would break importing."

	self assertMatchesCPythonAt: 'module_level'.
	self assertMatchesCPythonAt: 'class_body'.
%

category: 'Grail-Tests - Still Legal'
method: GlobalSyntaxErrorsTestCase
testDeclaringBeforeUseStaysLegal
	"The normal, correct spelling -- and by far the most common one in
	real code, so a check that got this wrong would be caught by the
	whole corpus failing to import rather than by one test."

	self assertMatchesCPythonAt: 'declared_first'.
	self assertMatchesCPythonAt: 'declared_first_then_read'.
%

category: 'Grail-Tests - Still Legal'
method: GlobalSyntaxErrorsTestCase
testTheCheckIsPerScope
	"An inner function has its own scope, so an outer binding -- or an
	outer PARAMETER -- of the same name must not poison it.  Consulting
	the enclosing scope's sets instead of the current one's would reject
	all three of these."

	self assertMatchesCPythonAt: 'inner_scope_is_separate'.
	self assertMatchesCPythonAt: 'sibling_scopes'.
	self assertMatchesCPythonAt: 'outer_param_inner_global'.
%

category: 'Grail-Tests - Still Legal'
method: GlobalSyntaxErrorsTestCase
testAComprehensionTargetDoesNotBlockTheDeclaration
	"The false positive this fixture actually caught.  A comprehension is
	its OWN scope in Python 3, so its target neither binds nor reads in
	the enclosing function -- but the reads emitted inside it DO land in
	the enclosing scope's readStack, which reported ``used prior to
	global declaration'' for code CPython compiles fine."

	self assertMatchesCPythonAt: 'comprehension_target'.
%

category: 'Grail-Tests - Still Legal'
method: GlobalSyntaxErrorsTestCase
testAReadInsideANestedDefBelongsToThatDef
	"The false positive the CPYTHON CORPUS caught, after the fixture had
	already passed: test_builtin declares ``global all, any, tuple''
	after several nested defs that CALL all/any/tuple, and rejecting it
	made the whole module fail to import.

	Grail propagates free names OUT of a nested scope into the enclosing
	read set, so that scope could answer closures and locals() -- which
	makes the enclosing read set TRANSITIVE, and unable to answer ``was
	this name read in THIS scope?''.  The check reads a separate own-reads
	set that popScope deliberately does not propagate."

	self assertMatchesCPythonAt: 'nested_def_read'.
	self assertMatchesCPythonAt: 'nested_def_genexp_read'.
%
