! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for MethodFunctionDelegationTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'MethodFunctionDelegationTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
MethodFunctionDelegationTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! MethodFunctionDelegationTestCase
!
! A METHOD DELEGATES TO ITS FUNCTION.
!
! CPython has two objects here and Grail has two objects here, but Grail had them
! wired as one.  ``F.a'' is the FUNCTION -- writable, with a __dict__, the thing
! a decorator tags.  ``fi.a'' is a bound METHOD -- no storage of its own, and
! every attribute it reports it reports by asking the function.
!
! BoundMethod>>__func__ answered SELF for an instance-bound handle, so the method
! WAS its own function, and every rule that distinguishes the two collapsed in
! the same direction:
!
!   * ``fi.a.__dict__'' was a flat AttributeError, so an attribute set on the
!     function was invisible through every instance;
!   * ``fi.a.__doc__'' ignored a docstring assigned to the function;
!   * ``fi.a.__func__.__dict__ = d'' raised from the METHOD -- which correctly
!     has no __dict__ -- rather than writing to the function;
!   * ``dir(fi.a)'' did not list what the function carried.
!
! The two ends of that are ONE idiom: a decorator tags the function, an instance
! reads the tag.  They disagreed, and nothing raised at the point of the write,
! so the loss surfaced later as a missing attribute rather than as an error.
!
! WHY AN UnboundMethod IS THE HONEST ANSWER for __func__.  It is the one object
! Grail has that plays the part of the function: interned per (class, selector),
! so ``fi.a.__func__ is F.a'' holds the way CPython's identity does, and
! invocable with the receiver first.  The class-receiver case already answered
! one (a @classmethod's __func__ takes cls first); this extends the same
! reasoning to instances, where the previous comment had claimed there was
! nothing to point at.
!
! THE SECOND HALF is that a FUNCTION's __dict__ can be REPLACED, and CPython
! installs the CALLER'S OWN mapping -- ``f.__dict__ = d'' then ``f.__dict__ is
! d'', which is what test_funcattrs checks.  Grail stored a dynamic slot that
! happened to be spelled __dict__ and left the real attribute storage untouched:
! the write looked like it worked, the mapping was never consulted again, and
! reads went on answering from the old storage.  So UnboundMethod grew an
! ``attrDict'' instVar -- a REAL one, not a dynamic one, so it stays out of the
! PyInstanceDict view it stands in for -- with the reads, writes and deletes
! routed through it once installed.  A ``dictView'' instVar holds the live view
! itself, made once and kept, because a fresh proxy per read is equally live but
! breaks ``m.__dict__ is m.__dict__''.
!
! ONE ADJACENT FIX, in Object>>__getattr__: it built its AttributeError with a
! BARE ``asString'', which in an env-1 method is looked up in env 1, where String
! has none -- so the default attribute-miss path raised MessageNotUnderstood
! instead.  Nothing reached it until a class overrode __getattr__ and called
! super, which is the ordinary spelling for "handle these names, default for the
! rest".
!
! WHAT IS NOT FIXED, and is not a message this class can send: Grail spells the
! Python type name of these objects ``UnboundMethod'' / ``BoundMethod'' rather
! than ``function'' / ``method'', so a miss reports
! ``'UnboundMethod' object has no attribute 'x'''.  The fixture asserts the
! exception TYPE for that one check and says why, rather than pinning a name
! this change does not touch.
!
! Drives tests/python/method_function_delegation.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and self-verifies against it.  Closes
! test_funcattrs' test___func__, test___class__, test_set_docstring_attr,
! test_setting_dict_to_valid, test_setting_dict_to_invalid and
! test_dir_includes_correct_attrs.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
MethodFunctionDelegationTestCase removeAllMethods.
MethodFunctionDelegationTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: MethodFunctionDelegationTestCase
setUp
	"Reload tests/python/method_function_delegation.py fresh each test.  Every
	probe builds its own class through ``fresh()'', but the module body has
	already run them all at import, and the UnboundMethod handles it tagged are
	interned for the session -- so a shared instance would let one test read
	another's replacement __dict__."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'method_function_delegation' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/method_function_delegation.py')
		name: 'method_function_delegation'.
%

category: 'Grail-Private'
method: MethodFunctionDelegationTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Method Is Not The Function'
method: MethodFunctionDelegationTestCase
testTheMethodsFunctionIsTheClassHandle
	"THE TEST THIS EXISTS FOR.  ``fi.a.__func__'' is ``F.a'' -- the same object
	the class hands out, not the bound handle answering itself.  Everything
	below follows from it: with the method as its own function there is no
	second object for storage to live on."

	self assertMatchesCPythonAt: 'func_is_the_class_handle'.
	self assertMatchesCPythonAt: 'self_is_the_receiver'.
%

category: 'Grail-Tests - Reads Delegate'
method: MethodFunctionDelegationTestCase
testTheMethodReportsTheFunctionsDocstring
	"``F.a.__doc__ = docstr'' has to be visible as ``fi.a.__doc__''.  CPython
	keeps one docstring, on the function, and the method merely reports it;
	Grail's method looked only in the class's compiled doc table and so ignored
	an assignment entirely."

	self assertMatchesCPythonAt: 'doc_assigned_on_the_function'.
	self assertMatchesCPythonAt: 'doc_absent_is_none'.
%

category: 'Grail-Tests - Reads Delegate'
method: MethodFunctionDelegationTestCase
testAnAttributeSetOnTheFunctionIsReadableThroughTheMethod
	"The decorator idiom, both ends: tag the function in the class body, read
	the tag off an instance's bound method.  This is what silently lost data --
	the write succeeded and the read said the attribute did not exist."

	self assertMatchesCPythonAt: 'attr_set_on_the_function'.
	self assertMatchesCPythonAt: 'dict_sees_a_later_write'.
	self assertMatchesCPythonAt: 'dir_of_the_method_lists_it'.
%

category: 'Grail-Tests - Reads Delegate'
method: MethodFunctionDelegationTestCase
testTheMethodsDictIsTheFunctionsDict
	"Not a copy and not a fresh view per read: the SAME object, which is how
	CPython code checks that two handles share a namespace."

	self assertMatchesCPythonAt: 'dict_is_the_functions_dict'.
%

category: 'Grail-Tests - Reads Delegate'
method: MethodFunctionDelegationTestCase
testDelegationStopsAtAnHonestMiss
	"Delegating every miss to the function must not turn a genuine miss into a
	value.  A name neither carries is still an AttributeError."

	self assertMatchesCPythonAt: 'attr_never_set'.
%

category: 'Grail-Tests - Writes On The Method Do Not Happen'
method: MethodFunctionDelegationTestCase
testAnArbitraryWriteOnTheMethodRaises
	"A method has no attribute storage, so ``fi.a.x = 1'' is a mistake worth
	reporting rather than a write to keep somewhere nothing reads back."

	self assertMatchesCPythonAt: 'set_arbitrary_on_method'.
	self assertMatchesCPythonAt: 'del_arbitrary_on_method'.
%

category: 'Grail-Tests - Writes On The Method Do Not Happen'
method: MethodFunctionDelegationTestCase
testTheDescriptorsTheMethodTypeOwnsRefuseDifferently
	"CPython uses a DIFFERENT message for the three names the method type
	exposes -- ``attribute '__doc__' of 'method' objects is not writable'' --
	because those attributes exist and simply have no setter, which is not the
	same complaint as a name the object has never heard of.  And __class__ is a
	TypeError rather than an AttributeError in both directions, because the
	store reaches object.__setattr__, which FINDS the slot descriptor and
	rejects the value."

	self assertMatchesCPythonAt: 'set_doc_on_method'.
	self assertMatchesCPythonAt: 'set_class_on_method'.
	self assertMatchesCPythonAt: 'del_class_on_method'.
%

category: 'Grail-Tests - Replacing The Functions Dict'
method: MethodFunctionDelegationTestCase
testAssignmentInstallsTheCallersOwnMapping
	"``F.a.__dict__ = d'' makes ``d'' the namespace, checked with ``is'' on both
	handles.  Grail stored a dynamic slot spelled __dict__ instead and left the
	real storage in place, so the mapping was never consulted again."

	self assertMatchesCPythonAt: 'replace_installs_that_mapping'.
	self assertMatchesCPythonAt: 'replace_is_visible_from_the_method'.
%

category: 'Grail-Tests - Replacing The Functions Dict'
method: MethodFunctionDelegationTestCase
testEveryAttributeOperationGoesThroughTheReplacement
	"Installing it is only half: once ``d'' IS the namespace, reads, writes and
	deletes have to land in ``d''.  A replacement the attribute path ignored
	would satisfy the identity check on the next line and diverge on the one
	after."

	self assertMatchesCPythonAt: 'read_goes_through_the_replacement'.
	self assertMatchesCPythonAt: 'write_goes_through_the_replacement'.
	self assertMatchesCPythonAt: 'delete_goes_through_the_replacement'.
%

category: 'Grail-Tests - Replacing The Functions Dict'
method: MethodFunctionDelegationTestCase
testTheFunctionRulesApplyToAClassBodyDef
	"An unbound handle is a FUNCTION, so it takes the function WRITE rules --
	the same ones a closure and a module-level def take.  It took none at all:
	a non-mapping __dict__ and an integer __name__ were both accepted.  Deleting
	__dict__ is a TypeError rather than an AttributeError, because what CPython
	refuses is the deletion of an attribute that exists."

	self assertMatchesCPythonAt: 'replace_with_a_non_dict'.
	self assertMatchesCPythonAt: 'delete_the_dict'.
	self assertMatchesCPythonAt: 'rename_the_function_to_an_int'.
%
