! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ModuleSpecTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ModuleSpecTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ModuleSpecTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ModuleSpecTestCase
!
! PEP 451 ``__spec__'' -- the canonical record the other machinery attributes
! are DERIVED from.
!
! Before this, ``mod.__spec__'' was None on every module in the corpus, and the
! four module-creation paths (loadModuleFromPath:name:, the namespace-package
! builder, the meta_path ___emptyModuleNamed___:spec:loader:, and CPythonShim's
! extension loader) each wrote ``__name__'', ``__package__'', ``__file__'',
! ``__loader__'' and ``__path__'' independently.
!
! THE DERIVATION IS THE POINT, not merely having a spec.  CPython treats a
! mirror that disagrees with its spec as a bug and warns about it --
! ``__package__ != __spec__.parent'' is a DeprecationWarning in 3.14.  A spec
! that merely existed ALONGSIDE independently-written attributes would satisfy
! an ``is it not None'' check and still be free to drift, so the tests below
! assert the agreement rather than the presence.
!
! ONE SEAM: importlib class >> ___initModuleAttrsFrom___:on:, which is CPython's
! _init_module_attrs.  ``__file__'' is keyed on ``has_location'' exactly as
! CPython keys it, which is what gives a namespace package ``__file__ = None''
! rather than a fabricated path.
!
! ONE TYPE.  importlib/__init__.py used to define its own four-slot
! ``_ModuleSpec'' and alias it as ``ModuleSpec''.  Once the machinery builds
! real specs, a second class of the same name makes
! ``isinstance(mod.__spec__, ModuleSpec)'' FALSE -- so the .py now takes the
! Smalltalk class instead of defining one.  The machinery's class has to be the
! Smalltalk one, because it needs a spec for modules that load before any .py
! has run.
!
! A SMALLTALK-IMPLEMENTED MODULE (json, string, sys) gets the BUILT-IN shape:
! origin ``built-in'', has_location false, no __file__.  That is not a
! placeholder -- CPython's own C modules report exactly that, measured on
! 3.14.6 as ``ModuleSpec(name='sys', loader=BuiltinImporter, origin='built-in')''.
! Those modules are minted by ``module class >> instance'' and never pass
! through registerModule:with: in a fresh session, so the stamp rides the same
! one-time sweep ``__builtins__'' uses; stamping only at registration left 25
! of 35 modules with __spec__ None, measured.
!
! KNOWN DIVERGENCE, deliberate: ``spec.cached'' is always None.  It names the
! compiled bytecode file and Grail writes no .pyc.  That is load-bearing rather
! than cosmetic -- _init_module_attrs sets ``__cached__'' only when spec.cached
! is not None, so the None here is what keeps module.__cached__ absent, matching
! the decision recorded on module >> __cached__.  The fixture marks it XFAIL.
!
! Drives tests/python/module_spec.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ModuleSpecTestCase removeAllMethods.
ModuleSpecTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ModuleSpecTestCase
setUp
	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'module_spec' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/module_spec.py')
		name: 'module_spec'.
%

category: 'Grail-Private'
method: ModuleSpecTestCase
assertMatchesAt: key in: tableName
	"Compare the fixture's recorded result against its expectation table, both
	through repr so a True and a 'True' cannot pass for each other."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: tableName) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Private'
method: ModuleSpecTestCase
assertMatchesCPythonAt: key
	^ self assertMatchesAt: key in: #EXPECTED
%

category: 'Grail-Tests'
method: ModuleSpecTestCase
testAModuleCarriesARealSpec
	"``mod.__spec__'' was None on every module before this."

	self assertMatchesCPythonAt: 'spec_is_not_none'.
	self assertMatchesCPythonAt: 'spec_type_name'.
	self assertMatchesCPythonAt: 'spec_name'.
%

category: 'Grail-Tests'
method: ModuleSpecTestCase
testEveryMirrorAgreesWithTheSpecItCameFrom
	"The invariant the whole change exists for.  CPython derives each of these
	in _init_module_attrs and warns when one drifts from the spec; a spec that
	merely sat alongside independently-written attributes would pass the
	presence test above and still be able to disagree here."

	self assertMatchesCPythonAt: 'file_is_spec_origin'.
	self assertMatchesCPythonAt: 'package_is_spec_parent'.
	self assertMatchesCPythonAt: 'loader_is_spec_loader'.
%

category: 'Grail-Tests'
method: ModuleSpecTestCase
testLocationAndParentAreComputedFromTheSpecsOwnFields
	"has_location decides whether __file__ is set at all -- it is what gives a
	namespace package __file__ None rather than a fabricated path -- and parent
	is what __package__ is set from."

	self assertMatchesCPythonAt: 'has_location'.
	self assertMatchesCPythonAt: 'parent_of_top_level_is_empty'.
	self assertMatchesCPythonAt: 'submodule_parent'.
%

category: 'Grail-Tests'
method: ModuleSpecTestCase
testCachedIsAlwaysNone
	"A DELIBERATE divergence, asserted so it stays deliberate.  CPython computes
	a __pycache__ path for any source module without checking it exists; Grail
	writes no bytecode.  Load-bearing, not cosmetic: _init_module_attrs sets
	``__cached__'' only when spec.cached is not None, so this None is what keeps
	module.__cached__ absent -- see ModuleCachedAbsentTestCase."

	self assertMatchesAt: 'cached_is_none' in: #GRAIL_ONLY.
%
