! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ModuleDocstringTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ModuleDocstringTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ModuleDocstringTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ModuleDocstringTestCase
!
! Module ``__doc__'' -- the module's own docstring, never Object's.
!
! NOT A MISSING ATTRIBUTE BUT A WRONG ANSWER, which is why it lasted.  module >>
! __doc__ ended in ``^ super __doc__'', climbing the Smalltalk superclass chain
! to Object, so EVERY module in the corpus reported
!
!     'The base class of the class hierarchy.  When called, it accepts no ...'
!
! as its docstring -- textwrap included, whose real ``Text wrapping and
! filling.'' sat unread in the source.  Nothing raised and the value was a
! plausible non-empty string, so no read-based check would have noticed; only
! comparing against the SOURCE does.
!
! TWO CAUSES, BOTH NEEDED FIXING.  The compiler never extracted a module-level
! docstring at all -- ModuleAst had no ``___docString___'', unlike ClassDefAst
! and FunctionDefAst, whose version carries the comment ``so a class no longer
! inherits object's docstring'' for the identical defect one level down.  And
! the accessor inherited one when the namespace had none.
!
! ON THE CLASS, THEN ONTO THE INSTANCE.  The compiler stamps a class-side
! ``___pyModuleDoc___'' in ___buildModuleClassBody:name:, and
! registerModule:with: copies it into the instance namespace.  The indirection
! is not decoration: the AST exists only on a COLD load, and a warm bind reuses
! a committed module class without parsing a line, so a docstring read straight
! from the AST would be present or absent depending on which path a session
! took.  Riding the class makes both agree.  Same reason ___methodCodeTable___
! sits there.
!
! IN THE NAMESPACE, not merely readable.  CPython's ``__doc__'' is an entry in
! ``mod.__dict__'', so dir(), vars() and any iteration see it; the tests below
! check membership as well as value, because a computed accessor would satisfy
! every read and none of the iteration.
!
! NONE IS A REAL ANSWER, and reached three correct ways: the source opens with a
! ``#'' comment rather than a string (Grail's own types.py, operator.py), the
! module is implemented in Smalltalk and has no Python source to read (json,
! string), or it genuinely has none (enum, in CPython too).  A module with no
! docstring HAS the attribute with value None -- distinct from lacking it, and
! distinct from inheriting somebody else's.
!
! KNOWN DIVERGENCE, out of scope here: a Smalltalk-implemented module answers
! None where CPython's same-named module has a docstring (json, string, sys).
! Closing that means declaring a docstring in the .gs, which is separate work.
!
! Drives tests/python/module_docstring.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ModuleDocstringTestCase removeAllMethods.
ModuleDocstringTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ModuleDocstringTestCase
setUp
	"Reload tests/python/module_docstring.py fresh each test, so each one reads
	a module built by this session's compiler rather than whatever an earlier
	test left in sys.modules."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'module_docstring' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/module_docstring.py')
		name: 'module_docstring'.
%

category: 'Grail-Private'
method: ModuleDocstringTestCase
assertMatchesCPythonAt: key
	"Compare the fixture's recorded result against its CPython-measured
	EXPECTED entry, both through repr so a True and a 'True' cannot pass for
	each other."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests'
method: ModuleDocstringTestCase
testAModuleReadsBackItsOwnDocstring
	"The compiler now extracts the leading bare string literal of a module body
	and stamps it; before this it discarded it, so the value below was
	unreachable no matter how the accessor behaved."

	self assertMatchesCPythonAt: 'own_doc_is_a_string'.
	self assertMatchesCPythonAt: 'own_doc_first_line'.
	self assertMatchesCPythonAt: 'imported_doc_value'.
%

category: 'Grail-Tests'
method: ModuleDocstringTestCase
testNoModuleReportsObjectsDocstring
	"The regression proper.  Stated as a property rather than against a literal
	so it survives a rewording of GemStone's Object docstring -- and because the
	literal is exactly what every module used to answer, an equality check
	against it would have passed for the wrong reason."

	self assertMatchesCPythonAt: 'own_doc_is_not_objects'.
	self assertMatchesCPythonAt: 'imported_doc_is_not_objects'.
%

category: 'Grail-Tests'
method: ModuleDocstringTestCase
testTheDocstringIsAnEntryInTheNamespaceNotMerelyReadable
	"CPython puts ``__doc__'' IN the module namespace, so dir(), vars() and any
	iteration see it.  Membership is what distinguishes a real entry from an
	accessor that merely answers a read."

	self assertMatchesCPythonAt: 'own_doc_in_namespace'.
	self assertMatchesCPythonAt: 'imported_doc_in_namespace'.
%

category: 'Grail-Tests'
method: ModuleDocstringTestCase
testAModuleWithNoDocstringAnswersNone
	"None, not absent and not inherited.  This is the half that the old
	``^ super __doc__'' got wrong in the most misleading way: it answered a
	string for a module that has no docstring at all."

	self assertMatchesCPythonAt: 'no_docstring_is_none'.
%
