! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for OsUtimeTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'OsUtimeTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
OsUtimeTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! OsUtimeTestCase
!
! os.utime -- setting a file's access and modification times.  The last of the
! os gaps that blocked driving an unmodified pip-installed kaggle client, which
! stamps every file it downloads with the server's timestamps.
!
! EVERY POSITIVE TEST HERE READS THE TIME BACK, and that is the whole design.
! os.utime was once stubbed as a NO-OP, and the stub reached a passing
! acceptance run: nothing in that harness looked at an mtime, so "returned None"
! and "worked" were indistinguishable.  A silent no-op is WORSE than the
! AttributeError it replaced -- it reports success while doing nothing -- so
! nothing below is satisfied by a call that merely fails to raise.
! testANoOpWouldBeCaught is the check that exists for no other purpose.
!
! GemStone exposes no utimes(2), so os.utime runs touch(1), and two things about
! that are checked rather than assumed:
!
!   * TIMEZONE.  The obvious spelling, ``touch -t CCYYMMDDhhmm.ss'', is defined
!     in LOCAL time.  Measured on the machine this was written on, it stamped a
!     time eight hours off UTC, and the size of that error moves with DST.  Grail
!     formats the instant as ``YYYY-MM-DDThh:mm:ssZ'' and passes ``-d'', which
!     both BSD touch (macOS) and GNU touch (Linux, and so CI) read as UTC.  The
!     timestamps in the fixture straddle summer, winter and pre-1970 on purpose:
!     a conversion that leaks the local zone gets at least one of them wrong on
!     any machine that observes DST.
!
!   * SHELL QUOTING.  A downloaded filename is attacker-influenced text going
!     onto a command line.  The fixture stamps a file whose name holds a space,
!     a single quote and a semicolon, and checks both that the times landed and
!     that the command the semicolon introduces did not run.
!
! WHOLE SECONDS.  os.stat here answers an int st_mtime where CPython answers a
! float (GsFileStat exposes whole seconds only), and os.utime floors to match,
! so a round trip agrees with CPython on math.floor(st_mtime) and not on
! st_mtime itself.  The fixture compares the floored value, which is true under
! CPython too.
!
! Drives tests/python/os_utime.py, whose EXPECTED table was generated by RUNNING
! CPython 3.14.6 and which self-verifies against it in scripts/check_python_fixtures.sh.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
OsUtimeTestCase removeAllMethods.
OsUtimeTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: OsUtimeTestCase
setUp
	"Reload tests/python/os_utime.py fresh each test.  The module body builds
	its tree, records every answer, and tears the tree down again, so the tests
	read recorded results rather than sharing filesystem state."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'os_utime' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/os_utime.py')
		name: 'os_utime'.
%

category: 'Grail-Private'
method: OsUtimeTestCase
assertMatchesCPythonAt: key
	"Compare through repr: most answers here are booleans or TUPLES of them,
	which asString would flatten into the same text."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - the times are really set'
method: OsUtimeTestCase
testBothTimesAreSetAndReadBack
	"os.utime(path, (atime, mtime)) sets the two INDEPENDENTLY, so the fixture
	passes a different value for each: swapping them, or setting only one, is
	silent otherwise."

	self assertMatchesCPythonAt: 'returns_none'.
	self assertMatchesCPythonAt: 'atime_read_back'.
	self assertMatchesCPythonAt: 'mtime_read_back'.
%

category: 'Grail-Tests - the times are really set'
method: OsUtimeTestCase
testANoOpWouldBeCaught
	"The one check whose only job is to fail against the crude stub this
	replaced.  A no-op leaves the mtime at the file's creation time; every
	other positive test here would still pass if os.utime did nothing and the
	fixture happened to ask for the value it already had."

	self assertMatchesCPythonAt: 'mtime_moved_off_creation'.
%

category: 'Grail-Tests - the times are really set'
method: OsUtimeTestCase
testTheConversionToUtcHoldsAcrossTheYear
	"``touch -t'' would have passed the first of these and failed the second by
	the DST offset, or the other way round depending on the gem's zone.  The
	pre-epoch value is the third trap: it is negative, so a truncating division
	in the civil-calendar conversion lands on the wrong DAY, not merely the
	wrong second."

	self assertMatchesCPythonAt: 'winter_exact'.
	self assertMatchesCPythonAt: 'summer_exact'.
	self assertMatchesCPythonAt: 'pre_epoch_exact'.
%

category: 'Grail-Tests - argument spellings'
method: OsUtimeTestCase
testTimesMayBeGivenAsAKeyword
	"kaggle spells it ``os.utime(outfile, times=(t, t))'', so the keyword form
	is the one that actually has to work in the field."

	self assertMatchesCPythonAt: 'times_as_a_keyword'.
%

category: 'Grail-Tests - argument spellings'
method: OsUtimeTestCase
testOmittedTimesMeansNow
	"Both spellings of ``now'' -- the argument absent, and an explicit None."

	self assertMatchesCPythonAt: 'omitted_means_now'.
	self assertMatchesCPythonAt: 'none_means_now'.
%

category: 'Grail-Tests - argument spellings'
method: OsUtimeTestCase
testSubSecondPrecisionIsFlooredNotDiscarded
	"ns= and a fractional seconds value both land on the whole second BELOW,
	rather than being rejected or rounded.  os.stat here answers whole seconds
	anyway, so flooring is the only answer that round-trips."

	self assertMatchesCPythonAt: 'ns_floors_to_whole_seconds'.
	self assertMatchesCPythonAt: 'fractional_seconds_floor'.
%

category: 'Grail-Tests - symlinks'
method: OsUtimeTestCase
testFollowSymlinksIsHonouredInBothDirections
	"The default FOLLOWS, so the target is stamped; follow_symlinks=False
	stamps the link itself and leaves the target alone.  Both halves are
	asserted, because an implementation that ignored the argument would pass
	either one on its own."

	self assertMatchesCPythonAt: 'default_follows_to_the_target'.
	self assertMatchesCPythonAt: 'follow_symlinks_false_stamps_the_link'.
%

category: 'Grail-Tests - shell quoting'
method: OsUtimeTestCase
testAShellHostileFilenameSurvives
	"os.utime runs touch(1), so the path is shell-quoted.  The name holds a
	space, a single quote and a SEMICOLON; quoting that is merely nearly right
	re-parses the last one as a command separator, which is arbitrary command
	execution rather than a wrong answer.  The times landing correctly is
	already most of the proof -- a re-parsed name would have been handed to
	touch as three fragments -- and the other two checks say the introduced
	command left nothing behind."

	self assertMatchesCPythonAt: 'hostile_name_keeps_its_times'.
	self assertMatchesCPythonAt: 'no_injected_command_ran'.
	self assertMatchesCPythonAt: 'nothing_extra_in_the_directory'.
%

category: 'Grail-Tests - errors'
method: OsUtimeTestCase
testAMissingPathIsFileNotFoundError
	"touch(1) would CREATE the file, which is the opposite of what os.utime
	means, so the existence check happens before the command runs."

	self assertMatchesCPythonAt: 'missing_path'.
%

category: 'Grail-Tests - errors'
method: OsUtimeTestCase
testBadArgumentShapesAreTypeErrors
	"CPython tests PyTuple_Check, so a LIST of two ints is a TypeError as
	surely as a string is.  Accepting a list would be the friendlier answer and
	the wrong one: code written against it then fails under CPython, which is
	the direction of breakage that costs the most to find."

	self assertMatchesCPythonAt: 'times_as_a_list'.
	self assertMatchesCPythonAt: 'times_of_three'.
	self assertMatchesCPythonAt: 'times_not_a_sequence'.
	self assertMatchesCPythonAt: 'times_of_strings'.
	self assertMatchesCPythonAt: 'ns_of_three'.
	self assertMatchesCPythonAt: 'ns_of_floats'.
	self assertMatchesCPythonAt: 'three_positional_arguments'.
	self assertMatchesCPythonAt: 'unexpected_keyword'.
%

category: 'Grail-Tests - errors'
method: OsUtimeTestCase
testTimesAndNsTogetherIsAValueError
	"Not a TypeError: CPython treats it as two valid spellings of one argument
	rather than a mistyped one, and code catches accordingly."

	self assertMatchesCPythonAt: 'times_and_ns_together'.
%

category: 'Grail-Tests - errors'
method: OsUtimeTestCase
testAnOutOfRangeTimestampOverflows
	"CPython says ``timestamp out of range for platform time_t''; Grail's
	boundary is the four-digit year its ISO formatting can render.  The exact
	boundary differs, the CLASS of error does not, and that is what a caller
	branches on."

	self assertMatchesCPythonAt: 'out_of_range_timestamp'.
%

category: 'Grail-Tests - errors'
method: OsUtimeTestCase
testDirFdIsRejectedRatherThanIgnored
	"A DOCUMENTED DIVERGENCE, so it is asserted here rather than in the
	CPython-compared table: CPython honours dir_fd for utime on Linux and
	macOS, and Grail has no dir_fd anywhere.  Accepting and ignoring it would
	resolve the path against the wrong directory and stamp the wrong file --
	a wrong answer rather than a missing feature -- so it says
	NotImplementedError instead.  dir_fd=None is the default and stays legal."

	| got |
	got := (testModule @env1:___pyAttrLoad___: #g) @env1:__getitem__: 'dir_fd'.
	self assert: got asString equals: 'NotImplementedError'.
	self assertMatchesCPythonAt: 'dir_fd_none_is_accepted'.
%
