! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for OsWalkTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'OsWalkTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
OsWalkTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! OsWalkTestCase
!
! os.walk -- the directory-tree generator -- and the two os.listdir errors its
! error handling rests on.
!
! Grail had no os.walk at all.  That is why test.test_reprlib could not clean up
! after itself: its LongNameTests tearDown walks the package it built and removes
! it bottom-up, so every suite run left the tree behind in the checkout.
!
! THE LAZINESS IS PART OF THE CONTRACT, not an optimisation.  With topdown true
! the caller may prune the walk by mutating ``dirnames'' IN PLACE between yields
! (``dirs.remove('__pycache__')''), which a materialised list cannot offer -- it
! would have finished recursing before the caller saw anything.  Grail can answer
! this honestly because PythonGenerator takes a 1-arg Smalltalk block and runs it
! as a coroutine, so a Smalltalk-implemented module method can suspend at a yield
! exactly where CPython's ``yield'' does.  testPruningStopsTheDescent is what
! proves it is a real generator; nothing else here would fail if it were a list.
!
! Two os.listdir defects surfaced on the way, both SILENT.  GsFile's directory
! listing EXPANDS A PATTERN rather than opening a directory, so it answers
! something plausible where CPython raises:
!
!   * a MISSING path answered [], so a walk of a missing tree yielded one empty
!     triple instead of nothing and never called its onerror;
!   * a path that is a FILE answered [that file], so ``os.listdir('a.txt')''
!     reported a directory containing itself -- the more dangerous of the two,
!     since that is exactly what a recursive walker follows.
!
! ORDER AMONG SIBLINGS IS NOT ASSERTED ANYWHERE.  It follows the filesystem's
! listing order, which GsFile and CPython's scandir need not agree on, so the
! fixture compares triples SORTED and checks the topdown/bottom-up distinction as
! an ordering INVARIANT -- parent before child, or child before parent.
! Asserting the literal sequence would be testing the filesystem.
!
! Drives tests/python/os_walk.py, whose EXPECTED table was generated by RUNNING
! CPython 3.14.6 and verified against it before commit.  The fixture builds its
! tree under tempfile.mkdtemp() and tears it down with os.walk itself -- the
! same shape as test_reprlib's tearDown, and the reason this work happened.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
OsWalkTestCase removeAllMethods.
OsWalkTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: OsWalkTestCase
setUp
	"Reload tests/python/os_walk.py fresh each test.  The module body builds
	its own tree and removes it again, so the tests read a recorded result
	rather than sharing filesystem state."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'os_walk' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/os_walk.py')
		name: 'os_walk'.
%

category: 'Grail-Private'
method: OsWalkTestCase
assertMatchesCPythonAt: key
	"Compare through repr.  asString would flatten a list of triples and a
	tuple of the same names to the same text, and several answers here differ
	only in structure."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Contents'
method: OsWalkTestCase
testEveryDirectoryIsReportedWithItsOwnNames
	"dirnames holds the SUBDIRECTORIES and filenames everything else, both as
	bare names rather than paths, for the root and every directory under it."

	self assertMatchesCPythonAt: 'topdown'.
	self assertMatchesCPythonAt: 'bottomup'.
%

category: 'Grail-Tests - Contents'
method: OsWalkTestCase
testTopdownAndBottomUpVisitTheSameDirectories
	"Only the ORDER differs between the two -- if bottom-up dropped or
	duplicated a directory this is where it would show, independently of any
	claim about ordering."

	self assertMatchesCPythonAt: 'same_set_either_way'.
%

category: 'Grail-Tests - Ordering'
method: OsWalkTestCase
testTopdownYieldsAParentBeforeItsChildren
	"The invariant, not the literal sequence: sibling order is the
	filesystem's, and GsFile need not list in the same order as CPython's
	scandir."

	self assertMatchesCPythonAt: 'topdown_parents_first'.
	self assertMatchesCPythonAt: 'topdown_root_first'.
%

category: 'Grail-Tests - Ordering'
method: OsWalkTestCase
testBottomUpYieldsChildrenBeforeTheirParent
	self assertMatchesCPythonAt: 'bottomup_children_first'.
	self assertMatchesCPythonAt: 'bottomup_root_last'.
%

category: 'Grail-Tests - Laziness'
method: OsWalkTestCase
testPruningStopsTheDescent
	"THE test for os.walk being a real generator.  Removing a name from
	dirnames between yields stops the walk descending into it -- which a
	materialised list could not offer, having finished recursing before the
	caller ever saw it.  Every other test here would pass against a list."

	self assertMatchesCPythonAt: 'pruned'.
	self assertMatchesCPythonAt: 'walk_is_its_own_iterator'.
%

category: 'Grail-Tests - Laziness'
method: OsWalkTestCase
testBottomUpPruningHasNoEffect
	"...and the deliberate ASYMMETRY.  Bottom-up fixes its descend list
	before yielding anything, because by the time the caller sees dirnames
	those directories have already been walked.  CPython documents this; an
	implementation that re-read the list after yielding -- the obvious way to
	share one code path with topdown -- would differ here."

	self assertMatchesCPythonAt: 'bottom_up_pruning_has_no_effect'.
%

category: 'Grail-Tests - Symlinks'
method: OsWalkTestCase
testASymlinkToADirectoryIsListedAsOne
	"is_dir FOLLOWS symlinks, so the link belongs in dirnames -- whether it
	is DESCENDED INTO is a separate question, answered by followlinks."

	self assertMatchesCPythonAt: 'link_listed_as_dir'.
%

category: 'Grail-Tests - Symlinks'
method: OsWalkTestCase
testASymlinkedDirectoryIsNotDescendedIntoByDefault
	"The default that keeps os.walk from looping forever on a link back up
	the tree.  Here ``b/lnk'' points at ``a'', so following it silently walks
	a's whole subtree a second time."

	self assertMatchesCPythonAt: 'link_not_followed_by_default'.
	self assertMatchesCPythonAt: 'link_followed_when_asked'.
%

category: 'Grail-Tests - Symlinks'
method: OsWalkTestCase
testIsLinkDistinguishesLinksFromWhatTheyPointAt
	"os.path.islink lstats rather than stats: stat FOLLOWS the link and would
	report the target's type, so every symlink would answer false.  And it
	answers false for what it cannot stat at all rather than raising, which
	is what makes it usable as a plain predicate."

	self assertMatchesCPythonAt: 'islink_on_link'.
	self assertMatchesCPythonAt: 'islink_on_dir'.
	self assertMatchesCPythonAt: 'islink_on_file'.
	self assertMatchesCPythonAt: 'islink_on_missing'.
%

category: 'Grail-Tests - Errors'
method: OsWalkTestCase
testAnUnlistableDirectoryIsSkippedNotYieldedEmpty
	"CPython does not yield a directory it could not list.  Grail's did --
	os.listdir answered [] for a missing path rather than raising, so the
	walk produced one empty triple for a tree that does not exist."

	self assertMatchesCPythonAt: 'missing_top_yields_nothing'.
%

category: 'Grail-Tests - Errors'
method: OsWalkTestCase
testOnErrorSeesTheErrorAndMayAbortTheWalk
	"onerror is how a caller learns about a directory the walk skipped; the
	default is to swallow it, which is what keeps one unreadable directory
	from ending a walk over a thousand readable ones.  Raising from onerror
	aborts -- the exception propagates out of the generator."

	self assertMatchesCPythonAt: 'onerror_is_called'.
	self assertMatchesCPythonAt: 'onerror_may_reraise'.
%

category: 'Grail-Tests - Errors'
method: OsWalkTestCase
testListdirRaisesForAMissingPathAndForAFile
	"Both were SILENT.  GsFile's listing expands a pattern instead of opening
	a directory, so a missing path answered [] and a FILE answered a
	one-element list holding that file -- a directory containing itself,
	which is precisely what a recursive walker follows."

	self assertMatchesCPythonAt: 'listdir_missing'.
	self assertMatchesCPythonAt: 'listdir_on_a_file'.
%

category: 'Grail-Tests - Errors'
method: OsWalkTestCase
testATreeCanBeTornDownWithWalkItself
	"The shape test_reprlib's tearDown uses, and the reason this work
	happened: walk bottom-up, remove the files, then the directories.  A
	symlinked directory is UNLINKED rather than rmdir'd, which is why the
	teardown needs islink as well as walk."

	self assertMatchesCPythonAt: 'teardown_removes_the_tree'.
%
