! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for PickleProtocolTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'PickleProtocolTestCase'
  instVarNames: #( testModule)
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()
%

expectvalue /Class
doit
PickleProtocolTestCase comment:
'CPython wire-format pickle: byte-exactness plus one test per bug found while
building it.

Grail''s pickle used to be a private tagged-blob format whose tag bytes
COLLIDED with real pickle opcodes, so a Grail pickle handed to CPython began
executing as a plausible opcode stream instead of being rejected. It is now a
real stack machine over protocols 0-5.

The byte-level assertions come from an ORACLE generated by the reference
CPython (scripts/gen_pickle_oracle.py -> tests/python/pickle_oracle.py), which
is the only trustworthy spec for a wire format. The named tests below cover the
cases where a plausible implementation silently produced wrong DATA rather than
an error -- the failure mode a serializer must never have.

Fixture: tests/python/pickle_protocol.py.'
%

expectvalue /Class
doit
PickleProtocolTestCase category: 'Grail-SUnit'
%

! ------------------- Remove existing test methods
expectvalue /Metaclass3
doit
PickleProtocolTestCase removeAllMethods: 0.
PickleProtocolTestCase class removeAllMethods: 0.
%

set compile_env: 0

category: 'Grail-Setup'
method: PickleProtocolTestCase
setUp
	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'pickle_oracle' ifAbsent: [].
	mods removeKey: #'pickle_protocol' ifAbsent: [].
	"The oracle is loaded first and by NAME, because the fixture reads it out
	of sys.modules -- it lives under tests/python/ rather than on the module
	search path."
	importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/pickle_oracle.py')
		name: 'pickle_oracle'.
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/pickle_protocol.py')
		name: 'pickle_protocol'.
%

category: 'Grail-Helpers'
method: PickleProtocolTestCase
resultAt: aKey
	^ (testModule @env1:___pyAttrLoad___: #RESULTS) @env1:__getitem__: aKey
%

category: 'Grail-Helpers'
method: PickleProtocolTestCase
assert: pySeq matches: anArray
	"Element-wise comparison: a Python list/tuple is NOT ``='' to a Smalltalk
	Array (atuple(1, 2) ~= anArray(1, 2)), so every sequence assertion here
	goes through this."

	| n |
	n := pySeq @env1:__len__.
	self assert: (n = anArray size)
		description: 'length ' , n printString , ' vs ' , anArray size printString
			, ' (' , pySeq printString , ')'.
	1 to: anArray size do: [:i |
		| got want |
		got := pySeq @env1:__getitem__: i - 1.
		want := anArray at: i.
		self assert: ((got = want) or: [got asString = want asString])
			description: 'element ' , i printString , ': ' , got printString
				, ' vs ' , want printString].
%

category: 'Grail-Helpers'
method: PickleProtocolTestCase
assert: aKey raised: excName
	| r |
	r := self resultAt: aKey.
	self assert: ((r @env1:__getitem__: 0) asString = 'raised')
		description: aKey , ' did not raise (got ' , r printString , ')'.
	self assert: ((r @env1:__getitem__: 1) asString = excName)
		description: aKey , ' raised ' , (r @env1:__getitem__: 1) asString
			, ', expected ' , excName.
	^ (r @env1:__getitem__: 2) asString
%

category: 'Grail-Helpers'
method: PickleProtocolTestCase
emptyList: aKey
	"Assert a fixture entry is an EMPTY list, reporting its contents when not
	(these entries collect failure descriptions)."

	| r |
	r := self resultAt: aKey.
	self assert: ((r @env1:__len__) = 0)
		description: aKey , ' reported: ' , r printString
%

category: 'Grail-Tests - Wire format'
method: PickleProtocolTestCase
testOracleByteExactBothDirections
	"Every value in the oracle must emit bytes IDENTICAL to CPython's, and
	CPython's own bytes must load back to an equal value -- for all six
	protocols.  This is the test that makes the format a contract rather than
	a convention; the named tests below only explain particular failures."

	| r dumpOk loadOk cases expected problems |
	r := self resultAt: 'oracle'.
	dumpOk := r @env1:__getitem__: 0.
	loadOk := r @env1:__getitem__: 1.
	cases := r @env1:__getitem__: 2.
	problems := r @env1:__getitem__: 3.
	self assert: ((problems @env1:__len__) = 0)
		description: 'oracle problems: ' , problems printString.
	"6 protocols per case, both directions."
	expected := cases * 6.
	self assert: (dumpOk = expected)
		description: 'byte-exact emissions: ' , dumpOk printString , ' of '
			, expected printString.
	self assert: (loadOk = expected)
		description: 'CPython bytes loaded: ' , loadOk printString , ' of '
			, expected printString
%

category: 'Grail-Tests - Wire format'
method: PickleProtocolTestCase
testRoundTripAcrossAllProtocols
	"Value AND type survive dumps/loads at every protocol."

	self emptyList: 'roundtrip_all_protocols'
%

category: 'Grail-Tests - Wire format'
method: PickleProtocolTestCase
testProtocolArgumentIsHonoured
	"The previous format accepted ``protocol='' and ignored it, so every
	protocol produced the same bytes.  Protocol 2+ must carry the PROTO
	header, and a bool is the integer 01 under protocol 0 (NEWTRUE only
	arrives in protocol 2)."

	self assert: (self resultAt: 'protocol_distinct')
		description: 'all protocols produced identical bytes'.
	self assert: (self resultAt: 'proto2_header').
	self assert: (self resultAt: 'bool_p0_is_int01')
%

category: 'Grail-Tests - Unpickler'
method: PickleProtocolTestCase
testMarkBasedContainersLoad
	"pop_mark() rebinds the stack, and Python binds ``.append'' BEFORE
	evaluating its argument -- so ``stack.append(tuple(pop_mark()))'' appends
	to the stack just discarded.  Every protocol 0/1 container is built through
	MARK, so this broke tuple, list, dict and frozenset at once while leaving
	the emitted bytes perfectly correct."

	| r |
	r := self resultAt: 'mark_containers'.
	self assert: (r @env1:__len__) equals: 8.
	0 to: 6 by: 4 do: [:base |
		self assert: (r @env1:__getitem__: base) matches: #(1 2).
		self assert: ((r @env1:__getitem__: base + 1) @env1:__len__) equals: 2.
		self assert: ((r @env1:__getitem__: base + 2) @env1:__getitem__: 1) equals: 2.
		self assert: ((r @env1:__getitem__: base + 3) @env1:__len__) equals: 1].
%

category: 'Grail-Tests - Globals'
method: PickleProtocolTestCase
testBuiltinTypesArePicklableByReference
	"set / frozenset / bytearray reduce through their own CLASS, so the class
	must be nameable by reference.  Grail's builtin types carry no __module__,
	and the builtins module exposes only the builtin FUNCTIONS -- getattr(
	builtins, 'iter') resolves but getattr(builtins, 'set') does not -- so
	neither the __module__ shortcut nor a module scan can find them."

	| s f b |
	s := self resultAt: 'set_via_reduce_p2'.
	f := self resultAt: 'frozenset_via_reduce_p2'.
	b := self resultAt: 'bytearray_via_reduce_p2'.
	self assert: (s @env1:__len__) equals: 3.
	self assert: (f @env1:__len__) equals: 2.
	self assert: b matches: #(120 121)
%

category: 'Grail-Tests - Globals'
method: PickleProtocolTestCase
testBytesUseCodecsEncodeBeforeProtocol3
	"Protocols 0-2 have no bytes opcode: CPython carries b'abc' as
	``_codecs.encode('abc', 'latin1')''.  Grail had no _codecs module at all,
	so this could neither match CPython nor LOAD a protocol 0-2 pickle
	containing bytes -- which real CPython produces routinely."

	self assert: (self resultAt: 'bytes_p0_names_codecs')
		description: 'protocol 0 bytes did not go through _codecs.encode'.
	self assert: (self resultAt: 'bytes_p0_roundtrip')
		equals: (ByteArray withAll: #(97 98 99))
%

category: 'Grail-Tests - Globals'
method: PickleProtocolTestCase
testRegistryDoesNotKeyOnTransientIdentity
	"A registry keyed on id() of whatever a bare builtin NAME evaluates to is
	UNSOUND: for a builtin function that is a freshly minted BoundMethod, which
	is collected -- and id() values are REUSED, so the entry later matches an
	unrelated object.  It misnamed ``iter'' as ``str'', so ``iter([])'' became
	``str([])'' and a spent list iterator unpickled as an iterator over the two
	characters of ''[]''.  A corruption that only appears under memory
	pressure, so it is pinned explicitly."

	self assert: ((self resultAt: 'spent_list_iterator') @env1:__len__) equals: 0.
	self assert: (self resultAt: 'iter_not_misnamed') matches: #(7 8)
%

category: 'Grail-Tests - Iterators'
method: PickleProtocolTestCase
testIteratorDirectionSurvives
	"ONE Grail class backs both iter(list) and reversed(list) -- ``type(iter(L))
	is type(reversed(L))'' -- with the direction in a state flag.  Ignoring the
	flag made every FORWARD iterator come back reversed."

	| r |
	r := self resultAt: 'iter_directions'.
	self assert: (r @env1:__getitem__: 'fwd_fresh') matches: #(10 11 12 13).
	self assert: (r @env1:__getitem__: 'fwd_partial') matches: #(11 12 13).
	self assert: (r @env1:__getitem__: 'rev_fresh') matches: #(13 12 11 10).
	self assert: (r @env1:__getitem__: 'rev_partial') matches: #(12 11 10)
%

category: 'Grail-Tests - Iterators'
method: PickleProtocolTestCase
testRangeIteratorSeekIsTypeAware
	"BUILD's state is a resume INDEX, and _getstate() layouts differ per type:
	a list_iterator is (coll, pos, reversed, exhausted) but a range_iterator is
	(start, stop, step, pos).  Reading slot 2 as a direction flag made every
	range(0, 10, 2) iterator look reversed -- step 2 is truthy -- and seeked it
	``stop - pos'' places, i.e. straight to exhaustion."

	| r |
	r := self resultAt: 'range_iterators'.
	self assert: (r @env1:__getitem__: 'fresh') matches: #(0 2 4 6 8).
	self assert: (r @env1:__getitem__: 'partial') matches: #(2 4 6 8).
	self assert: (r @env1:__getitem__: 'plain_step1') matches: #(0 1 2 3)
%

category: 'Grail-Tests - Iterators'
method: PickleProtocolTestCase
testDictViewIteratorsSnapshotTheirOwnView
	"A dict/set view has no stable resume index, so CPython pickles its
	iterator as a LIST of what is left.  That snapshot must come from the view
	the iterator actually walks: ``list(d)'' yields KEYS, so using it for a
	values or items iterator silently rebuilt the wrong data -- values came
	back as [1, 2, 3] instead of ['a', 'b', 'c']."

	| r items |
	r := self resultAt: 'dict_view_iterators'.
	self assert: (r @env1:__getitem__: 'keys') matches: #(1 2 3).
	self assert: (r @env1:__getitem__: 'values') matches: #('a' 'b' 'c').
	items := r @env1:__getitem__: 'items'.
	self assert: (items @env1:__len__) equals: 3.
	self assert: ((items @env1:__getitem__: 0) @env1:__getitem__: 0) equals: 1.
	self assert: ((items @env1:__getitem__: 0) @env1:__getitem__: 1) equals: 'a'
%

category: 'Grail-Tests - Subclasses'
method: PickleProtocolTestCase
testContainerSubclassKeepsTypeAndState
	"Dispatching on isinstance sent a set/frozenset SUBCLASS down the plain
	opcode path, which rebuilds a BASE-class instance -- dropping both the
	class and any instance attributes.  (Exact-type tests are wrong for Grail's
	scalars, where one Python type spans several GemStone classes, but right
	for containers, whose subclasses must keep their identity.)"

	| r |
	r := self resultAt: 'subclass_state'.
	self assert: (r @env1:__getitem__: 0) asString equals: 'MySet'.
	self assert: (r @env1:__getitem__: 1) matches: #(1 2).
	self assert: (r @env1:__getitem__: 2) asString equals: 'kept'.
	self assert: (r @env1:__getitem__: 3) asString equals: 'MyFrozenSet'.
	self assert: (r @env1:__getitem__: 4) matches: #(3).
	self assert: (r @env1:__getitem__: 5) asString equals: 'also'
%

category: 'Grail-Tests - range and slice'
method: PickleProtocolTestCase
testRangeAndSliceReduce
	"Neither was dispatched, so both fell through to the generic reduce path ->
	object.__new__(Interval) -> ``cannot create 'Interval' instances''.  CPython
	reduces each as (cls, (start, stop, step))."

	| sl |
	self assert: (self resultAt: 'range_roundtrip') matches: #(0 3 6 9).
	sl := self resultAt: 'slice_roundtrip'.
	self assert: (sl @env1:__getitem__: 0) equals: 1.
	self assert: (sl @env1:__getitem__: 1) equals: 9.
	self assert: (sl @env1:__getitem__: 2) equals: 2.
	self assert: (self resultAt: 'range_p0_roundtrip') matches: #(0 1 2)
%

category: 'Grail-Tests - range and slice'
method: PickleProtocolTestCase
testFixImportsRewritesNamesNotJustModules
	"fix_imports (protocols 0-2) rewrites NAMES too, for Python 2
	compatibility: ('builtins', 'range') is emitted as ('__builtin__',
	'xrange').  Only the module half was being mapped, and the oracle had no
	range case to catch it."

	self assert: (self resultAt: 'range_p2_names_xrange')
		description: 'protocol 2 did not rewrite range -> xrange'.
	self assert: (self resultAt: 'range_p3_names_range')
		description: 'protocol 3 should use the modern name'
%

category: 'Grail-Tests - range and slice'
method: PickleProtocolTestCase
testRangeAttributesAreValuesNotBoundMethods
	"CPython's range exposes start/stop/step as read-only ATTRIBUTES.  Grail
	answered a BoundMethod, so arithmetic on ``r.start'' silently operated on
	the method object and range's reduction serialized three BoundMethods.

	Asserted through PYTHON attribute access: RangeTestCase already exercised
	``result @env1:start'', a Smalltalk send, which resolves the same either
	way -- which is precisely why the bug survived."

	| attrs |
	attrs := self resultAt: 'range_attrs_are_values'.
	self assert: (attrs @env1:__getitem__: 0) equals: 2.
	self assert: (attrs @env1:__getitem__: 1) equals: 20.
	self assert: (attrs @env1:__getitem__: 2) equals: 3.
	self assert: (self resultAt: 'range_attr_arithmetic') equals: 3
%

category: 'Grail-Tests - Memo'
method: PickleProtocolTestCase
testSharedAndRecursiveReferences
	"The memo must make a shared object round-trip as ONE object (so a mutation
	through either reference is visible through both), and a self-referential
	container must not recurse forever."

	| shared rec |
	shared := self resultAt: 'shared_identity'.
	self assert: (shared @env1:__getitem__: 0)
		description: 'shared list did not round-trip as one object'.
	self assert: ((shared @env1:__getitem__: 1) @env1:__len__) equals: 3.
	rec := self resultAt: 'recursive_list'.
	self assert: (rec @env1:__getitem__: 0) equals: 1.
	self assert: (rec @env1:__getitem__: 1)
		description: 'self-reference was not restored'
%

category: 'Grail-Tests - marshal'
method: PickleProtocolTestCase
testMarshalRidesOnTheSameEncoder
	"marshal's wire format is explicitly an implementation detail in CPython,
	so reusing this encoder is legitimate -- but it must still round-trip its
	documented value types and refuse everything else, since delegating
	unchecked would be strictly MORE permissive than CPython (pickle serializes
	arbitrary objects through __reduce__)."

	| r |
	r := self resultAt: 'marshal_values'.
	self assert: (r @env1:__len__) equals: 11.
	0 to: 10 do: [:i |
		self assert: (r @env1:__getitem__: i)
			description: 'marshal value ' , i printString , ' did not round-trip'].
	self assert: ((self assert: 'marshal_rejects_object' raised: 'ValueError')
		includesString: 'unmarshallable')
%

category: 'Grail-Tests - Bytes'
method: PickleProtocolTestCase
testEveryByteSurvivesEveryProtocol
	"Protocol 0 carries bytes as a str through _codecs.encode, so each byte has
	to survive raw-unicode-escape.  Comparing CHARACTERS against control-char
	literals is unreliable: chr(128) reprs as EMPTY and matched the NUL literal,
	so 0x80 was escaped as \\u0000 and b'0x80' came back as b'0x00' -- silent
	single-byte corruption, at protocol 0 only.  The escape chain now compares
	CODEPOINTS.  Covers all 256 byte values, so a future slip cannot hide in an
	untested corner of the range."

	self emptyList: 'high_bytes_all_protocols'.
	self emptyList: 'high_str_all_protocols'
%

category: 'Grail-Tests - Subclasses'
method: PickleProtocolTestCase
testBytesSubclassKeepsTypeAndState
	"A bytes/bytearray SUBCLASS must keep its class and instance attributes; the
	plain opcode path rebuilds a base bytes/bytearray and drops both.  Same shape
	as the set/frozenset case -- and Grail's bytearray subclasses ByteArray, so
	the exact-type tests have to come before the isinstance one."

	| r |
	r := self resultAt: 'bytes_subclass_state'.
	self assert: (r @env1:__getitem__: 0) asString equals: 'MyBytes'.
	self assert: (r @env1:__getitem__: 1) matches: #(97 98).
	self assert: (r @env1:__getitem__: 2) asString equals: 'kept'.
	self assert: (r @env1:__getitem__: 3) asString equals: 'MyByteArray'.
	self assert: (r @env1:__getitem__: 4) matches: #(99 100).
	self assert: (r @env1:__getitem__: 5) asString equals: 'also'
%
