! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for RaiseSemanticsTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'RaiseSemanticsTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
RaiseSemanticsTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! RaiseSemanticsTestCase
!
! What the ``raise'' statement is actually defined to do.  Four separate holes,
! every one of them QUIET: each produced a plausible exception that was simply
! the wrong one, so nothing crashed and nothing said anything was amiss.
!
! 1. ``raise Cls'' IS ``raise Cls()''.  Grail signalled the CLASS instead
!    whenever nothing was being handled -- the common case, which is why this
!    survived so long -- so a user __init__ never ran and a class whose __init__
!    RAISES reported the class it was trying to build rather than the error that
!    stopped it being built.  A user __new__ never ran on any path, so a __new__
!    answering something that is not an exception at all went unnoticed where
!    CPython owes a TypeError naming both classes.
!
! 2. A CLASS after ``from'' is instantiated too.  ``raise IndexError from
!    KeyError'' left __cause__ holding the KeyError CLASS, so
!    ``isinstance(e.__cause__, KeyError)'' was False and every consumer
!    downstream -- a traceback's ``direct cause'' rendering, contextlib's
!    identity test -- was handed a type where it expected an exception.
!
! 3. A bare ``raise'' re-raises whatever sys.exc_info() points at, and that is a
!    property of the THREAD, not of the source text.  Grail decided it at
!    COMPILE time from the AST, and the two disagree in BOTH directions: a bare
!    raise in a called function saw nothing at all, and one inside a ``finally''
!    re-raised the handler's exception instead of the one in flight through it.
!
! 4. __context__ belongs on EVERY exception raised while another is handled, not
!    only on ones a ``raise'' statement produced.  A NameError from an undefined
!    name, an AttributeError from a missing attribute, anything raised inside a
!    context manager's __exit__ -- all arrived with __context__ None, and a
!    traceback with no context loses the ``During handling of the above
!    exception'' half, which is the part that says WHY the second one happened.
!
! THE ``must keep working'' TESTS ARE NOT FILLER.  Each fix moved an ordinary
! raise onto a different path: ``raise KeyError'' now consults two class-chain
! probes before taking the fast signal, a bare re-raise now goes through a
! runtime lookup, and every hand-built runtime exception now runs the chaining
! check.  Identity (``except E: raise'' must re-raise the SAME object), args,
! and ``from None'' are what would break if any of that were over-applied.
!
! NOT COVERED: the traceback OBJECT.  types.TracebackType is still a stub class,
! so ``isinstance(e.__traceback__, types.TracebackType)'' is False and tb_next
! cannot be assigned -- a different subsystem from the raise statement, and the
! four test_raise tests that need it are left failing rather than half-fixed.
!
! Drives tests/python/raise_semantics.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
RaiseSemanticsTestCase removeAllMethods.
RaiseSemanticsTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: RaiseSemanticsTestCase
setUp
	"Reload tests/python/raise_semantics.py fresh each test -- every entry in
	``r'' is a measurement taken while a particular exception was in flight and
	cannot be recomputed afterwards."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'raise_semantics' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/raise_semantics.py')
		name: 'raise_semantics'.
%

category: 'Grail-Private'
method: RaiseSemanticsTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Raising A Class'
method: RaiseSemanticsTestCase
testRaisingAClassRunsItsInit
	"``raise Cls'' is ``raise Cls()'', so an __init__ that raises surfaces ITS
	exception.  Grail reported Cls -- the exception the user was trying to
	construct -- and only when nothing happened to be in flight, because the
	other path already built the instance."

	self assertMatchesCPythonAt: 'bare_class_init_raises'.
	self assertMatchesCPythonAt: 'handled_class_init_raises'.
%

category: 'Grail-Tests - Raising A Class'
method: RaiseSemanticsTestCase
testRaisingAClassRunsItsNewAndChecksTheResult
	"A user __new__ can SUCCEED and answer something that is not an exception,
	which is the case allocation cannot detect however carefully it is done --
	only CALLING the class reveals it.  CPython's message names both the class
	called and the class it wrongly answered."

	self assertMatchesCPythonAt: 'bare_class_new_junk'.
	self assertMatchesCPythonAt: 'handled_class_new_junk'.
%

category: 'Grail-Tests - Raising A Class'
method: RaiseSemanticsTestCase
testTheCallFormGetsTheOtherMessage
	"``raise Cls()'' evaluates the call first, so what fails is the VALUE, and
	CPython says ``exceptions must derive from BaseException'' rather than
	``calling ... should have returned''.  Two messages for one mistake, and
	which one appears says where it was noticed."

	self assertMatchesCPythonAt: 'call_form_new_junk'.
%

category: 'Grail-Tests - The from Clause'
method: RaiseSemanticsTestCase
testAClassCauseIsInstantiated
	"``raise IndexError from KeyError'' must leave __cause__ holding a KeyError
	INSTANCE.  Grail stored the class, and nothing complained at the point the
	``from'' was written -- the type only surfaced wherever someone treated
	__cause__ as an exception."

	self assertMatchesCPythonAt: 'class_cause'.
%

category: 'Grail-Tests - The from Clause'
method: RaiseSemanticsTestCase
testAFailingCauseConstructionPropagates
	"Instantiating the cause is a real construction, with the same two failure
	modes as the raised operand: an __init__ that raises reports itself, and a
	__new__ answering a non-exception is a TypeError."

	self assertMatchesCPythonAt: 'cause_init_raises'.
	self assertMatchesCPythonAt: 'cause_new_junk'.
%

category: 'Grail-Tests - Bare Raise'
method: RaiseSemanticsTestCase
testABareRaiseInACalleeSeesItsCallersException
	"Handling is a property of the THREAD.  A bare raise inside a function
	called from an except block re-raises that block's exception, even though
	the text of the function contains no handler at all -- which is exactly what
	a compile-time decision cannot see."

	self assertMatchesCPythonAt: 'nested_reraise'.
%

category: 'Grail-Tests - Bare Raise'
method: RaiseSemanticsTestCase
testABareRaiseInAFinallyTakesTheExceptionInFlight
	"The mirror-image error, and the reason the fix is a runtime lookup rather
	than a wider lexical search: here the raise IS inside an except handler
	textually, and the right answer is still not that handler's exception but
	the one passing through the finally."

	self assertMatchesCPythonAt: 'finally_reraise'.
%

category: 'Grail-Tests - Bare Raise'
method: RaiseSemanticsTestCase
testABareRaiseWithNothingActiveIsARuntimeError
	"Including the exact wording: CPython spells it ``reraise'', unhyphenated,
	and Grail spelled it ``re-raise''.  test_raise's own check matches only the
	``No active exception'' prefix, so nothing in the corpus caught it."

	self assertMatchesCPythonAt: 'reraise_nothing_active'.
%

category: 'Grail-Tests - Implicit Context'
method: RaiseSemanticsTestCase
testTheRuntimesOwnExceptionsAreChainedToo
	"__context__ was applied only on the paths a ``raise'' STATEMENT takes.  An
	undefined name and a missing attribute are raised by the runtime on the
	user's behalf and got nothing, so the report lost the half that says why."

	self assertMatchesCPythonAt: 'context_of_name_error'.
	self assertMatchesCPythonAt: 'context_of_attribute_error'.
%

category: 'Grail-Tests - Implicit Context'
method: RaiseSemanticsTestCase
testAnExceptionInsideExitIsChainedToTheOneItWasCalledAbout
	"__exit__ runs ON BEHALF of the in-flight exception, so that exception is
	what sys.exc_info() reports while it runs -- and therefore what anything it
	raises is chained to."

	self assertMatchesCPythonAt: 'context_inside_exit'.
%

category: 'Grail-Tests - Still Legal'
method: RaiseSemanticsTestCase
testOrdinaryRaisesAreUnchanged
	"THE TESTS THAT MATTER MOST HERE.  Every fix above moved an ordinary raise
	onto a different path -- ``raise KeyError'' now consults two class-chain
	probes before the fast signal, and every hand-built runtime exception now
	runs the chaining check.  Args, message and instance-ness are what a
	mis-routed fast path would lose."

	self assertMatchesCPythonAt: 'plain_class'.
	self assertMatchesCPythonAt: 'plain_call'.
	self assertMatchesCPythonAt: 'user_init_runs'.
%

category: 'Grail-Tests - Still Legal'
method: RaiseSemanticsTestCase
testIdentityAndSuppressionSurvive
	"``except E: raise'' must re-raise the SAME object -- contextlib's
	@contextmanager is ``if exc is not value: raise'', so a copy breaks every
	one of them -- and ``from None'' must still record the context while
	suppressing its rendering."

	self assertMatchesCPythonAt: 'reraise_same_object'.
	self assertMatchesCPythonAt: 'instance_cause'.
	self assertMatchesCPythonAt: 'from_none'.
%
