! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ReprAndRangeTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ReprAndRangeTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
ReprAndRangeTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! ReprAndRangeTestCase
!
! TWO FIXES, related only in that reprlib's own test suite surfaced both.
!
! 1. reprlib was a 132-line hand-written SUBSET of CPython's 231-line module and
!    diverged in a dozen visible ways at once: the nesting depth cut off one level
!    early, frozensets truncated differently, ``indent='' was missing entirely,
!    Repr() accepted no keyword arguments, and repr_instance was not used as the
!    fallback it is meant to be.  Every one of those is a detail of a
!    well-specified algorithm, so the module is now VENDORED from CPython 3.14.6
!    -- smaller to maintain than a parallel implementation, and correct by
!    construction.  ONE adaptation, and it is the deviation the old file already
!    documented: no _thread module, so recursive_repr's cycle key is the object
!    identity alone rather than (id, thread-ident).
!
! 2. ``repr(range(...))'' PRINTED A DIFFERENT RANGE than the one being printed.
!    Two independent bugs in one method:
!
!      * it abbreviated ``range(0, N, 1)'' to ``range(N)'', but CPython never
!        abbreviates -- repr(range) is the normalised three-field form, not the
!        constructor call that happened to be written;
!      * it computed the exclusive stop as ``to + 1'', which is the
!        inclusive-to-exclusive conversion for a POSITIVE step only.  GemStone's
!        Interval keeps an inclusive bound, so a negative step needs ``to - 1''
!        and ``range(5, 0, -1)'' printed as ``range(5, 2, -1)''.
!
!    The second is the one worth the fixture.  The CONTENTS were right
!    ([5, 4, 3, 2, 1]) and .start / .stop / .step all reported the right values,
!    so the OBJECT was correct and only its printed form lied -- which is exactly
!    the kind of defect that survives review, and why testTheReprNamesThisRange
!    checks the round trip rather than the string.  The repr now reads the ``stop''
!    ACCESSOR instead of recomputing the conversion, so the two cannot disagree
!    again.
!
! ONE GRAIL GAP THIS SLICE DOES NOT TOUCH, recorded because it cost real time to
! rule out.  ``@reprlib.recursive_repr()'' written as a DECORATOR on a __repr__
! never takes effect: Grail drops non-declarative method decorators, so the method
! stays undecorated and the repr recurses until the stack runs out.  That looks
! exactly like a broken recursive_repr and is not one -- applied explicitly
! (``__repr__ = reprlib.recursive_repr()(f)'') it short-circuits correctly, which
! is what the fixture and tests/python/pkg_scaffolding/reprlib_recursive.py both
! do, and why.  What was measured and ruled out on the way: tuple hashing, set
! membership and id() stability all behave correctly, and closure state over a
! class-body method behaves exactly as CPython.
!
! A SEPARATE trap in the vendored source, worth its own note: CPython's reprlib
! opens with ``from _thread import get_ident''.  In Grail that import SUCCEEDS and
! binds an INT -- _thread.get_ident is a module METHOD, so importing the name
! performs the getter -- and ``get_ident()'' then raises ``TypeError:
! 'SmallInteger' object is not callable''.  A try/except ImportError does not help
! because nothing raises, so the shim is unconditional.
!
! Drives tests/python/repr_and_range.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6.  test.test_reprlib goes 25 broken -> 15.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
ReprAndRangeTestCase removeAllMethods.
ReprAndRangeTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: ReprAndRangeTestCase
setUp
	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'repr_and_range' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/repr_and_range.py')
		name: 'repr_and_range'.
%

category: 'Grail-Private'
method: ReprAndRangeTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - Range Repr'
method: ReprAndRangeTestCase
testTheReprAlwaysShowsStartAndStop
	"CPython never abbreviates: ``range(1)'' prints as ``range(0, 1)''.  The repr
	is the normalised three-field form, not the constructor call that was written."

	self assertMatchesCPythonAt: 'range_one_arg'.
	self assertMatchesCPythonAt: 'range_two_arg'.
	self assertMatchesCPythonAt: 'range_empty'.
	self assertMatchesCPythonAt: 'range_step'.
%

category: 'Grail-Tests - Range Repr'
method: ReprAndRangeTestCase
testANegativeStepReportsTheRightStop
	"THE TEST THIS EXISTS FOR.  ``to + 1'' is the inclusive-to-exclusive
	conversion for a POSITIVE step only, so ``range(5, 0, -1)'' printed as
	``range(5, 2, -1)'' -- a range with different contents from the one being
	printed."

	self assertMatchesCPythonAt: 'range_negative_step'.
%

category: 'Grail-Tests - Range Repr'
method: ReprAndRangeTestCase
testTheReprNamesThisRange
	"The property the repr exists for, checked as a ROUND TRIP rather than a
	string comparison: eval(repr(r)) must rebuild a range with the same contents
	and the same start/stop/step.  A repr that merely looks plausible passes a
	string check and fails this one."

	self assertMatchesCPythonAt: 'round_trips'.
	self assertMatchesCPythonAt: 'repr_agrees_with_attributes'.
%

category: 'Grail-Tests - reprlib'
method: ReprAndRangeTestCase
testTheSizeLimitsMatchCPython
	"Nesting depth, list truncation and string truncation -- three of the places
	the hand-written subset drifted."

	self assertMatchesCPythonAt: 'nesting_depth'.
	self assertMatchesCPythonAt: 'long_list'.
	self assertMatchesCPythonAt: 'long_string'.
	self assertMatchesCPythonAt: 'deep_dict'.
%

category: 'Grail-Tests - reprlib'
method: ReprAndRangeTestCase
testTheFeaturesTheSubsetLacked
	"Repr() takes its limits as KEYWORD arguments and supports ``indent='', which
	the subset had no notion of at all -- including the ValueError a negative
	indent must raise."

	self assertMatchesCPythonAt: 'keyword_construction'.
	self assertMatchesCPythonAt: 'indent_feature'.
	self assertMatchesCPythonAt: 'invalid_indent'.
%

category: 'Grail-Tests - reprlib'
method: ReprAndRangeTestCase
testRecursiveReprShortCircuitsACycle
	"The wrapper is applied EXPLICITLY in the fixture rather than with @-syntax --
	see this class's comment: a method decorator is dropped by Grail, which looks
	like a broken recursive_repr and is not one."

	self assertMatchesCPythonAt: 'recursive_repr_guard'.
%
