! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for StaticmethodOverridesBaseMethodTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'StaticmethodOverridesBaseMethodTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
StaticmethodOverridesBaseMethodTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! StaticmethodOverridesBaseMethodTestCase
!
! A @staticmethod or @classmethod in a subclass overrides an ordinary method of
! its base: the base's own self-sends reach it (Behavior >>
! ___grailInstallClassSideForwarders___), and a read off the class answers it
! rather than the base's method (___grailClassSideDefIsNearer___:family:).
! test_pickle's test_custom_find_class is the first shape.
!
! Drives tests/python/staticmethod_overrides_base_method.py, whose EXPECTED
! table was generated by RUNNING CPython 3.14.6 and which self-verifies against
! it in scripts/check_python_fixtures.sh.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
StaticmethodOverridesBaseMethodTestCase removeAllMethods.
StaticmethodOverridesBaseMethodTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: StaticmethodOverridesBaseMethodTestCase
setUp
	"Reload tests/python/staticmethod_overrides_base_method.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'staticmethod_overrides_base_method' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/staticmethod_overrides_base_method.py')
		name: 'staticmethod_overrides_base_method'.
%

category: 'Grail-Private'
method: StaticmethodOverridesBaseMethodTestCase
assertMatchesCPythonAt: key
	"Every recorded answer is already a repr string, so the two compare as text."

	| actual expected |
	actual := (testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key.
	expected := (testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key.
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testStaticmethodOverridesBaseSelfSend
	"The base's ``self.find_class(m, n)'' -- positional, keyword and via
	getattr -- runs the subclass's @staticmethod; so do class and instance
	reads.  Before: the base's method, and a TypeError from the class read."

	self assertMatchesCPythonAt: 'self_send_Static'.
	self assertMatchesCPythonAt: 'zero_arg'.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testClassmethodOverridesBaseSelfSend
	"The same for @classmethod, receiving the class as cls."

	self assertMatchesCPythonAt: 'self_send_Klass'.
	self assertMatchesCPythonAt: 'self_send_OverStatic'.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testInheritedAndDeeperOverrides
	"A subclass of the overriding class inherits the forwarder; an override two
	levels below the base gets its own."

	self assertMatchesCPythonAt: 'self_send_StaticChild'.
	self assertMatchesCPythonAt: 'self_send_DeepStatic'.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testOrdinaryOverrideAndBaseUnchanged
	"A plain def override and the base itself behave as before."

	self assertMatchesCPythonAt: 'self_send_Plain'.
	self assertMatchesCPythonAt: 'base_untouched'.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testDictHoldsTheDescriptor
	"``Sub.__dict__['find_class']'' is the staticmethod / classmethod object --
	including for a def that takes arguments, which the __dict__ view missed."

	self assertMatchesCPythonAt: 'dict_kinds'.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testUnpicklerFindClass
	"test_pickle's own shape: _Unpickler.load_global calls self.find_class."

	self assertMatchesCPythonAt: 'unpickler'.
%

category: 'Grail-Tests'
method: StaticmethodOverridesBaseMethodTestCase
testRedefinitionDropsTheForwarder
	"Redefining the class without the decorator leaves no forwarder behind."

	self assertMatchesCPythonAt: 'redefined'.
%
