! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for StructModuleTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'StructModuleTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
StructModuleTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! StructModuleTestCase
!
! The struct module had TWO LAYOUT MODES collapsed into one.  An unprefixed
! format like ``ci'' is NATIVE: C sizes, C alignment padding.  A prefixed one
! (``=ci'', ``<ci'') is STANDARD: fixed sizes, tightly packed.  Grail
! implemented only the standard sizes and applied them to native formats too,
! so calcsize('ci') answered 5 where CPython says 8, native long came back 4
! bytes instead of 8, and every unprefixed mixed-type format packed to the
! wrong LAYOUT.  Since the unprefixed form is what most callers write, that was
! the common case rather than a corner.
!
! Most of what these tests pin is SILENTLY WRONG rather than loudly broken,
! which is why they exist as assertions instead of being left to the CPython
! suite:
!
!   * struct.error did not exist.  ``except struct.error:'' raised
!     AttributeError from the except clause itself, while ``except ValueError:''
!     CAUGHT -- and CPython's struct.error subclasses Exception directly, so
!     both halves were wrong at once.
!   * pack('B', 256) TRUNCATED to b'\x00' instead of raising, so a round trip
!     returned a different number than it was handed.
!   * pack('f', x) truncated the mantissa instead of rounding to nearest, so a
!     float round trip returned a neighbouring float.  CPython's own
!     test_705836 exists for exactly this carry-into-the-exponent case.
!   * unpack('?', ...) parsed as ``= (0 not)'' -- unary binds tighter than
!     binary in Smalltalk -- and raised an uncatchable MessageNotUnderstood on
!     the SmallInteger 0 for EVERY bool unpack.
!   * NaN missed the inf/NaN check (every comparison with NaN is false), fell
!     into the finite path, and raised OverflowError; decoding collapsed NaN to
!     infinity, so the round trip changed the value.
!
! Drives tests/python/struct_module.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before being committed.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
StructModuleTestCase removeAllMethods.
StructModuleTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: StructModuleTestCase
setUp
	"Reload tests/python/struct_module.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'struct_module' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/struct_module.py')
		name: 'struct_module'.
%

category: 'Grail-Private'
method: StructModuleTestCase
assertMatchesCPythonAt: key
	self
		assert: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key) asString
		equals: ((testModule @env1:___pyAttrLoad___: #EXPECTED)
			@env1:__getitem__: key) asString
%

category: 'Grail-Tests - struct.error'
method: StructModuleTestCase
testErrorIsItsOwnClassAndNotAValueError
	"struct.error subclasses Exception DIRECTLY.  Raising ValueError
	instead got the hierarchy wrong in BOTH directions: the name did not
	exist to be caught, and an unrelated ``except ValueError'' caught
	what CPython would let propagate."

	self assertMatchesCPythonAt: 'error_name'.
	self assertMatchesCPythonAt: 'error_module'.
	self assertMatchesCPythonAt: 'error_is_exception'.
	self assertMatchesCPythonAt: 'error_is_not_valueerror'.
	self assertMatchesCPythonAt: 'caught_by_struct_error'.
	self assertMatchesCPythonAt: 'not_caught_as_valueerror'.
%

category: 'Grail-Tests - Layout'
method: StructModuleTestCase
testNativeModePadsAndStandardModeDoesNot
	"The default (unprefixed) mode is the PADDING one, which is the
	surprising half: calcsize('ci') is 8, not 5."

	self assertMatchesCPythonAt: 'native_ci'.
	self assertMatchesCPythonAt: 'standard_ci'.
	self assertMatchesCPythonAt: 'native_pack_ci'.
	self assertMatchesCPythonAt: 'standard_pack_ci'.
%

category: 'Grail-Tests - Layout'
method: StructModuleTestCase
testThereIsNoTrailingPaddingButAZeroCountStillAligns
	"Unlike a C struct, the total is NOT rounded up to the widest
	member -- calcsize('@qc') is 9.  A zero repeat count still aligns,
	which is the only reason to write ``0i''."

	self assertMatchesCPythonAt: 'no_trailing_pad'.
	self assertMatchesCPythonAt: 'zero_count_aligns'.
%

category: 'Grail-Tests - Layout'
method: StructModuleTestCase
testNativeLongIsEightBytesAndStandardLongIsFour
	"l/L are the codes whose SIZE depends on the mode, and native is the
	default -- so a bare 'l' is 8 bytes, not 4."

	self assertMatchesCPythonAt: 'native_long'.
	self assertMatchesCPythonAt: 'standard_long'.
%

category: 'Grail-Tests - Layout'
method: StructModuleTestCase
testNAndCapitalNAreNativeOnly
	"n/N exist natively and are an ERROR under a standard prefix, rather
	than silently taking some other size."

	self assertMatchesCPythonAt: 'native_n'.
	self assertMatchesCPythonAt: 'standard_n'.
	self assertMatchesCPythonAt: 'native_n_roundtrip'.
%

category: 'Grail-Tests - Range'
method: StructModuleTestCase
testOutOfRangeIntegersRaiseInsteadOfTruncating
	"pack('B', 256) answered b'\\x00' before: the round trip returned a
	different number with nothing to notice."

	self assertMatchesCPythonAt: 'byte_256'.
	self assertMatchesCPythonAt: 'byte_neg'.
	self assertMatchesCPythonAt: 'short_big'.
%

category: 'Grail-Tests - Range'
method: StructModuleTestCase
testAFloatIsNotAnIntegerButABoolIs
	"CPython rejects 1.0 for an integer code and accepts True."

	self assertMatchesCPythonAt: 'float_for_int'.
	self assertMatchesCPythonAt: 'bool_for_int'.
%

category: 'Grail-Tests - Bool'
method: StructModuleTestCase
testBoolPacksTruthinessAndUnpacksAnyNonZeroByte
	"Unpacking a bool raised an uncatchable MessageNotUnderstood for
	every input -- ``= 0 not'' sent #not to the SmallInteger 0, because
	unary binds tighter than binary."

	self assertMatchesCPythonAt: 'bool_pack_list'.
	self assertMatchesCPythonAt: 'bool_pack_three'.
	self assertMatchesCPythonAt: 'bool_unpack_one'.
	self assertMatchesCPythonAt: 'bool_unpack_seven'.
	self assertMatchesCPythonAt: 'bool_unpack_zero'.
%

category: 'Grail-Tests - Float'
method: StructModuleTestCase
testSinglePrecisionRoundsToNearestRatherThanTruncating
	"The carry out of the discarded mantissa bits must propagate into
	the exponent.  Truncating returned the neighbouring float, so the
	round trip silently changed the value -- CPython's test_705836
	exists for precisely this."

	self assertMatchesCPythonAt: 'float_rounds_to_nearest'.
%

category: 'Grail-Tests - Float'
method: StructModuleTestCase
testHalfFloatRoundTrips
	"``e'' was rejected outright as a bad format char."

	self assertMatchesCPythonAt: 'half_size'.
	self assertMatchesCPythonAt: 'half_round_trip'.
	self assertMatchesCPythonAt: 'half_precision'.
	self assertMatchesCPythonAt: 'half_overflow'.
%

category: 'Grail-Tests - Float'
method: StructModuleTestCase
testNaNSurvivesAsNaNAndInfinityKeepsItsSign
	"NaN missed an ``abs > fmax'' check -- every comparison involving
	NaN is false -- so it looked finite with an exponent of 1024 and
	raised OverflowError.  Decoding collapsed NaN to infinity, turning a
	round trip into a value change rather than an error."

	self assertMatchesCPythonAt: 'nan_round_trip'.
	self assertMatchesCPythonAt: 'inf_round_trip'.
	self assertMatchesCPythonAt: 'inf_sign_kept'.
%

category: 'Grail-Tests - Strings'
method: StructModuleTestCase
testPascalStringsStoreALengthByteAndTruncate
	"``p'' was unimplemented.  An over-long value truncates rather than
	raising, and the STORED length follows the truncation."

	self assertMatchesCPythonAt: 'pascal_pack'.
	self assertMatchesCPythonAt: 'pascal_unpack'.
	self assertMatchesCPythonAt: 'pascal_truncates'.
%

category: 'Grail-Tests - Buffer API'
method: StructModuleTestCase
testIterUnpackWalksFixedSizeRecords
	"A ragged buffer and a zero-length record are BOTH errors; the zero
	case would otherwise loop forever."

	self assertMatchesCPythonAt: 'iter_unpack'.
	self assertMatchesCPythonAt: 'iter_unpack_ragged'.
	self assertMatchesCPythonAt: 'iter_unpack_empty_fmt'.
%

category: 'Grail-Tests - Buffer API'
method: StructModuleTestCase
testPackIntoWritesInPlaceAndRejectsAnImmutableTarget
	"pack_into did not exist at all.  bytes is immutable and must be a
	TypeError; a bogus OFFSET is also a TypeError, NOT a struct.error."

	self assertMatchesCPythonAt: 'pack_into'.
	self assertMatchesCPythonAt: 'pack_into_immutable'.
	self assertMatchesCPythonAt: 'pack_into_overflow'.
	self assertMatchesCPythonAt: 'pack_into_bad_offset_kind'.
%

category: 'Grail-Tests - Buffer API'
method: StructModuleTestCase
testUnpackFromAcceptsAnOffsetIncludingANegativeOne
	"A negative offset counts back from the end, as everywhere else in
	Python, and running off either end is an error rather than a read of
	whatever happened to be there."

	self assertMatchesCPythonAt: 'unpack_from'.
	self assertMatchesCPythonAt: 'unpack_from_offset'.
	self assertMatchesCPythonAt: 'unpack_from_negative'.
	self assertMatchesCPythonAt: 'unpack_from_short'.
	self assertMatchesCPythonAt: 'unpack_from_far_neg'.
%

category: 'Grail-Tests - Buffer API'
method: StructModuleTestCase
testUnpackRequiresAnExactBufferAndARealBytesLike
	"A LONG buffer used to unpack fine and silently drop the tail; a
	non-buffer raised a raw Smalltalk MessageNotUnderstood, which no
	Python except can catch."

	self assertMatchesCPythonAt: 'unpack_exact'.
	self assertMatchesCPythonAt: 'unpack_too_long'.
	self assertMatchesCPythonAt: 'unpack_not_bytes'.
%

category: 'Grail-Tests - Format Strings'
method: StructModuleTestCase
testAFormatMayBeBytesButMayNotContainANull
	"#asString on a ByteArray answers its PRINT string, so a bytes
	format used to be parsed as the literal text 'aByteArray' -- every
	character bad, and Struct.format reporting that back."

	self assertMatchesCPythonAt: 'bytes_format'.
	self assertMatchesCPythonAt: 'bytes_format_type'.
	self assertMatchesCPythonAt: 'embedded_null'.
	self assertMatchesCPythonAt: 'repeat_no_code'.
%

category: 'Grail-Tests - Struct'
method: StructModuleTestCase
testStructReprAndReinitialization
	"__init__ is RE-CALLABLE in CPython: it repoints an existing Struct
	at a new format."

	self assertMatchesCPythonAt: 'struct_repr'.
	self assertMatchesCPythonAt: 'struct_reinit_format'.
	self assertMatchesCPythonAt: 'struct_reinit_pack'.
%

category: 'Grail-Tests - Struct'
method: StructModuleTestCase
testStructMirrorsTheModuleBufferAPI
	"Struct grew the same entry points as the module, including the
	keyword form of unpack_from's offset."

	self assertMatchesCPythonAt: 'struct_iter_unpack'.
	self assertMatchesCPythonAt: 'struct_unpack_from_kw'.
%
