! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for SystemExitTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'SystemExitTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%
expectvalue /Class
doit
SystemExitTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! SystemExitTestCase - Tests for Python SystemExit
!
! ``code'' -- THE EXIT STATUS, AND WHERE IT COMES FROM.
!
! CPython gives SystemExit exactly one attribute of its own, and sys.exit()'s
! whole contract is expressed through it: an int is the process status, None and
! 0 both mean success, and a str is a message for stderr.  Anything that catches
! SystemExit to decide what happens next reads it -- ``sys.exit(main())''
! wrappers, unittest's runner, and test_zipapp's four CLI tests, which assert on
! ``cm.exception.code'' directly.
!
! Grail had the attribute NOWHERE: ``SystemExit(1).code'' raised AttributeError.
! And the class DECLARED a ``code'' instVar that nothing ever assigned -- so the
! slot could only ever have read nil, and the declaration made the hole look
! filled.  Both halves are gone: the instVar is removed and ``code'' is DERIVED
! from args, by CPython's SystemExit_init rule --
!
!     len(args) == 0  ->  None            (CPython never assigns the slot)
!     len(args) == 1  ->  args[0]
!     len(args) >  1  ->  args            (the whole tuple)
!
! -- which is what makes it hold for every construction path at once.
! ``SystemExit(3)'', ``raise SystemExit(3)'' and ``sys.exit(3)'' build the
! instance three different ways and all three set args; none of them would have
! set an instVar.  StopIteration >> value derives ``value'' the same way, for the
! same reason.
!
! WHAT THE LENGTH TEST BUYS, and why the value cannot be tested instead:
! ``SystemExit(None)'' has args ``(None,)'' and ``SystemExit()'' has args ``()'',
! and both have code None.  Same code, different args -- so ``code is None'' and
! ``no argument was given'' are not the same question, and a derivation that read
! args[0] with a nil-as-absent default would answer the second one.
!
! THE BARE ``sys.exit()'' WAS ALSO WRONG, and is fixed here.  Grail signalled
! ``SystemExit ___signal___: 0'', filling args with ``(0,)'' and making code 0;
! CPython passes NO constructor argument, so args is empty and code is None.
! Both mean success to a shell, so nothing could see the difference until code
! existed to be read -- and then ``if e.code is None'', the documented test for
! "exited without a status", took the wrong arm.  It also put a spurious 0 in the
! repr.  Fixing code without fixing this would have shipped the new attribute
! reading the wrong value from its commonest producer.
!
! ``code'' is a plain writable member in CPython (T_OBJECT), and needs no setter
! here: ``e.code = 3'' lands in dynamic-instVar storage, which ___pyAttrLoad___
! probes (Phase B) BEFORE the value-attribute hook, so the store shadows the
! derivation and -- as in CPython -- leaves args alone.
!
! Drives tests/python/system_exit_code.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and self-verifies against it.  Unblocks test_zipapp's
! four ``cm.exception.code'' assertions (that module is still IMPORTERROR for a
! missing zipapp, so they do not score yet).
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
SystemExitTestCase removeAllMethods.
SystemExitTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: SystemExitTestCase
setUp
	"Reload tests/python/system_exit_code.py fresh each test: the module body
	runs every probe at import, so each test reads results produced by its own
	import rather than by whichever test happened to run first."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'system_exit_code' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/system_exit_code.py')
		name: 'system_exit_code'.
%

category: 'Grail-Private'
method: SystemExitTestCase
assertMatchesCPythonAt: key
	"Compare Grail's result for one fixture probe against the CPython 3.14.6
	value recorded in the fixture, by repr on both sides -- so a tuple, a str
	and an int are all compared as what they print as, and ``0'' does not match
	``False''."

	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - code Is Derived From args'
method: SystemExitTestCase
testCodeIsTheSingleConstructorArgument
	"THE TEST THIS EXISTS FOR.  ``SystemExit(3).code'' raised AttributeError --
	the attribute was absent, not merely unset -- so every reader of an exit
	status got an error instead of a status.  A str code is a MESSAGE rather
	than a number and is kept verbatim."

	self assertMatchesCPythonAt: 'one_argument'.
	self assertMatchesCPythonAt: 'string_argument'.
%

category: 'Grail-Tests - code Is Derived From args'
method: SystemExitTestCase
testNoConstructorArgumentMeansNone
	"CPython's SystemExit_init returns early on an empty args tuple, leaving the
	member unassigned -- which reads as None.  ``raise SystemExit'' with no call
	at all takes the same path."

	self assertMatchesCPythonAt: 'no_argument'.
	self assertMatchesCPythonAt: 'raise_bare_class'.
%

category: 'Grail-Tests - code Is Derived From args'
method: SystemExitTestCase
testAnExplicitNoneIsNotTheSameAsNoArgument
	"THE CASE THAT PINS THE RULE TO THE LENGTH OF args RATHER THAN ITS VALUE.
	``SystemExit(None)'' has args ``(None,)'' while ``SystemExit()'' has args
	``()'', and both have code None -- so a derivation cannot decide by looking
	at args[0] and treating a missing value as absent.  0 is the other half:
	``code == 0'' with ``code is None'' false, because 0 and None both mean
	success and are still different objects."

	self assertMatchesCPythonAt: 'explicit_none_argument'.
	self assertMatchesCPythonAt: 'zero_is_not_none'.
%

category: 'Grail-Tests - code Is Derived From args'
method: SystemExitTestCase
testMoreThanOneArgumentMakesCodeTheWholeTuple
	"CPython slices the whole args tuple in the size > 1 branch, so code IS args
	-- not args[0], and not a TypeError."

	self assertMatchesCPythonAt: 'two_arguments'.
	self assertMatchesCPythonAt: 'three_arguments'.
%

category: 'Grail-Tests - Every Construction Path Agrees'
method: SystemExitTestCase
testSysExitWithAStatusCarriesIt
	"sys.exit() is the commonest producer, and it builds the instance by a route
	of its own -- so it has to be checked separately from the constructor."

	self assertMatchesCPythonAt: 'sys_exit_status'.
	self assertMatchesCPythonAt: 'sys_exit_zero'.
	self assertMatchesCPythonAt: 'sys_exit_message'.
%

category: 'Grail-Tests - Every Construction Path Agrees'
method: SystemExitTestCase
testBareSysExitPassesNoArgumentAtAll
	"THE SECOND BUG.  Grail signalled ``___signal___: 0'', so args was ``(0,)''
	and code 0 where CPython gives ``()'' and None.  Invisible while code did
	not exist -- 0 and None are the same exit status to a shell -- and wrong the
	moment anything read it, because ``e.code is None'' is how ``exited without a
	status'' is spelled."

	self assertMatchesCPythonAt: 'sys_exit_bare'.
%

category: 'Grail-Tests - Every Construction Path Agrees'
method: SystemExitTestCase
testTheRaiseStatementAgreesWithTheConstructor
	"``raise SystemExit(7)'' goes through ___signalNew___:kw:, a third path,
	which must produce the same args -- and therefore the same code -- as the
	other two."

	self assertMatchesCPythonAt: 'raise_statement'.
%

category: 'Grail-Tests - code Is Writable'
method: SystemExitTestCase
testAssigningCodeShadowsTheDerivationAndLeavesArgsAlone
	"CPython's ``code'' is a plain writable member, so ``e.code = 99'' is an
	ordinary store that does NOT rewrite args.  Storing None must read back as
	None rather than falling through to the derivation, which would answer 1 --
	the guard that the store is genuinely consulted first and not merely
	non-nil."

	self assertMatchesCPythonAt: 'assignment_wins'.
	self assertMatchesCPythonAt: 'assignment_of_none'.
	self assertMatchesCPythonAt: 'assignment_without_args'.
%

category: 'Grail-Tests - Inheritance'
method: SystemExitTestCase
testSubclassesInheritCode
	"A subclass gets code for free precisely BECAUSE it follows args: a plain
	subclass sets args through the inherited __init__, and one with its own
	__init__ sets them by forwarding to super()."

	self assertMatchesCPythonAt: 'plain_subclass'.
	self assertMatchesCPythonAt: 'subclass_with_init'.
%

category: 'Grail-Tests - Inheritance'
method: SystemExitTestCase
testInheritance
	"Why SystemExit hangs off BaseException and not Exception: ``except
	Exception'' must NOT swallow an exit request.  Nothing to do with code, and
	everything to do with whether the code is ever read."

	| exc |
	exc := SystemExit ___new___:  SystemExit .
	self assert: (exc isKindOf: BaseException).
	self assertMatchesCPythonAt: 'still_a_baseexception_not_an_exception'.
%

category: 'Grail-Tests - Regression Guards'
method: SystemExitTestCase
testCreation
	"Test creating a SystemExit instance."

	| exc |
	exc := SystemExit ___new___:  SystemExit .
	self assert: exc notNil.
%

category: 'Grail-Tests - Regression Guards'
method: SystemExitTestCase
testArgsStrAndReprAreUndisturbed
	"Adding code must not move anything else.  str/repr read args, and the
	sys.exit() fix CHANGES what the bare exit's repr says -- ``SystemExit()''
	rather than ``SystemExit(0)'' -- so pinning them is what says the change is
	the intended one and not a second, quieter difference."

	self assertMatchesCPythonAt: 'str_and_repr'.
%
