! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for TarfileTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'TarfileTestCase'
  instVarNames: #()
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()
%

expectvalue /Class
doit
TarfileTestCase comment:
'Reads tar archives produced by CPython and by the GNU/bsd tar CLI.\nSee fixturePrelude for why every fixture is foreign-produced.'
%

expectvalue /Class
doit
TarfileTestCase category: 'Grail-SUnit'
%

! ------------------- Remove existing test methods
expectvalue /Metaclass3
doit
TarfileTestCase removeAllMethods: 0.
TarfileTestCase class removeAllMethods: 0.
%

set compile_env: 0

category: 'Grail-Fixtures'
method: TarfileTestCase
fixturePrelude
	"Python source that writes the CPython-produced archive fixtures into
	this checkout''s $TMP and binds the expected payloads.

	The archives are NOT built here: they are byte literals written by
	CPython''s own zipfile/tarfile (the ZIP64 one hand-assembled and then
	verified with CPython''s zipfile), regenerated by
	tests/scripts/make_archive_fixtures.py.  That is the whole point --
	Grail cannot write archives, so the only round trip worth testing is
	against another implementation.

	The fixtures are small but the payloads are not: big.txt/big.bin are
	320000 bytes of repetitive text, which deflates to under a kilobyte
	while still forcing the reader across many buffer boundaries."

	^ 'import io, os, zlib
_ZIPHEX = (
            "504b0304140000000800000021582d3b08af0e0000000c0000000900000068656c6c6f2e747874cb48cdc9c9"
            "5728cf2fca49e10200504b03041400000008000000215800000000020000000000000009000000656d707479"
            "2e7478740300504b030414000000000000002158570d652480000000800000000a00000073746f7265642e62"
            "696e000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526272829"
            "2a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455"
            "565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f504b"
            "0304140000000800000021580a3fa3418f02000000e20400070000006269672e747874edc7c901c0100000b0"
            "9594bac641d97f840ee19bfc129e98de5c6aeb63ae6f9fe0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee7ef91f504b030414000000080000002158"
            "9e0c457e140000002d0000000e0000007375622f6e65737465642e747874cb4b2d2e494d512848acccc94f4c"
            "e1cac3cb0500504b01021403140000000800000021582d3b08af0e0000000c00000009000000000000000000"
            "000080010000000068656c6c6f2e747874504b01021403140000000800000021580000000002000000000000"
            "00090000000000000000000000800135000000656d7074792e747874504b0102140314000000000000002158"
            "570d652480000000800000000a000000000000000000000080015e00000073746f7265642e62696e504b0102"
            "1403140000000800000021580a3fa3418f02000000e204000700000000000000000000008001060100006269"
            "672e747874504b01021403140000000800000021589e0c457e140000002d0000000e00000000000000000000"
            "008001ba0300007375622f6e65737465642e747874504b0506000000000500050017010000fa0300000000")
_TGZHEX = (
            "1f8b08000000000002ffedd54d6eda400086e159e7143e0178f08ca73d8ef9691b892611365272fb8e5c6511"
            "14baa94c55f1bc1bf37863898fc1e369b70e0bd7d64acef3b576799d3fc79437a99436cdf7fb5cfad0e47083"
            "cee3349cea23c37d36d6fd7f1c8ec7e7d5f43a2db87f9fd2f5fde3e6e3feb14d5d179ad6fe8b376fdfd4afe0"
            "21e84ecfffe1e7cbf4f62fcfffe5ff7f3dffbdf37fb3fdb78fdf57dbc7a745dfffd7f68fb18f9fecdf76adfd"
            "6f517df77629f7e5cbd761bbdb1fbe3133333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "33333333333333333333333333333333333333ffadc7d36e3d9eb7ebb0606dade43c5f6b97d7f9734c79934a"
            "69d37cbf747d094d0e37e83c4ec3a93e32dc67effb3f1dc6e9b05f4dafd332fbf7295ddfbffe363eec1f638a"
            "9bd0b4f65fbcdfbb372fc3dbf179d83ffc99419224499224fd8ffd026f23b84a00000500")
_PAXHEX = (
            "1f8b08000000000002ffedd6bd6ac330140560cd790a3d817cf5137b0ab4531be850fa06c2569b402219590d"
            "cedbd776a1504a041d6c4272bec5b6eee0e1fa702c0a513cbcdafed9d9c645360bfa76e94a5a963ff7d3b924"
            "25d78cf76c019f5db271783dbb4fdaf0a7b7c7ed8bf021b9cd7b88b5ebb8e5adedf96efa2456b252c363da6d"
            "ba5817f6e4e2f910fc47b38fae4e219eeb706c83773e1165a7323b55d9a9ce4e4dd138d78ad4a715837f5a62"
            "a963a84b632ee69f86b04bb356a6aac88ce75a51651827e47f76637486780f2bb40de2737fc415f43f19f5b7"
            "ff25faff3afa1f19b9f5fe6f0f76efc7ff27365ffeb3fd4fe5effe97647489fe5fc2b47b641c000000000000"
            "0000000000e0667c01791775fa00280000")
_GNUHEX = (
            "1f8b08000000000002ffedd4418e82301480e1aee7149c001eb4d0ed1c804b34d018a25348ed18bdbd302693"
            "b810579818ff6f43d3b77cfdc98bbcf86ec7b06b87b057db909b475fa98cfe3fdfeeadad8dca5af502bfc7e4"
            "6296a90f758c5de14e3e5e0ef31be887e8bb34c64b37fe4c63f02189ac4ecbd569b53ad5ab5353f4de4f793a"
            "278537dfff127563ccc3fea5ac5569eaca582b66b9d795e8b97fa1ffcd2d9565939b57e8fa2f72f8c8fea783"
            "1bc286bfdaa7fd4b73df7f29da36f4ff0a7fbb277c00000000000000000000787b57a1c24ef900280000")
_Z64HEX = (
            "504b0304140000000000000000009e71935d0e0000000e000000070000007a36342e7478747a697036342070"
            "61796c6f61640a504b01021400140000000000000000009e71935d0e0000000e000000070000000000000000"
            "0000000000000000007a36342e747874504b06062c000000000000002d002d00000000000000000001000000"
            "00000000010000000000000035000000000000003300000000000000504b0607000000006800000000000000"
            "01000000504b0506ffffffffffffffffffffffffffffffff0000")
ZIPPATH = "$TMP/grail_fix.zip"
TGZPATH = "$TMP/grail_fix.tar.gz"
TARPATH = "$TMP/grail_fix.tar"
PAXPATH = "$TMP/grail_fix_pax.tar.gz"
GNUPATH = "$TMP/grail_fix_gnu.tar.gz"
Z64PATH = "$TMP/grail_fix64.zip"
JUNKPATH = "$TMP/grail_fix_junk.bin"
def _write(path, data):
    f = io.open(path, "wb")
    if len(data) > 0:
        f.write(data)
    f.close()
_write(ZIPPATH, bytes.fromhex(_ZIPHEX))
_write(TGZPATH, bytes.fromhex(_TGZHEX))
_write(PAXPATH, bytes.fromhex(_PAXHEX))
_write(GNUPATH, bytes.fromhex(_GNUHEX))
_write(Z64PATH, bytes.fromhex(_Z64HEX))
_write(TARPATH, zlib.decompress(bytes.fromhex(_TGZHEX), 47))
_write(JUNKPATH, b"this is definitely not an archive" * 20)
BIG = ("0123456789abcdef" * 20000).encode()
NESTED = b"nested payload\n" * 3
TARNESTED = b"nested payload\n" * 3
STORED = bytes(range(128))
LONGNAME = ("src/" + "/".join(["averylongdirectorycomponent%02d" % i for i in range(5)])
            + "/deep.txt")
def _outdir(tag):
    return "$TMP/grail_fix_out_" + tag
'
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testPlainNamesAndTypes
	"Header blocks are walked in order; directory members are recognised and their trailing slash stripped, as CPython does."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
t = tarfile.open(TARPATH, "r:")
names = t.getnames()
d = t.getmember("src/sub")
f = t.getmember("src/hello.txt")
t.close()
(names == ["src", "src/hello.txt", "src/empty.txt", "src/big.bin",
           "src/sub", "src/sub/nested.txt"]
 and d.isdir() and f.isreg() and f.size == 10)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testGzipMatchesPlain
	"The same archive read through r:gz and through r: yields identical members. The gz path inflates to a temp file so getmembers/extractfile can seek."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
a = tarfile.open(TGZPATH, "r:gz")
na = a.getnames()
ba = a.extractfile("src/big.bin").read()
a.close()
b = tarfile.open(TARPATH, "r:")
nb = b.getnames()
bb = b.extractfile("src/big.bin").read()
b.close()
(na == nb and ba == bb and ba == BIG and len(ba) == 320000)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testAutoDetectCompression
	"Mode ''r'' sniffs the magic bytes rather than trusting the file extension."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
a = tarfile.open(TGZPATH)
na = len(a.getnames())
a.close()
b = tarfile.open(TARPATH)
nb = len(b.getnames())
b.close()
(na == 6 and nb == 6)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testExtractFileContents
	"Every member reads back byte-identical, including a zero-length one."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
t = tarfile.open(TGZPATH, "r:gz")
h = t.extractfile("src/hello.txt").read()
e = t.extractfile("src/empty.txt").read()
n = t.extractfile("src/sub/nested.txt").read()
t.close()
(h == b"hello tar\n" and e == b"" and n == TARNESTED)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testExtractAll
	"extractall writes files and directories, creating parents as needed."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile, io, os
d = _outdir("tar_all")
t = tarfile.open(TGZPATH, "r:gz")
t.extractall(d)
t.close()
h = io.open(d + "/src/hello.txt", "rb").read()
n = io.open(d + "/src/sub/nested.txt", "rb").read()
b = io.open(d + "/src/big.bin", "rb").read()
(h == b"hello tar\n" and n == TARNESTED and b == BIG
 and os.path.isdir(d + "/src/sub"))').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testStreamReadsInSmallChunks
	"A member stream honours read(n) and tell() across the whole payload."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
t = tarfile.open(TARPATH, "r:")
f = t.extractfile("src/big.bin")
acc = b""
while True:
    chunk = f.read(1024)
    if len(chunk) == 0:
        break
    acc = acc + chunk
pos = f.tell()
f.close()
t.close()
(acc == BIG and pos == 320000)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testIterationAndGetmember
	"TarFile iterates its members, and getmember raises KeyError for an absent name."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
t = tarfile.open(TARPATH, "r:")
seen = [m.name for m in t]
try:
    t.getmember("nope")
    caught = False
except KeyError:
    caught = True
t.close()
(len(seen) == 6 and seen[0] == "src" and caught)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testGzipTempFileIsCleanedUp
	"The temp file the r:gz path inflates into exists while the archive is open and is removed by close() -- a leak here would fill /tmp one archive at a time."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile, os
def _count():
    return len([n for n in os.listdir("/tmp") if n.startswith("grail_tarfile_")])
before = _count()
t = tarfile.open(TGZPATH, "r:gz")
during = _count()
names = len(t.getnames())
t.close()
after = _count()
(during == before + 1 and after == before and names == 6)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testContextManager
	"TarFile works as a context manager and closes on exit."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
with tarfile.open(TGZPATH, "r:gz") as t:
    inside = len(t.getnames())
closed = t._closed
(inside == 6 and closed is True)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testIsTarfile
	"is_tarfile accepts both forms and rejects a non-archive without raising."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
(tarfile.is_tarfile(TARPATH) is True
 and tarfile.is_tarfile(TGZPATH) is True
 and tarfile.is_tarfile(JUNKPATH) is False)').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testNotATarRaises
	"Garbage in the first header block is a ReadError, not a bare checksum error."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
try:
    t = tarfile.open(JUNKPATH, "r:")
    t.getnames()
    caught = False
except tarfile.ReadError:
    caught = True
except tarfile.TarError:
    caught = True
caught').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testGzipModeOnPlainFileRaises
	"r:gz on an uncompressed file reports a ReadError rather than inflating garbage."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
try:
    tarfile.open(TARPATH, "r:gz")
    caught = False
except tarfile.ReadError:
    caught = True
caught').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testBz2AndXzRaiseCompressionError
	"bz2 and xz are documented gaps and say so, rather than being read as
	an uncompressed tar."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
caught = 0
for mode in ("r:bz2", "r:xz"):
    try:
        tarfile.open(TARPATH, mode)
    except tarfile.CompressionError:
        caught = caught + 1
caught == 2').
	self assert: result
%

category: 'Grail-Tests - tarfile'
method: TarfileTestCase
testWriteModeRaises
	"Writing is a documented V1 gap."

	self
		should: [self eval: (self fixturePrelude, 'import tarfile
tarfile.open(TARPATH, "w")')]
		raise: NotImplementedError
%

category: 'Grail-Tests - tarfile metadata'
method: TarfileTestCase
testPaxHeaderMembers
	"A PAX archive puts a metadata-only ././@PaxHeader member before each real one.  Consuming that member MOVES the file position, so the next header must be read from the recomputed offset -- a reader that seeks once, before the loop, reports a bad checksum on this perfectly good archive."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
t = tarfile.open(PAXPATH, "r:gz")
names = t.getnames()
deep = t.extractfile(LONGNAME).read()
plain = t.extractfile("src/plain.txt").read()
t.close()
(names == [LONGNAME, "src/plain.txt"]
 and deep == b"deep payload\n" and plain == b"plain\n"
 and len(LONGNAME) == 162)').
	self assert: result
%

category: 'Grail-Tests - tarfile metadata'
method: TarfileTestCase
testGnuLongNameMembers
	"A GNU archive stores a name longer than the 100-char header field in a preceding typeflag-L member.  Same position hazard as the PAX case, and the long name must be picked up rather than the truncated one."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile
t = tarfile.open(GNUPATH, "r:gz")
names = t.getnames()
deep = t.extractfile(LONGNAME).read()
plain = t.extractfile("src/plain.txt").read()
t.close()
(names == [LONGNAME, "src/plain.txt"]
 and deep == b"deep payload\n" and plain == b"plain\n")').
	self assert: result
%

category: 'Grail-Tests - tarfile metadata'
method: TarfileTestCase
testMetadataArchivesExtract
	"extractall reproduces a deeply nested long path on disk."

	| result |
	result := self eval: (self fixturePrelude, 'import tarfile, io
d = _outdir("tar_pax")
t = tarfile.open(PAXPATH, "r:gz")
t.extractall(d)
t.close()
io.open(d + "/" + LONGNAME, "rb").read() == b"deep payload\n"').
	self assert: result
%
