! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for TracebackObjectTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'TracebackObjectTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
TracebackObjectTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! TracebackObjectTestCase
!
! The traceback OBJECT -- ``e.__traceback__'', and the type it is an instance of.
!
! Grail has had real traceback objects for a while: a linked list of nodes with
! tb_frame / tb_lineno / tb_next, built as an exception unwinds.  What it did not
! have was any of the things code DOES with them, and each gap was quiet in its
! own way.
!
! 1. THE TYPE HAD NO NAME.  types.TracebackType was an empty stub class, so
!    ``isinstance(tb, types.TracebackType)'' was False about an object that was
!    one -- and that check is what every traceback-handling library leads with,
!    so they all took their ``this is not a traceback'' branch.  The stub was not
!    standing in for a missing feature, only for a missing NAME, which is why it
!    is the one entry in types.py worth converting: it stops isinstance lying
!    about something real.
!
! 2. with_traceback() DID NOT SURVIVE THE RAISE.  ``raise X().with_traceback(tb)''
!    is meant to PREPEND the new raise's frames to the attached chain.  Grail read
!    the attached chain as a partial unwind record, decided it was stale, and
!    discarded it -- so the traceback the caller had deliberately attached
!    vanished at exactly the raise that was supposed to use it.
!
! 3. tb_next TOOK ANYTHING.  ``tb.tb_next = 'asdf''' was stored, so the failure
!    surfaced later, inside whichever formatter walked into a string; and
!    ``tb.tb_next = tb'' built a cycle, which HANGS every walker, since they all
!    loop until tb_next is None.  ``del tb.tb_next'' removed the slot, and an
!    absent dynamic instVar reads back as AttributeError -- a third error,
!    further from the cause than the second.
!
! 4. THERE WAS NO CONSTRUCTOR.  types.TracebackType(...) is how a replacement
!    node is built, which is how frames are trimmed off a chain before
!    re-raising.  The class was not callable at all.  It takes a CLASSMETHOD
!    named __new__ rather than an __init__: PyTraceback is Smalltalk-defined, so
!    calling it lands in ``object class >> value:value:'', which dispatches on
!    arity to __new__ on the metaclass and never consults __init__.
!
! NOT FIXED, and stated rather than skipped: ``tb.tb_frame is sys._getframe()''.
! CPython has ONE mutable frame object per activation, so a traceback's frame and
! the running frame are the same object at different line numbers.  Grail
! synthesises a fresh frame from the VM's stack capture each time it is asked, so
! the two are equal in content and never identical.  That is the assertion
! test_raise's test_attrs still fails on, and closing it needs real frame
! objects, not a change to any of this.
!
! Drives tests/python/traceback_object.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before commit.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
TracebackObjectTestCase removeAllMethods.
TracebackObjectTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: TracebackObjectTestCase
setUp
	"Reload tests/python/traceback_object.py fresh each test -- the module body
	MUTATES the tracebacks it builds (tb_next is reassigned, cleared and
	re-pointed), so a shared instance would be reading a previous test's edits."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'traceback_object' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/traceback_object.py')
		name: 'traceback_object'.
%

category: 'Grail-Private'
method: TracebackObjectTestCase
assertMatchesCPythonAt: key
	| builtinsInstance actual expected |
	builtinsInstance := (Python at: #builtins) @env1:instance.
	actual := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key).
	expected := builtinsInstance
		@env1:repr: ((testModule @env1:___pyAttrLoad___: #EXPECTED) @env1:__getitem__: key).
	self assert: actual asString equals: expected asString.
%

category: 'Grail-Tests - The Type'
method: TracebackObjectTestCase
testATracebackIsAnInstanceOfTracebackType
	"THE TEST THIS EXISTS FOR.  isinstance(tb, types.TracebackType) was False
	about a genuine traceback, which is the first thing any traceback-handling
	code asks."

	self assertMatchesCPythonAt: 'is_traceback_type'.
	self assertMatchesCPythonAt: 'type_is_tracebacktype'.
%

category: 'Grail-Tests - The Type'
method: TracebackObjectTestCase
testTheTypeIsNamedTraceback
	"CPython's is a builtin type spelled ``traceback'', module ``builtins''.
	Grail's internal ``PyTraceback'' spelling leaked into every repr and every
	type(tb).__name__."

	self assertMatchesCPythonAt: 'type_name'.
	self assertMatchesCPythonAt: 'type_module'.
	self assertMatchesCPythonAt: 'type_repr'.
%

category: 'Grail-Tests - The Type'
method: TracebackObjectTestCase
testTheFieldsAWalkerReads
	"tb_lasti was ABSENT, so reading it raised where CPython answers an int.
	Grail compiles to Smalltalk and has no bytecode offset, so it reports -1 --
	CPython's own value for ``no instruction index'', not a placeholder invented
	here."

	self assertMatchesCPythonAt: 'lineno_is_int'.
	self assertMatchesCPythonAt: 'lasti_is_int'.
	self assertMatchesCPythonAt: 'frame_is_not_none'.
	self assertMatchesCPythonAt: 'tb_next_of_leaf'.
%

category: 'Grail-Tests - with_traceback'
method: TracebackObjectTestCase
testAnAttachedTracebackIsPrependedToNotReplaced
	"``raise X().with_traceback(tb)'' must leave __traceback__ as a NEW head
	whose tb_next is the attached chain.  Grail discarded the chain, so the
	whole idiom silently did nothing."

	self assertMatchesCPythonAt: 'accepts_traceback'.
%

category: 'Grail-Tests - with_traceback'
method: TracebackObjectTestCase
testWithTracebackNoneClearsIt
	"None has to be stored as the ABSENCE of a traceback, not as the None
	singleton: everything that asks whether there is a chain yet asks
	``tracebackObj isNil'', and a stored None answered that wrong."

	self assertMatchesCPythonAt: 'with_traceback_none_clears'.
%

category: 'Grail-Tests - tb_next Is Guarded'
method: TracebackObjectTestCase
testAssigningANonTracebackIsATypeError
	"Stored as-is before, so the failure surfaced later, inside whichever
	formatter walked into a string."

	self assertMatchesCPythonAt: 'assign_str'.
%

category: 'Grail-Tests - tb_next Is Guarded'
method: TracebackObjectTestCase
testDeletingTbNextIsATypeError
	"TypeError, not AttributeError: the attribute exists and is writable, so
	what is refused is the DELETION.  Grail removed the slot, and an absent slot
	reads back as AttributeError -- a different error, further away."

	self assertMatchesCPythonAt: 'delete_next'.
%

category: 'Grail-Tests - tb_next Is Guarded'
method: TracebackObjectTestCase
testALoopIsAValueError
	"The one that matters most: every traceback walker loops until tb_next is
	None, so a cycle does not raise anything -- it HANGS.  Both the direct
	self-link and the two-node indirect one."

	self assertMatchesCPythonAt: 'self_loop'.
	self assertMatchesCPythonAt: 'indirect_loop'.
%

category: 'Grail-Tests - tb_next Is Guarded'
method: TracebackObjectTestCase
testTheValidAssignmentsStillWork
	"The guard would be worthless if it also refused the writes the field exists
	for -- clearing to None, and re-pointing at another node."

	self assertMatchesCPythonAt: 'valid_assignments'.
%

category: 'Grail-Tests - Constructor'
method: TracebackObjectTestCase
testTracebackTypeIsCallable
	"types.TracebackType(tb_next, tb_frame, tb_lasti, tb_lineno) -- how a
	replacement node is built, and so how frames are trimmed off a chain before
	re-raising.  The class was not callable at all."

	self assertMatchesCPythonAt: 'construct'.
	self assertMatchesCPythonAt: 'construct_none_next'.
%

category: 'Grail-Tests - Constructor'
method: TracebackObjectTestCase
testEachArgumentIsCheckedWithItsOwnMessage
	"Three different shapes of message for four arguments, and CPython's own
	wording for each: ``expected traceback object or None'' names what was
	wanted, ``must be frame, not str'' names the argument, and the two integers
	share the generic ``cannot be interpreted as an integer''."

	self assertMatchesCPythonAt: 'construct_bad_next'.
	self assertMatchesCPythonAt: 'construct_bad_frame'.
	self assertMatchesCPythonAt: 'construct_bad_lasti'.
	self assertMatchesCPythonAt: 'construct_bad_lineno'.
%

category: 'Grail-Tests - Still Legal'
method: TracebackObjectTestCase
testTheOrdinaryReportingPathIsUndisturbed
	"A traceback is not only an object to poke at -- it is what the traceback
	module formats.  Renaming the type and guarding the field must leave the
	chain walkable and the report readable."

	self assertMatchesCPythonAt: 'walk_chain'.
	self assertMatchesCPythonAt: 'format_still_works'.
%
