! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for TypeAliasTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'TypeAliasTestCase'
  instVarNames: #( testModule irRegistrySnapshot )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
TypeAliasTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! TypeAliasTestCase
!
! PEP 695's ``type X = value'' statement.  Grail's parser had no type-alias
! statement at all, so every construct here was a SyntaxError rather than a
! wrong answer.
!
! The load-bearing detail is that ``__value__'' is LAZY.  PEP 695 evaluates it
! on FIRST ACCESS, which is what lets an alias name something defined later in
! the module, or name ITSELF (``type Json = int | list[Json]'').  An eager
! implementation turns both into a NameError at the point of definition, so the
! laziness is the semantics and not an optimisation -- hence a test that defines
! an alias BEFORE the name it refers to exists.
!
! Two mistakes this pins that would otherwise read as working code:
!
!   * The attributes are ATTRIBUTES, not methods.  Defining __name__ as a
!     zero-arg method made ``Alias.__name__'' answer a BoundMethod -- an object,
!     printed without complaint, which looks like a working attribute right up
!     until something compares it.
!   * A ``once'' cache keyed on ``is the stored value nil?'' re-runs its thunk
!     forever for an alias whose value legitimately IS None -- which
!     test_annotationlib writes twice.  The fixture reads such an alias twice.
!
! ``type'' is a SOFT keyword AND a builtin, so it is an ordinary identifier far
! more often than it opens a statement; the last test pins that it still is.
!
! Drives tests/python/type_alias.py, whose EXPECTED table was generated by
! RUNNING CPython 3.14.6 and verified against it before being committed, so a
! disagreement is Grail differing from CPython rather than from a guess.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
TypeAliasTestCase removeAllMethods.
TypeAliasTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: TypeAliasTestCase
setUp
	"Reload tests/python/type_alias.py fresh each test."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'type_alias' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/type_alias.py')
		name: 'type_alias'.
%

category: 'Grail-Private'
method: TypeAliasTestCase
assertMatchesCPythonAt: key
	"Compare repr against the fixture's own EXPECTED entry -- CPython's
	actual output."

	self
		assert: ((builtins @env1:instance) @env1:repr:
			((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key)) asString
		equals: ((testModule @env1:___pyAttrLoad___: #EXPECTED)
			@env1:__getitem__: key) asString
%

category: 'Grail-Tests - The alias object'
method: TypeAliasTestCase
testNameAndReprAndTypeParamsAreAttributesNotMethods
	"repr() is the BARE NAME -- CPython prints ``Alias'', not a
	constructor-shaped string, and annotation formatting depends on it.
	__name__ and __type_params__ read as values; as zero-arg methods they
	answered a BoundMethod, which prints without complaint."

	self assertMatchesCPythonAt: 'repr'.
	self assertMatchesCPythonAt: 'name'.
	self assertMatchesCPythonAt: 'type_params'.
%

category: 'Grail-Tests - Laziness'
method: TypeAliasTestCase
testTheValueIsEvaluatedLazily
	"The alias is defined BEFORE the name it refers to exists.  An eager
	implementation raises NameError at the definition, so this is the
	check that the thunk is real."

	self assertMatchesCPythonAt: 'lazy_forward_reference'.
%

category: 'Grail-Tests - Laziness'
method: TypeAliasTestCase
testAnAliasWhoseValueIsNoneIsStillOnlyEvaluatedOnce
	"``type C1 = None'' -- test_annotationlib writes it twice.  A once-cache
	that asks ``is the stored value nil?'' cannot tell ``not yet run'' from
	``ran and answered None'', and re-runs the thunk on every access."

	self assertMatchesCPythonAt: 'none_value'.
	self assertMatchesCPythonAt: 'none_value_again'.
%

category: 'Grail-Tests - Binding'
method: TypeAliasTestCase
testTheAliasBindsItsNameLikeAnAssignment
	"A type alias binds exactly as an assignment does, so at module scope
	it is an ordinary module global.  Emitting a plain ``X := ...'' instead
	of routing through AssignAst reproduced none of that cascade, and a
	module-level ``type X = int'' compiled to an undefined symbol."

	self assertMatchesCPythonAt: 'is_a_module_global'.
%

category: 'Grail-Tests - Soft keyword'
method: TypeAliasTestCase
testTypeRemainsTheBuiltin
	"``type'' opens a type alias in exactly one position and stays the
	builtin everywhere else -- called, passed to isinstance, and read as a
	value."

	self assertMatchesCPythonAt: 'builtin_call'.
	self assertMatchesCPythonAt: 'builtin_isinstance'.
	self assertMatchesCPythonAt: 'builtin_as_value'.
%

category: 'Grail-Tests - type alias'
method: TypeAliasTestCase
tearDown
	importlib ___irCodegenEnabledInvalidate___.
	(importlib @env1:modules) removeKey: #'type_alias_ir' ifAbsent: [].
	irRegistrySnapshot ifNotNil: [:snap |
		importlib ___canonicalRegistryRestore___: snap.
		irRegistrySnapshot := nil].
	self ___forgetCanonicalModule___: 'type_alias_ir'
%

category: 'Grail-Tests - type alias'
method: TypeAliasTestCase
___censusAndResultsUnderForcedIR___
	"Load the same fixture with the seam FORCED on and the census collecting;
	answer { the census counts. the fixture's r }."

	| census mod |
	(importlib @env1:modules) removeKey: #'type_alias_ir' ifAbsent: [].
	self ___forgetCanonicalModule___: 'type_alias_ir'.
	irRegistrySnapshot ifNil: [
		irRegistrySnapshot := importlib ___canonicalRegistrySnapshot___].
	importlib ___irCodegenForce___: true.
	importlib ___irStatsReset___.
	importlib ___irCensusReset___.
	importlib ___irCensusOn: true.
	mod := [importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/type_alias.py')
		name: 'type_alias_ir'] ensure: [importlib ___irCensusOn: false].
	census := importlib ___irCensus___.
	^ { census at: #counts. mod @env1:___pyAttrLoad___: #'r' }
%

category: 'Grail-Tests - type alias'
method: TypeAliasTestCase
testTheStatementCompilesThroughIR
	"THE TESTS ABOVE PASS ON EITHER PATH.  Neither TypeAliasAst nor
	TypeAliasValueAst had any IR protocol, so every def holding a type alias
	refused eligibility and compiled as TEXT -- which handles all of this
	already, so every value was right and nothing said the IR arm had never
	run.

	Two assertions.  The CENSUS one says the refusal is gone, naming BOTH rows:
	giving the statement its protocol first moved `stmt:TypeAliasAst' to
	`value:TypeAliasValueAst' with cm:eligible unchanged at 660 -- the row
	moved one node down rather than closing, which a count cannot see.  The
	RESULTS one says the emit that replaced it is right, over the same keys the
	text arm checks.

	``lazy_forward_reference'' and ``lazy_in_a_function'' are the two that
	matter most: the value lives in a THUNK, and an emit that evaluated it
	eagerly would turn a legal forward reference into a NameError at the point
	of definition while passing every other check here."

	| pair counts results present |
	pair := self ___censusAndResultsUnderForcedIR___.
	counts := pair at: 1.
	results := pair at: 2.
	#('repr' 'name' 'type_params' 'none_value' 'none_value_again'
	  'lazy_forward_reference' 'is_a_module_global' 'in_a_function'
	  'lazy_in_a_function' 'in_a_method') do: [:key |
		self assert: ((results @env1:__getitem__: key) @env1:__repr__ @env0:asString)
			equals: ((testModule @env1:___pyAttrLoad___: #'EXPECTED')
				@env1:__getitem__: key) @env0:asString
			description: 'under forced IR: ' , key].
	importlib ___irCodegenSupported___ ifFalse: [^ self assert: true].
	present := #('stmt:TypeAliasAst' 'cm:stmt:TypeAliasAst'
		'value:TypeAliasValueAst' 'cm:value:TypeAliasValueAst') select: [:row |
			(counts at: row asSymbol otherwise: 0) > 0].
	self assert: present isEmpty
		description: 'a type-alias refusal is still in the census: '
			, (present collect: [:r | r , '=' ,
				(counts at: r asSymbol otherwise: 0) printString]) asArray printString
%
