! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for WarningsModuleFilterTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'WarningsModuleFilterTestCase'
  instVarNames: #( testModule )
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()

%

expectvalue /Class
doit
WarningsModuleFilterTestCase category: 'Grail-SUnit'
%

! ===============================================================================
! WarningsModuleFilterTestCase
!
! ``warnings.filterwarnings(..., module=PATTERN)'' scopes a filter to WHERE the
! warning was raised from.  Grail had only fixed-arity positional forms, so the
! call raised ``takes a different number of arguments'' and errored every test
! in test_global's setUp; then it accepted the keyword but could not evaluate
! it, because nothing recorded a warning's origin, so such a filter was skipped.
!
! THE TRAP, and the reason the first working implementation was still wrong:
! CPython matches ``module='' against the raising module's dotted ``__name__'',
! NOT its filename.  The pure-Python warn_explicit fallback DOES derive a name
! from the filename, so the two look interchangeable until they are tested --
! and under real CPython a filter naming a script's own PATH does not fire at
! all, while ``module=''__main__''' does.  Matching the filename would have
! scoped every filter to a string no caller ever writes: a filter that silently
! NEVER FIRES, which is worse than the skip it replaced.  That is what
! testAPathIsNotAModuleName exists to catch.
!
! The origin comes from BaseException class>>___liveFrameChain___, the same live
! stack capture sys._getframe stands on.  It gets the stack the only way a
! running gem can, by RAISING -- ``thisContext'' is an undefined symbol in
! GemStone even inside a compiled method, and ``GsProcess _current'' answers
! stackDepth 0 for the running process, so probing those two makes the
! capability look absent when it is not.  The capture is taken ONLY when some
! filter actually carries a module pattern, so the common case walks no stack.
!
! ``lineno='' remains unmatchable and still skips: that needs a per-frame line,
! which is separate work.
!
! Drives tests/python/warnings_module_filter.py, whose EXPECTED table was
! generated by RUNNING CPython 3.14.6 and verified against it before being
! committed -- which is how the filename-versus-__name__ mistake was caught at
! all, since it passed every hand-written probe.
! ===============================================================================

set compile_env: 0

expectvalue /Metaclass3
doit
WarningsModuleFilterTestCase removeAllMethods.
WarningsModuleFilterTestCase class removeAllMethods.
%

set compile_env: 0

category: 'Grail-Setup'
method: WarningsModuleFilterTestCase
setUp
	"Reload tests/python/warnings_module_filter.py fresh each test.

	The fixture installs and removes its own filters inside
	catch_warnings(), so a test cannot leak an ``error'' filter into the
	rest of the suite."

	| mods |
	mods := importlib @env1:modules.
	mods removeKey: #'warnings_module_filter' ifAbsent: [].
	testModule := importlib
		loadModuleFromPath: (importlib grailDir , '/tests/python/warnings_module_filter.py')
		name: 'warnings_module_filter'.
%

category: 'Grail-Private'
method: WarningsModuleFilterTestCase
assertMatchesCPythonAt: key
	self
		assert: ((builtins @env1:instance) @env1:repr:
			((testModule @env1:___pyAttrLoad___: #r) @env1:__getitem__: key)) asString
		equals: ((testModule @env1:___pyAttrLoad___: #EXPECTED)
			@env1:__getitem__: key) asString
%

category: 'Grail-Tests - Scoping'
method: WarningsModuleFilterTestCase
testAFilterNamingTheRaisingModuleFires
	"The case the whole feature exists for, and the one a skipped filter
	got wrong: a warning from the named module IS escalated."

	self assertMatchesCPythonAt: 'exact_name'.
%

category: 'Grail-Tests - Scoping'
method: WarningsModuleFilterTestCase
testTheMatchIsAnchoredSoAPrefixCounts
	"CPython compiles the pattern and applies #match, which is anchored at
	the START -- so a prefix of the module name matches, and a substring
	appearing later in it does not."

	self assertMatchesCPythonAt: 'name_prefix'.
%

category: 'Grail-Tests - Scoping'
method: WarningsModuleFilterTestCase
testAFilterNamingAnotherModuleDoesNotFire
	"The other half of scoping: a module-scoped filter must leave warnings
	from everywhere else alone.  Treating an unevaluatable constraint as
	SATISFIED would fail here -- it silently widens every such filter,
	turning unrelated warnings into errors far from their cause."

	self assertMatchesCPythonAt: 'unrelated_name'.
%

category: 'Grail-Tests - Scoping'
method: WarningsModuleFilterTestCase
testAPathIsNotAModuleName
	"``module='' is matched against the dotted __name__, never the
	filename.  This is the check that catches the plausible wrong
	implementation: matching co_filename passes every hand-written probe
	and then scopes every real filter to a string no caller writes, so the
	filter silently never fires."

	self assertMatchesCPythonAt: 'a_path_is_not_a_name'.
%

category: 'Grail-Tests - Scoping'
method: WarningsModuleFilterTestCase
testAnEmptyPatternMeansNoConstraint
	"CPython's default is the EMPTY REGEX, which matches every string.  An
	implementation reading it as ``matches only the empty string'' makes
	``filterwarnings('error', '')'' match nothing at all."

	self assertMatchesCPythonAt: 'empty_means_no_constraint'.
%

category: 'Grail-Tests - Signature'
method: WarningsModuleFilterTestCase
testTheFullSignatureIsAccepted
	"action, message, category, module, lineno, append -- by position or
	by keyword.  Only fixed-arity positional forms existed, so
	``filterwarnings('error', module=...)'' raised a TypeError about the
	argument count and errored all 20 of test_global's tests in setUp."

	self assertMatchesCPythonAt: 'keyword_module'.
	self assertMatchesCPythonAt: 'all_six_positional'.
	self assertMatchesCPythonAt: 'keyword_append'.
%

category: 'Grail-Tests - Signature'
method: WarningsModuleFilterTestCase
testAMissingActionIsATypeError
	"``action'' is required; CPython raises rather than installing a filter
	that matches everything with no action."

	self assertMatchesCPythonAt: 'missing_action'.
%

category: 'Grail-Tests - Signature'
method: WarningsModuleFilterTestCase
testAppendPutsTheFilterLast
	"``append=True'' adds at the END of the list, so an earlier filter
	still wins.  It was unavailable at any arity, and without it the two
	orderings are indistinguishable."

	self assertMatchesCPythonAt: 'append_goes_last'.
%
