! ------------------- Superclass check
run
PythonTestCase ifNil: [self error: 'PythonTestCase is not defined. Check file ordering.'].
%

! ------------------- Class definition for ZipfileTestCase
expectvalue /Class
doit
PythonTestCase subclass: 'ZipfileTestCase'
  instVarNames: #()
  classVars: #()
  classInstVars: #()
  poolDictionaries: #()
  inDictionary: PythonTests
  options: #()
%

expectvalue /Class
doit
ZipfileTestCase comment:
'Reads archives produced by CPython and by the /usr/bin/zip CLI tool.\nSee fixturePrelude for why every fixture is foreign-produced.'
%

expectvalue /Class
doit
ZipfileTestCase category: 'Grail-SUnit'
%

! ------------------- Remove existing test methods
expectvalue /Metaclass3
doit
ZipfileTestCase removeAllMethods: 0.
ZipfileTestCase class removeAllMethods: 0.
%

set compile_env: 0

category: 'Grail-Fixtures'
method: ZipfileTestCase
fixturePrelude
	"Python source that writes the CPython-produced archive fixtures into
	this checkout''s $TMP and binds the expected payloads.

	The archives are NOT built here: they are byte literals written by
	CPython''s own zipfile/tarfile (the ZIP64 one hand-assembled and then
	verified with CPython''s zipfile), regenerated by
	tests/scripts/make_archive_fixtures.py.  That is the whole point --
	Grail cannot write archives, so the only round trip worth testing is
	against another implementation.

	The fixtures are small but the payloads are not: big.txt/big.bin are
	320000 bytes of repetitive text, which deflates to under a kilobyte
	while still forcing the reader across many buffer boundaries."

	^ 'import io, os, zlib
_ZIPHEX = (
            "504b0304140000000800000021582d3b08af0e0000000c0000000900000068656c6c6f2e747874cb48cdc9c9"
            "5728cf2fca49e10200504b03041400000008000000215800000000020000000000000009000000656d707479"
            "2e7478740300504b030414000000000000002158570d652480000000800000000a00000073746f7265642e62"
            "696e000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20212223242526272829"
            "2a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455"
            "565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f504b"
            "0304140000000800000021580a3fa3418f02000000e20400070000006269672e747874edc7c901c0100000b0"
            "9594bac641d97f840ee19bfc129e98de5c6aeb63ae6f9fe0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
            "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee7ef91f504b030414000000080000002158"
            "9e0c457e140000002d0000000e0000007375622f6e65737465642e747874cb4b2d2e494d512848acccc94f4c"
            "e1cac3cb0500504b01021403140000000800000021582d3b08af0e0000000c00000009000000000000000000"
            "000080010000000068656c6c6f2e747874504b01021403140000000800000021580000000002000000000000"
            "00090000000000000000000000800135000000656d7074792e747874504b0102140314000000000000002158"
            "570d652480000000800000000a000000000000000000000080015e00000073746f7265642e62696e504b0102"
            "1403140000000800000021580a3fa3418f02000000e204000700000000000000000000008001060100006269"
            "672e747874504b01021403140000000800000021589e0c457e140000002d0000000e00000000000000000000"
            "008001ba0300007375622f6e65737465642e747874504b0506000000000500050017010000fa0300000000")
_TGZHEX = (
            "1f8b08000000000002ffedd54d6eda400086e159e7143e0178f08ca73d8ef9691b892611365272fb8e5c6511"
            "14baa94c55f1bc1bf37863898fc1e369b70e0bd7d64acef3b576799d3fc79437a99436cdf7fb5cfad0e47083"
            "cee3349cea23c37d36d6fd7f1c8ec7e7d5f43a2db87f9fd2f5fde3e6e3feb14d5d179ad6fe8b376fdfd4afe0"
            "21e84ecfffe1e7cbf4f62fcfffe5ff7f3dffbdf37fb3fdb78fdf57dbc7a745dfffd7f68fb18f9fecdf76adfd"
            "6f517df77629f7e5cbd761bbdb1fbe3133333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"
            "33333333333333333333333333333333333333ffadc7d36e3d9eb7ebb0606dade43c5f6b97d7f9734c79934a"
            "69d37cbf747d094d0e37e83c4ec3a93e32dc67effb3f1dc6e9b05f4dafd332fbf7295ddfbffe363eec1f638a"
            "9bd0b4f65fbcdfbb372fc3dbf179d83ffc99419224499224fd8ffd026f23b84a00000500")
_PAXHEX = (
            "1f8b08000000000002ffedd6bd6ac330140560cd790a3d817cf5137b0ab4531be850fa06c2569b402219590d"
            "cedbd776a1504a041d6c4272bec5b6eee0e1fa702c0a513cbcdafed9d9c645360bfa76e94a5a963ff7d3b924"
            "25d78cf76c019f5db271783dbb4fdaf0a7b7c7ed8bf021b9cd7b88b5ebb8e5adedf96efa2456b252c363da6d"
            "ba5817f6e4e2f910fc47b38fae4e219eeb706c83773e1165a7323b55d9a9ce4e4dd138d78ad4a715837f5a62"
            "a963a84b632ee69f86b04bb356a6aac88ce75a51651827e47f76637486780f2bb40de2737fc415f43f19f5b7"
            "ff25faff3afa1f19b9f5fe6f0f76efc7ff27365ffeb3fd4fe5effe97647489fe5fc2b47b641c000000000000"
            "0000000000e0667c01791775fa00280000")
_GNUHEX = (
            "1f8b08000000000002ffedd4418e82301480e1aee7149c001eb4d0ed1c804b34d018a25348ed18bdbd302693"
            "b810579818ff6f43d3b77cfdc98bbcf86ec7b06b87b057db909b475fa98cfe3fdfeeadad8dca5af502bfc7e4"
            "6296a90f758c5de14e3e5e0ef31be887e8bb34c64b37fe4c63f02189ac4ecbd569b53ad5ab5353f4de4f793a"
            "278537dfff127563ccc3fea5ac5569eaca582b66b9d795e8b97fa1ffcd2d9565939b57e8fa2f72f8c8fea783"
            "1bc286bfdaa7fd4b73df7f29da36f4ff0a7fbb277c00000000000000000000787b57a1c24ef900280000")
_Z64HEX = (
            "504b0304140000000000000000009e71935d0e0000000e000000070000007a36342e7478747a697036342070"
            "61796c6f61640a504b01021400140000000000000000009e71935d0e0000000e000000070000000000000000"
            "0000000000000000007a36342e747874504b06062c000000000000002d002d00000000000000000001000000"
            "00000000010000000000000035000000000000003300000000000000504b0607000000006800000000000000"
            "01000000504b0506ffffffffffffffffffffffffffffffff0000")
ZIPPATH = "$TMP/grail_fix.zip"
TGZPATH = "$TMP/grail_fix.tar.gz"
TARPATH = "$TMP/grail_fix.tar"
PAXPATH = "$TMP/grail_fix_pax.tar.gz"
GNUPATH = "$TMP/grail_fix_gnu.tar.gz"
Z64PATH = "$TMP/grail_fix64.zip"
JUNKPATH = "$TMP/grail_fix_junk.bin"
def _write(path, data):
    f = io.open(path, "wb")
    if len(data) > 0:
        f.write(data)
    f.close()
_write(ZIPPATH, bytes.fromhex(_ZIPHEX))
_write(TGZPATH, bytes.fromhex(_TGZHEX))
_write(PAXPATH, bytes.fromhex(_PAXHEX))
_write(GNUPATH, bytes.fromhex(_GNUHEX))
_write(Z64PATH, bytes.fromhex(_Z64HEX))
_write(TARPATH, zlib.decompress(bytes.fromhex(_TGZHEX), 47))
_write(JUNKPATH, b"this is definitely not an archive" * 20)
BIG = ("0123456789abcdef" * 20000).encode()
NESTED = b"nested payload\n" * 3
TARNESTED = b"nested payload\n" * 3
STORED = bytes(range(128))
LONGNAME = ("src/" + "/".join(["averylongdirectorycomponent%02d" % i for i in range(5)])
            + "/deep.txt")
def _outdir(tag):
    return "$TMP/grail_fix_out_" + tag
'
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testNamelistAndInfolist
	"The central directory is parsed in order, with per-entry method and sizes."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
names = z.namelist()
infos = z.infolist()
stored = z.getinfo("stored.bin")
big = z.getinfo("big.txt")
z.close()
(names == ["hello.txt", "empty.txt", "stored.bin", "big.txt", "sub/nested.txt"]
 and len(infos) == 5
 and stored.compress_type == 0 and stored.file_size == 128
 and big.compress_type == 8 and big.file_size == 320000
 and big.compress_size < 2000
 and len(big.date_time) == 6 and big.date_time[0] >= 1980)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testReadStoredAndDeflated
	"Both methods that occur in practice: 0 (stored) and 8 (deflated)."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
a = z.read("hello.txt")
b = z.read("stored.bin")
z.close()
(a == b"hello world\n" and b == STORED and len(b) == 128)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testEmptyEntry
	"A zero-length deflated entry reads back as b'''' rather than raising."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
data = z.read("empty.txt")
info = z.getinfo("empty.txt")
z.close()
(data == b"" and info.file_size == 0)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testLargeEntrySpansBuffers
	"A 320000-byte member crosses many 65536-byte read and 16384-byte inflate buffers."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
data = z.read("big.txt")
z.close()
(data == BIG and len(data) == 320000)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testNestedPathEntry
	"A member inside a subdirectory keeps its full stored name."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
data = z.read("sub/nested.txt")
z.close()
data == NESTED').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testOpenStreamsInSmallReads
	"ZipFile.open inflates incrementally: many small reads reassemble the member exactly."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
f = z.open("big.txt")
acc = b""
while True:
    chunk = f.read(1000)
    if len(chunk) == 0:
        break
    acc = acc + chunk
tell = f.tell()
f.close()
z.close()
(acc == BIG and tell == 320000)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testExtractAll
	"extractall writes every member to disk, creating subdirectories as needed."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile, io
d = _outdir("zip_all")
z = zipfile.ZipFile(ZIPPATH)
z.extractall(d)
z.close()
h = io.open(d + "/hello.txt", "rb").read()
n = io.open(d + "/sub/nested.txt", "rb").read()
b = io.open(d + "/big.txt", "rb").read()
s = io.open(d + "/stored.bin", "rb").read()
(h == b"hello world\n" and n == NESTED and b == BIG and s == STORED)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testExtractSingleMember
	"extract() answers the path it wrote and honours a ZipInfo argument."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile, io
d = _outdir("zip_one")
z = zipfile.ZipFile(ZIPPATH)
p = z.extract(z.getinfo("sub/nested.txt"), d)
z.close()
(io.open(p, "rb").read() == NESTED and p.endswith("nested.txt"))').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testCorruptPayloadRaisesBadZipFile
	"The CRC in the archive is checked: one flipped payload byte is caught. Without this the test suite could not tell a correct inflate from a plausible-looking wrong one."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
raw = bytes.fromhex(_ZIPHEX)
bad = raw[:40] + bytes([raw[40] ^ 255]) + raw[41:]
_write(ZIPPATH + ".bad", bad)
z = zipfile.ZipFile(ZIPPATH + ".bad")
try:
    z.read("hello.txt")
    caught = False
except zipfile.BadZipFile:
    caught = True
z.close()
caught').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testNotAZipRaises
	"A file with no end-of-central-directory signature is rejected, and is_zipfile answers False rather than raising."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
try:
    zipfile.ZipFile(JUNKPATH)
    caught = False
except zipfile.BadZipFile:
    caught = True
(caught and zipfile.is_zipfile(JUNKPATH) is False
 and zipfile.is_zipfile(ZIPPATH) is True)').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testZip64CentralDirectory
	"A ZIP64 archive: every 32-bit field in the classic end-of-central-directory record is saturated, so the reader MUST follow the locator to the ZIP64 record to find the directory at all.  Kaggle datasets reach that size."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(Z64PATH)
names = z.namelist()
data = z.read("z64.txt")
z.close()
(names == ["z64.txt"] and data == b"zip64 payload\n")').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testContextManagerAndRepr
	"ZipFile works as a context manager and closes on exit."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
with zipfile.ZipFile(ZIPPATH) as z:
    inside = len(z.namelist())
    text = repr(z)
closed = z._closed
(inside == 5 and closed is True and text.startswith("<ZipFile"))').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testGetinfoMissingRaisesKeyError
	"An absent member is a KeyError, as in CPython."

	| result |
	result := self eval: (self fixturePrelude, 'import zipfile
z = zipfile.ZipFile(ZIPPATH)
try:
    z.getinfo("nope.txt")
    caught = False
except KeyError:
    caught = True
z.close()
caught').
	self assert: result
%

category: 'Grail-Tests - zipfile'
method: ZipfileTestCase
testWriteModeRaises
	"Writing is a documented V1 gap and says so, rather than half-working."

	self
		should: [self eval: (self fixturePrelude, 'import zipfile
zipfile.ZipFile(ZIPPATH, "w")')]
		raise: NotImplementedError
%
