#!/usr/bin/env python3
"""Generate tests/python/class_attr_dunder_binding.py (issue #1218).

Writes one class statement per (protocol dunder, value kind) case -- once as a
class-body assignment, once as a setattr after the class exists -- then RUNS the
result under this interpreter to record EXPECTED.  Run it with CPython 3.14,
never with Grail: EXPECTED is CPython's answer, and a table written by the
implementation under test would only pin its current behaviour.

Usage: python3 scripts/generate_class_attr_dunder_fixture.py [output.py]
"""
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    ROOT, 'tests', 'python', 'class_attr_dunder_binding.py')

protos = [
    ("__add__", "o + 1", "'v'"), ("__radd__", "1 + o", "'v'"), ("__lt__", "o < 1", "'v'"),
    ("__eq__", "o == 1", "'v'"), ("__call__", "o()", "'v'"), ("__getitem__", "o[0]", "'v'"),
    ("__setitem__", "_setitem(o)", "'v'"), ("__contains__", "1 in o", "True"),
    ("__len__", "len(o)", "3"), ("__bool__", "bool(o)", "False"),
    ("__iter__", "type(iter(o)).__name__", "iter([])"), ("__next__", "next(o)", "'v'"),
    ("__reversed__", "type(reversed(o)).__name__", "iter([])"),
    ("__repr__", "repr(o)", "'r'"), ("__str__", "str(o)", "'s'"), ("__format__", "format(o, 'x')", "'f'"),
    ("__hash__", "hash(o)", "7"), ("__neg__", "-o", "'v'"), ("__abs__", "abs(o)", "'v'"),
    ("__invert__", "~o", "'v'"), ("__mul__", "o * 2", "'v'"), ("__rmul__", "2 * o", "'v'"),
    ("__index__", "[10, 20][o]", "1"), ("__int__", "int(o)", "5"), ("__float__", "float(o)", "2.5"),
    ("__enter__", "_with(o)", "'v'"), ("__getattr__", "o.zz_missing", "'v'"),
]
kinds = [
    ("func", "mkfunc({r})"),
    ("lambda", "(lambda r: lambda *a: enc(r, len(a)))({r})"),
    ("plainfn", "H{n}.f"),
    ("classm", "classmethod(mkfunc({r}))"),
    ("static", "staticmethod(mkfunc({r}))"),
    ("bound", "Ret({r}).m"),
    ("callobj", "CallObj({r})"),
]
head = '''"""Issue #1218: a callable stored as a CLASS ATTRIBUTE under a protocol dunder
must be called the way CPython's special-method lookup calls it -- looked up on
the type, then bound by the descriptor protocol -- whatever the protocol and
however the value got onto the class.

Every case stores one kind of value under one dunder and exercises the implicit
protocol (``o + 1'', ``len(o)'', ``bool(o)'', ...), once in the class body and
once with setattr after the class exists.  The kinds differ in whether CPython
passes the instance:

    func, lambda, plainfn   functions: bound, the instance comes first
    classm                  bound to the CLASS
    static                  a staticmethod: the arguments alone
    bound                   a method ALREADY bound (``__len__ = lst.__len__''):
                            not a descriptor, the arguments alone
    callobj                 a callable instance: not a descriptor either

Each value reports how many arguments it received (``enc''), so passing the
instance wrongly -- or failing to -- changes the answer.  Grail used to prepend
the instance to every one of them, and several protocols (len, bool, unary
operators, __index__, int, float, a setattr __getitem__/__call__/...) never
looked at a class attribute at all; ``bool(o)'' silently answered True.

GENERATED by scripts/generate_class_attr_dunder_fixture.py -- edit that and
rerun it under CPython rather than editing this file.  The class statements
are written out one per case, because a
class-body assignment and a setattr store are different code paths and a loop
over ``type(...)'' would exercise neither.  EXPECTED is CPython 3.14's output.
"""

import io


def enc(r, n):
    # Encode the argument count into a value the protocol still accepts, so a
    # wrongly bound (or unbound) call shows up in the result.
    if r == 'v':
        return (r, n)
    if r is True or r is False:
        return n == 0
    if isinstance(r, int):
        return r + 100 * n
    if isinstance(r, float):
        return r + 100 * n
    if isinstance(r, str):
        return r + str(n)
    return r


class Ret:
    def __init__(self, r):
        self.r = r

    def m(self, *a):
        return enc(self.r, len(a))


class CallObj:
    def __init__(self, r):
        self.r = r

    def __call__(self, *a):
        return enc(self.r, len(a))


def mkfunc(r):
    def f(*a):
        return enc(r, len(a))
    return f


def _setitem(o):
    o[0] = 1
    return 'set'


def _with(o):
    with o as v:
        return v


RESULTS = {}


def run(label, thunk):
    try:
        r = thunk()
    except Exception as e:
        r = type(e).__name__
    RESULTS[label] = repr(r)

'''
body = []
n = 0
for d, use, r in protos:
    for k, expr in kinds:
        n += 1
        v = expr.format(r=r, n=n)
        if k == "plainfn":
            body.append(f"class H{n}:\n    def f(*a):\n        return enc({r}, len(a))\n")
        extra = "\n    __exit__ = lambda *a: False" if d == "__enter__" else ""
        body.append(f"class B{n}:\n    {d} = {v}{extra}\nrun('body    {d} {k}', lambda: (lambda o: {use})(B{n}()))\n")
        sx = f"\n    __exit__ = lambda *a: False" if d == "__enter__" else "\n    pass"
        body.append(f"class S{n}:{sx}\nS{n}.{d} = {v}\nrun('setattr {d} {k}', lambda: (lambda o: {use})(S{n}()))\n")

tail_issue = '''

# The issue's own end-to-end case: CPython 3.14's iterparse builds its iterator
# class with ``__next__ = gen.__next__''.
def _iterparse():
    import xml.etree.ElementTree as ET
    return [(ev, el.tag) for ev, el in ET.iterparse(io.BytesIO(b"<a><b/></a>"))]


run('issue   ET.iterparse', _iterparse)


# object's OWN method stored under its own name is the default, not an
# override -- the protocol must not call it as one (it would call itself).
class ObjStrBody:
    __str__ = object.__str__
    __format__ = object.__format__
    def __repr__(self):
        return 'objdefault'
class ObjStrSet:
    def __repr__(self):
        return 'objdefault'
ObjStrSet.__str__ = object.__str__
ObjStrSet.__format__ = object.__format__
run('body    str object.default', lambda: str(ObjStrBody()))
run('body    format object.default', lambda: format(ObjStrBody()))
run('setattr str object.default', lambda: str(ObjStrSet()))
run('setattr format object.default', lambda: format(ObjStrSet()))

'''
fixture = head + "\n# ---- generated cases ----\n" + "".join(body) + tail_issue
with tempfile.TemporaryDirectory() as tmp:
    stage = os.path.join(tmp, 'stage.py')
    with open(stage, 'w') as f:
        f.write(fixture + "\nif __name__ == '__main__':\n    import json\n    print(json.dumps(RESULTS))\n")
    out = subprocess.run([sys.executable, stage], capture_output=True, text=True, check=True).stdout
results = json.loads(out)
exp_lines = ["EXPECTED = {"] + [f"    {k!r}: {v!r}," for k, v in results.items()] + ["}"]
final = fixture + "\n" + "\n".join(exp_lines) + '''


def mismatches(kind):
    """The cases for one value kind (the label's last word) whose result
    differs from CPython's, as 'label: got X, CPython Y' -- what the Smalltalk
    test case asserts is empty."""
    return ['%s: got %s, CPython %s' % (k, RESULTS.get(k), v)
            for k, v in EXPECTED.items()
            if k.split()[-1] == kind and RESULTS.get(k) != v]


if __name__ == '__main__':
    for label, expected in EXPECTED.items():
        print('%-4s %s' % ('OK' if RESULTS.get(label) == expected else 'FAIL', label))
'''
with open(OUT, 'w') as f:
    f.write(final)
print('%s: %d cases' % (OUT, len(results)))
