#!/usr/bin/env python3
"""Regenerate src/smalltalk/Python/unicode_numeric_types.gs: the code-point
ranges behind str.isdecimal, str.isdigit and str.isnumeric.

WHY THIS EXISTS.  The three predicates are Unicode's Numeric_Type property:
isdecimal is Numeric_Type=Decimal, isdigit adds Digit ('\\u00b2', the circled
digits), isnumeric adds Numeric ('\\u00bd', Roman numerals, CJK numerals).
Grail answered all three with the kernel's Character >> isDigit, which is the
Decimal set only -- and an older Unicode's: '\\u00b2'.isdigit() and
'\\u00bd'.isnumeric() were False, and 180 decimal digits added since (Kawi,
Garay, Sunuwar, ...) were not decimal at all.  The kernel never claims a
character CPython rejects, so the tables replace it rather than patch it.

WHAT IS GENERATED.  Three sorted literal arrays of inclusive (first, last)
code-point pairs, one per predicate, each a superset of the one before.  They
are read from CPython's OWN str methods on every code point, so they are its
definitions by construction, and the Unicode version must equal the one
Grail's unicodedata reports (src/python/stdlib/unicodedata.py).

VERIFIED BEFORE WRITING.  The ranges are expanded again and compared with
CPython on every code point; any disagreement stops the script with nothing
written.

Run with the CPython version Grail vendors (3.14.x):
    python3.14 scripts/generate_unicode_numeric.py
"""
import os
import re
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src', 'smalltalk', 'Python', 'unicode_numeric_types.gs')
GRAIL_UNICODEDATA = os.path.join(ROOT, 'src', 'python', 'stdlib', 'unicodedata.py')

PREDICATES = (
    ('isdecimal', '___pyDecimalRanges___', 'Numeric_Type=Decimal'),
    ('isdigit', '___pyDigitRanges___', 'Numeric_Type=Decimal or Digit'),
    ('isnumeric', '___pyNumericRanges___', 'Numeric_Type=Decimal, Digit or Numeric'),
)


def grail_unidata_version():
    with open(GRAIL_UNICODEDATA) as f:
        m = re.search(r"^unidata_version = '([^']+)'", f.read(), re.M)
    if not m:
        sys.exit('cannot find unidata_version in %s' % GRAIL_UNICODEDATA)
    return m.group(1)


def ranges_for(predicate):
    out = []
    for cp in range(0x110000):
        if getattr(chr(cp), predicate)():
            if out and out[-1][1] == cp - 1:
                out[-1][1] = cp
            else:
                out.append([cp, cp])
    return out


def contains(ranges, cp):
    lo, hi = 0, len(ranges) - 1
    while lo <= hi:
        mid = (lo + hi) // 2
        first, last = ranges[mid]
        if cp < first:
            hi = mid - 1
        elif cp > last:
            lo = mid + 1
        else:
            return True
    return False


def literal(ranges):
    words = ['%d %d' % (a, b) for a, b in ranges]
    lines, line = [], '\t^ #('
    for w in words:
        if len(line) + 1 + len(w) > 76:
            lines.append(line)
            line = '\t\t' + w
        else:
            line = line + ' ' + w
    lines.append(line + ' )')
    return '\n'.join(lines)


def main():
    version = grail_unidata_version()
    if unicodedata.unidata_version != version:
        sys.exit('CPython has Unicode %s but Grail\'s unicodedata reports %s; '
                 'run with the CPython Grail vendors'
                 % (unicodedata.unidata_version, version))
    tables = []
    for predicate, selector, meaning in PREDICATES:
        ranges = ranges_for(predicate)
        for cp in range(0x110000):
            if contains(ranges, cp) != getattr(chr(cp), predicate)():
                sys.exit('%s disagrees at U+%04X; nothing written' % (predicate, cp))
        tables.append((predicate, selector, meaning, ranges))
    for (_, _, _, small), (name, _, _, big) in zip(tables, tables[1:]):
        if any(not contains(big, cp) for a, b in small for cp in range(a, b + 1)):
            sys.exit('%s is not a superset of the table before it' % name)

    parts = [
        '! GENERATED by scripts/generate_unicode_numeric.py from CPython %s\'s'
        % sys.version.split()[0],
        '! Unicode %s database -- do not edit; rerun the script.' % version,
        '',
        'set compile_env: 0',
        '',
    ]
    for predicate, selector, meaning, ranges in tables:
        count = sum(b - a + 1 for a, b in ranges)
        parts += [
            "category: 'Grail-Unicode Data'",
            'classmethod: CharacterCollection',
            selector,
            '\t"str.%s: %s, Unicode %s -- %d code points in %d'
            % (predicate, meaning, version, count, len(ranges)),
            '\tinclusive (first last) ranges, sorted.  See',
            '\tCharacterCollection class >> ___pyCodePoint___:inRanges:."',
            '',
            literal(ranges),
            '%',
            '',
        ]
    parts.append('set compile_env: 0')
    with open(OUT, 'w') as f:
        f.write('\n'.join(parts) + '\n')
    for predicate, _, _, ranges in tables:
        print('%-9s %5d code points, %4d ranges'
              % (predicate, sum(b - a + 1 for a, b in ranges), len(ranges)))
    print('wrote', os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
