#!/usr/bin/env python3
"""Generate src/c/shim/grail_digit_table.h -- the Unicode decimal-digit ranges
the CPython shim's _grail_unicode_isdecimal needs.

Authoritative source: CPython's own str.isdecimal(), which IS
Py_UNICODE_ISDECIMAL applied per character.  That predicate is exactly the Nd
general category -- checked here rather than assumed, so a future Unicode
version that broke the equivalence would fail the run instead of quietly
producing a table that disagrees with unicodedata.

The shim keeps an ASCII fast path, so only code points >= 128 are tabulated.
They fall in 70 contiguous runs (each digit set is ten consecutive code
points), which is why this is a range table and not a per-character one.

Run with the SAME CPython version Grail vendors (3.14.x):
    python3.14 scripts/generate_unicode_digit_table.py
"""
import sys
import unicodedata

OUT = "src/c/shim/grail_digit_table.h"
MAX = 0x110000


def decimal_ranges():
    ranges = []
    for codepoint in range(128, MAX):
        if not chr(codepoint).isdecimal():
            continue
        if ranges and codepoint == ranges[-1][1] + 1:
            ranges[-1][1] = codepoint
        else:
            ranges.append([codepoint, codepoint])
    return ranges


def assert_isdecimal_is_nd():
    by_category = {cp for cp in range(MAX)
                   if unicodedata.category(chr(cp)) == "Nd"}
    by_predicate = {cp for cp in range(MAX) if chr(cp).isdecimal()}
    if by_category != by_predicate:
        raise SystemExit(
            "str.isdecimal() and the Nd category no longer agree "
            "(%d only-Nd, %d only-isdecimal) -- decide which one the shim "
            "should follow before regenerating"
            % (len(by_category - by_predicate),
               len(by_predicate - by_category)))


def main():
    assert_isdecimal_is_nd()
    ranges = decimal_ranges()

    with open(OUT, "w") as f:
        f.write("/* GENERATED by scripts/generate_unicode_digit_table.py"
                " -- do not edit.\n")
        f.write(" * Source: CPython %s str.isdecimal(), which is exactly the"
                " Nd category.\n" % sys.version.split()[0])
        f.write(" * Unicode %s.  Non-ASCII only; ASCII is a range check in"
                " the shim.\n" % unicodedata.unidata_version)
        f.write(" * Sorted and non-adjacent, so a binary search decides"
                " membership. */\n\n")
        f.write("typedef struct { unsigned int first; unsigned int last; }"
                " GrailCodepointRange;\n\n")
        f.write("static const GrailCodepointRange grail_decimal_ranges[] = {\n")
        for index in range(0, len(ranges), 4):
            row = "".join("{0x%05x,0x%05x}," % (first, last)
                          for first, last in ranges[index:index + 4])
            f.write("    " + row + "\n")
        f.write("};\n")
        f.write("static const int grail_decimal_ranges_len = %d;\n"
                % len(ranges))

    print("wrote %s: %d ranges, %d code points"
          % (OUT, len(ranges),
             sum(last - first + 1 for first, last in ranges)))


if __name__ == "__main__":
    main()
