#!/usr/bin/env python3
"""Generate src/c/shim/grail_case_tables.h -- simple Unicode case tables for
the CPython shim's _grail_unicode_tolower / _grail_unicode_toupper / iscased.

Authoritative source: CPython's own _sre.unicode_tolower (which is
Py_UNICODE_TOLOWER, the SIMPLE lowercase used by the regex engine) plus
_sre.unicode_iscased.  Simple uppercase is derived from str.upper() single-char
results (validated to agree with the simple mapping for all code points that
matter here).  Only non-ASCII (cp >= 128) entries are tabulated; the shim keeps
a ctype fast-path for ASCII.

Run with the SAME CPython version Grail vendors (3.14.x) so the tables match
_casefix.py:  python3.14 scripts/generate_grail_case_tables.py
"""
import _sre
import sys

OUT = "src/c/shim/grail_case_tables.h"
MAX = 0x110000


def simple_upper(cp):
    up = chr(cp).upper()
    return ord(up) if len(up) == 1 else cp


def main():
    lower = [(cp, _sre.unicode_tolower(cp)) for cp in range(128, MAX)
             if _sre.unicode_tolower(cp) != cp]
    upper = [(cp, simple_upper(cp)) for cp in range(128, MAX)
             if simple_upper(cp) != cp]
    # Cased code points whose "cased" status is NOT implied by a simple
    # lower/upper mapping difference (e.g. sharp-s, dotted-I, the ﬅ/ﬆ
    # ligatures) -- iscased must still return true for these.
    cased_extra = [cp for cp in range(128, MAX)
                   if _sre.unicode_iscased(cp)
                   and simple_upper(cp) == cp
                   and _sre.unicode_tolower(cp) == cp]

    def emit_pairs(f, name, pairs):
        f.write(f"static const GrailCasePair {name}[] = {{\n")
        for i in range(0, len(pairs), 4):
            row = "".join(f"{{0x{a:05x},0x{b:05x}}}," for a, b in pairs[i:i+4])
            f.write("    " + row + "\n")
        f.write("};\n")
        f.write(f"static const int {name}_len = {len(pairs)};\n\n")

    with open(OUT, "w") as f:
        f.write("/* GENERATED by scripts/generate_grail_case_tables.py -- do not edit.\n")
        f.write(f" * Source: CPython {sys.version.split()[0]} _sre simple case tables.\n")
        f.write(" * Simple Unicode case mappings for the regex engine (non-ASCII only;\n")
        f.write(" * ASCII is handled by ctype in the shim).  Sorted by `from` for bsearch. */\n\n")
        f.write("typedef struct { unsigned int from; unsigned int to; } GrailCasePair;\n\n")
        emit_pairs(f, "grail_lower_map", lower)
        emit_pairs(f, "grail_upper_map", upper)
        f.write("/* Cased code points with no simple case mapping (iscased add-ons). */\n")
        f.write("static const unsigned int grail_cased_extra[] = {\n")
        for i in range(0, len(cased_extra), 8):
            f.write("    " + "".join(f"0x{cp:05x}," for cp in cased_extra[i:i+8]) + "\n")
        f.write("};\n")
        f.write(f"static const int grail_cased_extra_len = {len(cased_extra)};\n")

    print(f"wrote {OUT}: lower={len(lower)} upper={len(upper)} cased_extra={len(cased_extra)}")

    # Also emit the Smalltalk multi-character SpecialCasing arrays used by
    # str.gs (___multicharUpperData___ / ___multicharLowerData___).  These are
    # pasted into src/smalltalk/Python/str.gs by hand when the Unicode version
    # changes -- the layout is flat: key, count, cp1..cpCount, key, count, ...
    import textwrap

    def flat_full(kind):
        m = {cp: getattr(chr(cp), kind)() for cp in range(MAX)
             if len(getattr(chr(cp), kind)()) > 1}
        out = []
        for cp in sorted(m):
            exp = [ord(c) for c in m[cp]]
            out += [cp, len(exp)] + exp
        return out, len(m)

    for kind, meth in (("upper", "___multicharUpperData___"),
                       ("lower", "___multicharLowerData___")):
        arr, n = flat_full(kind)
        print(f"\n--- str.gs {meth}  ({n} chars, {kind}) ---")
        print("\t^ #(")
        for line in textwrap.wrap(" ".join(map(str, arr)), 84):
            print("\t\t" + line)
        print("\t)")


if __name__ == "__main__":
    main()
