#!/usr/bin/env python3
"""Regenerate the ``initialize_html5`` method in
src/smalltalk/Python/html_entities.gs from CPython's own html.entities.html5.

Authoritative source: the vendored CPython's ``html.entities.html5``, which is
the WHATWG named-character-reference table.  Its SHAPE matters as much as its
contents: every entity appears under ``name;``, and the 106 LEGACY entities
appear a second time under the bare ``name``.  That is what makes

    html.unescape('&gt;')   '>'      -- exact hit on 'gt;'
    html.unescape('&gt')    '>'      -- exact hit on the legacy bare 'gt'
    html.unescape('&acE')   '&acE'   -- 'acE' is NOT legacy, so no hit at all

Grail's table used to hold 2125 BARE names and none with a semicolon, which
gets the first two wrong in opposite directions: a lookup of 'gt;' missed, and
'acE' hit when it should not have.  Match upstream exactly and the algorithm in
html.gs's unescape: needs no special cases.

Run with the SAME CPython version Grail vendors (3.14.x):
    python3.14 scripts/generate_html5_entities.py
"""
import html.entities
import io
import re
import sys

GS = "src/smalltalk/Python/html_entities.gs"


def value_expr(text):
    """The Smalltalk expression for one entity's replacement string."""
    parts = ["(Character @env0:codePoint: %d) @env0:asString" % ord(ch)
             for ch in text]
    if len(parts) == 1:
        return parts[0]
    return "(" + " @env0:, ".join(parts) + ")"


def main():
    table = html.entities.html5
    lines = ["initialize_html5",
             "\t\"Build the html5 dictionary (%d WHATWG HTML5 entities)." % len(table),
             "\tMaps entity name (String) to character string (String).",
             "",
             "\tGENERATED by scripts/generate_html5_entities.py -- do not edit by hand.",
             "",
             "\tEvery entity appears under ``name;'', and the %d LEGACY entities"
             % sum(1 for k in table if not k.endswith(';')),
             "\talso under the bare ``name''.  That shape is what lets unescape:",
             "\tconvert ``&gt;'' and ``&gt'' alike while leaving ``&acE'' alone --",
             "\t``acE'' is not legacy, so only ``acE;'' is a key.\"",
             "",
             "\t| d |",
             "\td := KeyValueDictionary @env0:new.",
             ""]
    for name in sorted(table, key=lambda k: (k.rstrip(';'), k)):
        lines.append("\td @env0:at: '%s' put: %s."
                     % (name, value_expr(table[name])))
    lines += ["", "\tself @env0:at: #html5 put: d", "%"]
    generated = "\n".join(lines) + "\n"

    source = io.open(GS, encoding="utf-8").read()
    start = source.index("initialize_html5\n")
    end = source.index("\n%\n", source.index("self @env0:at: #html5 put: d", start)) + 3
    io.open(GS, "w", encoding="utf-8").write(source[:start] + generated + source[end:])
    print("wrote %d entities into %s" % (len(table), GS))


if __name__ == "__main__":
    main()
